// swiftlint:disable file_length type_body_length
enum EnglishStrings {
    static let all: [String: String] = {
        var d = [String: String]()

        // MARK: - Common
        d["common.back"] = "Back"
        d["common.continue"] = "Continue"
        d["common.done"] = "Done"
        d["common.skip"] = "Skip"
        d["common.cancel"] = "Cancel"
        d["common.save"] = "Save"
        d["common.delete"] = "Delete"
        d["common.yes"] = "Yes"
        d["common.no"] = "No"
        d["common.ok"] = "OK"
        d["common.close"] = "Close"
        d["common.enter"] = "Enter"
        d["common.next"] = "Next"
        d["common.a_little"] = "A little"
        d["common.a_lot"] = "A lot"
        d["common.settings"] = "Settings"
        d["common.selected_count"] = "%d/%d selected"
        d["common.step_of"] = "STEP %@"

        // MARK: - Splash
        d["splash.title"] = "Komal"
        d["splash.tagline"] = "Your child's safe digital companion"

        // MARK: - Login
        d["login.welcome"] = "Welcome to Komal"
        d["login.tagline"] = "Your child's safe digital companion"
        d["login.sign_in_google"] = "Sign in with Google"
        d["login.sign_in_apple"] = "Sign in with Apple"
        d["login.or"] = "or"
        d["login.guest_user"] = "Continue as Guest"
        d["login.signing_in"] = "Signing in..."
        d["login.failed"] = "Login Failed"
        d["login.try_again"] = "Try Again"
        d["login.guest.welcome"] = "Welcome, Guest!"
        d["login.guest.description"] = "Your data will be stored locally on this device. You can sign in later to sync across devices."
        d["login.guest.getting_started"] = "Getting Started"
        d["login.onboarding.welcome"] = "Welcome to Komal!"
        d["login.onboarding.description"] = "Let's set up your safe browsing experience."
        d["login.onboarding.get_started"] = "Get Started"

        // MARK: - Onboarding Welcome
        d["onboarding.welcome.title"] = "Child Safety Assessment"
        d["onboarding.welcome.subtitle"] = "Evidence-based digital wellbeing profile"
        d["onboarding.welcome.card1.title"] = "Developmental Psychology"
        d["onboarding.welcome.card1.desc"] = "Settings tailored to cognitive development stages as defined by child psychology research."
        d["onboarding.welcome.card2.title"] = "Behavioral Analysis"
        d["onboarding.welcome.card2.desc"] = "Understanding browsing patterns to create personalized safety boundaries."
        d["onboarding.welcome.card3.title"] = "Proactive Protection"
        d["onboarding.welcome.card3.desc"] = "Content filtering based on identified risk factors and preferences."
        d["onboarding.welcome.time_estimate"] = "This assessment takes approximately 3-4 minutes"
        d["onboarding.welcome.begin"] = "Begin Assessment"
        d["onboarding.welcome.language"] = "Language"

        // MARK: - Onboarding Child Info
        d["onboarding.info.step"] = "1 of 6"
        d["onboarding.info.title"] = "Basic Information"
        d["onboarding.info.subtitle"] = "Help us understand who we're protecting"
        d["onboarding.info.name_label"] = "Child's First Name"
        d["onboarding.info.name_placeholder"] = "Enter name"
        d["onboarding.info.age_label"] = "Age Group"
        d["onboarding.info.age_desc"] = "Content restrictions are calibrated based on developmental milestones"
        d["onboarding.info.research_note"] = "Research shows that age-appropriate content boundaries support healthy cognitive development and reduce anxiety in children."

        // Age group descriptions
        d["onboarding.age.under10"] = "Early childhood - Maximum protection"
        d["onboarding.age.10to13"] = "Pre-teen - Guided exploration"
        d["onboarding.age.13to16"] = "Teen - Balanced boundaries"
        d["onboarding.age.16to18"] = "Late teen - Age-appropriate freedom"
        d["onboarding.age.18plus"] = "Adult - Full access"

        // MARK: - Onboarding Websites
        d["onboarding.websites.step"] = "2 of 6"
        d["onboarding.websites.title"] = "Favorite Websites"
        d["onboarding.websites.subtitle"] = "Select up to 5 websites your child visits most"
        d["onboarding.websites.desc"] = "Understanding browsing habits helps us identify trusted sources and personalize protection."

        // MARK: - Onboarding Interests
        d["onboarding.interests.step"] = "3 of 6"
        d["onboarding.interests.title"] = "Topics of Interest"
        d["onboarding.interests.subtitle"] = "What does your child enjoy learning about?"
        d["onboarding.interests.desc"] = "Select 3-5 topics. This helps us understand what content to prioritize and protect."

        // Interest names
        d["onboarding.interest.gaming"] = "Gaming"
        d["onboarding.interest.animals"] = "Animals"
        d["onboarding.interest.science"] = "Science"
        d["onboarding.interest.art"] = "Art & Drawing"
        d["onboarding.interest.music"] = "Music"
        d["onboarding.interest.sports"] = "Sports"
        d["onboarding.interest.coding"] = "Coding"
        d["onboarding.interest.reading"] = "Reading"
        d["onboarding.interest.cooking"] = "Cooking"
        d["onboarding.interest.nature"] = "Nature"
        d["onboarding.interest.space"] = "Space"
        d["onboarding.interest.history"] = "History"
        d["onboarding.interest.movies"] = "Movies"
        d["onboarding.interest.crafts"] = "Crafts"
        d["onboarding.interest.dinosaurs"] = "Dinosaurs"
        d["onboarding.interest.vehicles"] = "Vehicles"
        d["onboarding.interest.fashion"] = "Fashion"
        d["onboarding.interest.dance"] = "Dance"
        d["onboarding.interest.photography"] = "Photography"
        d["onboarding.interest.travel"] = "Travel"
        d["onboarding.interest.math"] = "Math"
        d["onboarding.interest.puzzles"] = "Puzzles"
        d["onboarding.interest.robots"] = "Robots"
        d["onboarding.interest.magic"] = "Magic"
        d["onboarding.interest.superheroes"] = "Superheroes"
        d["onboarding.interest.gardening"] = "Gardening"
        d["onboarding.interest.astronomy"] = "Astronomy"
        d["onboarding.interest.languages"] = "Languages"
        d["onboarding.interest.boardgames"] = "Board Games"
        d["onboarding.interest.swimming"] = "Swimming"
        d["onboarding.interest.comics"] = "Comics"
        d["onboarding.interest.yoga"] = "Yoga"
        d["onboarding.interest.theater"] = "Theater"

        // MARK: - Onboarding Likes
        d["onboarding.likes.step"] = "4 of 6"
        d["onboarding.likes.title"] = "What They Enjoy Online"
        d["onboarding.likes.subtitle"] = "Understanding positive online experiences"
        d["onboarding.likes.desc"] = "Select activities your child enjoys. This helps us ensure they have access to enriching content."
        d["onboarding.likes.other"] = "Other (optional)"
        d["onboarding.likes.other_placeholder"] = "Add something else they enjoy..."

        // Like options
        d["onboarding.like.watching_videos"] = "Watching videos"
        d["onboarding.like.playing_games"] = "Playing games"
        d["onboarding.like.chatting"] = "Chatting with friends"
        d["onboarding.like.learning"] = "Learning new things"
        d["onboarding.like.creative"] = "Creative projects"
        d["onboarding.like.exploring"] = "Exploring websites"
        d["onboarding.like.music"] = "Listening to music"
        d["onboarding.like.virtual_worlds"] = "Virtual worlds"
        d["onboarding.like.puzzles"] = "Puzzles & challenges"
        d["onboarding.like.funny"] = "Funny content"
        d["onboarding.like.stories"] = "Stories & books"
        d["onboarding.like.making_videos"] = "Making videos"
        d["onboarding.like.drawing"] = "Drawing & painting"
        d["onboarding.like.photography"] = "Taking photos"
        d["onboarding.like.coding"] = "Coding & programming"
        d["onboarding.like.reading_comics"] = "Reading comics"
        d["onboarding.like.collecting"] = "Collecting things"
        d["onboarding.like.building"] = "Building & crafting"
        d["onboarding.like.cooking_videos"] = "Cooking videos"
        d["onboarding.like.science_experiments"] = "Science experiments"
        d["onboarding.like.dancing"] = "Dancing"
        d["onboarding.like.trivia"] = "Trivia & quizzes"
        d["onboarding.like.anime"] = "Anime & cartoons"
        d["onboarding.like.podcasts"] = "Podcasts"
        d["onboarding.like.shopping"] = "Online shopping"
        d["onboarding.like.live_streams"] = "Watching live streams"

        // MARK: - Onboarding Dislikes
        d["onboarding.dislikes.step"] = "5 of 6"
        d["onboarding.dislikes.title"] = "What Bothers Them"
        d["onboarding.dislikes.subtitle"] = "Identifying triggers and discomforts"
        d["onboarding.dislikes.desc"] = "Select things that upset or concern your child online. This helps us filter potentially distressing content."
        d["onboarding.dislikes.other"] = "Other concerns (optional)"
        d["onboarding.dislikes.other_placeholder"] = "Add other things that bother them..."
        d["onboarding.dislikes.research_note"] = "Understanding what distresses children online allows us to proactively filter content before exposure, reducing anxiety and negative experiences."

        // Dislike options
        d["onboarding.dislike.scary"] = "Scary content"
        d["onboarding.dislike.loud"] = "Loud noises/jumpscares"
        d["onboarding.dislike.mean"] = "Mean comments"
        d["onboarding.dislike.strangers"] = "Strangers messaging"
        d["onboarding.dislike.violent"] = "Violent games"
        d["onboarding.dislike.sad"] = "Sad stories"
        d["onboarding.dislike.ads"] = "Confusing ads"
        d["onboarding.dislike.reading"] = "Too much reading"
        d["onboarding.dislike.timed"] = "Timed challenges"
        d["onboarding.dislike.losing"] = "Losing in games"
        d["onboarding.dislike.popups"] = "Pop-up videos"
        d["onboarding.dislike.rushed"] = "Being rushed"

        // MARK: - Onboarding Concerns
        d["onboarding.concerns.step"] = "6 of 8"
        d["onboarding.concerns.title"] = "Your Concerns"
        d["onboarding.concerns.subtitle"] = "What worries you most about your child online?"
        d["onboarding.concerns.desc"] = "Select your top concerns. We'll prioritize protection in these areas."

        // Concern items
        d["onboarding.concern.cyberbullying"] = "Cyberbullying"
        d["onboarding.concern.cyberbullying.desc"] = "Harassment, mean messages, exclusion"
        d["onboarding.concern.inappropriate"] = "Inappropriate Content"
        d["onboarding.concern.inappropriate.desc"] = "Violence, mature themes, explicit material"
        d["onboarding.concern.predators"] = "Online Predators"
        d["onboarding.concern.predators.desc"] = "Strangers, grooming, personal info requests"
        d["onboarding.concern.addiction"] = "Screen Addiction"
        d["onboarding.concern.addiction.desc"] = "Excessive use, difficulty stopping"
        d["onboarding.concern.privacy"] = "Privacy Risks"
        d["onboarding.concern.privacy.desc"] = "Data collection, location sharing"
        d["onboarding.concern.misinfo"] = "Misinformation"
        d["onboarding.concern.misinfo.desc"] = "Fake news, conspiracy theories"
        d["onboarding.concern.scams"] = "Financial Scams"
        d["onboarding.concern.scams.desc"] = "In-app purchases, phishing"
        d["onboarding.concern.mental"] = "Mental Health"
        d["onboarding.concern.mental.desc"] = "Anxiety, comparison, FOMO"

        // MARK: - Onboarding Filters
        d["onboarding.filters.step"] = "7 of 8"
        d["onboarding.filters.title"] = "Content Filters"
        d["onboarding.filters.subtitle"] = "Review and customize content filtering"
        d["onboarding.filters.desc"] = "These defaults are based on your child's age and your concerns. Adjust any setting below."

        // MARK: - Onboarding PIN
        d["onboarding.pin.step"] = "8 of 8"
        d["onboarding.pin.title"] = "Set Parent PIN"
        d["onboarding.pin.subtitle"] = "Create a PIN to protect parent settings"
        d["onboarding.pin.desc"] = "This PIN will be required to access parent mode and approve gated content."
        d["onboarding.pin.enter"] = "Enter PIN"
        d["onboarding.pin.placeholder"] = "4-digit PIN"
        d["onboarding.pin.confirm"] = "Confirm PIN"
        d["onboarding.pin.confirm_placeholder"] = "Confirm PIN"
        d["onboarding.pin.mismatch"] = "PINs do not match. Please try again."
        d["onboarding.pin.enable_biometric"] = "Enable %@"
        d["onboarding.pin.use_biometric"] = "Use %@ instead of PIN"
        d["onboarding.pin.research_note"] = "A parent PIN ensures only authorized adults can modify safety settings and approve gated content."

        // MARK: - Avatar Selection
        d["onboarding.avatar.title"] = "Choose Your Buddy"
        d["onboarding.avatar.subtitle"] = "Pick an animal friend to be your guide!"
        d["settings.avatar.title"] = "Your Avatar"
        d["settings.avatar.change"] = "Tap to change your avatar"

        // MARK: - Onboarding Completion
        d["onboarding.complete.title"] = "Profile Complete"
        d["onboarding.complete.subtitle"] = "%@'s safety profile is ready"
        d["onboarding.complete.summary"] = "Assessment Summary"
        d["onboarding.complete.name"] = "Name"
        d["onboarding.complete.age_group"] = "Age Group"
        d["onboarding.complete.interests"] = "Interests"
        d["onboarding.complete.concerns"] = "Key Concerns"
        d["onboarding.complete.adjust_note"] = "Settings can be adjusted anytime in the app"
        d["onboarding.complete.start"] = "Start Using Komal"
        d["onboarding.complete.review"] = "Review Answers"

        // MARK: - Menu / Navigation
        d["menu.browse"] = "Browse"
        d["menu.talk"] = "Talk"
        d["menu.reflect"] = "Reflect"
        d["menu.settings"] = "Settings"

        // MARK: - Settings
        d["settings.title"] = "Settings"
        d["settings.language"] = "Language"
        d["settings.whos_using"] = "Who's Using?"
        d["settings.whos_using.desc"] = "Select who is currently using the device"
        d["settings.child"] = "Child"
        d["settings.child.subtitle"] = "Safe browsing"
        d["settings.parent"] = "Parent"
        d["settings.parent.subtitle"] = "Full access"

        // Settings - Child Mode
        d["settings.child.greeting"] = "Hi %@!"
        d["settings.child.greeting_default"] = "Hi there!"
        d["settings.child.safe_msg"] = "Komal is here to keep you safe while you explore!"
        d["settings.child.chatty"] = "Feeling Chatty?"
        d["settings.child.chatty.desc"] = "Talk to Riki! Your friendly companion is always here to chat and help you out."
        d["settings.child.go_talk"] = "Go to Talk"
        d["settings.child.profile"] = "Your Profile"
        d["settings.child.explorer"] = "Explorer"
        d["settings.child.age"] = "Age: %@"
        d["settings.child.journey"] = "My Journey"
        d["settings.child.day_streak"] = "Day Streak"
        d["settings.child.milestones"] = "Milestones"
        d["settings.child.view_journey"] = "View My Journey"

        // Settings - Parent Mode
        d["settings.parent.digital_journey"] = "Digital Journey"
        d["settings.parent.view_journey"] = "View Digital Journey"
        d["settings.parent.journey_desc"] = "See your child's browsing activity with AI insights"
        d["settings.parent.wellness"] = "Child Wellness"
        d["settings.parent.wellness_dashboard"] = "Wellness Dashboard"
        d["settings.parent.wellness_desc"] = "Mood trends, conversations, growth metrics"
        d["settings.parent.morning_checkin"] = "Morning Check-in"
        d["settings.parent.morning_desc"] = "Daily morning mood anchor"
        d["settings.parent.evening_winddown"] = "Evening Wind-down"
        d["settings.parent.evening_desc"] = "Daily evening reflection anchor"
        d["settings.parent.child_profile"] = "Child Profile"
        d["settings.parent.name_label"] = "Name"
        d["settings.parent.name_placeholder"] = "Child's Name"
        d["settings.parent.age_label"] = "Age Group"
        d["settings.parent.controls"] = "Parent Controls"
        d["settings.parent.notify_block"] = "Notify on Block"
        d["settings.parent.notify_desc"] = "Get alerts when blocked content is accessed"
        d["settings.parent.safe_search"] = "Force Safe Search"
        d["settings.parent.safe_search_desc"] = "Enforce strict safety on search engines"
        d["settings.parent.view_insights"] = "View Insights"
        d["settings.parent.insights_desc"] = "See browsing activity and blocked content"
        d["settings.parent.modify_content"] = "Modify Content"
        d["settings.parent.modify_filters"] = "Modify Filters"
        d["settings.parent.custom_keywords"] = "Custom Keywords"
        d["settings.parent.add_keyword"] = "Add keyword (e.g. 'weapons')"
        d["settings.parent.no_keywords"] = "No custom keywords added yet."
        d["settings.parent.custom_websites"] = "Custom Websites"
        d["settings.parent.add_website"] = "Add website (e.g. 'badsite.com')"
        d["settings.parent.no_websites"] = "No custom websites added yet."

        // Settings - Account
        d["settings.account"] = "Account"
        d["settings.account.guest"] = "Using as Guest"
        d["settings.account.guest_desc"] = "Your data is stored locally on this device only. Sign in to sync across devices."
        d["settings.account.sign_in"] = "Sign In"
        d["settings.account.exit_guest"] = "Exit Guest Mode"
        d["settings.account.delete"] = "Delete Account"
        d["settings.account.logout"] = "Logout"
        d["settings.account.login"] = "Login"
        d["settings.account.sync_desc"] = "Sign in to sync your preferences across devices"

        // Settings - Alerts
        d["settings.alert.logout.title"] = "Logout"
        d["settings.alert.logout.message"] = "Do you want to logout?"
        d["settings.alert.delete.title"] = "Delete Account"
        d["settings.alert.delete.message"] = "Are You Sure to delete account? This action cannot be undone."

        // Settings - PIN Entry
        d["settings.pin.title"] = "Enter Parent PIN"
        d["settings.pin.subtitle"] = "Enter your 4-digit PIN to access parent settings"
        d["settings.pin.placeholder"] = "PIN"
        d["settings.pin.error"] = "Incorrect PIN. Try again."
        d["settings.pin.biometric"] = "Use %@"

        // Settings - Localized UI Strings
        d["settings.logout_confirm"] = "Do you want to logout?"
        d["settings.delete_confirm"] = "Are you sure you want to delete your account? This action cannot be undone."
        d["settings.wellness_dashboard"] = "Wellness Dashboard"
        d["settings.wellness_desc"] = "Mood trends, conversations, growth metrics"
        d["settings.view_insights"] = "View Insights"
        d["settings.insights_desc"] = "See browsing activity and blocked content"
        d["settings.modify_filters"] = "Modify Filters"
        d["settings.custom_keywords"] = "Custom Keywords"
        d["settings.no_keywords"] = "No custom keywords added yet."
        d["settings.custom_websites"] = "Custom Websites"
        d["settings.no_websites"] = "No custom websites added yet."
        d["settings.using_guest"] = "Using as Guest"
        d["settings.guest_data_info"] = "Your data is stored locally on this device only. Sign in to sync across devices."
        d["settings.sign_in"] = "Sign In"
        d["settings.exit_guest"] = "Exit Guest Mode"
        d["settings.delete_account"] = "Delete Account"
        d["settings.logout"] = "Logout"
        d["settings.login"] = "Login"
        d["settings.sync_desc"] = "Sign in to sync your preferences across devices"
        d["settings.enter_pin"] = "Enter Parent PIN"
        d["settings.pin_desc"] = "Enter your 4-digit PIN to access parent settings"
        d["settings.incorrect_pin"] = "Incorrect PIN. Try again."
        d["settings.use_biometric"] = "Use %@"
        d["settings.enter"] = "Enter"

        // MARK: - Riki / Talk
        d["riki.choose_friend"] = "Choose a Friend"
        d["riki.who_chat"] = "Who would you like to chat with?"
        d["riki.typing"] = "Typing..."
        d["riki.online"] = "Online"
        d["riki.listening"] = "Listening..."
        d["riki.tap_send"] = "Tap to send"
        d["riki.tap_talk"] = "Tap to talk"
        d["riki.speaking"] = "%@ is speaking..."
        d["riki.error_fallback"] = "Oops! I got a little confused there. Can you try saying that again?"
        d["riki.how_feeling"] = "How are you feeling?"
        d["riki.friend_title"] = "%@ the Friend"

        // SEL emoji labels
        d["sel.happy"] = "Happy"
        d["sel.sad"] = "Sad"
        d["sel.angry"] = "Angry"
        d["sel.worried"] = "Worried"
        d["sel.grateful"] = "Grateful"
        d["sel.tired"] = "Tired"
        d["sel.happy_msg"] = "I'm feeling happy today!"
        d["sel.sad_msg"] = "I'm feeling a bit sad right now."
        d["sel.angry_msg"] = "I'm feeling angry about something."
        d["sel.worried_msg"] = "I'm feeling worried."
        d["sel.grateful_msg"] = "I'm feeling grateful!"
        d["sel.tired_msg"] = "I'm feeling really tired today."

        // Character greetings
        d["riki.greeting.momo"] = "Hey friend! I'm Momo. What's on your mind today?"
        d["riki.greeting.goldie"] = "Hey there! I'm Goldie, and I'm so happy to see you! What should we talk about?"
        d["riki.greeting.oreo"] = "Hello! I'm Oreo. Ready for a fun chat?"
        d["riki.greeting.leo"] = "Hey! I'm Leo. Tell me something brave about your day!"
        d["riki.greeting.bunny"] = "Hi there! I'm Bunny. What fun things have you been up to?"
        d["riki.greeting.tiki"] = "Hey! I'm Tiki. What adventure shall we go on today?"
        d["riki.greeting.fluffy"] = "Hi! I'm Fluffy. Come sit with me and let's have a cozy chat!"
        d["riki.greeting.kitty"] = "Hey! I'm Kitty. I've been napping and now I'm ready to chat!"
        d["riki.greeting.panda"] = "Hi there! I'm Panda. Want to hang out and chat for a bit?"
        d["riki.greeting.ellie"] = "Hey! I'm Ellie. I never forget my friends! What's new with you?"
        d["riki.greeting.ducky"] = "Hey! I'm Ducky. Let's make today a good one — what's going on?"

        // Character personalities
        d["riki.personality.momo"] = "A playful, curious monkey who loves climbing trees and exploring. Energetic and fun, loves jokes and riddles. Talks like a real buddy who's always up for an adventure."
        d["riki.personality.goldie"] = "A loyal, enthusiastic golden retriever. Loves playing fetch, going on walks, and making friends happy. Super supportive, always excited to hear what's going on in your life."
        d["riki.personality.oreo"] = "A clever, friendly monkey who loves puzzles and learning new things. Thoughtful and encouraging, great at helping you think through tricky stuff."
        d["riki.personality.leo"] = "A brave, kind lion who leads with courage. Encourages you to be brave, try new things, and believe in yourself. Warm and protective, like a big brother."
        d["riki.personality.bunny"] = "A gentle, sweet bunny who loves gardens, nature, and cozy things. A calming presence who's really good at listening and understanding how you feel."
        d["riki.personality.tiki"] = "An adventurous tiger who loves exploring and discovering new things. Brave but gentle, loves telling stories about nature and faraway places."
        d["riki.personality.fluffy"] = "A soft, warm-hearted sheep who loves comfort and kindness. Very gentle and calming, great at helping you with feelings and worries. Like a best friend who always makes you feel better."
        d["riki.personality.kitty"] = "A curious, independent cat who loves cozy spots and being playful. Witty and fun, sometimes a little cheeky but always kind at heart."
        d["riki.personality.panda"] = "A chill, lovable panda who enjoys taking it easy and being silly. Laid-back and funny, always knows how to make you laugh with goofy comments."
        d["riki.personality.ellie"] = "A wise, caring elephant with a great memory. Thoughtful and nurturing, loves sharing fun facts and helping you learn new things. Like a really smart friend who makes learning feel easy."
        d["riki.personality.ducky"] = "A cheerful, bubbly duck who loves being upbeat and positive. Great at cheering you up when things feel tough, always finds the bright side."

        // MARK: - Reflection
        d["reflect.title"] = "Reflection Time"
        d["reflect.how_feeling"] = "How are you feeling right now?"
        d["reflect.select_emotion"] = "Select an emotion to begin"
        d["reflect.session.title"] = "Guided Reflection"
        d["reflect.session.breathe"] = "Let's take a deep breath together"
        d["reflect.session.think_about"] = "Think about..."
        d["reflect.session.complete"] = "Great reflection!"
        d["reflect.session.done"] = "You did great! Remember, it's okay to feel any emotion."
        d["reflect.coping.title"] = "Coping Strategies"
        d["reflect.coping.try_this"] = "Try this:"

        // Emotions
        d["reflect.emotion.happy"] = "Happy"
        d["reflect.emotion.sad"] = "Sad"
        d["reflect.emotion.angry"] = "Angry"
        d["reflect.emotion.scared"] = "Scared"
        d["reflect.emotion.worried"] = "Worried"
        d["reflect.emotion.calm"] = "Calm"
        d["reflect.emotion.excited"] = "Excited"
        d["reflect.emotion.confused"] = "Confused"
        d["reflect.emotion.tired"] = "Tired"
        d["reflect.emotion.lonely"] = "Lonely"
        d["reflect.emotion.grateful"] = "Grateful"
        d["reflect.emotion.frustrated"] = "Frustrated"

        // Reflection exercises
        d["reflect.exercise.gratitude"] = "Name 3 things you're grateful for today"
        d["reflect.exercise.breathing"] = "Deep Breathing"
        d["reflect.exercise.body_scan"] = "Body Scan"
        d["reflect.exercise.journaling"] = "Write about your feelings"

        // Coping strategies
        d["reflect.coping.deep_breath"] = "Take 5 deep breaths"
        d["reflect.coping.talk"] = "Talk to someone you trust"
        d["reflect.coping.move"] = "Go for a walk or stretch"
        d["reflect.coping.create"] = "Draw or write about how you feel"
        d["reflect.coping.music"] = "Listen to your favorite music"
        d["reflect.coping.count"] = "Count backwards from 10"

        // MARK: - Digital Journey
        d["journey.title"] = "Digital Journey"
        d["journey.tab.insights"] = "AI Insights"
        d["journey.tab.history"] = "History"
        d["journey.analyzing"] = "Analyzing browsing activity..."
        d["journey.no_history"] = "No browsing history yet"
        d["journey.history_will_appear"] = "History will appear here as your child browses"
        d["journey.needs_attention"] = "Needs Attention"
        d["journey.allowed_links"] = "Allowed Links"
        d["journey.loading_history"] = "Loading browsing history..."
        d["journey.time_range"] = "Time Range"
        d["journey.links"] = "links"
        d["journey.filter.all"] = "All"
        d["journey.filter.blocked"] = "Blocked"
        d["journey.filter.gated"] = "Gated"
        d["journey.filter.allowed"] = "Allowed"
        d["journey.range.1h"] = "1 Hour"
        d["journey.range.3h"] = "3 Hours"
        d["journey.range.6h"] = "6 Hours"
        d["journey.range.12h"] = "12 Hours"
        d["journey.range.24h"] = "24 Hours"
        d["journey.range.all"] = "All Time"

        // MARK: - Browser
        d["browser.address_placeholder"] = "Search or enter URL"
        d["browser.loading"] = "Loading..."
        d["browser.new_tab"] = "New Tab"
        d["browser.tabs"] = "Tabs"
        d["browser.no_open_tabs"] = "No open tabs"
        d["browser.close_tab"] = "Close Tab"
        d["browser.menu"] = "Menu"
        d["browser.share"] = "Share"
        d["browser.reload"] = "Reload"
        d["browser.forward"] = "Forward"
        d["browser.history"] = "History"
        d["browser.homepage"] = "Homepage"
        d["browser.quick_checkin"] = "How are you feeling?"
        d["browser.search_or_url"] = "Search or type URL"
        d["browser.past_tabs"] = "Past Tabs"
        d["browser.no_past_tabs"] = "No past tabs yet"
        d["browser.tabs_appear_here"] = "Websites you visit will appear here"

        // MARK: - Blocked Content
        d["blocked.title"] = "Content Blocked"
        d["blocked.not_available"] = "This content isn't available"
        d["blocked.keeping_safe"] = "Komal is keeping you safe!"
        d["blocked.message"] = "This page has been blocked for your safety."
        d["blocked.reason"] = "Reason: %@"
        d["blocked.ask_parent"] = "Ask a parent if you need access."
        d["blocked.go_back"] = "Go Back"
        d["blocked.countdown"] = "Going back in %d..."
        d["blocked.emoji_prompt"] = "How does this make you feel?"
        d["blocked.tap_talk"] = "Tap to talk to Komal"
        d["blocked.fallback_response"] = "I'm here for you. Let's go explore something fun together!"

        // MARK: - Chat Content Filtering
        d["chat.content_redirect"] = "Hey, that's not something I can chat about! How about we talk about something fun instead? What's your favorite thing to do after school?"
        d["browser.checking_page"] = "Checking this page for you..."
        d["blocked.hi_there"] = "Hi there! 👋"
        d["blocked.find_something_else"] = "Let's find something else!"
        d["blocked.friendly_1"] = "I'm sorry, but this content isn't available right now. Let's find something else fun to explore together! 🌟"
        d["blocked.friendly_2"] = "This isn't quite right for us right now. How about we look for something else that's awesome? 💙"
        d["blocked.friendly_3"] = "Let's skip this one and find something even better! I'm here to help you discover great things! 🎈"
        d["blocked.friendly_4"] = "This content isn't available at the moment. Want to explore something else together? 😊"

        // MARK: - Gate (parent approval)
        d["gate.title"] = "Gated content"
        d["gate.riki_pause"] = "Riki suggests a pause"
        d["gate.touches_on"] = "This page touches on %@. Let's check in before continuing."
        d["gate.start_break"] = "Start Mindful Break"
        d["gate.parent_approval"] = "Parent approval"
        d["gate.enter_pin"] = "Enter parent PIN"
        d["gate.approve_continue"] = "Approve and Continue"
        d["gate.access_gated"] = "Access is gated for %@ (%@)."
        d["gate.message"] = "This content needs parent approval to access."

        // MARK: - Emoji Check-in
        d["checkin.how_feeling"] = "How're you feeling exploring this?"
        d["checkin.how_are_you"] = "How are you feeling?"
        d["checkin.hi_there"] = "Hi there! 👋"
        d["checkin.intro_message"] = "I'm Komal, and I'm here surfing the internet with you! How are you feeling right now?"
        d["checkin.thanks_komal"] = "Thanks, Komal! 😊"
        d["checkin.emotion.happy"] = "Happy"
        d["checkin.emotion.okay"] = "Okay"
        d["checkin.emotion.sad"] = "Sad"
        d["checkin.emotion.tired"] = "Tired"
        d["checkin.emotion.curious"] = "Curious"
        d["checkin.emotion.excited"] = "Excited"
        d["checkin.response.happy"] = "That's wonderful! I'm so glad you're having a good time exploring! 🌟"
        d["checkin.response.okay"] = "That's alright! If you need anything, I'm here to help! 💙"
        d["checkin.response.sad"] = "I'm sorry you're feeling that way. Would you like to take a break? 🫂"
        d["checkin.response.tired"] = "It's okay to rest! Maybe we can explore more later? 😴"
        d["checkin.response.curious"] = "I love your curiosity! What are you wondering about? 🤔"
        d["checkin.response.excited"] = "That's awesome! I'm excited to explore with you too! 🎉"

        // MARK: - Mindful Break
        d["mindful.title"] = "Mindful Break"
        d["mindful.pause_message"] = "Take a gentle pause. Notice your breath and the room around you."
        d["mindful.im_ready"] = "I'm ready"

        // MARK: - Filter Preferences
        d["filter.content_settings"] = "Content Settings"
        d["filter.customize"] = "Customize what content is allowed"
        d["filter.block"] = "Block"
        d["filter.gate"] = "Gate"
        d["filter.allow"] = "Allow"

        // MARK: - Intervention
        d["intervention.tip"] = "It's okay to be curious - that's how we learn!"
        d["intervention.lets_think"] = "Let's think about it..."
        d["intervention.share_thoughts"] = "Share your thoughts..."
        d["intervention.done_reflecting"] = "Done reflecting"
        d["intervention.lets_talk"] = "Let's Talk About It"
        d["intervention.go_back"] = "Go Back to Safety"
        d["intervention.main.search"] = "Hey, I noticed you searched for something..."
        d["intervention.main.url"] = "Hold on a moment!"
        d["intervention.main.image"] = "I found something we should talk about"
        d["intervention.main.page"] = "This page has some grown-up content"
        d["intervention.sub.search"] = "Curiosity is totally normal! But some topics are better to explore with a trusted grown-up."
        d["intervention.sub.url"] = "This website might have content meant for adults. Would you like to talk about what you're looking for?"
        d["intervention.sub.image"] = "I spotted something that might not be appropriate. Let's chat about it."
        d["intervention.sub.page"] = "Some of what's here is for older people. Want to talk, or find something else?"
        d["intervention.reflect.search"] = "What made you curious about this?"
        d["intervention.reflect.url"] = "What were you hoping to find?"
        d["intervention.reflect.image"] = "How did seeing that make you feel?"
        d["intervention.reflect.page"] = "Is there something you had questions about?"

        // MARK: - Reflection Time
        d["reflect.title"] = "Reflection Time"
        d["reflect.welcome.title"] = "Welcome to Reflection Time"
        d["reflect.welcome.subtitle"] = "15 minutes of mindful digital wellness"
        d["reflect.remaining"] = "remaining"
        d["reflect.feelings.title"] = "Feelings Check-In"
        d["reflect.feelings.desc"] = "Explore and understand your emotions"
        d["reflect.mindfulness.title"] = "Mindfulness Exercise"
        d["reflect.mindfulness.desc"] = "Calm breathing and relaxation"
        d["reflect.guided.title"] = "Guided Reflection"
        d["reflect.guided.desc"] = "Think about your digital experiences"
        d["reflect.free_chat.title"] = "Free Chat"
        d["reflect.free_chat.desc"] = "Talk about anything on your mind"
        d["reflect.sel.title"] = "How Are You Feeling?"
        d["reflect.sel.subtitle"] = "It's okay to feel any emotion. Let's explore together."
        d["reflect.sel.intensity"] = "How strong is this feeling?"
        d["reflect.sel.a_little"] = "A little"
        d["reflect.sel.a_lot"] = "A lot"
        d["reflect.sel.things_help"] = "Things that might help:"
        d["reflect.mindfulness.header"] = "Mindfulness"
        d["reflect.mindfulness.calm_mind"] = "Take a moment to calm your mind"
        d["reflect.going_deeper"] = "Going deeper..."
        d["reflect.thinking_followup"] = "Thinking of a follow-up..."
        d["reflect.previous"] = "Previous"
        d["reflect.next"] = "Next"
        d["reflect.free_chat.placeholder"] = "Type your thoughts..."
        d["reflect.free_chat.thinking"] = "Thinking..."
        d["reflect.completion.title"] = "Great Job!"
        d["reflect.completion.subtitle"] = "You completed your Reflection Time"
        d["reflect.completion.message"] = "Taking time to reflect helps you understand yourself better and stay healthy online."

        // MARK: - SEL Emotions
        d["reflect.emotion.happy"] = "Happy"
        d["reflect.emotion.sad"] = "Sad"
        d["reflect.emotion.angry"] = "Angry"
        d["reflect.emotion.worried"] = "Worried"
        d["reflect.emotion.tired"] = "Tired"
        d["reflect.emotion.excited"] = "Excited"
        d["reflect.emotion.okay"] = "Okay"
        d["reflect.emotion.confused"] = "Confused"

        // MARK: - Coping Strategies
        d["reflect.coping.sad.1"] = "Talk to someone you trust"
        d["reflect.coping.sad.2"] = "Draw or write about your feelings"
        d["reflect.coping.sad.3"] = "Listen to your favorite music"
        d["reflect.coping.sad.4"] = "Give yourself a hug"
        d["reflect.coping.angry.1"] = "Take 5 deep breaths"
        d["reflect.coping.angry.2"] = "Count backwards from 10"
        d["reflect.coping.angry.3"] = "Squeeze a stress ball"
        d["reflect.coping.angry.4"] = "Go for a short walk"
        d["reflect.coping.worried.1"] = "Tell an adult how you feel"
        d["reflect.coping.worried.2"] = "Think of 3 things you're grateful for"
        d["reflect.coping.worried.3"] = "Imagine your happy place"
        d["reflect.coping.worried.4"] = "Take slow, deep breaths"
        d["reflect.coping.tired.1"] = "Rest your eyes for a minute"
        d["reflect.coping.tired.2"] = "Drink some water"
        d["reflect.coping.tired.3"] = "Stretch your body"
        d["reflect.coping.tired.4"] = "Take a break from screens"
        d["reflect.coping.default.1"] = "Share your feelings with someone"
        d["reflect.coping.default.2"] = "Do something you enjoy"
        d["reflect.coping.default.3"] = "Take a mindful moment"
        d["reflect.coping.default.4"] = "Be kind to yourself"

        // MARK: - Mindfulness Exercises
        d["reflect.exercise.box.title"] = "Box Breathing"
        d["reflect.exercise.box.desc"] = "A calming technique used by athletes and astronauts"
        d["reflect.exercise.box.step1"] = "Breathe in for 4 seconds"
        d["reflect.exercise.box.step2"] = "Hold for 4 seconds"
        d["reflect.exercise.box.step3"] = "Breathe out for 4 seconds"
        d["reflect.exercise.box.step4"] = "Hold for 4 seconds"
        d["reflect.exercise.box.step5"] = "Repeat 4 times"
        d["reflect.exercise.grounding.title"] = "5-4-3-2-1 Grounding"
        d["reflect.exercise.grounding.desc"] = "Connect with the present moment"
        d["reflect.exercise.grounding.step1"] = "Notice 5 things you can SEE"
        d["reflect.exercise.grounding.step2"] = "Notice 4 things you can TOUCH"
        d["reflect.exercise.grounding.step3"] = "Notice 3 things you can HEAR"
        d["reflect.exercise.grounding.step4"] = "Notice 2 things you can SMELL"
        d["reflect.exercise.grounding.step5"] = "Notice 1 thing you can TASTE"
        d["reflect.exercise.bodyscan.title"] = "Body Scan"
        d["reflect.exercise.bodyscan.desc"] = "Relax your body from head to toe"
        d["reflect.exercise.bodyscan.step1"] = "Relax your forehead and eyes"
        d["reflect.exercise.bodyscan.step2"] = "Relax your jaw and shoulders"
        d["reflect.exercise.bodyscan.step3"] = "Relax your arms and hands"
        d["reflect.exercise.bodyscan.step4"] = "Relax your stomach"
        d["reflect.exercise.bodyscan.step5"] = "Relax your legs and feet"
        d["reflect.exercise.gratitude.title"] = "Gratitude Moment"
        d["reflect.exercise.gratitude.desc"] = "Focus on the good things in life"
        d["reflect.exercise.gratitude.step1"] = "Think of someone who makes you happy"
        d["reflect.exercise.gratitude.step2"] = "Think of something you're good at"
        d["reflect.exercise.gratitude.step3"] = "Think of a place that makes you feel safe"
        d["reflect.exercise.gratitude.step4"] = "Think of a happy memory"
        d["reflect.exercise.gratitude.step5"] = "Smile and feel grateful"
        d["reflect.breathe.inhale"] = "Breathe In"
        d["reflect.breathe.hold"] = "Hold"
        d["reflect.breathe.exhale"] = "Breathe Out"

        // MARK: - Reflection Questions
        d["reflect.q1.question"] = "What was the best thing you saw online today?"
        d["reflect.q1.prompt"] = "Share something that made you smile or feel good..."
        d["reflect.q2.question"] = "Did anything online make you feel uncomfortable?"
        d["reflect.q2.prompt"] = "It's okay to talk about things that bothered you..."
        d["reflect.q3.question"] = "What did you learn today from the internet?"
        d["reflect.q3.prompt"] = "Share something interesting you discovered..."
        d["reflect.q4.question"] = "How much time did you spend on screens today?"
        d["reflect.q4.prompt"] = "Was it too much, just right, or not enough?"
        d["reflect.q5.question"] = "What would you like to do offline tomorrow?"
        d["reflect.q5.prompt"] = "Think of fun activities away from screens..."

        // MARK: - Free Chat Greetings
        d["reflect.chat.greeting.1"] = "Hi! This is a safe space to share your thoughts. What's on your mind today?"
        d["reflect.chat.greeting.2"] = "Hey there! I'm here to listen. Tell me about something interesting that happened."
        d["reflect.chat.greeting.3"] = "Welcome! You can talk about anything here. What would you like to chat about?"
        d["reflect.chat.fallback.1"] = "Thank you for sharing that with me. How does that make you feel?"
        d["reflect.chat.fallback.2"] = "I hear you. That sounds really important to you."
        d["reflect.chat.fallback.3"] = "It's great that you're talking about this. Tell me more?"
        d["reflect.chat.fallback.4"] = "I understand. It's okay to feel that way."
        d["reflect.chat.fallback.5"] = "Thanks for trusting me with that. What else is on your mind?"

        // MARK: - Insights View
        d["insights.view.title"] = "Insights"
        d["insights.overview"] = "Overview"
        d["insights.sites_visited"] = "Sites Visited"
        d["insights.blocked"] = "Blocked"
        d["insights.gated"] = "Gated"
        d["insights.sessions"] = "Sessions"
        d["insights.content_categories"] = "Content Categories"
        d["insights.activity_timeline"] = "Activity Timeline"
        d["insights.recent_sessions"] = "Recent Sessions"
        d["insights.no_sessions"] = "No browsing sessions yet"
        d["insights.protection_summary"] = "Protection Summary"
        d["insights.images_protected"] = "Images Protected"
        d["insights.of_scanned"] = "of %d scanned"
        d["insights.sites_blocked"] = "Sites Blocked"
        d["insights.harmful_content"] = "harmful content"
        d["insights.engagement"] = "Engagement"
        d["insights.avg_time_page"] = "Average Time per Page"
        d["insights.avg_scroll_depth"] = "Average Scroll Depth"
        d["insights.meaningful_engagement"] = "Meaningful Engagement"
        d["insights.most_engaged"] = "Most Engaged Sites"
        d["insights.visits"] = "%d visits"
        d["insights.avg_time"] = "avg time"
        d["insights.browsing_patterns"] = "Browsing Patterns"
        d["insights.session_depth"] = "Session Depth"
        d["insights.pages"] = "%d pages"
        d["insights.how_deep"] = "How deep into sites"
        d["insights.back_navigation"] = "Back Navigation"
        d["insights.returning_pages"] = "Returning to previous pages"
        d["insights.quick_visits"] = "Quick Visits"
        d["insights.pages_under_10s"] = "Pages viewed < 10 seconds"
        d["insights.content_viewed"] = "Content Viewed"
        d["insights.words_read"] = "Words Read"
        d["insights.images"] = "Images"
        d["insights.videos"] = "Videos"
        d["insights.topics"] = "Topics"
        d["insights.avg_time_short"] = "Avg Time"
        d["insights.reading"] = "Reading"
        d["insights.concerning_content"] = "Concerning Content Detected"
        d["insights.keywords"] = "Keywords: %@"
        d["insights.found_on_pages"] = "Found on %d page(s)"
        d["insights.recent_pages"] = "Recent Pages Viewed"
        d["insights.topics_viewed"] = "Topics Viewed:"
        d["insights.flagged"] = "Flagged: %@"
        d["insights.avg_time_per_page"] = "Avg time per page"

        // MARK: - Anchor - Morning
        d["anchor.morning.title"] = "Good Morning!"
        d["anchor.morning.greeting"] = "Good Morning!"
        d["anchor.morning.subtitle"] = "How are you feeling this morning?"
        d["anchor.morning.how_feeling"] = "How are you feeling today?"
        d["anchor.morning.how_strong"] = "How strong is this feeling?"
        d["anchor.morning.set_intention"] = "Set your intention for today"
        d["anchor.morning.looking_forward"] = "What are you looking forward to today?"
        d["anchor.morning.intention_placeholder"] = "Today I want to..."
        d["anchor.morning.looking_forward_placeholder"] = "Something fun, a class, seeing a friend..."
        d["anchor.morning.ready"] = "I'm ready for today!"
        d["anchor.morning.start_my_day"] = "Start My Day!"

        // MARK: - Anchor - Evening
        d["anchor.evening.title"] = "Evening Reflection"
        d["anchor.evening.greeting"] = "Good Evening!"
        d["anchor.evening.subtitle"] = "How was your day?"
        d["anchor.evening.wind_down"] = "Let's wind down together"
        d["anchor.evening.how_feeling"] = "How are you feeling tonight?"
        d["anchor.evening.best_part"] = "What was the best part of your day?"
        d["anchor.evening.best_placeholder"] = "The best part was..."
        d["anchor.evening.best_part_placeholder"] = "Tell me about it..."
        d["anchor.evening.anything_bothering"] = "Anything bothering you?"
        d["anchor.evening.bothering_placeholder"] = "It's okay to share..."
        d["anchor.evening.learned"] = "What did you learn today?"
        d["anchor.evening.learned_placeholder"] = "I learned..."
        d["anchor.evening.deep_breaths"] = "Take 3 deep breaths"
        d["anchor.evening.breathe_in_out"] = "Breathe in... and out..."
        d["anchor.evening.goodnight"] = "Goodnight!"
        d["anchor.evening.good_night"] = "Good Night!"

        // MARK: - Reconnection
        d["reconnection.title"] = "Welcome Back!"
        d["reconnection.welcome_back"] = "Welcome Back!"
        d["reconnection.subtitle"] = "We missed you! It's been a while."
        d["reconnection.ellie_greeting"] = "It's Ellie! I never forget my friends, and I'm so happy to see you again!"
        d["reconnection.days_since"] = "It's been %d days since we last hung out."
        d["reconnection.hi_ellie"] = "Hi Ellie!"
        d["reconnection.how_have_you_been"] = "How have you been?"
        d["reconnection.mood_great"] = "Great!"
        d["reconnection.mood_okay"] = "Okay"
        d["reconnection.mood_not_great"] = "Not great"
        d["reconnection.response_great"] = "That's wonderful to hear! Let's keep the good vibes going."
        d["reconnection.response_not_great"] = "I'm sorry to hear that. Remember, I'm always here for you."
        d["reconnection.response_okay"] = "Good to know! Let's hang out and have some fun."
        d["reconnection.what_to_do"] = "What would you like to do?"
        d["reconnection.browse_web"] = "Browse the Web"
        d["reconnection.chat_friend"] = "Chat with a Friend"
        d["reconnection.reflection_time"] = "Reflection Time"
        d["reconnection.whats_new"] = "Here's what's new since you were away"
        d["reconnection.lets_go"] = "Let's Go!"
        d["reconnection.missed_days"] = "You've been away for %d days"

        // MARK: - Growth / Journey
        d["growth.title"] = "My Journey"
        d["growth.milestones"] = "Milestones"
        d["growth.weekly_snapshot"] = "Weekly Snapshot"
        d["growth.noticed_about_you"] = "What we've noticed about you:"
        d["growth.day_streak"] = "Day Streak"
        d["growth.this_week"] = "This Week"
        d["growth.active_days"] = "Active Days"
        d["growth.chats"] = "Chats"
        d["growth.reflections"] = "Reflections"
        d["growth.moods"] = "Moods"
        d["growth.streak"] = "Streak"
        d["growth.days"] = "days"
        d["growth.level"] = "Level"
        d["growth.explorer"] = "Explorer"
        d["growth.adventurer"] = "Adventurer"
        d["growth.champion"] = "Champion"
        d["growth.legend"] = "Legend"
        d["growth.earned"] = "Earned!"
        d["growth.locked"] = "Keep going!"
        d["growth.snapshot.title"] = "Your Week in Review"
        d["growth.snapshot.conversations"] = "Conversations"
        d["growth.snapshot.reflections"] = "Reflections"
        d["growth.snapshot.browsing_time"] = "Browsing Time"
        d["growth.snapshot.mood_checks"] = "Mood Checks"
        d["growth.snapshot.mood_checkins"] = "Mood Check-ins"
        d["growth.snapshot.most_common_mood"] = "Most Common Mood"
        d["growth.snapshot.favorite_friend"] = "Favorite Friend"
        d["growth.snapshot.growth_insight"] = "Growth Insight"
        d["growth.snapshot.keep_going"] = "Keep Going!"

        // MARK: - Parent Insights
        d["insights.title"] = "Parent Insights"
        d["insights.wellness"] = "Wellness Overview"
        d["insights.mood_trends"] = "Mood Trends"
        d["insights.chat_activity"] = "Chat Activity"
        d["insights.browsing_summary"] = "Browsing Summary"
        d["insights.alerts"] = "Alerts"
        d["insights.no_alerts"] = "No alerts to show"
        d["insights.this_week"] = "This Week"
        d["insights.this_month"] = "This Month"

        // MARK: - Parent Insights Dashboard
        d["insights.dashboard.title"] = "Child Wellness"
        d["insights.dashboard.this_week_vs_last"] = "This Week vs Last"
        d["insights.dashboard.chats"] = "Chats"
        d["insights.dashboard.reflections"] = "Reflections"
        d["insights.dashboard.moods"] = "Moods"
        d["insights.dashboard.active_days"] = "Active Days"
        d["insights.dashboard.conversation_starter"] = "Tonight's Conversation Starter"
        d["insights.dashboard.generating_starter"] = "Generating a conversation starter..."
        d["insights.dashboard.starter_placeholder"] = "Use the app for a few days to get personalized conversation starters."
        d["insights.dashboard.daily_insight"] = "Daily Insight"
        d["insights.dashboard.generating_insight"] = "Generating insight..."
        d["insights.dashboard.insight_placeholder"] = "Insights will appear as your child uses the app more."
        d["insights.dashboard.emotional_wellness"] = "Emotional Wellness"
        d["insights.dashboard.last_7_days"] = "Last 7 Days"
        d["insights.dashboard.emotion_distribution"] = "30-Day Emotion Distribution"
        d["insights.dashboard.no_mood_data"] = "No mood data yet. Mood entries will appear here as your child uses the app."
        d["insights.dashboard.conversation_insights"] = "Conversation Insights"
        d["insights.dashboard.messages"] = "Messages"
        d["insights.dashboard.characters_used"] = "Characters Used"
        d["insights.dashboard.popular_topics"] = "Popular Topics"
        d["insights.dashboard.growth_metrics"] = "Growth Metrics"
        d["insights.dashboard.current_streak"] = "Current Streak"
        d["insights.dashboard.milestones"] = "Milestones"
        d["insights.dashboard.active_days_30d"] = "Active Days (30d)"
        d["insights.dashboard.activity_30d"] = "30-Day Activity"
        d["insights.dashboard.engagement_quality"] = "Engagement Quality"
        d["insights.dashboard.voluntary_returns"] = "Voluntary Returns"
        d["insights.dashboard.avg_reflection_depth"] = "Avg Reflection Depth"
        d["insights.dashboard.total_sessions"] = "Total Sessions"
        d["insights.dashboard.voluntary_returns_explanation"] = "Higher voluntary return rates indicate genuine engagement rather than notification-driven usage."
        d["insights.dashboard.daily_checkins"] = "Daily Check-ins"
        d["insights.dashboard.morning"] = "Morning"
        d["insights.dashboard.evening"] = "Evening"
        d["insights.dashboard.wellness_alert"] = "Wellness Alert"
        d["insights.dashboard.wellness_alert_message"] = "Your child has reported feeling sad for 3 or more consecutive check-ins. Consider having a gentle conversation about how they're feeling."

        // MARK: - Browsing History
        d["history.title"] = "Browsing History"
        d["history.loading"] = "Loading browsing history..."
        d["history.today"] = "Today"
        d["history.yesterday"] = "Yesterday"
        d["history.earlier"] = "Earlier"
        d["history.no_history"] = "No browsing history yet"
        d["history.empty_message"] = "History will appear here as your child browses."
        d["history.time_range"] = "Time Range"
        d["history.pages"] = "pages"
        d["history.emoji_journey"] = "Emoji Journey"
        d["history.summary"] = "Summary"
        d["history.pages_visited"] = "Pages Visited"
        d["history.session_detail"] = "Session Detail"
        d["history.back_label"] = "History"
        d["history.clear"] = "Clear History"
        d["history.clear_confirm"] = "Are you sure you want to clear all browsing history?"

        // MARK: - Contextual Prompts
        d["prompt.welcome_back"] = "Welcome back! Ready to explore?"
        d["prompt.take_break"] = "You've been browsing for a while. Take a break?"
        d["prompt.try_reflect"] = "How about checking in with your feelings?"
        d["prompt.chat_riki"] = "Want to chat with a friend?"
        d["prompt.new_milestone"] = "You earned a new milestone!"
        d["prompt.dismiss"] = "Maybe later"
        d["prompt.lets_go"] = "Let's go!"
        d["prompt.curiosity_noticed"] = "I noticed something interesting today... Want to hear about it?"
        d["prompt.curiosity_learned"] = "Curious about what I learned from you? You might be surprised!"
        d["prompt.curiosity_question_young"] = "I have a super fun question for you! Want to play?"
        d["prompt.growth_calm"] = "You handled that calmly. How did you do that?"
        d["prompt.growth_evolved"] = "Your thinking has really evolved. Want to see how far you've come?"
        d["prompt.growth_proud_young"] = "Wow, you're getting so good at this! I'm really proud of you!"
        d["prompt.growth_streak_celebrate"] = "Look at that streak! You're building something amazing, one day at a time."
        d["prompt.brave_question"] = "Can I ask you something brave? It might surprise you."
        d["prompt.brave_future"] = "What would future-you say about today? Let's find out."
        d["prompt.brave_try_young"] = "Want to try something new together? I believe in you!"
        d["prompt.transition_reflect"] = "Quick reflection before you go? Just 2 minutes."
        d["prompt.transition_progress"] = "Want to see your progress map? You've been busy!"
        d["prompt.return_changed"] = "Something small changed while you were away. Want to see?"
        d["prompt.return_secret"] = "Want to see a secret insight about yourself? I saved it for you."
        d["prompt.return_missed_young"] = "Yay, you're back! I missed you! Want to play together?"
        d["prompt.emotional_check_negative"] = "Hey, I noticed you might be having a tough time. I'm here for you."
        d["prompt.emotional_celebrate_positive"] = "You seem to be in a great mood! That's wonderful to see."
        d["prompt.browsing_learned"] = "Learned something cool while browsing? I'd love to hear about it!"
        d["prompt.browsing_break"] = "How are you feeling right now? Want to do a quick check-in?"
        d["prompt.browsing_riddle_young"] = "Want to take a fun break? I've got a riddle for you!"
        d["prompt.reflect_done_great"] = "That was a really thoughtful reflection. You should be proud of yourself."
        d["prompt.reflect_deeper_teen"] = "Nice reflection. Want to go a little deeper? Sometimes the best insights come next."
        d["prompt.action.tell_me"] = "Tell me!"
        d["prompt.action.show_me"] = "Show me"
        d["prompt.action.lets_play"] = "Let's play!"
        d["prompt.action.let_me_think"] = "Let me think..."
        d["prompt.action.show_my_growth"] = "Show my growth"
        d["prompt.action.see_my_journey"] = "See my journey"
        d["prompt.action.go_ahead"] = "Go ahead"
        d["prompt.action.lets_explore"] = "Let's explore"
        d["prompt.action.lets_try"] = "Let's try!"
        d["prompt.action.sure"] = "Sure!"
        d["prompt.action.show_me_excited"] = "Show me!"
        d["prompt.action.what_changed"] = "What changed?"
        d["prompt.action.talk_about_it"] = "Talk about it"
        d["prompt.action.lets_chat"] = "Let's chat"
        d["prompt.action.check_in"] = "Check in"
        d["prompt.action.go_deeper"] = "Go deeper"

        // MARK: - Notifications
        d["notification.morning.title"] = "Good Morning!"
        d["notification.morning.body"] = "Momo here! Let's start your day with a quick check-in. How are you feeling?"
        d["notification.evening.title"] = "Time to Wind Down"
        d["notification.evening.body"] = "Hey, it's Bunny! Let's take a moment to reflect on your day together."
        d["notification.reconnect.title"] = "We Miss You!"
        d["notification.reconnect.body"] = "Ellie here - I never forget my friends! Come back and say hi, I have something fun to share."
        d["notification.milestone.title"] = "New Milestone!"
        d["notification.milestone.body"] = "You've earned a new achievement. Check it out!"

        // MARK: - Mood History
        d["mood.history.title"] = "Mood History"
        d["mood.history.recent"] = "Recent Moods"
        d["mood.history.no_entries"] = "No mood entries yet"
        d["mood.history.trend"] = "Your mood trend"

        // MARK: - Scan Results
        d["scan.overall_safety_score"] = "Overall Safety Score"
        d["scan.scanned"] = "Scanned"
        d["scan.live_analysis"] = "Live Analysis"
        d["scan.demo_mode"] = "Demo Mode"
        d["scan.blocked_under_16"] = "Blocked Under 16"
        d["scan.out_of_100"] = "/100"
        d["scan.age_appropriate_actions"] = "Age-Appropriate Actions"
        d["scan.score"] = "Score"
        d["scan.safety_risks_detected"] = "Safety Risks Detected"
        d["scan.matches"] = "matches"
        d["scan.content_analysis"] = "Content Analysis"
        d["scan.nlp_text_analysis"] = "NLP Text Analysis"
        d["scan.sentiment"] = "Sentiment:"
        d["scan.language_score"] = "Language Score:"
        d["scan.key_topics"] = "Key Topics:"
        d["scan.vision_ai_analysis"] = "Vision AI Analysis"
        d["scan.visual_safety_score"] = "Visual Safety Score:"
        d["scan.detected_objects"] = "Detected Objects:"

        // MARK: - Screen Time
        d["screentime.minimal"] = "30 min/day"
        d["screentime.moderate"] = "1-2 hours/day"
        d["screentime.flexible"] = "Flexible"

        return d
    }()
}
// swiftlint:enable file_length type_body_length
