// swiftlint:disable file_length type_body_length
enum EnglishStrings {
    static let all: [String: String] = {
        var d = [String: String]()

        // MARK: - Common
        d["common.back"] = "back"
        d["common.continue"] = "continue"
        d["common.done"] = "done"
        d["common.skip"] = "skip"
        d["common.cancel"] = "cancel"
        d["common.save"] = "save"
        d["common.delete"] = "delete"
        d["common.yes"] = "yes"
        d["common.no"] = "no"
        d["common.ok"] = "ok"
        d["common.close"] = "close"
        d["common.enter"] = "enter"
        d["common.next"] = "next"
        d["common.settings"] = "settings"
        d["common.selected_count"] = "%d/%d selected"
        d["common.step_of"] = "step %@"

        // MARK: - Splash
        d["splash.title"] = "Komal"
        d["splash.tagline"] = "your digital buddy"

        // MARK: - Login
        d["login.welcome"] = "welcome to Komal"
        d["login.tagline"] = "safe browsing for kids"
        d["login.sign_in_google"] = "sign in with Google"
        d["login.sign_in_apple"] = "sign in with Apple"
        d["login.or"] = "or"
        d["login.guest_user"] = "continue as guest"
        d["login.signing_in"] = "signing in..."
        d["login.failed"] = "login failed"
        d["login.try_again"] = "try again"
        d["login.guest.welcome"] = "welcome, guest!"
        d["login.guest.description"] = "your data will be stored locally on this device. you can sign in later to sync across devices."
        d["login.guest.getting_started"] = "getting started"
        d["login.onboarding.welcome"] = "welcome to Komal!"
        d["login.onboarding.description"] = "let's set up your safe browsing experience."
        d["login.onboarding.get_started"] = "get started"

        // MARK: - Onboarding Welcome
        d["onboarding.welcome.title"] = "child safety assessment"
        d["onboarding.welcome.subtitle"] = "evidence-based digital wellbeing profile"
        d["onboarding.welcome.card1.title"] = "developmental psychology"
        d["onboarding.welcome.card1.desc"] = "settings tailored to cognitive development stages as defined by child psychology research."
        d["onboarding.welcome.card2.title"] = "behavioral analysis"
        d["onboarding.welcome.card2.desc"] = "understanding browsing patterns to create personalized safety boundaries."
        d["onboarding.welcome.card3.title"] = "proactive protection"
        d["onboarding.welcome.card3.desc"] = "content filtering based on identified risk factors and preferences."
        d["onboarding.welcome.time_estimate"] = "this assessment takes approximately 3-4 minutes"
        d["onboarding.welcome.begin"] = "begin assessment"
        d["onboarding.welcome.language"] = "language"

        // MARK: - Onboarding Child Info
        d["onboarding.info.step"] = "1 of 6"
        d["onboarding.info.title"] = "basic information"
        d["onboarding.info.subtitle"] = "help us understand who we're protecting"
        d["onboarding.info.name_label"] = "child's first name"
        d["onboarding.info.name_placeholder"] = "enter name"
        d["onboarding.info.age_label"] = "age group"
        d["onboarding.info.age_desc"] = "Content restrictions are calibrated based on developmental milestones"
        d["onboarding.info.research_note"] = "Research shows that age-appropriate content boundaries support healthy cognitive development and reduce anxiety in children."

        // Age group descriptions
        d["onboarding.age.under10"] = "Early childhood - Maximum protection"
        d["onboarding.age.10to13"] = "Pre-teen - Guided exploration"
        d["onboarding.age.13to16"] = "Teen - Balanced boundaries"
        d["onboarding.age.16to18"] = "Late teen - Age-appropriate freedom"
        d["onboarding.age.18plus"] = "Adult - Full access"

        // MARK: - Onboarding Websites
        d["onboarding.websites.step"] = "2 of 6"
        d["onboarding.websites.title"] = "Favorite Websites"
        d["onboarding.websites.subtitle"] = "Select up to 5 websites your child visits most"
        d["onboarding.websites.desc"] = "Understanding browsing habits helps us identify trusted sources and personalize protection."

        // MARK: - Onboarding Interests
        d["onboarding.interests.step"] = "3 of 6"
        d["onboarding.interests.title"] = "Topics of Interest"
        d["onboarding.interests.subtitle"] = "What does your child enjoy learning about?"
        d["onboarding.interests.desc"] = "Select 3-5 topics. This helps us understand what content to prioritize and protect."

        // Interest names
        d["onboarding.interest.gaming"] = "Gaming"
        d["onboarding.interest.animals"] = "Animals"
        d["onboarding.interest.science"] = "Science"
        d["onboarding.interest.art"] = "Art & Drawing"
        d["onboarding.interest.music"] = "Music"
        d["onboarding.interest.sports"] = "Sports"
        d["onboarding.interest.coding"] = "Coding"
        d["onboarding.interest.reading"] = "Reading"
        d["onboarding.interest.cooking"] = "Cooking"
        d["onboarding.interest.nature"] = "Nature"
        d["onboarding.interest.space"] = "Space"
        d["onboarding.interest.history"] = "History"
        d["onboarding.interest.movies"] = "Movies"
        d["onboarding.interest.crafts"] = "Crafts"
        d["onboarding.interest.dinosaurs"] = "Dinosaurs"
        d["onboarding.interest.vehicles"] = "Vehicles"
        d["onboarding.interest.fashion"] = "Fashion"
        d["onboarding.interest.dance"] = "Dance"
        d["onboarding.interest.photography"] = "Photography"
        d["onboarding.interest.travel"] = "Travel"
        d["onboarding.interest.math"] = "Math"
        d["onboarding.interest.puzzles"] = "Puzzles"
        d["onboarding.interest.robots"] = "Robots"
        d["onboarding.interest.magic"] = "Magic"
        d["onboarding.interest.superheroes"] = "Superheroes"
        d["onboarding.interest.gardening"] = "Gardening"
        d["onboarding.interest.astronomy"] = "Astronomy"
        d["onboarding.interest.languages"] = "Languages"
        d["onboarding.interest.boardgames"] = "Board Games"
        d["onboarding.interest.swimming"] = "Swimming"
        d["onboarding.interest.comics"] = "Comics"
        d["onboarding.interest.yoga"] = "Yoga"
        d["onboarding.interest.theater"] = "Theater"

        // MARK: - Onboarding Likes
        d["onboarding.likes.step"] = "4 of 6"
        d["onboarding.likes.title"] = "What They Enjoy Online"
        d["onboarding.likes.subtitle"] = "Understanding positive online experiences"
        d["onboarding.likes.desc"] = "Select activities your child enjoys. This helps us ensure they have access to enriching content."
        d["onboarding.likes.other"] = "Other (optional)"
        d["onboarding.likes.other_placeholder"] = "Add something else they enjoy..."

        // Like options
        d["onboarding.like.watching_videos"] = "Watching videos"
        d["onboarding.like.playing_games"] = "Playing games"
        d["onboarding.like.chatting"] = "Chatting with friends"
        d["onboarding.like.learning"] = "Learning new things"
        d["onboarding.like.creative"] = "Creative projects"
        d["onboarding.like.exploring"] = "Exploring websites"
        d["onboarding.like.music"] = "Listening to music"
        d["onboarding.like.virtual_worlds"] = "Virtual worlds"
        d["onboarding.like.puzzles"] = "Puzzles & challenges"
        d["onboarding.like.funny"] = "Funny content"
        d["onboarding.like.stories"] = "Stories & books"
        d["onboarding.like.making_videos"] = "Making videos"
        d["onboarding.like.drawing"] = "Drawing & painting"
        d["onboarding.like.photography"] = "Taking photos"
        d["onboarding.like.coding"] = "Coding & programming"
        d["onboarding.like.reading_comics"] = "Reading comics"
        d["onboarding.like.collecting"] = "Collecting things"
        d["onboarding.like.building"] = "Building & crafting"
        d["onboarding.like.cooking_videos"] = "Cooking videos"
        d["onboarding.like.science_experiments"] = "Science experiments"
        d["onboarding.like.dancing"] = "Dancing"
        d["onboarding.like.trivia"] = "Trivia & quizzes"
        d["onboarding.like.anime"] = "Anime & cartoons"
        d["onboarding.like.podcasts"] = "Podcasts"
        d["onboarding.like.shopping"] = "Online shopping"
        d["onboarding.like.live_streams"] = "Watching live streams"

        // MARK: - Onboarding Dislikes
        d["onboarding.dislikes.step"] = "5 of 6"
        d["onboarding.dislikes.title"] = "What Bothers Them"
        d["onboarding.dislikes.subtitle"] = "Identifying triggers and discomforts"
        d["onboarding.dislikes.desc"] = "Select things that upset or concern your child online. This helps us filter potentially distressing content."
        d["onboarding.dislikes.other"] = "Other concerns (optional)"
        d["onboarding.dislikes.other_placeholder"] = "Add other things that bother them..."
        d["onboarding.dislikes.research_note"] = "Understanding what distresses children online allows us to proactively filter content before exposure, reducing anxiety and negative experiences."

        // Dislike options
        d["onboarding.dislike.scary"] = "Scary content"
        d["onboarding.dislike.loud"] = "Loud noises/jumpscares"
        d["onboarding.dislike.mean"] = "Mean comments"
        d["onboarding.dislike.strangers"] = "Strangers messaging"
        d["onboarding.dislike.violent"] = "Violent games"
        d["onboarding.dislike.sad"] = "Sad stories"
        d["onboarding.dislike.ads"] = "Confusing ads"
        d["onboarding.dislike.reading"] = "Too much reading"
        d["onboarding.dislike.timed"] = "Timed challenges"
        d["onboarding.dislike.losing"] = "Losing in games"
        d["onboarding.dislike.popups"] = "Pop-up videos"
        d["onboarding.dislike.rushed"] = "Being rushed"

        // MARK: - Onboarding Concerns
        d["onboarding.concerns.step"] = "6 of 8"
        d["onboarding.concerns.title"] = "Your Concerns"
        d["onboarding.concerns.subtitle"] = "What worries you most about your child online?"
        d["onboarding.concerns.desc"] = "Select your top concerns. We'll prioritize protection in these areas."

        // Concern items
        d["onboarding.concern.cyberbullying"] = "Cyberbullying"
        d["onboarding.concern.cyberbullying.desc"] = "Harassment, mean messages, exclusion"
        d["onboarding.concern.inappropriate"] = "Inappropriate Content"
        d["onboarding.concern.inappropriate.desc"] = "Violence, mature themes, explicit material"
        d["onboarding.concern.predators"] = "Online Predators"
        d["onboarding.concern.predators.desc"] = "Strangers, grooming, personal info requests"
        d["onboarding.concern.addiction"] = "Screen Addiction"
        d["onboarding.concern.addiction.desc"] = "Excessive use, difficulty stopping"
        d["onboarding.concern.privacy"] = "Privacy Risks"
        d["onboarding.concern.privacy.desc"] = "Data collection, location sharing"
        d["onboarding.concern.misinfo"] = "Misinformation"
        d["onboarding.concern.misinfo.desc"] = "Fake news, conspiracy theories"
        d["onboarding.concern.scams"] = "Financial Scams"
        d["onboarding.concern.scams.desc"] = "In-app purchases, phishing"
        d["onboarding.concern.mental"] = "Mental Health"
        d["onboarding.concern.mental.desc"] = "Anxiety, comparison, FOMO"

        // MARK: - Onboarding Filters
        d["onboarding.filters.step"] = "7 of 8"
        d["onboarding.filters.title"] = "Content Filters"
        d["onboarding.filters.subtitle"] = "Review and customize content filtering"
        d["onboarding.filters.desc"] = "These defaults are based on your child's age and your concerns. Adjust any setting below."

        // MARK: - Onboarding PIN
        d["onboarding.pin.step"] = "8 of 8"
        d["onboarding.pin.title"] = "Set Parent PIN"
        d["onboarding.pin.subtitle"] = "Create a PIN to protect parent settings"
        d["onboarding.pin.desc"] = "This PIN will be required to access parent mode and approve gated content."
        d["onboarding.pin.enter"] = "Enter PIN"
        d["onboarding.pin.placeholder"] = "4-digit PIN"
        d["onboarding.pin.confirm"] = "Confirm PIN"
        d["onboarding.pin.confirm_placeholder"] = "Confirm PIN"
        d["onboarding.pin.mismatch"] = "PINs do not match. Please try again."
        d["onboarding.pin.weak"] = "This PIN is too common. Please choose a stronger one."
        d["onboarding.pin.enable_biometric"] = "Enable %@"
        d["onboarding.pin.use_biometric"] = "Use %@ instead of PIN"
        d["onboarding.pin.research_note"] = "A parent PIN ensures only authorized adults can modify safety settings and approve gated content."

        // MARK: - Onboarding Guided Access
        d["onboarding.guided_access.title"] = "lock your child's device"
        d["onboarding.guided_access.subtitle"] = "keep your child safely in Komal"
        d["onboarding.guided_access.explanation"] = "Guided Access prevents children from leaving the app or switching to other apps."
        d["onboarding.guided_access.step1_title"] = "open accessibility settings"
        d["onboarding.guided_access.step1_detail"] = "tap the button below — it opens your iPhone's Accessibility page. scroll down and look for \"Guided Access\" near the bottom."
        d["onboarding.guided_access.step2_title"] = "turn on Guided Access"
        d["onboarding.guided_access.step2_detail"] = "tap \"Guided Access\" then flip the switch to green (ON). it will ask you to set a passcode — pick something you'll remember (your child won't know this code)."
        d["onboarding.guided_access.step3_title"] = "come back & lock the app"
        d["onboarding.guided_access.step3_detail"] = "switch back to Komal. when you're ready to hand the device to your child, triple-click the side button (or home button on older iPhones) to lock them into Komal."
        d["onboarding.guided_access.open_settings"] = "open settings"
        d["onboarding.guided_access.open_accessibility"] = "tap here to open accessibility settings"
        d["onboarding.guided_access.return_hint"] = "after turning on Guided Access, come back here — we'll detect it automatically!"
        d["onboarding.guided_access.enabled_title"] = "Guided Access is enabled!"
        d["onboarding.guided_access.enabled_explanation"] = "great job! now when you hand the device to your child, triple-click the side button to lock them into Komal. triple-click again and enter your passcode to unlock."
        d["onboarding.guided_access.research_note"] = "Single-app mode is recommended by child safety researchers to prevent unsupervised app switching on shared devices."

        // MARK: - Guided Access Reminder
        d["guided_access.reminder.title"] = "activate Guided Access"
        d["guided_access.reminder.explanation"] = "Guided Access locks the device to Komal so your child can't switch apps."
        d["guided_access.reminder.step1"] = "tap the button below to open Accessibility settings, then scroll down to find \"Guided Access\""
        d["guided_access.reminder.step2"] = "tap Guided Access, flip the switch to green, and set a passcode only you know"
        d["guided_access.reminder.step3"] = "come back to Komal, then triple-click the side button to lock your child in"
        d["guided_access.reminder.open_accessibility"] = "open accessibility settings"
        d["guided_access.reminder.enabled_title"] = "Guided Access is ready!"
        d["guided_access.reminder.enabled_explanation"] = "triple-click the side button to lock your child into Komal."
        d["guided_access.reminder.got_it"] = "got it"
        d["guided_access.reminder.done"] = "done"
        d["guided_access.reminder.dont_remind"] = "don't remind me again"

        // MARK: - Avatar Selection
        d["onboarding.avatar.title"] = "choose your buddy"
        d["onboarding.avatar.subtitle"] = "pick an animal friend to be your guide!"
        d["settings.avatar.title"] = "your avatar"
        d["settings.avatar.change"] = "tap to change your avatar"

        // MARK: - Onboarding Completion
        d["onboarding.complete.title"] = "profile complete"
        d["onboarding.complete.subtitle"] = "%@'s safety profile is ready"
        d["onboarding.complete.summary"] = "assessment summary"
        d["onboarding.complete.name"] = "name"
        d["onboarding.complete.age_group"] = "age group"
        d["onboarding.complete.interests"] = "interests"
        d["onboarding.complete.concerns"] = "key concerns"
        d["onboarding.complete.adjust_note"] = "settings can be adjusted anytime in the app"
        d["onboarding.complete.start"] = "start using Komal"
        d["onboarding.complete.review"] = "review answers"

        // MARK: - Menu / Navigation
        d["menu.browse"] = "browse"
        d["menu.talk"] = "talk"
        d["menu.reflect"] = "reflect"
        d["menu.settings"] = "settings"

        // MARK: - Plan Selection
        d["plan.choose_title"] = "Choose Your Plan"
        d["plan.choose_subtitle"] = "Pick the right level of protection for your family"
        d["plan.start_essentials"] = "Start with Essentials"
        d["plan.subscribe_to"] = "Subscribe to %@"
        d["plan.restore_purchases"] = "Restore Purchases"
        d["plan.purchase_error"] = "Purchase Error"
        d["plan.unavailable"] = "This plan is currently unavailable. Please try again later."
        d["plan.recommended"] = "RECOMMENDED"
        d["plan.free"] = "Free"
        d["plan.per_month"] = "%@/month"
        d["plan.loading"] = "Loading..."
        d["plan.profiles_up_to"] = "Up to %d child profiles"
        d["plan.profiles_unlimited"] = "Unlimited child profiles"

        // MARK: - Settings
        d["settings.title"] = "settings"
        d["settings.language"] = "language"
        d["settings.whos_using"] = "who's using?"
        d["settings.whos_using.desc"] = "select who is currently using the device"
        d["settings.child"] = "child"
        d["settings.child.subtitle"] = "safe browsing"
        d["settings.parent"] = "parent"
        d["settings.parent.subtitle"] = "full access"

        // Settings - Child Mode
        d["settings.child.greeting"] = "hi %@!"
        d["settings.child.greeting_default"] = "hi there!"
        d["settings.child.safe_msg"] = "Komal is here to keep you safe while you explore!"
        d["settings.child.chatty"] = "feeling chatty?"
        d["settings.child.chatty.desc"] = "talk to your buddy! your friendly companion is always here to chat and help you out."
        d["settings.child.go_talk"] = "go to talk"
        d["settings.child.profile"] = "your profile"
        d["settings.child.explorer"] = "explorer"
        d["settings.child.age"] = "age: %@"
        d["settings.child.journey"] = "my journey"
        d["settings.child.day_streak"] = "day streak"
        d["settings.child.milestones"] = "milestones"
        d["settings.child.view_journey"] = "view my journey"

        // Settings - Parent Mode
        d["settings.parent.digital_journey"] = "digital journey"
        d["settings.parent.view_journey"] = "view digital journey"
        d["settings.parent.journey_desc"] = "see your child's browsing activity with AI insights"
        d["settings.parent.wellness"] = "child wellness"
        d["settings.parent.wellness_dashboard"] = "wellness dashboard"
        d["settings.parent.wellness_desc"] = "mood trends, conversations, growth metrics"
        d["settings.parent.morning_checkin"] = "morning check-in"
        d["settings.parent.morning_desc"] = "daily morning mood anchor"
        d["settings.parent.evening_winddown"] = "evening wind-down"
        d["settings.parent.evening_desc"] = "daily evening reflection anchor"
        d["settings.parent.child_profile"] = "child profile"
        d["settings.parent.name_label"] = "name"
        d["settings.parent.name_placeholder"] = "child's name"
        d["settings.parent.age_label"] = "age group"
        d["settings.parent.controls"] = "parent controls"
        d["settings.parent.notify_block"] = "notify on block"
        d["settings.parent.notify_desc"] = "get alerts when blocked content is accessed"
        d["settings.parent.safe_search"] = "force safe search"
        d["settings.parent.safe_search_desc"] = "enforce strict safety on search engines"
        d["settings.parent.view_insights"] = "view insights"
        d["settings.parent.insights_desc"] = "see browsing activity and blocked content"
        d["settings.parent.modify_content"] = "modify content"
        d["settings.parent.modify_filters"] = "modify filters"
        d["settings.parent.custom_keywords"] = "custom keywords"
        d["settings.parent.add_keyword"] = "add keyword (e.g. 'weapons')"
        d["settings.parent.no_keywords"] = "no custom keywords added yet."
        d["settings.parent.custom_websites"] = "custom websites"
        d["settings.parent.add_website"] = "add website (e.g. 'badsite.com')"
        d["settings.parent.no_websites"] = "no custom websites added yet."

        // Settings - Account
        d["settings.account"] = "account"
        d["settings.account.guest"] = "using as guest"
        d["settings.account.guest_desc"] = "your data is stored locally on this device only. sign in to sync across devices."
        d["settings.account.sign_in"] = "sign in"
        d["settings.account.exit_guest"] = "exit guest mode"
        d["settings.account.delete"] = "delete account"
        d["settings.account.logout"] = "logout"
        d["settings.account.login"] = "login"
        d["settings.account.sync_desc"] = "sign in to sync your preferences across devices"

        // Settings - Alerts
        d["settings.alert.logout.title"] = "logout"
        d["settings.alert.logout.message"] = "do you want to logout?"
        d["settings.alert.delete.title"] = "delete account"
        d["settings.alert.delete.message"] = "are you sure you want to delete your account? this action cannot be undone."

        // Settings - PIN Entry
        d["settings.pin.title"] = "enter parent PIN"
        d["settings.pin.subtitle"] = "enter your 4-digit PIN to access parent settings"
        d["settings.pin.placeholder"] = "PIN"
        d["settings.pin.error"] = "incorrect PIN. try again."
        d["settings.pin.biometric"] = "use %@"

        // Settings - Subscription & Billing
        d["settings.view_plans"] = "view all plans and pricing"
        d["settings.billing_invoices"] = "billing & invoices"
        d["settings.billing_desc"] = "view transaction history and receipts"
        d["settings.manage_appstore"] = "manage in App Store"
        d["settings.manage_appstore_desc"] = "cancel, renew, or update payment method"
        d["settings.current_plan"] = "current plan"
        d["settings.per_month"] = "per month"
        d["settings.next_renewal"] = "Next renewal: %@"
        d["settings.transaction_history"] = "Transaction History"
        d["settings.no_transactions"] = "No transactions yet"
        d["settings.transactions_placeholder"] = "Your purchase history will appear here"
        d["settings.subscriptions_info"] = "Subscriptions are managed through your Apple ID. To request a refund, visit reportaproblem.apple.com"
        d["settings.plan_monthly"] = "%@ Monthly"

        // Settings - PIN Management
        d["settings.change_pin"] = "change PIN"
        d["settings.change_pin_desc"] = "set a new 4-digit parent PIN"
        d["settings.forgot_pin"] = "forgot PIN? reset with %@"
        d["settings.pin_updated"] = "PIN updated"
        d["settings.pin_saved_msg"] = "your new parent PIN has been saved."
        d["settings.set_new_pin"] = "set new PIN"
        d["settings.new_pin_desc"] = "enter a new 4-digit parent PIN"
        d["settings.pin_mismatch"] = "PINs don't match or are incomplete"
        d["settings.new_pin_placeholder"] = "New PIN"
        d["settings.confirm_pin_placeholder"] = "Confirm PIN"
        d["settings.save_pin"] = "save PIN"

        // Settings - Localized UI Strings
        d["settings.logout_confirm"] = "Do you want to logout?"
        d["settings.delete_confirm"] = "Are you sure you want to delete your account? This action cannot be undone."
        d["settings.wellness_dashboard"] = "wellness dashboard"
        d["settings.wellness_desc"] = "mood trends, conversations, growth metrics"
        d["settings.view_insights"] = "view insights"
        d["settings.insights_desc"] = "see browsing activity and blocked content"
        d["settings.modify_filters"] = "modify filters"
        d["settings.custom_keywords"] = "custom keywords"
        d["settings.no_keywords"] = "no custom keywords added yet."
        d["settings.custom_websites"] = "custom websites"
        d["settings.no_websites"] = "no custom websites added yet."
        d["settings.using_guest"] = "using as guest"
        d["settings.guest_data_info"] = "your data is stored locally on this device only. sign in to sync across devices."
        d["settings.sign_in"] = "sign in"
        d["settings.exit_guest"] = "exit guest mode"
        d["settings.delete_account"] = "delete account"
        d["settings.logout"] = "logout"
        d["settings.login"] = "login"
        d["settings.sync_desc"] = "sign in to sync your preferences across devices"
        d["settings.enter_pin"] = "enter parent PIN"
        d["settings.pin_desc"] = "enter your 4-digit PIN to access parent settings"
        d["settings.incorrect_pin"] = "incorrect PIN. try again."
        d["settings.use_biometric"] = "use %@"
        d["settings.enter"] = "enter"
        d["settings.sel_journey"] = "SEL journey"
        d["settings.view_sel_report"] = "view SEL report"
        d["settings.sel_progress_desc"] = "track your child's social-emotional learning progress"

        // MARK: - Riki / Talk
        d["riki.choose_friend"] = "choose a friend"
        d["riki.who_chat"] = "who would you like to chat with?"
        d["riki.typing"] = "typing..."
        d["riki.online"] = "online"
        d["riki.listening"] = "listening..."
        d["riki.tap_send"] = "tap to send"
        d["riki.tap_talk"] = "tap to talk"
        d["riki.speaking"] = "%@ is speaking..."
        d["riki.error_fallback"] = "oops! I got a little confused there. can you try saying that again?"
        d["riki.friend_title"] = "%@ the friend"
        d["riki.paused"] = "paused"
        d["riki.tap_resume"] = "tap to resume"

        // SEL emoji labels
        d["sel.happy"] = "Happy"
        d["sel.sad"] = "Sad"
        d["sel.angry"] = "Angry"
        d["sel.worried"] = "Worried"
        d["sel.grateful"] = "Grateful"
        d["sel.tired"] = "Tired"
        // Character greetings
        d["riki.greeting.momo"] = "Hey friend! I'm Momo. What's on your mind today?"
        d["riki.greeting.goldie"] = "Hey there! I'm Goldie, and I'm so happy to see you! What should we talk about?"
        d["riki.greeting.oreo"] = "Hello! I'm Oreo. Ready for a fun chat?"
        d["riki.greeting.leo"] = "Hey! I'm Leo. Tell me something brave about your day!"
        d["riki.greeting.bunny"] = "Hi there! I'm Bunny. What fun things have you been up to?"
        d["riki.greeting.tiki"] = "Hey! I'm Tiki. What adventure shall we go on today?"
        d["riki.greeting.fluffy"] = "Hi! I'm Fluffy. Come sit with me and let's have a cozy chat!"
        d["riki.greeting.kitty"] = "Hey! I'm Kitty. I've been napping and now I'm ready to chat!"
        d["riki.greeting.panda"] = "Hi there! I'm Panda. Want to hang out and chat for a bit?"
        d["riki.greeting.ellie"] = "Hey! I'm Ellie. I never forget my friends! What's new with you?"
        d["riki.greeting.ducky"] = "Hey! I'm Ducky. Let's make today a good one — what's going on?"

        // Character personalities
        d["riki.personality.momo"] = "A playful, curious monkey who loves climbing trees and exploring. Energetic and fun, loves jokes and riddles. Talks like a real buddy who's always up for an adventure."
        d["riki.personality.goldie"] = "A loyal, enthusiastic golden retriever. Loves playing fetch, going on walks, and making friends happy. Super supportive, always excited to hear what's going on in your life."
        d["riki.personality.oreo"] = "A clever, friendly monkey who loves puzzles and learning new things. Thoughtful and encouraging, great at helping you think through tricky stuff."
        d["riki.personality.leo"] = "A brave, kind lion who leads with courage. Encourages you to be brave, try new things, and believe in yourself. Warm and protective, like a big brother."
        d["riki.personality.bunny"] = "A gentle, sweet bunny who loves gardens, nature, and cozy things. A calming presence who's really good at listening and understanding how you feel."
        d["riki.personality.tiki"] = "An adventurous tiger who loves exploring and discovering new things. Brave but gentle, loves telling stories about nature and faraway places."
        d["riki.personality.fluffy"] = "A soft, warm-hearted sheep who loves comfort and kindness. Very gentle and calming, great at helping you with feelings and worries. Like a best friend who always makes you feel better."
        d["riki.personality.kitty"] = "A curious, independent cat who loves cozy spots and being playful. Witty and fun, sometimes a little cheeky but always kind at heart."
        d["riki.personality.panda"] = "A chill, lovable panda who enjoys taking it easy and being silly. Laid-back and funny, always knows how to make you laugh with goofy comments."
        d["riki.personality.ellie"] = "A wise, caring elephant with a great memory. Thoughtful and nurturing, loves sharing fun facts and helping you learn new things. Like a really smart friend who makes learning feel easy."
        d["riki.personality.ducky"] = "A cheerful, bubbly duck who loves being upbeat and positive. Great at cheering you up when things feel tough, always finds the bright side."

        // MARK: - Reflection
        d["reflect.title"] = "reflection time"
        d["reflect.daily_checkin"] = "Daily Check-In"
        d["reflect.how_feeling"] = "how are you feeling right now?"
        d["reflect.session.title"] = "guided reflection"
        d["reflect.session.breathe"] = "let's take a deep breath together"
        d["reflect.session.think_about"] = "think about..."
        d["reflect.session.complete"] = "great reflection!"
        d["reflect.session.done"] = "you did great! remember, it's okay to feel any emotion."
        d["reflect.coping.title"] = "coping strategies"
        d["reflect.coping.try_this"] = "try this:"

        // Emotions

        // Reflection exercises
        d["reflect.exercise.gratitude"] = "Name 3 things you're grateful for today"
        d["reflect.exercise.breathing"] = "Deep Breathing"
        d["reflect.exercise.body_scan"] = "Body Scan"
        d["reflect.exercise.journaling"] = "Write about your feelings"

        // Coping strategies
        d["reflect.coping.deep_breath"] = "Take 5 deep breaths"
        d["reflect.coping.talk"] = "Talk to someone you trust"
        d["reflect.coping.move"] = "Go for a walk or stretch"
        d["reflect.coping.create"] = "Draw or write about how you feel"
        d["reflect.coping.music"] = "Listen to your favorite music"
        d["reflect.coping.count"] = "Count backwards from 10"

        // MARK: - Digital Journey
        d["journey.title"] = "digital journey"
        d["journey.tab.insights"] = "AI insights"
        d["journey.tab.history"] = "history"
        d["journey.analyzing"] = "analyzing browsing activity..."
        d["journey.no_history"] = "no browsing history yet"
        d["journey.history_will_appear"] = "Browsing activity will appear here as your child uses the browser. Switch to the History tab to see local session data."
        d["journey.history_empty_hint"] = "Your child's browsing sessions will be recorded here automatically."
        d["journey.ai_insights"] = "AI Insights"
        d["journey.history"] = "History"
        d["journey.no_activity"] = "No activity recorded yet"
        d["journey.time_spent"] = "Time Spent"
        d["journey.sites_visited"] = "Sites Visited"
        d["journey.blocked_attempts"] = "Blocked Attempts"
        d["journey.needs_attention"] = "Needs Attention"
        d["journey.allowed_links"] = "Allowed Links"
        d["journey.loading_history"] = "Loading browsing history..."
        d["journey.time_range"] = "Time Range"
        d["journey.links"] = "links"
        d["journey.filter.all"] = "All"
        d["journey.filter.blocked"] = "Blocked"
        d["journey.filter.gated"] = "Gated"
        d["journey.filter.allowed"] = "Allowed"
        d["journey.range.1h"] = "1 Hour"
        d["journey.range.3h"] = "3 Hours"
        d["journey.range.6h"] = "6 Hours"
        d["journey.range.12h"] = "12 Hours"
        d["journey.range.24h"] = "24 Hours"
        d["journey.range.all"] = "All Time"

        // MARK: - Browser
        d["browser.address_placeholder"] = "search or enter URL"
        d["browser.loading"] = "loading..."
        d["browser.new_tab"] = "new tab"
        d["browser.tabs"] = "tabs"
        d["browser.no_open_tabs"] = "no open tabs"
        d["browser.close_tab"] = "close tab"
        d["browser.menu"] = "menu"
        d["browser.share"] = "share"
        d["browser.reload"] = "reload"
        d["browser.forward"] = "forward"
        d["browser.history"] = "history"
        d["browser.homepage"] = "homepage"
        d["browser.quick_checkin"] = "quick check-in"
        d["browser.search_or_url"] = "search or type URL"
        d["browser.past_tabs"] = "past tabs"
        d["browser.no_past_tabs"] = "no past tabs yet"
        d["browser.tabs_appear_here"] = "websites you visit will appear here"

        // MARK: - Blocked Content
        d["blocked.title"] = "content blocked"
        d["blocked.not_available"] = "this content isn't available"
        d["blocked.keeping_safe"] = "Komal is keeping you safe!"
        d["blocked.message"] = "this page has been blocked for your safety."
        d["blocked.reason"] = "reason: %@"
        d["blocked.ask_parent"] = "ask a parent if you need access."
        d["blocked.go_back"] = "go back"
        d["blocked.countdown"] = "going back in %d..."
        d["blocked.emoji_prompt"] = "how does this make you feel?"
        d["blocked.tap_talk"] = "tap to talk to Komal"
        d["blocked.fallback_response"] = "I'm here for you. Let's go explore something fun together!"

        // MARK: - Chat Content Filtering
        d["chat.content_redirect"] = "Hey, that's not something I can chat about! How about we talk about something fun instead? What's your favorite thing to do after school?"
        d["browser.checking_page"] = "Checking this page for you..."
        d["browser.before_you_go"] = "Before You Go"
        d["browser.content_filtered"] = "This content has been filtered for your safety."
        d["browser.content_unverified"] = "This content could not be verified as safe."
        d["blocked.hi_there"] = "Hey there!"
        d["blocked.find_something_else"] = "Let's find something else!"
        d["blocked.educational.1"] = "That page isn't quite right for exploring right now. How about we find something amazing together?"
        d["blocked.educational.2"] = "Some corners of the internet need a grown-up guide. Let's discover something cool instead!"
        d["blocked.educational.3"] = "There's so much to explore! Let's find a path that leads to something awesome."
        d["blocked.educational.4"] = "Not every door needs opening today. Let's find one that leads somewhere great!"
        d["blocked.friendly_1"] = "I'm sorry, but this content isn't available right now. Let's find something else fun to explore together! 🌟"
        d["blocked.friendly_2"] = "This isn't quite right for us right now. How about we look for something else that's awesome? 💙"
        d["blocked.friendly_3"] = "Let's skip this one and find something even better! I'm here to help you discover great things! 🎈"
        d["blocked.friendly_4"] = "This content isn't available at the moment. Want to explore something else together? 😊"

        // MARK: - Gate (parent approval)
        d["gate.title"] = "gated content"
        d["gate.riki_pause"] = "your buddy suggests a pause"
        d["gate.touches_on"] = "this page touches on %@. let's check in before continuing."
        d["gate.start_break"] = "start mindful break"
        d["gate.parent_approval"] = "parent approval"
        d["gate.enter_pin"] = "enter parent PIN"
        d["gate.approve_continue"] = "approve and continue"
        d["gate.access_gated"] = "access is gated for %@ (%@)."
        d["gate.message"] = "this content needs parent approval to access."
        d["gate.wrong_pin"] = "incorrect PIN. try again."
        d["gate.locked_out"] = "too many attempts. try again in %d seconds."
        d["gate.no_pin_set"] = "no parental PIN has been set. please set one in Settings first."

        // MARK: - Emoji Check-in
        d["checkin.how_feeling"] = "how're you feeling exploring this?"
        d["checkin.how_are_you"] = "how are you feeling today?"
        d["checkin.whats_on_your_mind"] = "what's on your mind?"
        d["checkin.hi_there"] = "hi there! 👋"
        d["checkin.intro_message"] = "I'm Komal, and I'm here surfing the internet with you! How are you feeling right now?"
        d["checkin.thanks_komal"] = "Thanks, Komal! 😊"
        d["checkin.emotion.happy"] = "Happy"
        d["checkin.emotion.okay"] = "Okay"
        d["checkin.emotion.sad"] = "Sad"
        d["checkin.emotion.tired"] = "Tired"
        d["checkin.emotion.curious"] = "Curious"
        d["checkin.emotion.excited"] = "Excited"
        d["checkin.response.happy"] = "That's wonderful! I'm so glad you're having a good time exploring! 🌟"
        d["checkin.response.okay"] = "That's alright! If you need anything, I'm here to help! 💙"
        d["checkin.response.sad"] = "I'm sorry you're feeling that way. Would you like to take a break? 🫂"
        d["checkin.response.tired"] = "It's okay to rest! Maybe we can explore more later? 😴"
        d["checkin.response.curious"] = "I love your curiosity! What are you wondering about? 🤔"
        d["checkin.response.excited"] = "That's awesome! I'm excited to explore with you too! 🎉"

        // MARK: - Mindful Break
        d["mindful.title"] = "mindful break"
        d["mindful.pause_message"] = "take a gentle pause. notice your breath and the room around you."
        d["mindful.im_ready"] = "i'm ready"

        // MARK: - Filter Preferences
        d["filter.content_settings"] = "content settings"
        d["filter.customize"] = "customize what content is allowed"
        d["filter.block"] = "block"
        d["filter.gate"] = "gate"
        d["filter.allow"] = "allow"

        // MARK: - Intervention
        d["intervention.tip"] = "It's okay to be curious - that's how we learn!"
        d["intervention.lets_think"] = "Let's think about it..."
        d["intervention.share_thoughts"] = "Share your thoughts..."
        d["intervention.done_reflecting"] = "Done reflecting"
        d["intervention.lets_talk"] = "Let's Talk About It"
        d["intervention.go_back"] = "Go Back to Safety"
        d["intervention.main.search"] = "Hey, I noticed you searched for something..."
        d["intervention.main.url"] = "Hold on a moment!"
        d["intervention.main.image"] = "I found something we should talk about"
        d["intervention.main.page"] = "This page has some grown-up content"
        d["intervention.sub.search"] = "Curiosity is totally normal! But some topics are better to explore with a trusted grown-up."
        d["intervention.sub.url"] = "This website might have content meant for adults. Would you like to talk about what you're looking for?"
        d["intervention.sub.image"] = "I spotted something that might not be appropriate. Let's chat about it."
        d["intervention.sub.page"] = "Some of what's here is for older people. Want to talk, or find something else?"
        d["intervention.reflect.search"] = "What made you curious about this?"
        d["intervention.reflect.url"] = "What were you hoping to find?"
        d["intervention.reflect.image"] = "How did seeing that make you feel?"
        d["intervention.reflect.page"] = "Is there something you had questions about?"

        // MARK: - Reflection Time
        d["reflect.feelings.title"] = "feelings check-in"
        d["reflect.feelings.desc"] = "explore and understand your emotions"
        d["reflect.mindfulness.title"] = "mindfulness exercise"
        d["reflect.mindfulness.desc"] = "calm breathing and relaxation"
        d["reflect.guided.title"] = "guided reflection"
        d["reflect.guided.desc"] = "think about your digital experiences"
        d["reflect.free_chat.title"] = "free chat"
        d["reflect.free_chat.desc"] = "talk about anything on your mind"
        d["reflect.sel.title"] = "how are you feeling?"
        d["reflect.sel.subtitle"] = "it's okay to feel any emotion. let's explore together."
        d["reflect.sel.things_help"] = "things that might help:"

        // MARK: - SEL Insights
        d["sel.insight.no_data"] = "Complete your first SEL session to start tracking growth."
        d["sel.insight.improving"] = "Great progress! Keep up the excellent work."
        d["sel.insight.improving_with_strengths"] = "Great progress! Strong in %@."
        d["sel.insight.growth_areas"] = "%@ could use more support. Consider more practice in these areas."
        d["sel.insight.balanced"] = "Well-balanced development across all domains. Keep it up!"

        // MARK: - SEL Domain Labels
        d["sel.domain.social_communication"] = "Social Communication"
        d["sel.domain.emotional_intelligence"] = "Emotional Intelligence"
        d["sel.domain.cognitive_development"] = "Cognitive Development"
        d["sel.domain.life_skills"] = "Life Skills"
        d["sel.domain.language_development"] = "Language Development"

        // MARK: - SEL Competency Labels (mock data)
        d["sel.mock.check_fallback"] = "Check"
        d["sel.competency.sc.1"] = "Initiates greetings"
        d["sel.competency.sc.2"] = "Starts conversations"
        d["sel.competency.sc.3"] = "Responds to invitations"
        d["sel.competency.ei.1"] = "Identifies emotions"
        d["sel.competency.ei.2"] = "Understands feelings"
        d["sel.competency.ei.3"] = "Shows empathy"
        d["sel.competency.cd.1"] = "Problem solving"
        d["sel.competency.cd.2"] = "Sequential thinking"
        d["sel.competency.cd.3"] = "Logical reasoning"
        d["sel.competency.ls.1"] = "Safety awareness"
        d["sel.competency.ls.2"] = "Self-care routines"
        d["sel.competency.ls.3"] = "Healthy choices"
        d["sel.competency.ld.1"] = "Describes events"
        d["sel.competency.ld.2"] = "Answers questions"
        d["sel.competency.ld.3"] = "Shares experiences"

        // MARK: - SEL Scenarios: Social Communication
        d["sel.sc1.title"] = "New Friend at School"
        d["sel.sc1.narrative"] = "A new kid joins your class and sits alone at lunch. Nobody has talked to them yet."
        d["sel.sc1-1.q"] = "What would you do when you see them sitting alone?"
        d["sel.sc1-1.o1"] = "Walk over and say hi, introduce myself"
        d["sel.sc1-1.o2"] = "Smile at them from my table"
        d["sel.sc1-1.o3"] = "Keep eating with my friends"
        d["sel.sc1-2.q"] = "They tell you they like drawing. What would you say?"
        d["sel.sc1-2.o1"] = "Cool! I like drawing too! What do you draw?"
        d["sel.sc1-2.o2"] = "That's nice"
        d["sel.sc1-2.o3"] = "Oh, okay"
        d["sel.sc1-3.q"] = "They ask if you want to draw together after school."
        d["sel.sc1-3.o1"] = "Yes! Let me ask my parents first"
        d["sel.sc1-3.o2"] = "Maybe another time"
        d["sel.sc1-3.o3"] = "I don't know..."

        d["sel.sc2.title"] = "The Group Project"
        d["sel.sc2.narrative"] = "Your teacher puts you in a group with kids you don't usually play with for a project."
        d["sel.sc2-1.q"] = "How would you start working with the new group?"
        d["sel.sc2-1.o1"] = "Hi everyone! I'm excited to work together. What should we do first?"
        d["sel.sc2-1.o2"] = "Wait for someone else to start talking"
        d["sel.sc2-1.o3"] = "Stay quiet and hope they tell me what to do"
        d["sel.sc2-2.q"] = "One of the kids shares a really good idea for the project."
        d["sel.sc2-2.o1"] = "That's a great idea! I think we should use it"
        d["sel.sc2-2.o2"] = "Nod and say nothing"
        d["sel.sc2-2.o3"] = "I think my idea is better"
        d["sel.sc2-3.q"] = "You notice someone in the group is struggling with their part."
        d["sel.sc2-3.o1"] = "Do you want me to help you with that?"
        d["sel.sc2-3.o2"] = "Tell the teacher they need help"
        d["sel.sc2-3.o3"] = "Focus on my own work"

        d["sel.sc3.title"] = "Game Night"
        d["sel.sc3.narrative"] = "You and your friends are playing a board game. One friend keeps losing and is getting upset."
        d["sel.sc3-1.q"] = "Your friend wants to play a different game, but everyone else wants to keep playing this one. What do you do?"
        d["sel.sc3-1.o1"] = "Suggest we finish this game and then play their choice next"
        d["sel.sc3-1.o2"] = "Tell them to just wait"
        d["sel.sc3-1.o3"] = "Ignore them and keep playing"
        d["sel.sc3-2.q"] = "Two friends disagree about the rules. What would you do?"
        d["sel.sc3-2.o1"] = "Suggest we read the rules together and figure it out calmly"
        d["sel.sc3-2.o2"] = "Get frustrated and say it doesn't matter"
        d["sel.sc3-2.o3"] = "Walk away from the game"
        d["sel.sc3-3.q"] = "A new kid from your neighborhood wants to join the game. What do you say?"
        d["sel.sc3-3.o1"] = "Sure! We'll teach you the rules — come sit with us!"
        d["sel.sc3-3.o2"] = "Maybe you can watch for now"
        d["sel.sc3-3.o3"] = "Sorry, we already started"

        // MARK: - SEL Scenarios: Emotional Intelligence
        d["sel.ei1.title"] = "The Ice Cream Incident"
        d["sel.ei1.narrative"] = "Your friend just dropped their ice cream cone on the ground. It was their favorite flavor and they'd been waiting all day for it."
        d["sel.ei1-1.q"] = "How do you think your friend is feeling right now?"
        d["sel.ei1-1.o1"] = "Sad and disappointed"
        d["sel.ei1-1.o2"] = "Angry"
        d["sel.ei1-1.o3"] = "I'm not sure"
        d["sel.ei1-2.q"] = "Why do you think they feel that way?"
        d["sel.ei1-2.o1"] = "They were excited about it and now it's gone"
        d["sel.ei1-2.o2"] = "Because ice cream is yummy"
        d["sel.ei1-2.o3"] = "I don't know why"
        d["sel.ei1-3.q"] = "What would you do to help your friend feel better?"
        d["sel.ei1-3.o1"] = "Offer to share mine or help get a new one"
        d["sel.ei1-3.o2"] = "Tell them it's okay, don't worry"
        d["sel.ei1-3.o3"] = "It's just ice cream, no big deal"

        d["sel.ei2.title"] = "The Talent Show"
        d["sel.ei2.narrative"] = "Your friend practiced really hard for the talent show but forgot their lines on stage and had to stop. They come backstage looking upset."
        d["sel.ei2-1.q"] = "Your friend is looking at the ground with clenched fists. What does their body language tell you?"
        d["sel.ei2-1.o1"] = "They're feeling embarrassed and frustrated"
        d["sel.ei2-1.o2"] = "They're angry at the audience"
        d["sel.ei2-1.o3"] = "They're tired"
        d["sel.ei2-2.q"] = "Why might they feel more than just sad?"
        d["sel.ei2-2.o1"] = "They feel embarrassed because everyone was watching, and disappointed because they practiced so hard"
        d["sel.ei2-2.o2"] = "Because they didn't win"
        d["sel.ei2-2.o3"] = "Because the show was boring"
        d["sel.ei2-3.q"] = "What would you say to your friend?"
        d["sel.ei2-3.o1"] = "That took real courage. I'm proud of you for trying!"
        d["sel.ei2-3.o2"] = "Don't worry, everyone forgets sometimes"
        d["sel.ei2-3.o3"] = "You should have practiced more"

        d["sel.ei3.title"] = "The Moving Day"
        d["sel.ei3.narrative"] = "Your best friend tells you their family is moving to another city next month. You won't see each other at school anymore."
        d["sel.ei3-1.q"] = "How are you feeling when you hear this news?"
        d["sel.ei3-1.o1"] = "Sad we won't be together, but happy for the memories we have"
        d["sel.ei3-1.o2"] = "Just sad"
        d["sel.ei3-1.o3"] = "I don't know how I feel"
        d["sel.ei3-2.q"] = "Your friend seems quiet and won't talk about the move. What do you do?"
        d["sel.ei3-2.o1"] = "Tell them it's okay to feel sad, and I'm here to listen whenever they're ready"
        d["sel.ei3-2.o2"] = "Get upset at them for not talking"
        d["sel.ei3-2.o3"] = "Just leave them alone"
        d["sel.ei3-3.q"] = "You feel really upset about your friend leaving. What helps you handle these big feelings?"
        d["sel.ei3-3.o1"] = "Take deep breaths, write in my journal, and talk to someone I trust about how I feel"
        d["sel.ei3-3.o2"] = "Cry a lot and stay in my room"
        d["sel.ei3-3.o3"] = "Pretend I'm not upset and ignore the feelings"

        // MARK: - SEL Scenarios: Cognitive Development
        d["sel.cd1.title"] = "The Lost Pet"
        d["sel.cd1.narrative"] = "Your neighbor's cat went missing. They're looking everywhere but can't find it."
        d["sel.cd1-1.q"] = "What is the first thing you should do to help?"
        d["sel.cd1-1.o1"] = "Ask the neighbor where the cat was last seen and make a plan"
        d["sel.cd1-1.o2"] = "Start looking around randomly"
        d["sel.cd1-1.o3"] = "Wait and hope the cat comes home"
        d["sel.cd1-2.q"] = "How would you organize a search plan?"
        d["sel.cd1-2.o1"] = "First check the house, then the yard, then ask neighbors, and put up posters"
        d["sel.cd1-2.o2"] = "Look in the nearest spots"
        d["sel.cd1-2.o3"] = "I wouldn't know where to start"
        d["sel.cd1-3.q"] = "It rained last night. Where might the cat have gone to stay dry?"
        d["sel.cd1-3.o1"] = "Under a porch, in a garage, or somewhere sheltered — cats don't like getting wet"
        d["sel.cd1-3.o2"] = "Maybe in a tree?"
        d["sel.cd1-3.o3"] = "I don't know, cats go anywhere"

        d["sel.cd2.title"] = "The Bake Sale"
        d["sel.cd2.narrative"] = "Your class is having a bake sale to raise money. You want to help by making cookies."
        d["sel.cd2-1.q"] = "The bake sale is on Friday. It's Tuesday. When should you start baking?"
        d["sel.cd2-1.o1"] = "Thursday evening, so they're fresh. I need to get ingredients on Wednesday"
        d["sel.cd2-1.o2"] = "Friday morning before school"
        d["sel.cd2-1.o3"] = "Whenever my parent tells me to"
        d["sel.cd2-2.q"] = "Each cookie costs 50 cents to make. How much should you sell them for?"
        d["sel.cd2-2.o1"] = "More than 50 cents, like $1, so we make money for the school"
        d["sel.cd2-2.o2"] = "50 cents each"
        d["sel.cd2-2.o3"] = "Give them away for free"
        d["sel.cd2-3.q"] = "You made 24 cookies. By noon you sold 18. How many are left?"
        d["sel.cd2-3.o1"] = "6 cookies. I should lower the price to sell them before school ends"
        d["sel.cd2-3.o2"] = "Some are left, I'll keep trying"
        d["sel.cd2-3.o3"] = "I'm not sure, math is hard"

        d["sel.cd3.title"] = "The Science Fair"
        d["sel.cd3.narrative"] = "You're doing a science fair project about growing plants. You planted two seeds — one in sunlight and one in a dark closet."
        d["sel.cd3-1.q"] = "After one week, the plant in sunlight is tall and green, but the one in the dark is small and yellow. What does this tell you?"
        d["sel.cd3-1.o1"] = "Plants need sunlight to grow properly — the pattern shows light makes a big difference"
        d["sel.cd3-1.o2"] = "One seed was probably better than the other"
        d["sel.cd3-1.o3"] = "I'm not sure what happened"
        d["sel.cd3-2.q"] = "You forgot to water the sunny plant for 3 days and it started wilting. What caused this?"
        d["sel.cd3-2.o1"] = "Without water, the plant can't stay healthy even with sunlight — both water and light matter"
        d["sel.cd3-2.o2"] = "Maybe it got too much sun"
        d["sel.cd3-2.o3"] = "I don't know why it's wilting"
        d["sel.cd3-3.q"] = "For your next experiment, you want to test if music helps plants grow. What would you predict?"
        d["sel.cd3-3.o1"] = "I'd predict that the plant with music might grow differently, but I'd need to test it to be sure"
        d["sel.cd3-3.o2"] = "Music definitely helps plants"
        d["sel.cd3-3.o3"] = "I have no idea"

        // MARK: - SEL Scenarios: Life Skills
        d["sel.ls1.title"] = "Walking Home"
        d["sel.ls1.narrative"] = "You're walking to the park with your friend. It's a route you know well, but today the usual path is blocked by construction."
        d["sel.ls1-1.q"] = "You need to cross the street. What's the safest way?"
        d["sel.ls1-1.o1"] = "Stop at the crosswalk, look left, right, and left again, then cross when clear"
        d["sel.ls1-1.o2"] = "Look both ways quickly and cross"
        d["sel.ls1-1.o3"] = "Cross wherever, cars will stop"
        d["sel.ls1-2.q"] = "A stranger in a car pulls over and asks if you need a ride. What do you do?"
        d["sel.ls1-2.o1"] = "Say no thank you, keep walking, and tell a trusted adult right away"
        d["sel.ls1-2.o2"] = "Ignore them and walk faster"
        d["sel.ls1-2.o3"] = "Ask where they're going"
        d["sel.ls1-3.q"] = "The usual path is blocked. What's the best choice?"
        d["sel.ls1-3.o1"] = "Take the other route I know, or call my parents for help"
        d["sel.ls1-3.o2"] = "Try to go around the construction"
        d["sel.ls1-3.o3"] = "Go through the construction site, it's faster"

        d["sel.ls2.title"] = "Getting Ready for School"
        d["sel.ls2.narrative"] = "It's morning and you need to get ready for school. Your parent is busy with your younger sibling."
        d["sel.ls2-1.q"] = "What should you do first when you wake up?"
        d["sel.ls2-1.o1"] = "Brush my teeth, wash my face, and get dressed"
        d["sel.ls2-1.o2"] = "Get dressed"
        d["sel.ls2-1.o3"] = "Watch TV until someone tells me what to do"
        d["sel.ls2-2.q"] = "It's raining today and you have PE class. What should you wear?"
        d["sel.ls2-2.o1"] = "Rain jacket, sneakers for PE, and bring extra socks"
        d["sel.ls2-2.o2"] = "My regular clothes"
        d["sel.ls2-2.o3"] = "Whatever is on my floor"
        d["sel.ls2-3.q"] = "You need to pack your own lunch today. What would you choose?"
        d["sel.ls2-3.o1"] = "Sandwich, fruit, water bottle, and a small snack"
        d["sel.ls2-3.o2"] = "Whatever snacks I can find"
        d["sel.ls2-3.o3"] = "I'll just buy chips at school"

        d["sel.ls3.title"] = "The Playground Injury"
        d["sel.ls3.narrative"] = "You're playing at recess and your friend trips, falls, and scrapes their knee. It's bleeding a little and they're crying."
        d["sel.ls3-1.q"] = "What's the first thing you should do?"
        d["sel.ls3-1.o1"] = "Stay calm, comfort my friend, and tell a teacher or school nurse right away"
        d["sel.ls3-1.o2"] = "Try to help them up and keep playing"
        d["sel.ls3-1.o3"] = "Wait and see if they stop crying"
        d["sel.ls3-2.q"] = "The teacher asks if you can get the first aid kit. What should be used on a scrape?"
        d["sel.ls3-2.o1"] = "Clean it with water, put a bandage on it, and let the nurse check it"
        d["sel.ls3-2.o2"] = "Just put water on it"
        d["sel.ls3-2.o3"] = "I don't know what to do with a first aid kit"
        d["sel.ls3-3.q"] = "If your friend got hurt badly and no adult was around, who would you call?"
        d["sel.ls3-3.o1"] = "Call my parents, or dial the emergency number, and stay with my friend"
        d["sel.ls3-3.o2"] = "Run to find someone"
        d["sel.ls3-3.o3"] = "Panic and not know what to do"

        // MARK: - SEL Scenarios: Language Development
        d["sel.ld1.title"] = "Show and Tell"
        d["sel.ld1.narrative"] = "It's Show and Tell day. You brought your favorite toy robot to share with the class."
        d["sel.ld1-1.q"] = "How would you describe your robot to the class?"
        d["sel.ld1-1.o1"] = "This is Robo. It's a red robot with blue lights. It can walk and make sounds when you press the button on its back"
        d["sel.ld1-1.o2"] = "This is my robot. It's cool and it moves"
        d["sel.ld1-1.o3"] = "It's a robot"
        d["sel.ld1-2.q"] = "Your classmate asks \"Where did you get it and what does it do?\""
        d["sel.ld1-2.o1"] = "My grandma gave it to me for my birthday. It walks forward when you turn it on and its eyes light up!"
        d["sel.ld1-2.o2"] = "I got it as a present. It walks."
        d["sel.ld1-2.o3"] = "I don't remember"
        d["sel.ld1-3.q"] = "Your teacher asks you to share a fun memory with your robot."
        d["sel.ld1-3.o1"] = "One time I brought it to the park and my dog thought it was real! She kept barking and running around it. It was so funny!"
        d["sel.ld1-3.o2"] = "I play with it a lot at home"
        d["sel.ld1-3.o3"] = "It's fun"

        d["sel.ld2.title"] = "The Birthday Party"
        d["sel.ld2.narrative"] = "You went to an amazing birthday party over the weekend. Your friend wants to hear all about it!"
        d["sel.ld2-1.q"] = "Tell your friend what happened at the party from start to finish."
        d["sel.ld2-1.o1"] = "First we played games, then we had pizza, after that we had cake, and at the end we got party bags to take home!"
        d["sel.ld2-1.o2"] = "We played games and had cake"
        d["sel.ld2-1.o3"] = "It was fun"
        d["sel.ld2-2.q"] = "What was happening when everyone started laughing at the party?"
        d["sel.ld2-2.o1"] = "The birthday kid opened a present and it was a silly hat — everyone was laughing and being playful together"
        d["sel.ld2-2.o2"] = "Someone told a joke"
        d["sel.ld2-2.o3"] = "I forget"
        d["sel.ld2-3.q"] = "You met your friend's cousin at the party. Tell me about them."
        d["sel.ld2-3.o1"] = "Her name is Maya. She's really tall and has curly hair. She was really funny and taught us a new game!"
        d["sel.ld2-3.o2"] = "She was nice"
        d["sel.ld2-3.o3"] = "I don't remember much"

        d["sel.ld3.title"] = "Movie Day"
        d["sel.ld3.narrative"] = "You just watched a really exciting movie with your family. Your friend at school asks you about it the next day."
        d["sel.ld3-1.q"] = "Your friend asks \"What was the movie about?\" How would you explain it?"
        d["sel.ld3-1.o1"] = "It was about a brave girl who found a magical map and went on an adventure to save her village from a storm. At the end she figured out the map was a puzzle!"
        d["sel.ld3-1.o2"] = "It was about a girl on an adventure"
        d["sel.ld3-1.o3"] = "It was good"
        d["sel.ld3-2.q"] = "What was your favorite part? Describe it so your friend can picture it."
        d["sel.ld3-2.o1"] = "The best part was when the girl climbed a huge mountain covered in snow — the wind was blowing hard and she almost fell, but she grabbed a vine and swung across a big gap!"
        d["sel.ld3-2.o2"] = "The part where she climbed a mountain was cool"
        d["sel.ld3-2.o3"] = "I liked the end"
        d["sel.ld3-3.q"] = "Your friend hasn't seen the movie. They ask \"Should I watch it? Is there anything confusing?\""
        d["sel.ld3-3.o1"] = "Yes, you should! The beginning is a little slow, but once she finds the map it gets really exciting. You might wonder how the map works at first, but they explain it later"
        d["sel.ld3-3.o2"] = "Yeah it's good, you should watch it"
        d["sel.ld3-3.o3"] = "I don't know, maybe"

        // MARK: - SEL Journey & Daily Session
        d["sel.growth_report"] = "Growth Report"
        d["sel.no_data_yet"] = "No data yet. Your child can start a Daily Check-In from the Reflect tab to begin tracking growth."
        d["sel.empty_state_hint"] = "Tap the Reflect tab and choose \"Daily Check-In\" to begin."
        d["sel.progress_description"] = "Your child's social-emotional learning progress over the last 30 days."
        d["sel.overall_score"] = "Overall Score"
        d["sel.domain_profile"] = "Domain Profile"
        d["sel.domain_breakdown"] = "Domain Breakdown"
        d["sel.seven_day_trends"] = "7-Day Trends"
        d["sel.need_more_sessions"] = "Complete at least 2 sessions to see trend data."
        d["sel.recent_sessions"] = "Recent Sessions"
        d["sel.mindfulness_moment"] = "MINDFULNESS MOMENT"
        d["sel.deep_breaths"] = "Let's take %d deep breaths"
        d["sel.breathe_instruction"] = "Breathe in slowly... and breathe out."
        d["sel.skip_to_activities"] = "Skip to Activities"
        d["sel.wonderful_job"] = "Wonderful job! 🌟"
        d["sel.closing_message"] = "You did great reflecting on your feelings today. Keep it up!"
        d["sel.activities_completed"] = "%d activities completed"
        d["reflect.mindfulness.header"] = "Mindfulness"
        d["reflect.mindfulness.calm_mind"] = "Take a moment to calm your mind"
        d["reflect.going_deeper"] = "Going deeper..."
        d["reflect.thinking_followup"] = "Thinking of a follow-up..."
        d["reflect.previous"] = "Previous"
        d["reflect.next"] = "Next"
        d["reflect.free_chat.placeholder"] = "Type your thoughts..."
        d["reflect.free_chat.thinking"] = "Thinking..."

        // MARK: - SEL Session UI
        d["sel.breath_counter"] = "Breath %d of %d"
        d["sel.domain_check"] = "%@ • CHECK %d/3"
        d["sel.checks_completed"] = "%d checks completed"
        d["sel.checks_mindfulness"] = "%d checks completed • Mindfulness"
        d["sel.eye_bridge.high"] = "Strong focus today — this supports deeper social-emotional engagement."
        d["sel.eye_bridge.moderate"] = "Moderate attention — SEL activities may benefit from shorter, focused sessions."
        d["sel.eye_bridge.low"] = "Low attention today — consider breaks before SEL activities."
        d["sel.feedback.great"] = "Great thinking!"
        d["sel.feedback.good"] = "Good choice!"
        d["sel.feedback.okay"] = "That's okay! Let's keep going"

        // MARK: - SEL Emotions (additional)

        // MARK: - Coping Strategies
        d["reflect.coping.sad.1"] = "Talk to someone you trust"
        d["reflect.coping.sad.2"] = "Draw or write about your feelings"
        d["reflect.coping.sad.3"] = "Listen to your favorite music"
        d["reflect.coping.sad.4"] = "Give yourself a hug"
        d["reflect.coping.angry.1"] = "Take 5 deep breaths"
        d["reflect.coping.angry.2"] = "Count backwards from 10"
        d["reflect.coping.angry.3"] = "Squeeze a stress ball"
        d["reflect.coping.angry.4"] = "Go for a short walk"
        d["reflect.coping.worried.1"] = "Tell an adult how you feel"
        d["reflect.coping.worried.2"] = "Think of 3 things you're grateful for"
        d["reflect.coping.worried.3"] = "Imagine your happy place"
        d["reflect.coping.worried.4"] = "Take slow, deep breaths"
        d["reflect.coping.tired.1"] = "Rest your eyes for a minute"
        d["reflect.coping.tired.2"] = "Drink some water"
        d["reflect.coping.tired.3"] = "Stretch your body"
        d["reflect.coping.tired.4"] = "Take a break from screens"
        d["reflect.coping.default.1"] = "Share your feelings with someone"
        d["reflect.coping.default.2"] = "Do something you enjoy"
        d["reflect.coping.default.3"] = "Take a mindful moment"
        d["reflect.coping.default.4"] = "Be kind to yourself"

        // MARK: - Mindfulness Exercises
        d["reflect.exercise.box.title"] = "Box Breathing"
        d["reflect.exercise.box.desc"] = "A calming technique used by athletes and astronauts"
        d["reflect.exercise.box.step1"] = "Breathe in for 4 seconds"
        d["reflect.exercise.box.step2"] = "Hold for 4 seconds"
        d["reflect.exercise.box.step3"] = "Breathe out for 4 seconds"
        d["reflect.exercise.box.step4"] = "Hold for 4 seconds"
        d["reflect.exercise.box.step5"] = "Repeat 4 times"
        d["reflect.exercise.grounding.title"] = "5-4-3-2-1 Grounding"
        d["reflect.exercise.grounding.desc"] = "Connect with the present moment"
        d["reflect.exercise.grounding.step1"] = "Notice 5 things you can SEE"
        d["reflect.exercise.grounding.step2"] = "Notice 4 things you can TOUCH"
        d["reflect.exercise.grounding.step3"] = "Notice 3 things you can HEAR"
        d["reflect.exercise.grounding.step4"] = "Notice 2 things you can SMELL"
        d["reflect.exercise.grounding.step5"] = "Notice 1 thing you can TASTE"
        d["reflect.exercise.bodyscan.title"] = "Body Scan"
        d["reflect.exercise.bodyscan.desc"] = "Relax your body from head to toe"
        d["reflect.exercise.bodyscan.step1"] = "Relax your forehead and eyes"
        d["reflect.exercise.bodyscan.step2"] = "Relax your jaw and shoulders"
        d["reflect.exercise.bodyscan.step3"] = "Relax your arms and hands"
        d["reflect.exercise.bodyscan.step4"] = "Relax your stomach"
        d["reflect.exercise.bodyscan.step5"] = "Relax your legs and feet"
        d["reflect.exercise.gratitude.title"] = "Gratitude Moment"
        d["reflect.exercise.gratitude.desc"] = "Focus on the good things in life"
        d["reflect.exercise.gratitude.step1"] = "Think of someone who makes you happy"
        d["reflect.exercise.gratitude.step2"] = "Think of something you're good at"
        d["reflect.exercise.gratitude.step3"] = "Think of a place that makes you feel safe"
        d["reflect.exercise.gratitude.step4"] = "Think of a happy memory"
        d["reflect.exercise.gratitude.step5"] = "Smile and feel grateful"
        d["reflect.breathe.inhale"] = "Breathe In"
        d["reflect.breathe.hold"] = "Hold"
        d["reflect.breathe.exhale"] = "Breathe Out"

        // MARK: - Reflection Questions
        d["reflect.q1.question"] = "What was the best thing you saw online today?"
        d["reflect.q1.prompt"] = "Share something that made you smile or feel good..."
        d["reflect.q2.question"] = "Did anything online make you feel uncomfortable?"
        d["reflect.q2.prompt"] = "It's okay to talk about things that bothered you..."
        d["reflect.q3.question"] = "What did you learn today from the internet?"
        d["reflect.q3.prompt"] = "Share something interesting you discovered..."
        d["reflect.q4.question"] = "How much time did you spend on screens today?"
        d["reflect.q4.prompt"] = "Was it too much, just right, or not enough?"
        d["reflect.q5.question"] = "What would you like to do offline tomorrow?"
        d["reflect.q5.prompt"] = "Think of fun activities away from screens..."

        // MARK: - Free Chat Greetings
        d["reflect.chat.greeting.1"] = "Hi! This is a safe space to share your thoughts. What's on your mind today?"
        d["reflect.chat.greeting.2"] = "Hey there! I'm here to listen. Tell me about something interesting that happened."
        d["reflect.chat.greeting.3"] = "Welcome! You can talk about anything here. What would you like to chat about?"
        d["reflect.chat.fallback.1"] = "Thank you for sharing that with me. How does that make you feel?"
        d["reflect.chat.fallback.2"] = "I hear you. That sounds really important to you."
        d["reflect.chat.fallback.3"] = "It's great that you're talking about this. Tell me more?"
        d["reflect.chat.fallback.4"] = "I understand. It's okay to feel that way."
        d["reflect.chat.fallback.5"] = "Thanks for trusting me with that. What else is on your mind?"

        // MARK: - Insights View
        d["insights.view.title"] = "Insights"
        d["insights.overview"] = "Overview"
        d["insights.sites_visited"] = "Sites Visited"
        d["insights.blocked"] = "Blocked"
        d["insights.gated"] = "Gated"
        d["insights.sessions"] = "Sessions"
        d["insights.content_categories"] = "Content Categories"
        d["insights.activity_timeline"] = "Activity Timeline"
        d["insights.recent_sessions"] = "Recent Sessions"
        d["insights.no_sessions"] = "No browsing sessions yet"
        d["insights.protection_summary"] = "Protection Summary"
        d["insights.images_protected"] = "Images Protected"
        d["insights.of_scanned"] = "of %d scanned"
        d["insights.sites_blocked"] = "Sites Blocked"
        d["insights.harmful_content"] = "harmful content"
        d["insights.engagement"] = "Engagement"
        d["insights.avg_time_page"] = "Average Time per Page"
        d["insights.avg_scroll_depth"] = "Average Scroll Depth"
        d["insights.meaningful_engagement"] = "Meaningful Engagement"
        d["insights.most_engaged"] = "Most Engaged Sites"
        d["insights.visits"] = "%d visits"
        d["insights.avg_time"] = "avg time"
        d["insights.browsing_patterns"] = "Browsing Patterns"
        d["insights.session_depth"] = "Session Depth"
        d["insights.pages"] = "%d pages"
        d["insights.how_deep"] = "How deep into sites"
        d["insights.back_navigation"] = "Back Navigation"
        d["insights.returning_pages"] = "Returning to previous pages"
        d["insights.quick_visits"] = "Quick Visits"
        d["insights.pages_under_10s"] = "Pages viewed < 10 seconds"
        d["insights.content_viewed"] = "Content Viewed"
        d["insights.words_read"] = "Words Read"
        d["insights.images"] = "Images"
        d["insights.videos"] = "Videos"
        d["insights.topics"] = "Topics"
        d["insights.avg_time_short"] = "Avg Time"
        d["insights.reading"] = "Reading"
        d["insights.concerning_content"] = "Concerning Content Detected"
        d["insights.keywords"] = "Keywords: %@"
        d["insights.found_on_pages"] = "Found on %d page(s)"
        d["insights.recent_pages"] = "Recent Pages Viewed"
        d["insights.topics_viewed"] = "Topics Viewed:"
        d["insights.flagged"] = "Flagged: %@"
        d["insights.avg_time_per_page"] = "Avg time per page"

        // MARK: - Anchor - Morning

        // MARK: - Anchor - Evening

        // MARK: - Reconnection
        d["reconnection.title"] = "Welcome Back!"
        d["reconnection.welcome_back"] = "Welcome Back!"
        d["reconnection.subtitle"] = "We missed you! It's been a while."
        d["reconnection.ellie_greeting"] = "It's Ellie! I never forget my friends, and I'm so happy to see you again!"
        d["reconnection.days_since"] = "It's been %d days since we last hung out."
        d["reconnection.hi_ellie"] = "Hi Ellie!"
        d["reconnection.how_have_you_been"] = "How have you been?"
        d["reconnection.mood_great"] = "Great!"
        d["reconnection.mood_okay"] = "Okay"
        d["reconnection.mood_not_great"] = "Not great"
        d["reconnection.response_great"] = "That's wonderful to hear! Let's keep the good vibes going."
        d["reconnection.response_not_great"] = "I'm sorry to hear that. Remember, I'm always here for you."
        d["reconnection.response_okay"] = "Good to know! Let's hang out and have some fun."
        d["reconnection.what_to_do"] = "What would you like to do?"
        d["reconnection.browse_web"] = "Browse the Web"
        d["reconnection.chat_friend"] = "Chat with a Friend"
        d["reconnection.reflection_time"] = "Reflection Time"
        d["reconnection.whats_new"] = "Here's what's new since you were away"
        d["reconnection.lets_go"] = "Let's Go!"
        d["reconnection.missed_days"] = "You've been away for %d days"

        // MARK: - Growth / Journey
        d["growth.title"] = "My Journey"
        d["growth.milestones"] = "Milestones"
        d["growth.weekly_snapshot"] = "Weekly Snapshot"
        d["growth.noticed_about_you"] = "What we've noticed about you:"
        d["growth.day_streak"] = "Day Streak"
        d["growth.this_week"] = "This Week"
        d["growth.active_days"] = "Active Days"
        d["growth.chats"] = "Chats"
        d["growth.reflections"] = "Reflections"
        d["growth.moods"] = "Moods"
        d["growth.streak"] = "Streak"
        d["growth.days"] = "days"
        d["growth.level"] = "Level"
        d["growth.explorer"] = "Explorer"
        d["growth.adventurer"] = "Adventurer"
        d["growth.champion"] = "Champion"
        d["growth.legend"] = "Legend"
        d["growth.earned"] = "Earned!"
        d["growth.locked"] = "Keep going!"
        d["growth.snapshot.title"] = "Your Week in Review"
        d["growth.snapshot.conversations"] = "Conversations"
        d["growth.snapshot.reflections"] = "Reflections"
        d["growth.snapshot.browsing_time"] = "Browsing Time"
        d["growth.snapshot.mood_checks"] = "Mood Checks"
        d["growth.snapshot.mood_checkins"] = "Mood Check-ins"
        d["growth.snapshot.most_common_mood"] = "Most Common Mood"
        d["growth.snapshot.favorite_friend"] = "Favorite Friend"
        d["growth.snapshot.growth_insight"] = "Growth Insight"
        d["growth.snapshot.keep_going"] = "Keep Going!"

        // MARK: - Parent Insights
        d["insights.title"] = "Parent Insights"
        d["insights.wellness"] = "Wellness Overview"
        d["insights.mood_trends"] = "Mood Trends"
        d["insights.chat_activity"] = "Chat Activity"
        d["insights.browsing_summary"] = "Browsing Summary"
        d["insights.alerts"] = "Alerts"
        d["insights.no_alerts"] = "No alerts to show"
        d["insights.this_week"] = "This Week"
        d["insights.this_month"] = "This Month"

        // MARK: - Parent Insights Dashboard
        d["insights.dashboard.title"] = "Child Wellness"
        d["insights.dashboard.this_week_vs_last"] = "This Week vs Last"
        d["insights.dashboard.chats"] = "Chats"
        d["insights.dashboard.reflections"] = "Reflections"
        d["insights.dashboard.moods"] = "Moods"
        d["insights.dashboard.active_days"] = "Active Days"
        d["insights.dashboard.conversation_starter"] = "Tonight's Conversation Starter"
        d["insights.dashboard.generating_starter"] = "Generating a conversation starter..."
        d["insights.dashboard.starter_placeholder"] = "Use the app for a few days to get personalized conversation starters."
        d["insights.dashboard.daily_insight"] = "Daily Insight"
        d["insights.dashboard.generating_insight"] = "Generating insight..."
        d["insights.dashboard.insight_placeholder"] = "Insights will appear as your child uses the app more."
        d["insights.dashboard.emotional_wellness"] = "Emotional Wellness"
        d["insights.dashboard.last_7_days"] = "Last 7 Days"
        d["insights.dashboard.emotion_distribution"] = "30-Day Emotion Distribution"
        d["insights.dashboard.no_mood_data"] = "No mood data yet. Mood entries will appear here as your child uses the app."
        d["insights.dashboard.conversation_insights"] = "Conversation Insights"
        d["insights.dashboard.messages"] = "Messages"
        d["insights.dashboard.characters_used"] = "Characters Used"
        d["insights.dashboard.popular_topics"] = "Popular Topics"
        d["insights.dashboard.growth_metrics"] = "Growth Metrics"
        d["insights.dashboard.current_streak"] = "Current Streak"
        d["insights.dashboard.milestones"] = "Milestones"
        d["insights.dashboard.active_days_30d"] = "Active Days (30d)"
        d["insights.dashboard.activity_30d"] = "30-Day Activity"
        d["insights.dashboard.engagement_quality"] = "Engagement Quality"
        d["insights.dashboard.voluntary_returns"] = "Voluntary Returns"
        d["insights.dashboard.avg_reflection_depth"] = "Avg Reflection Depth"
        d["insights.dashboard.total_sessions"] = "Total Sessions"
        d["insights.dashboard.voluntary_returns_explanation"] = "Higher voluntary return rates indicate genuine engagement rather than notification-driven usage."
        d["insights.dashboard.daily_checkins"] = "Daily Check-ins"
        d["insights.dashboard.morning"] = "Morning"
        d["insights.dashboard.evening"] = "Evening"
        d["insights.dashboard.wellness_alert"] = "Wellness Alert"
        d["insights.dashboard.wellness_alert_message"] = "Your child has reported feeling sad for 3 or more consecutive check-ins. Consider having a gentle conversation about how they're feeling."
        d["insights.dashboard.value_alignment"] = "Value Alignment"
        d["insights.dashboard.value_alignment_desc"] = "Discuss values your child explored online this week:"
        d["insights.dashboard.generating_prompt"] = "Generating prompt..."
        d["insights.dashboard.value_kindness"] = "What did you learn about kindness today?"
        d["insights.dashboard.value_fairness"] = "Tell me about a time someone was fair to you this week."
        d["insights.dashboard.value_helping"] = "How did you help someone today?"

        // MARK: - Browsing History
        d["history.title"] = "Browsing History"
        d["history.loading"] = "Loading browsing history..."
        d["history.today"] = "Today"
        d["history.yesterday"] = "Yesterday"
        d["history.earlier"] = "Earlier"
        d["history.no_history"] = "No browsing history yet"
        d["history.empty_message"] = "History will appear here as your child browses."
        d["history.time_range"] = "Time Range"
        d["history.pages"] = "pages"
        d["history.emoji_journey"] = "Emoji Journey"
        d["history.summary"] = "Summary"
        d["history.pages_visited"] = "Pages Visited"
        d["history.session_detail"] = "Session Detail"
        d["history.back_label"] = "History"
        d["history.clear"] = "Clear History"
        d["history.clear_confirm"] = "Are you sure you want to clear all browsing history?"

        // MARK: - Contextual Prompts
        d["prompt.welcome_back"] = "Welcome back! Ready to explore?"
        d["prompt.take_break"] = "You've been browsing for a while. Take a break?"
        d["prompt.try_reflect"] = "How about checking in with your feelings?"
        d["prompt.chat_riki"] = "Want to chat with a friend?"
        d["prompt.new_milestone"] = "You earned a new milestone!"
        d["prompt.dismiss"] = "Maybe later"
        d["prompt.lets_go"] = "Let's go!"
        d["prompt.curiosity_noticed"] = "I noticed something interesting today... Want to hear about it?"
        d["prompt.curiosity_learned"] = "Curious about what I learned from you? You might be surprised!"
        d["prompt.curiosity_question_young"] = "I have a super fun question for you! Want to play?"
        d["prompt.growth_calm"] = "You handled that calmly. How did you do that?"
        d["prompt.growth_evolved"] = "Your thinking has really evolved. Want to see how far you've come?"
        d["prompt.growth_proud_young"] = "Wow, you're getting so good at this! I'm really proud of you!"
        d["prompt.growth_streak_celebrate"] = "Look at that streak! You're building something amazing, one day at a time."
        d["prompt.brave_question"] = "Can I ask you something brave? It might surprise you."
        d["prompt.brave_future"] = "What would future-you say about today? Let's find out."
        d["prompt.brave_try_young"] = "Want to try something new together? I believe in you!"
        d["prompt.transition_reflect"] = "Quick reflection before you go? Just 2 minutes."
        d["prompt.transition_progress"] = "Want to see your progress map? You've been busy!"
        d["prompt.return_changed"] = "Something small changed while you were away. Want to see?"
        d["prompt.return_secret"] = "Want to see a secret insight about yourself? I saved it for you."
        d["prompt.return_missed_young"] = "Yay, you're back! I missed you! Want to play together?"
        d["prompt.emotional_check_negative"] = "Hey, I noticed you might be having a tough time. I'm here for you."
        d["prompt.emotional_celebrate_positive"] = "You seem to be in a great mood! That's wonderful to see."
        d["prompt.browsing_learned"] = "Learned something cool while browsing? I'd love to hear about it!"
        d["prompt.browsing_break"] = "How are you feeling right now? Want to do a quick check-in?"
        d["prompt.browsing_riddle_young"] = "Want to take a fun break? I've got a riddle for you!"
        d["prompt.reflect_done_great"] = "That was a really thoughtful reflection. You should be proud of yourself."
        d["prompt.reflect_deeper_teen"] = "Nice reflection. Want to go a little deeper? Sometimes the best insights come next."
        d["prompt.action.tell_me"] = "Tell me!"
        d["prompt.action.show_me"] = "Show me"
        d["prompt.action.lets_play"] = "Let's play!"
        d["prompt.action.let_me_think"] = "Let me think..."
        d["prompt.action.show_my_growth"] = "Show my growth"
        d["prompt.action.see_my_journey"] = "See my journey"
        d["prompt.action.go_ahead"] = "Go ahead"
        d["prompt.action.lets_explore"] = "Let's explore"
        d["prompt.action.lets_try"] = "Let's try!"
        d["prompt.action.sure"] = "Sure!"
        d["prompt.action.show_me_excited"] = "Show me!"
        d["prompt.action.what_changed"] = "What changed?"
        d["prompt.action.talk_about_it"] = "Talk about it"
        d["prompt.action.lets_chat"] = "Let's chat"
        d["prompt.action.check_in"] = "Check in"
        d["prompt.action.go_deeper"] = "Go deeper"

        // MARK: - Notifications
        d["notification.reconnect.title"] = "We Miss You!"
        d["notification.reconnect.body"] = "Ellie here - I never forget my friends! Come back and say hi, I have something fun to share."
        d["notification.milestone.title"] = "New Milestone!"
        d["notification.milestone.body"] = "You've earned a new achievement. Check it out!"

        // MARK: - Mood History
        d["mood.history.title"] = "Mood History"
        d["mood.history.recent"] = "Recent Moods"
        d["mood.history.no_entries"] = "No mood entries yet"
        d["mood.history.trend"] = "Your mood trend"

        // MARK: - Scan Results
        d["scan.overall_safety_score"] = "Overall Safety Score"
        d["scan.scanned"] = "Scanned"
        d["scan.live_analysis"] = "Live Analysis"
        d["scan.demo_mode"] = "Demo Mode"
        d["scan.blocked_under_16"] = "Blocked Under 16"
        d["scan.out_of_100"] = "/100"
        d["scan.age_appropriate_actions"] = "Age-Appropriate Actions"
        d["scan.score"] = "Score"
        d["scan.safety_risks_detected"] = "Safety Risks Detected"
        d["scan.matches"] = "matches"
        d["scan.content_analysis"] = "Content Analysis"
        d["scan.nlp_text_analysis"] = "NLP Text Analysis"
        d["scan.sentiment"] = "Sentiment:"
        d["scan.language_score"] = "Language Score:"
        d["scan.key_topics"] = "Key Topics:"
        d["scan.vision_ai_analysis"] = "Vision AI Analysis"
        d["scan.visual_safety_score"] = "Visual Safety Score:"
        d["scan.detected_objects"] = "Detected Objects:"

        // MARK: - Screen Time
        d["screentime.minimal"] = "30 min/day"
        d["screentime.moderate"] = "1-2 hours/day"
        d["screentime.flexible"] = "Flexible"

        // MARK: - Eye Tracking
        d["eye.settings_title"] = "Eye Tracking"
        d["eye.enable_toggle"] = "Enable Eye Tracking"
        d["eye.enable_subtitle"] = "Monitor attention & eye comfort (on-device only)"
        d["eye.view_report"] = "View Eye Tracking Report"
        d["eye.view_report_desc"] = "Attention, fatigue & gaze insights"
        d["eye.report_title"] = "Eye Tracking Report"
        d["eye.privacy_badge"] = "All data stays on this device"
        d["eye.metric_attention"] = "Attention"
        d["eye.metric_focus"] = "Avg Focus"
        d["eye.metric_blink"] = "Blink Rate"
        d["eye.metric_fatigue"] = "Fatigue"
        d["eye.trend_attention"] = "7-Day Attention Trend"
        d["eye.trend_blink"] = "7-Day Blink Rate"
        d["eye.gaze_distribution"] = "Gaze Distribution"
        d["eye.interpretation_title"] = "Insights"
        d["eye.no_data_title"] = "No Eye Tracking Data Yet"
        d["eye.no_data_message"] = "Enable eye tracking in Settings and use the app for a while. Reports will appear here."
        d["eye.delete_button"] = "Delete All Eye Tracking Data"
        d["eye.delete_confirm_title"] = "Delete Eye Data?"
        d["eye.delete_confirm_message"] = "This will permanently remove all eye tracking history from this device. This cannot be undone."
        d["eye.sel_bridge_title"] = "Eye Insights"

        // MARK: - Accessibility
        d["accessibility.komal_character"] = "Komal character"
        d["accessibility.ellie_character"] = "Ellie the elephant"
        d["accessibility.emoji_react"] = "React with %@"
        d["accessibility.emotion_intensity"] = "Emotion intensity"
        d["accessibility.go_back"] = "Go back"
        d["accessibility.go_forward"] = "Go forward"
        d["accessibility.tab_switcher"] = "%d open tabs"
        d["accessibility.sel.breathing_circle"] = "Breathing exercise circle"
        d["accessibility.sel.completion_star"] = "Completion star"
        d["accessibility.sel.score"] = "Score: %d out of 100"
        d["accessibility.sel.sparkline"] = "Score trend chart"
        d["accessibility.sel.no_change"] = "No change"
        d["accessibility.sel.radar_chart"] = "Domain profile radar chart"
        d["accessibility.sel.trend_chart"] = "7-day trend line chart"

        // MARK: - Gate (additional)
        d["gate.approve_biometric"] = "Approve with %@"
        d["gate.or_enter_pin"] = "or enter PIN"

        return d
    }()
}
// swiftlint:enable file_length type_body_length
