#if os(iOS)
// swiftlint:disable file_length type_body_length
enum FrenchStrings {
    static let all: [String: String] = {
        var d = [String: String]()

        // MARK: - Common
        d["common.back"] = "Retour"
        d["common.continue"] = "Continuer"
        d["common.done"] = "Terminé"
        d["common.skip"] = "Passer"
        d["common.cancel"] = "Annuler"
        d["common.save"] = "Enregistrer"
        d["common.delete"] = "Supprimer"
        d["common.yes"] = "Oui"
        d["common.no"] = "Non"
        d["common.ok"] = "OK"
        d["common.close"] = "Fermer"
        d["common.enter"] = "Entrer"
        d["common.selected_count"] = "%d/%d sélectionnés"
        d["common.step_of"] = "ÉTAPE %@"

        // MARK: - Splash
        d["splash.title"] = "Komal"
        d["splash.tagline"] = "Le compagnon numérique sûr de votre enfant"

        // MARK: - Onboarding Welcome
        d["onboarding.welcome.title"] = "Évaluation de la sécurité de l'enfant"
        d["onboarding.welcome.subtitle"] = "Profil de bien-être numérique basé sur des preuves"
        d["onboarding.welcome.card1.title"] = "Psychologie du développement"
        d["onboarding.welcome.card1.desc"] = "Paramètres adaptés aux stades de développement cognitif définis par la recherche en psychologie de l'enfant."
        d["onboarding.welcome.card2.title"] = "Analyse comportementale"
        d["onboarding.welcome.card2.desc"] = "Comprendre les habitudes de navigation pour créer des limites de sécurité personnalisées."
        d["onboarding.welcome.card3.title"] = "Protection proactive"
        d["onboarding.welcome.card3.desc"] = "Filtrage de contenu basé sur les facteurs de risque et les préférences identifiés."
        d["onboarding.welcome.time_estimate"] = "Cette évaluation prend environ 3-4 minutes"
        d["onboarding.welcome.begin"] = "Commencer l'évaluation"
        d["onboarding.welcome.language"] = "Langue"

        // MARK: - Onboarding Child Info
        d["onboarding.info.step"] = "1 sur 6"
        d["onboarding.info.title"] = "Informations de base"
        d["onboarding.info.subtitle"] = "Aidez-nous à comprendre qui nous protégeons"
        d["onboarding.info.name_label"] = "Prénom de l'enfant"
        d["onboarding.info.name_placeholder"] = "Entrez le prénom"
        d["onboarding.info.age_label"] = "Groupe d'âge"
        d["onboarding.info.age_desc"] = "Les restrictions de contenu sont calibrées en fonction des étapes de développement"
        d["onboarding.info.research_note"] = "La recherche montre que des limites de contenu adaptées à l'âge favorisent un développement cognitif sain et réduisent l'anxiété chez les enfants."

        d["onboarding.age.under10"] = "Petite enfance - Protection maximale"
        d["onboarding.age.10to13"] = "Pré-adolescent - Exploration guidée"
        d["onboarding.age.13to16"] = "Adolescent - Limites équilibrées"
        d["onboarding.age.16to18"] = "Grand adolescent - Liberté adaptée à l'âge"
        d["onboarding.age.18plus"] = "Adulte - Accès complet"

        // MARK: - Onboarding Websites
        d["onboarding.websites.step"] = "2 sur 6"
        d["onboarding.websites.title"] = "Sites Web favoris"
        d["onboarding.websites.subtitle"] = "Sélectionnez jusqu'à 5 sites que votre enfant visite le plus"
        d["onboarding.websites.desc"] = "Comprendre les habitudes de navigation nous aide à identifier les sources fiables et à personnaliser la protection."

        // MARK: - Onboarding Interests
        d["onboarding.interests.step"] = "3 sur 6"
        d["onboarding.interests.title"] = "Centres d'intérêt"
        d["onboarding.interests.subtitle"] = "Qu'est-ce que votre enfant aime apprendre ?"
        d["onboarding.interests.desc"] = "Sélectionnez 3 à 5 sujets. Cela nous aide à comprendre quel contenu prioriser et protéger."

        d["onboarding.interest.gaming"] = "Jeux vidéo"
        d["onboarding.interest.animals"] = "Animaux"
        d["onboarding.interest.science"] = "Sciences"
        d["onboarding.interest.art"] = "Art et dessin"
        d["onboarding.interest.music"] = "Musique"
        d["onboarding.interest.sports"] = "Sports"
        d["onboarding.interest.coding"] = "Programmation"
        d["onboarding.interest.reading"] = "Lecture"
        d["onboarding.interest.cooking"] = "Cuisine"
        d["onboarding.interest.nature"] = "Nature"
        d["onboarding.interest.space"] = "Espace"
        d["onboarding.interest.history"] = "Histoire"
        d["onboarding.interest.movies"] = "Films"
        d["onboarding.interest.crafts"] = "Bricolage"
        d["onboarding.interest.dinosaurs"] = "Dinosaures"
        d["onboarding.interest.vehicles"] = "Véhicules"
        d["onboarding.interest.fashion"] = "Mode"
        d["onboarding.interest.dance"] = "Danse"

        // MARK: - Onboarding Likes
        d["onboarding.likes.step"] = "4 sur 6"
        d["onboarding.likes.title"] = "Ce qu'ils aiment en ligne"
        d["onboarding.likes.subtitle"] = "Comprendre les expériences positives en ligne"
        d["onboarding.likes.desc"] = "Sélectionnez les activités que votre enfant apprécie. Cela nous aide à garantir l'accès à du contenu enrichissant."
        d["onboarding.likes.other"] = "Autre (facultatif)"
        d["onboarding.likes.other_placeholder"] = "Ajoutez autre chose qu'ils aiment..."

        d["onboarding.like.watching_videos"] = "Regarder des vidéos"
        d["onboarding.like.playing_games"] = "Jouer à des jeux"
        d["onboarding.like.chatting"] = "Discuter avec des amis"
        d["onboarding.like.learning"] = "Apprendre de nouvelles choses"
        d["onboarding.like.creative"] = "Projets créatifs"
        d["onboarding.like.exploring"] = "Explorer des sites web"
        d["onboarding.like.music"] = "Écouter de la musique"
        d["onboarding.like.virtual_worlds"] = "Mondes virtuels"
        d["onboarding.like.puzzles"] = "Puzzles et défis"
        d["onboarding.like.funny"] = "Contenu drôle"
        d["onboarding.like.stories"] = "Histoires et livres"
        d["onboarding.like.making_videos"] = "Créer des vidéos"

        // MARK: - Onboarding Dislikes
        d["onboarding.dislikes.step"] = "5 sur 6"
        d["onboarding.dislikes.title"] = "Ce qui les dérange"
        d["onboarding.dislikes.subtitle"] = "Identifier les déclencheurs et les inconforts"
        d["onboarding.dislikes.desc"] = "Sélectionnez ce qui inquiète ou dérange votre enfant en ligne. Cela nous aide à filtrer le contenu potentiellement perturbant."
        d["onboarding.dislikes.other"] = "Autres préoccupations (facultatif)"
        d["onboarding.dislikes.other_placeholder"] = "Ajoutez d'autres choses qui les dérangent..."
        d["onboarding.dislikes.research_note"] = "Comprendre ce qui perturbe les enfants en ligne nous permet de filtrer proactivement le contenu avant l'exposition, réduisant l'anxiété et les expériences négatives."

        d["onboarding.dislike.scary"] = "Contenu effrayant"
        d["onboarding.dislike.loud"] = "Bruits forts/jumpscares"
        d["onboarding.dislike.mean"] = "Commentaires méchants"
        d["onboarding.dislike.strangers"] = "Messages d'inconnus"
        d["onboarding.dislike.violent"] = "Jeux violents"
        d["onboarding.dislike.sad"] = "Histoires tristes"
        d["onboarding.dislike.ads"] = "Publicités confuses"
        d["onboarding.dislike.reading"] = "Trop de lecture"
        d["onboarding.dislike.timed"] = "Défis chronométrés"
        d["onboarding.dislike.losing"] = "Perdre dans les jeux"
        d["onboarding.dislike.popups"] = "Vidéos pop-up"
        d["onboarding.dislike.rushed"] = "Être pressé"

        // MARK: - Onboarding Concerns
        d["onboarding.concerns.step"] = "6 sur 8"
        d["onboarding.concerns.title"] = "Vos préoccupations"
        d["onboarding.concerns.subtitle"] = "Qu'est-ce qui vous inquiète le plus concernant votre enfant en ligne ?"
        d["onboarding.concerns.desc"] = "Sélectionnez vos principales préoccupations. Nous prioriserons la protection dans ces domaines."

        d["onboarding.concern.cyberbullying"] = "Cyberharcèlement"
        d["onboarding.concern.cyberbullying.desc"] = "Harcèlement, messages méchants, exclusion"
        d["onboarding.concern.inappropriate"] = "Contenu inapproprié"
        d["onboarding.concern.inappropriate.desc"] = "Violence, thèmes adultes, matériel explicite"
        d["onboarding.concern.predators"] = "Prédateurs en ligne"
        d["onboarding.concern.predators.desc"] = "Inconnus, manipulation, demandes d'informations personnelles"
        d["onboarding.concern.addiction"] = "Addiction aux écrans"
        d["onboarding.concern.addiction.desc"] = "Utilisation excessive, difficulté à arrêter"
        d["onboarding.concern.privacy"] = "Risques de confidentialité"
        d["onboarding.concern.privacy.desc"] = "Collecte de données, partage de localisation"
        d["onboarding.concern.misinfo"] = "Désinformation"
        d["onboarding.concern.misinfo.desc"] = "Fausses nouvelles, théories conspirationnistes"
        d["onboarding.concern.scams"] = "Arnaques financières"
        d["onboarding.concern.scams.desc"] = "Achats intégrés, hameçonnage"
        d["onboarding.concern.mental"] = "Santé mentale"
        d["onboarding.concern.mental.desc"] = "Anxiété, comparaison, FOMO"

        // MARK: - Onboarding Filters
        d["onboarding.filters.step"] = "7 sur 8"
        d["onboarding.filters.title"] = "Filtres de contenu"
        d["onboarding.filters.subtitle"] = "Examiner et personnaliser le filtrage de contenu"
        d["onboarding.filters.desc"] = "Ces paramètres par défaut sont basés sur l'âge de votre enfant et vos préoccupations. Ajustez les paramètres ci-dessous."

        // MARK: - Onboarding PIN
        d["onboarding.pin.step"] = "8 sur 8"
        d["onboarding.pin.title"] = "Définir le PIN parental"
        d["onboarding.pin.subtitle"] = "Créez un PIN pour protéger les paramètres parentaux"
        d["onboarding.pin.desc"] = "Ce PIN sera requis pour accéder au mode parent et approuver le contenu restreint."
        d["onboarding.pin.enter"] = "Entrez le PIN"
        d["onboarding.pin.placeholder"] = "PIN à 4 chiffres"
        d["onboarding.pin.confirm"] = "Confirmez le PIN"
        d["onboarding.pin.confirm_placeholder"] = "Confirmez le PIN"
        d["onboarding.pin.mismatch"] = "Les PIN ne correspondent pas. Veuillez réessayer."
        d["onboarding.pin.enable_biometric"] = "Activer %@"
        d["onboarding.pin.use_biometric"] = "Utiliser %@ au lieu du PIN"
        d["onboarding.pin.research_note"] = "Un PIN parental garantit que seuls les adultes autorisés peuvent modifier les paramètres de sécurité et approuver le contenu restreint."

        // MARK: - Onboarding Completion
        d["onboarding.complete.title"] = "Profil terminé"
        d["onboarding.complete.subtitle"] = "Le profil de sécurité de %@ est prêt"
        d["onboarding.complete.summary"] = "Résumé de l'évaluation"
        d["onboarding.complete.name"] = "Nom"
        d["onboarding.complete.age_group"] = "Groupe d'âge"
        d["onboarding.complete.interests"] = "Centres d'intérêt"
        d["onboarding.complete.concerns"] = "Préoccupations principales"
        d["onboarding.complete.adjust_note"] = "Les paramètres peuvent être ajustés à tout moment dans l'application"
        d["onboarding.complete.start"] = "Commencer à utiliser Komal"
        d["onboarding.complete.review"] = "Revoir les réponses"

        // MARK: - Menu
        d["menu.browse"] = "Naviguer"
        d["menu.talk"] = "Parler"
        d["menu.reflect"] = "Réfléchir"
        d["menu.settings"] = "Réglages"

        // MARK: - Settings
        d["settings.title"] = "Réglages"
        d["settings.whos_using"] = "Qui utilise ?"
        d["settings.whos_using.desc"] = "Sélectionnez qui utilise actuellement l'appareil"
        d["settings.child"] = "Enfant"
        d["settings.child.subtitle"] = "Navigation sécurisée"
        d["settings.parent"] = "Parent"
        d["settings.parent.subtitle"] = "Accès complet"

        d["settings.child.greeting"] = "Salut %@ !"
        d["settings.child.greeting_default"] = "Salut !"
        d["settings.child.safe_msg"] = "Komal est là pour te protéger pendant que tu explores !"
        d["settings.child.chatty"] = "Envie de discuter ?"
        d["settings.child.chatty.desc"] = "Parle à Riki ! Ton compagnon amical est toujours là pour discuter et t'aider."
        d["settings.child.go_talk"] = "Aller à Parler"
        d["settings.child.profile"] = "Ton profil"
        d["settings.child.explorer"] = "Explorateur"
        d["settings.child.age"] = "Âge : %@"
        d["settings.child.journey"] = "Mon parcours"
        d["settings.child.day_streak"] = "Jours consécutifs"
        d["settings.child.milestones"] = "Jalons"
        d["settings.child.view_journey"] = "Voir mon parcours"

        d["settings.parent.digital_journey"] = "Parcours numérique"
        d["settings.parent.view_journey"] = "Voir le parcours numérique"
        d["settings.parent.journey_desc"] = "Voir l'activité de navigation de votre enfant avec des analyses IA"
        d["settings.parent.wellness"] = "Bien-être de l'enfant"
        d["settings.parent.wellness_dashboard"] = "Tableau de bord bien-être"
        d["settings.parent.wellness_desc"] = "Tendances d'humeur, conversations, indicateurs de croissance"
        d["settings.parent.morning_checkin"] = "Bilan du matin"
        d["settings.parent.morning_desc"] = "Ancrage d'humeur matinal quotidien"
        d["settings.parent.evening_winddown"] = "Détente du soir"
        d["settings.parent.evening_desc"] = "Ancrage de réflexion du soir quotidien"
        d["settings.parent.child_profile"] = "Profil de l'enfant"
        d["settings.parent.name_label"] = "Nom"
        d["settings.parent.name_placeholder"] = "Nom de l'enfant"
        d["settings.parent.age_label"] = "Groupe d'âge"
        d["settings.parent.controls"] = "Contrôles parentaux"
        d["settings.parent.notify_block"] = "Notifier en cas de blocage"
        d["settings.parent.notify_desc"] = "Recevoir des alertes lors de l'accès au contenu bloqué"
        d["settings.parent.safe_search"] = "Recherche sécurisée forcée"
        d["settings.parent.safe_search_desc"] = "Appliquer la sécurité stricte sur les moteurs de recherche"
        d["settings.parent.view_insights"] = "Voir les analyses"
        d["settings.parent.insights_desc"] = "Voir l'activité de navigation et le contenu bloqué"
        d["settings.parent.modify_content"] = "Modifier le contenu"
        d["settings.parent.modify_filters"] = "Modifier les filtres"
        d["settings.parent.custom_keywords"] = "Mots-clés personnalisés"
        d["settings.parent.add_keyword"] = "Ajouter un mot-clé (ex : 'armes')"
        d["settings.parent.no_keywords"] = "Aucun mot-clé personnalisé ajouté."
        d["settings.parent.custom_websites"] = "Sites web personnalisés"
        d["settings.parent.add_website"] = "Ajouter un site (ex : 'siteinterdit.com')"
        d["settings.parent.no_websites"] = "Aucun site web personnalisé ajouté."

        d["settings.account"] = "Compte"
        d["settings.account.guest"] = "Utilisation en tant qu'invité"
        d["settings.account.guest_desc"] = "Vos données sont stockées localement sur cet appareil uniquement. Connectez-vous pour synchroniser sur plusieurs appareils."
        d["settings.account.sign_in"] = "Se connecter"
        d["settings.account.exit_guest"] = "Quitter le mode invité"
        d["settings.account.delete"] = "Supprimer le compte"
        d["settings.account.logout"] = "Déconnexion"
        d["settings.account.login"] = "Connexion"
        d["settings.account.sync_desc"] = "Connectez-vous pour synchroniser vos préférences sur plusieurs appareils"

        d["settings.alert.logout.title"] = "Déconnexion"
        d["settings.alert.logout.message"] = "Voulez-vous vous déconnecter ?"
        d["settings.alert.delete.title"] = "Supprimer le compte"
        d["settings.alert.delete.message"] = "Êtes-vous sûr de vouloir supprimer le compte ? Cette action est irréversible."

        d["settings.pin.title"] = "Entrez le PIN parental"
        d["settings.pin.subtitle"] = "Entrez votre PIN à 4 chiffres pour accéder aux paramètres parentaux"
        d["settings.pin.placeholder"] = "PIN"
        d["settings.pin.error"] = "PIN incorrect. Réessayez."
        d["settings.pin.biometric"] = "Utiliser %@"

        // MARK: - Riki
        d["riki.choose_friend"] = "Choisis un ami"
        d["riki.who_chat"] = "Avec qui veux-tu discuter ?"
        d["riki.typing"] = "Écrit..."
        d["riki.online"] = "En ligne"
        d["riki.listening"] = "Écoute..."
        d["riki.tap_send"] = "Appuie pour envoyer"
        d["riki.tap_talk"] = "Appuie pour parler"
        d["riki.speaking"] = "%@ parle..."
        d["riki.error_fallback"] = "Oups ! Je me suis un peu perdu. Tu peux réessayer ?"

        d["riki.greeting.momo"] = "Salut l'ami ! Je suis Momo. Qu'est-ce qui te préoccupe aujourd'hui ?"
        d["riki.greeting.goldie"] = "Coucou ! Je suis Goldie, et je suis tellement content de te voir ! De quoi on parle ?"
        d["riki.greeting.oreo"] = "Bonjour ! Je suis Oreo. Prêt pour une discussion sympa ?"
        d["riki.greeting.leo"] = "Salut ! Je suis Leo. Raconte-moi quelque chose de courageux sur ta journée !"
        d["riki.greeting.bunny"] = "Coucou ! Je suis Bunny. Qu'est-ce que tu as fait de fun ?"
        d["riki.greeting.tiki"] = "Salut ! Je suis Tiki. Quelle aventure allons-nous vivre aujourd'hui ?"
        d["riki.greeting.fluffy"] = "Salut ! Je suis Fluffy. Viens t'asseoir avec moi pour une discussion cosy !"
        d["riki.greeting.kitty"] = "Salut ! Je suis Kitty. J'ai fait la sieste et maintenant je suis prêt à discuter !"
        d["riki.greeting.panda"] = "Coucou ! Je suis Panda. On traîne ensemble et on discute un peu ?"
        d["riki.greeting.ellie"] = "Salut ! Je suis Ellie. Je n'oublie jamais mes amis ! Quoi de neuf ?"
        d["riki.greeting.ducky"] = "Salut ! Je suis Ducky. Faisons de cette journée une bonne journée — qu'est-ce qui se passe ?"

        d["riki.personality.momo"] = "Un singe joueur et curieux qui adore grimper aux arbres et explorer. Énergique et amusant, adore les blagues et les devinettes. Parle comme un vrai copain toujours prêt pour une aventure."
        d["riki.personality.goldie"] = "Un golden retriever loyal et enthousiaste. Adore jouer à la balle, se promener et rendre ses amis heureux. Super encourageant, toujours excité d'entendre ce qui se passe dans ta vie."
        d["riki.personality.oreo"] = "Un singe intelligent et amical qui adore les puzzles et apprendre de nouvelles choses. Réfléchi et encourageant, excellent pour t'aider à résoudre les problèmes compliqués."
        d["riki.personality.leo"] = "Un lion brave et gentil qui dirige avec courage. T'encourage à être brave, essayer de nouvelles choses et croire en toi. Chaleureux et protecteur, comme un grand frère."
        d["riki.personality.bunny"] = "Un lapin doux et gentil qui adore les jardins, la nature et les choses confortables. Une présence apaisante qui est vraiment bon pour écouter et comprendre ce que tu ressens."
        d["riki.personality.tiki"] = "Un tigre aventurier qui adore explorer et découvrir de nouvelles choses. Courageux mais doux, adore raconter des histoires sur la nature et les endroits lointains."
        d["riki.personality.fluffy"] = "Un mouton doux et chaleureux qui adore le confort et la gentillesse. Très doux et apaisant, excellent pour t'aider avec tes sentiments et tes soucis. Comme un meilleur ami qui te fait toujours sentir mieux."
        d["riki.personality.kitty"] = "Un chat curieux et indépendant qui adore les coins confortables et être joueur. Drôle et amusant, parfois un peu espiègle mais toujours gentil au fond."
        d["riki.personality.panda"] = "Un panda décontracté et adorable qui aime prendre son temps et être bête. Détendu et drôle, sait toujours comment te faire rire avec des commentaires rigolos."
        d["riki.personality.ellie"] = "Un éléphant sage et bienveillant avec une excellente mémoire. Réfléchi et attentionné, adore partager des faits amusants et t'aider à apprendre de nouvelles choses. Comme un ami très intelligent qui rend l'apprentissage facile."
        d["riki.personality.ducky"] = "Un canard joyeux et pétillant qui adore être optimiste et positif. Excellent pour te remonter le moral quand les choses sont difficiles, trouve toujours le bon côté."

        // MARK: - Reflection
        d["reflect.title"] = "Temps de réflexion"
        d["reflect.how_feeling"] = "Comment te sens-tu en ce moment ?"
        d["reflect.select_emotion"] = "Sélectionne une émotion pour commencer"
        d["reflect.session.title"] = "Réflexion guidée"
        d["reflect.session.breathe"] = "Prenons une grande respiration ensemble"
        d["reflect.session.think_about"] = "Pense à..."
        d["reflect.session.complete"] = "Belle réflexion !"
        d["reflect.session.done"] = "Tu as été super ! N'oublie pas, c'est normal de ressentir n'importe quelle émotion."
        d["reflect.coping.title"] = "Stratégies d'adaptation"
        d["reflect.coping.try_this"] = "Essaie ceci :"

        d["reflect.emotion.happy"] = "Content"
        d["reflect.emotion.sad"] = "Triste"
        d["reflect.emotion.angry"] = "En colère"
        d["reflect.emotion.scared"] = "Effrayé"
        d["reflect.emotion.worried"] = "Inquiet"
        d["reflect.emotion.calm"] = "Calme"
        d["reflect.emotion.excited"] = "Excité"
        d["reflect.emotion.confused"] = "Confus"
        d["reflect.emotion.tired"] = "Fatigué"
        d["reflect.emotion.lonely"] = "Seul"
        d["reflect.emotion.grateful"] = "Reconnaissant"
        d["reflect.emotion.frustrated"] = "Frustré"

        d["reflect.exercise.gratitude"] = "Nomme 3 choses pour lesquelles tu es reconnaissant aujourd'hui"
        d["reflect.exercise.breathing"] = "Respiration profonde"
        d["reflect.exercise.body_scan"] = "Scan corporel"
        d["reflect.exercise.journaling"] = "Écris sur tes sentiments"

        d["reflect.coping.deep_breath"] = "Prends 5 grandes respirations"
        d["reflect.coping.talk"] = "Parle à quelqu'un en qui tu as confiance"
        d["reflect.coping.move"] = "Fais une promenade ou étire-toi"
        d["reflect.coping.create"] = "Dessine ou écris sur ce que tu ressens"
        d["reflect.coping.music"] = "Écoute ta musique préférée"
        d["reflect.coping.count"] = "Compte à rebours depuis 10"

        // MARK: - Browser
        d["browser.address_placeholder"] = "Rechercher ou entrer une URL"
        d["browser.loading"] = "Chargement..."
        d["browser.new_tab"] = "Nouvel onglet"
        d["browser.tabs"] = "Onglets"
        d["browser.close_tab"] = "Fermer l'onglet"
        d["browser.menu"] = "Menu"
        d["browser.share"] = "Partager"
        d["browser.reload"] = "Recharger"
        d["browser.forward"] = "Suivant"
        d["browser.history"] = "Historique"
        d["browser.homepage"] = "Accueil"

        // MARK: - Blocked
        d["blocked.title"] = "Contenu bloqué"
        d["blocked.message"] = "Cette page a été bloquée pour ta sécurité."
        d["blocked.reason"] = "Raison : %@"
        d["blocked.ask_parent"] = "Demande à un parent de l'autoriser"
        d["blocked.go_back"] = "Retour"
        d["blocked.countdown"] = "Retour dans %d..."
        d["blocked.emoji_prompt"] = "Comment tu te sens ?"

        d["gate.title"] = "Approbation parentale nécessaire"
        d["gate.message"] = "Ce contenu nécessite l'approbation d'un parent."
        d["gate.enter_pin"] = "Entrez le PIN parental pour continuer"

        d["checkin.how_feeling"] = "Comment te sens-tu en explorant ça ?"
        d["checkin.how_are_you"] = "Comment te sens-tu ?"

        // MARK: - Anchors
        d["anchor.morning.title"] = "Bonjour !"
        d["anchor.morning.subtitle"] = "Comment te sens-tu ce matin ?"
        d["anchor.morning.set_intention"] = "Définis ton intention pour aujourd'hui"
        d["anchor.morning.intention_placeholder"] = "Aujourd'hui je veux..."
        d["anchor.morning.ready"] = "Je suis prêt pour aujourd'hui !"

        d["anchor.evening.title"] = "Réflexion du soir"
        d["anchor.evening.subtitle"] = "Comment s'est passée ta journée ?"
        d["anchor.evening.best_part"] = "Quelle a été la meilleure partie de ta journée ?"
        d["anchor.evening.best_placeholder"] = "La meilleure partie c'était..."
        d["anchor.evening.learned"] = "Qu'as-tu appris aujourd'hui ?"
        d["anchor.evening.learned_placeholder"] = "J'ai appris..."
        d["anchor.evening.goodnight"] = "Bonne nuit !"

        // MARK: - Reconnection
        d["reconnection.title"] = "Bon retour !"
        d["reconnection.subtitle"] = "Tu nous as manqué ! Ça fait un moment."
        d["reconnection.whats_new"] = "Voici les nouveautés depuis ta dernière visite"
        d["reconnection.lets_go"] = "C'est parti !"
        d["reconnection.missed_days"] = "Tu as été absent pendant %d jours"

        // MARK: - Growth
        d["growth.title"] = "Parcours de croissance"
        d["growth.milestones"] = "Jalons"
        d["growth.weekly_snapshot"] = "Bilan hebdomadaire"
        d["growth.streak"] = "Série"
        d["growth.days"] = "jours"
        d["growth.level"] = "Niveau"
        d["growth.explorer"] = "Explorateur"
        d["growth.adventurer"] = "Aventurier"
        d["growth.champion"] = "Champion"
        d["growth.legend"] = "Légende"
        d["growth.earned"] = "Obtenu !"
        d["growth.locked"] = "Continue comme ça !"
        d["growth.snapshot.conversations"] = "Conversations"
        d["growth.snapshot.reflections"] = "Réflexions"
        d["growth.snapshot.browsing_time"] = "Temps de navigation"
        d["growth.snapshot.mood_checks"] = "Bilans d'humeur"

        // MARK: - Journey
        d["journey.title"] = "Parcours numérique"
        d["journey.ai_insights"] = "Analyses IA"
        d["journey.history"] = "Historique"
        d["journey.no_activity"] = "Aucune activité enregistrée"
        d["journey.time_spent"] = "Temps passé"
        d["journey.sites_visited"] = "Sites visités"
        d["journey.blocked_attempts"] = "Tentatives bloquées"

        // MARK: - Insights
        d["insights.title"] = "Analyses parentales"
        d["insights.wellness"] = "Aperçu du bien-être"
        d["insights.mood_trends"] = "Tendances d'humeur"
        d["insights.chat_activity"] = "Activité de discussion"
        d["insights.browsing_summary"] = "Résumé de navigation"
        d["insights.alerts"] = "Alertes"
        d["insights.no_alerts"] = "Aucune alerte à afficher"
        d["insights.this_week"] = "Cette semaine"
        d["insights.this_month"] = "Ce mois"

        // MARK: - History
        d["history.title"] = "Historique de navigation"
        d["history.today"] = "Aujourd'hui"
        d["history.yesterday"] = "Hier"
        d["history.earlier"] = "Plus tôt"
        d["history.no_history"] = "Aucun historique de navigation"
        d["history.clear"] = "Effacer l'historique"
        d["history.clear_confirm"] = "Êtes-vous sûr de vouloir effacer tout l'historique de navigation ?"

        // MARK: - Prompts
        d["prompt.welcome_back"] = "Bon retour ! Prêt à explorer ?"
        d["prompt.take_break"] = "Tu navigues depuis un moment. Une pause ?"
        d["prompt.try_reflect"] = "Et si tu faisais un bilan de tes émotions ?"
        d["prompt.chat_riki"] = "Tu veux discuter avec un ami ?"
        d["prompt.new_milestone"] = "Tu as gagné un nouveau jalon !"
        d["prompt.dismiss"] = "Peut-être plus tard"
        d["prompt.lets_go"] = "C'est parti !"

        // MARK: - Notifications
        d["notification.morning.title"] = "Bonjour !"
        d["notification.morning.body"] = "Commence ta journée avec un bilan du matin"
        d["notification.evening.title"] = "C'est le soir"
        d["notification.evening.body"] = "Détends-toi avec une réflexion du soir"
        d["notification.reconnect.title"] = "Tu nous manques !"
        d["notification.reconnect.body"] = "Tes amis t'attendent pour discuter"
        d["notification.milestone.title"] = "Nouveau jalon !"
        d["notification.milestone.body"] = "Tu as gagné une nouvelle réussite. Découvre-la !"

        // MARK: - Mood
        d["mood.history.title"] = "Historique d'humeur"
        d["mood.history.recent"] = "Humeurs récentes"
        d["mood.history.no_entries"] = "Aucune entrée d'humeur"
        d["mood.history.trend"] = "Ta tendance d'humeur"

        // MARK: - Screen Time
        d["screentime.minimal"] = "30 min/jour"
        d["screentime.moderate"] = "1-2 heures/jour"
        d["screentime.flexible"] = "Flexible"

        return d
    }()
}
// swiftlint:enable file_length type_body_length
#endif
