// swiftlint:disable file_length type_body_length
enum FrenchStrings {
    static let all: [String: String] = {
        var d = [String: String]()

        // MARK: - Common
        d["common.back"] = "Retour"
        d["common.continue"] = "Continuer"
        d["common.done"] = "Terminé"
        d["common.skip"] = "Passer"
        d["common.cancel"] = "Annuler"
        d["common.save"] = "Enregistrer"
        d["common.delete"] = "Supprimer"
        d["common.yes"] = "Oui"
        d["common.no"] = "Non"
        d["common.ok"] = "OK"
        d["common.close"] = "Fermer"
        d["common.enter"] = "Entrer"
        d["common.next"] = "Suivant"
        d["common.settings"] = "Réglages"
        d["common.selected_count"] = "%d/%d sélectionnés"
        d["common.step_of"] = "ÉTAPE %@"

        // MARK: - Splash
        d["splash.title"] = "Komal"
        d["splash.tagline"] = "Le compagnon numérique sûr de votre enfant"

        // MARK: - Login
        d["login.welcome"] = "Bienvenue sur Komal"
        d["login.tagline"] = "Le compagnon numérique sûr de votre enfant"
        d["login.sign_in_google"] = "Se connecter avec Google"
        d["login.sign_in_apple"] = "Se connecter avec Apple"
        d["login.or"] = "ou"
        d["login.guest_user"] = "Continuer en tant qu'invité"
        d["login.signing_in"] = "Connexion en cours..."
        d["login.failed"] = "Échec de la connexion"
        d["login.try_again"] = "Réessayer"
        d["login.guest.welcome"] = "Bienvenue, Invité !"
        d["login.guest.description"] = "Vos données seront stockées localement sur cet appareil. Vous pourrez vous connecter plus tard pour synchroniser sur plusieurs appareils."
        d["login.guest.getting_started"] = "Commencer"
        d["login.onboarding.welcome"] = "Bienvenue sur Komal !"
        d["login.onboarding.description"] = "Configurons votre expérience de navigation sécurisée."
        d["login.onboarding.get_started"] = "Commencer"

        // MARK: - Onboarding Welcome
        d["onboarding.welcome.title"] = "Évaluation de la sécurité de l'enfant"
        d["onboarding.welcome.subtitle"] = "Profil de bien-être numérique basé sur des preuves"
        d["onboarding.welcome.card1.title"] = "Psychologie du développement"
        d["onboarding.welcome.card1.desc"] = "Paramètres adaptés aux stades de développement cognitif définis par la recherche en psychologie de l'enfant."
        d["onboarding.welcome.card2.title"] = "Analyse comportementale"
        d["onboarding.welcome.card2.desc"] = "Comprendre les habitudes de navigation pour créer des limites de sécurité personnalisées."
        d["onboarding.welcome.card3.title"] = "Protection proactive"
        d["onboarding.welcome.card3.desc"] = "Filtrage de contenu basé sur les facteurs de risque et les préférences identifiés."
        d["onboarding.welcome.time_estimate"] = "Cette évaluation prend environ 3-4 minutes"
        d["onboarding.welcome.begin"] = "Commencer l'évaluation"
        d["onboarding.welcome.language"] = "Langue"

        // MARK: - Onboarding Child Info
        d["onboarding.info.step"] = "1 sur 6"
        d["onboarding.info.title"] = "Informations de base"
        d["onboarding.info.subtitle"] = "Aidez-nous à comprendre qui nous protégeons"
        d["onboarding.info.name_label"] = "Prénom de l'enfant"
        d["onboarding.info.name_placeholder"] = "Entrez le prénom"
        d["onboarding.info.age_label"] = "Groupe d'âge"
        d["onboarding.info.age_desc"] = "Les restrictions de contenu sont calibrées en fonction des étapes de développement"
        d["onboarding.info.research_note"] = "La recherche montre que des limites de contenu adaptées à l'âge favorisent un développement cognitif sain et réduisent l'anxiété chez les enfants."

        // Age group descriptions
        d["onboarding.age.under10"] = "Petite enfance - Protection maximale"
        d["onboarding.age.10to13"] = "Pré-adolescent - Exploration guidée"
        d["onboarding.age.13to16"] = "Adolescent - Limites équilibrées"
        d["onboarding.age.16to18"] = "Grand adolescent - Liberté adaptée à l'âge"
        d["onboarding.age.18plus"] = "Adulte - Accès complet"

        // MARK: - Onboarding Websites
        d["onboarding.websites.step"] = "2 sur 6"
        d["onboarding.websites.title"] = "Sites Web favoris"
        d["onboarding.websites.subtitle"] = "Sélectionnez jusqu'à 5 sites que votre enfant visite le plus"
        d["onboarding.websites.desc"] = "Comprendre les habitudes de navigation nous aide à identifier les sources fiables et à personnaliser la protection."

        // MARK: - Onboarding Interests
        d["onboarding.interests.step"] = "3 sur 6"
        d["onboarding.interests.title"] = "Centres d'intérêt"
        d["onboarding.interests.subtitle"] = "Qu'est-ce que votre enfant aime apprendre ?"
        d["onboarding.interests.desc"] = "Sélectionnez 3 à 5 sujets. Cela nous aide à comprendre quel contenu prioriser et protéger."

        // Interest names
        d["onboarding.interest.gaming"] = "Jeux vidéo"
        d["onboarding.interest.animals"] = "Animaux"
        d["onboarding.interest.science"] = "Sciences"
        d["onboarding.interest.art"] = "Art et dessin"
        d["onboarding.interest.music"] = "Musique"
        d["onboarding.interest.sports"] = "Sports"
        d["onboarding.interest.coding"] = "Programmation"
        d["onboarding.interest.reading"] = "Lecture"
        d["onboarding.interest.cooking"] = "Cuisine"
        d["onboarding.interest.nature"] = "Nature"
        d["onboarding.interest.space"] = "Espace"
        d["onboarding.interest.history"] = "Histoire"
        d["onboarding.interest.movies"] = "Films"
        d["onboarding.interest.crafts"] = "Bricolage"
        d["onboarding.interest.dinosaurs"] = "Dinosaures"
        d["onboarding.interest.vehicles"] = "Véhicules"
        d["onboarding.interest.fashion"] = "Mode"
        d["onboarding.interest.dance"] = "Danse"
        d["onboarding.interest.photography"] = "Photographie"
        d["onboarding.interest.travel"] = "Voyage"
        d["onboarding.interest.math"] = "Maths"
        d["onboarding.interest.puzzles"] = "Puzzles"
        d["onboarding.interest.robots"] = "Robots"
        d["onboarding.interest.magic"] = "Magie"
        d["onboarding.interest.superheroes"] = "Super-héros"
        d["onboarding.interest.gardening"] = "Jardinage"
        d["onboarding.interest.astronomy"] = "Astronomie"
        d["onboarding.interest.languages"] = "Langues"
        d["onboarding.interest.boardgames"] = "Jeux de société"
        d["onboarding.interest.swimming"] = "Natation"
        d["onboarding.interest.comics"] = "Bandes dessinées"
        d["onboarding.interest.yoga"] = "Yoga"
        d["onboarding.interest.theater"] = "Théâtre"

        // MARK: - Onboarding Likes
        d["onboarding.likes.step"] = "4 sur 6"
        d["onboarding.likes.title"] = "Ce qu'ils aiment en ligne"
        d["onboarding.likes.subtitle"] = "Comprendre les expériences positives en ligne"
        d["onboarding.likes.desc"] = "Sélectionnez les activités que votre enfant apprécie. Cela nous aide à garantir l'accès à du contenu enrichissant."
        d["onboarding.likes.other"] = "Autre (facultatif)"
        d["onboarding.likes.other_placeholder"] = "Ajoutez autre chose qu'ils aiment..."

        // Like options
        d["onboarding.like.watching_videos"] = "Regarder des vidéos"
        d["onboarding.like.playing_games"] = "Jouer à des jeux"
        d["onboarding.like.chatting"] = "Discuter avec des amis"
        d["onboarding.like.learning"] = "Apprendre de nouvelles choses"
        d["onboarding.like.creative"] = "Projets créatifs"
        d["onboarding.like.exploring"] = "Explorer des sites web"
        d["onboarding.like.music"] = "Écouter de la musique"
        d["onboarding.like.virtual_worlds"] = "Mondes virtuels"
        d["onboarding.like.puzzles"] = "Puzzles et défis"
        d["onboarding.like.funny"] = "Contenu drôle"
        d["onboarding.like.stories"] = "Histoires et livres"
        d["onboarding.like.making_videos"] = "Créer des vidéos"
        d["onboarding.like.drawing"] = "Dessin et peinture"
        d["onboarding.like.photography"] = "Prendre des photos"
        d["onboarding.like.coding"] = "Codage et programmation"
        d["onboarding.like.reading_comics"] = "Lire des BD"
        d["onboarding.like.collecting"] = "Collectionner"
        d["onboarding.like.building"] = "Construire et bricoler"
        d["onboarding.like.cooking_videos"] = "Vidéos de cuisine"
        d["onboarding.like.science_experiments"] = "Expériences scientifiques"
        d["onboarding.like.dancing"] = "Danser"
        d["onboarding.like.trivia"] = "Quiz et anecdotes"
        d["onboarding.like.anime"] = "Anime et dessins animés"
        d["onboarding.like.podcasts"] = "Podcasts"
        d["onboarding.like.shopping"] = "Shopping en ligne"
        d["onboarding.like.live_streams"] = "Regarder des streams"

        // MARK: - Onboarding Dislikes
        d["onboarding.dislikes.step"] = "5 sur 6"
        d["onboarding.dislikes.title"] = "Ce qui les dérange"
        d["onboarding.dislikes.subtitle"] = "Identifier les déclencheurs et les malaises"
        d["onboarding.dislikes.desc"] = "Sélectionnez ce qui inquiète ou dérange votre enfant en ligne. Cela nous aide à filtrer le contenu potentiellement perturbant."
        d["onboarding.dislikes.other"] = "Autres préoccupations (facultatif)"
        d["onboarding.dislikes.other_placeholder"] = "Ajoutez d'autres choses qui les dérangent..."
        d["onboarding.dislikes.research_note"] = "Comprendre ce qui perturbe les enfants en ligne nous permet de filtrer proactivement le contenu avant l'exposition, réduisant l'anxiété et les expériences négatives."

        // Dislike options
        d["onboarding.dislike.scary"] = "Contenu effrayant"
        d["onboarding.dislike.loud"] = "Bruits forts/jumpscares"
        d["onboarding.dislike.mean"] = "Commentaires méchants"
        d["onboarding.dislike.strangers"] = "Messages d'inconnus"
        d["onboarding.dislike.violent"] = "Jeux violents"
        d["onboarding.dislike.sad"] = "Histoires tristes"
        d["onboarding.dislike.ads"] = "Publicités confuses"
        d["onboarding.dislike.reading"] = "Trop de lecture"
        d["onboarding.dislike.timed"] = "Défis chronométrés"
        d["onboarding.dislike.losing"] = "Perdre dans les jeux"
        d["onboarding.dislike.popups"] = "Vidéos pop-up"
        d["onboarding.dislike.rushed"] = "Être pressé"

        // MARK: - Onboarding Concerns
        d["onboarding.concerns.step"] = "6 sur 8"
        d["onboarding.concerns.title"] = "Vos préoccupations"
        d["onboarding.concerns.subtitle"] = "Qu'est-ce qui vous inquiète le plus concernant votre enfant en ligne ?"
        d["onboarding.concerns.desc"] = "Sélectionnez vos principales préoccupations. Nous prioriserons la protection dans ces domaines."

        // Concern items
        d["onboarding.concern.cyberbullying"] = "Cyberharcèlement"
        d["onboarding.concern.cyberbullying.desc"] = "Harcèlement, messages méchants, exclusion"
        d["onboarding.concern.inappropriate"] = "Contenu inapproprié"
        d["onboarding.concern.inappropriate.desc"] = "Violence, thèmes adultes, matériel explicite"
        d["onboarding.concern.predators"] = "Prédateurs en ligne"
        d["onboarding.concern.predators.desc"] = "Inconnus, manipulation, demandes d'informations personnelles"
        d["onboarding.concern.addiction"] = "Addiction aux écrans"
        d["onboarding.concern.addiction.desc"] = "Utilisation excessive, difficulté à arrêter"
        d["onboarding.concern.privacy"] = "Risques de confidentialité"
        d["onboarding.concern.privacy.desc"] = "Collecte de données, partage de localisation"
        d["onboarding.concern.misinfo"] = "Désinformation"
        d["onboarding.concern.misinfo.desc"] = "Fausses nouvelles, théories conspirationnistes"
        d["onboarding.concern.scams"] = "Arnaques financières"
        d["onboarding.concern.scams.desc"] = "Achats intégrés, hameçonnage"
        d["onboarding.concern.mental"] = "Santé mentale"
        d["onboarding.concern.mental.desc"] = "Anxiété, comparaison, peur de manquer"

        // MARK: - Onboarding Filters
        d["onboarding.filters.step"] = "7 sur 8"
        d["onboarding.filters.title"] = "Filtres de contenu"
        d["onboarding.filters.subtitle"] = "Examiner et personnaliser le filtrage de contenu"
        d["onboarding.filters.desc"] = "Ces paramètres par défaut sont basés sur l'âge de votre enfant et vos préoccupations. Ajustez les paramètres ci-dessous."

        // MARK: - Onboarding PIN
        d["onboarding.pin.step"] = "8 sur 8"
        d["onboarding.pin.title"] = "Définir le PIN parental"
        d["onboarding.pin.subtitle"] = "Créez un PIN pour protéger les paramètres parentaux"
        d["onboarding.pin.desc"] = "Ce PIN sera requis pour accéder au mode parent et approuver le contenu restreint."
        d["onboarding.pin.enter"] = "Entrez le PIN"
        d["onboarding.pin.placeholder"] = "PIN à 4 chiffres"
        d["onboarding.pin.confirm"] = "Confirmez le PIN"
        d["onboarding.pin.confirm_placeholder"] = "Confirmez le PIN"
        d["onboarding.pin.mismatch"] = "Les PIN ne correspondent pas. Veuillez réessayer."
        d["onboarding.pin.enable_biometric"] = "Activer %@"
        d["onboarding.pin.use_biometric"] = "Utiliser %@ au lieu du PIN"
        d["onboarding.pin.research_note"] = "Un PIN parental garantit que seuls les adultes autorisés peuvent modifier les paramètres de sécurité et approuver le contenu restreint."

        // MARK: - Avatar Selection
        d["onboarding.avatar.title"] = "Choisis ton compagnon"
        d["onboarding.avatar.subtitle"] = "Choisis un ami animal pour te guider !"
        d["settings.avatar.title"] = "Ton avatar"
        d["settings.avatar.change"] = "Appuie pour changer ton avatar"

        // MARK: - Onboarding Completion
        d["onboarding.complete.title"] = "Profil terminé"
        d["onboarding.complete.subtitle"] = "Le profil de sécurité de %@ est prêt"
        d["onboarding.complete.summary"] = "Résumé de l'évaluation"
        d["onboarding.complete.name"] = "Nom"
        d["onboarding.complete.age_group"] = "Groupe d'âge"
        d["onboarding.complete.interests"] = "Centres d'intérêt"
        d["onboarding.complete.concerns"] = "Préoccupations principales"
        d["onboarding.complete.adjust_note"] = "Les paramètres peuvent être ajustés à tout moment dans l'application"
        d["onboarding.complete.start"] = "Commencer à utiliser Komal"
        d["onboarding.complete.review"] = "Revoir les réponses"

        // MARK: - Menu / Navigation
        d["menu.browse"] = "Naviguer"
        d["menu.talk"] = "Parler"
        d["menu.reflect"] = "Réfléchir"
        d["menu.settings"] = "Réglages"

        // MARK: - Plan Selection
        d["plan.choose_title"] = "Choisissez votre forfait"
        d["plan.choose_subtitle"] = "Choisissez le bon niveau de protection pour votre famille"
        d["plan.start_essentials"] = "Commencer avec Essentials"
        d["plan.subscribe_to"] = "S'abonner à %@"
        d["plan.restore_purchases"] = "Restaurer les achats"
        d["plan.purchase_error"] = "Erreur d'achat"
        d["plan.unavailable"] = "Ce forfait n'est pas disponible pour le moment. Veuillez réessayer plus tard."
        d["plan.recommended"] = "RECOMMANDÉ"
        d["plan.free"] = "Gratuit"
        d["plan.per_month"] = "%@/mois"
        d["plan.loading"] = "Chargement..."
        d["plan.profiles_up_to"] = "Jusqu'à %d profils enfant"
        d["plan.profiles_unlimited"] = "Profils enfant illimités"

        // MARK: - Settings
        d["settings.title"] = "Réglages"
        d["settings.language"] = "Langue"
        d["settings.whos_using"] = "Qui utilise ?"
        d["settings.whos_using.desc"] = "Sélectionnez qui utilise actuellement l'appareil"
        d["settings.child"] = "Enfant"
        d["settings.child.subtitle"] = "Navigation sécurisée"
        d["settings.parent"] = "Parent"
        d["settings.parent.subtitle"] = "Accès complet"

        // Settings - Child Mode
        d["settings.child.greeting"] = "Salut %@ !"
        d["settings.child.greeting_default"] = "Salut !"
        d["settings.child.safe_msg"] = "Komal est là pour te protéger pendant que tu explores !"
        d["settings.child.chatty"] = "Envie de discuter ?"
        d["settings.child.chatty.desc"] = "Parle à Riki ! Ton compagnon amical est toujours là pour discuter et t'aider."
        d["settings.child.go_talk"] = "Aller à Parler"
        d["settings.child.profile"] = "Ton profil"
        d["settings.child.explorer"] = "Explorateur"
        d["settings.child.age"] = "Âge : %@"
        d["settings.child.journey"] = "Mon parcours"
        d["settings.child.day_streak"] = "Jours consécutifs"
        d["settings.child.milestones"] = "Jalons"
        d["settings.child.view_journey"] = "Voir mon parcours"

        // Settings - Parent Mode
        d["settings.parent.digital_journey"] = "Parcours numérique"
        d["settings.parent.view_journey"] = "Voir le parcours numérique"
        d["settings.parent.journey_desc"] = "Voir l'activité de navigation de votre enfant avec des analyses IA"
        d["settings.parent.wellness"] = "Bien-être de l'enfant"
        d["settings.parent.wellness_dashboard"] = "Tableau de bord bien-être"
        d["settings.parent.wellness_desc"] = "Tendances d'humeur, conversations, indicateurs de croissance"
        d["settings.parent.morning_checkin"] = "Bilan du matin"
        d["settings.parent.morning_desc"] = "Ancrage d'humeur matinal quotidien"
        d["settings.parent.evening_winddown"] = "Détente du soir"
        d["settings.parent.evening_desc"] = "Ancrage de réflexion du soir quotidien"
        d["settings.parent.child_profile"] = "Profil de l'enfant"
        d["settings.parent.name_label"] = "Nom"
        d["settings.parent.name_placeholder"] = "Nom de l'enfant"
        d["settings.parent.age_label"] = "Groupe d'âge"
        d["settings.parent.controls"] = "Contrôles parentaux"
        d["settings.parent.notify_block"] = "Notifier en cas de blocage"
        d["settings.parent.notify_desc"] = "Recevoir des alertes lors de l'accès au contenu bloqué"
        d["settings.parent.safe_search"] = "Recherche sécurisée forcée"
        d["settings.parent.safe_search_desc"] = "Appliquer la sécurité stricte sur les moteurs de recherche"
        d["settings.parent.view_insights"] = "Voir les analyses"
        d["settings.parent.insights_desc"] = "Voir l'activité de navigation et le contenu bloqué"
        d["settings.parent.modify_content"] = "Modifier le contenu"
        d["settings.parent.modify_filters"] = "Modifier les filtres"
        d["settings.parent.custom_keywords"] = "Mots-clés personnalisés"
        d["settings.parent.add_keyword"] = "Ajouter un mot-clé (ex : 'armes')"
        d["settings.parent.no_keywords"] = "Aucun mot-clé personnalisé ajouté."
        d["settings.parent.custom_websites"] = "Sites web personnalisés"
        d["settings.parent.add_website"] = "Ajouter un site (ex : 'siteinterdit.com')"
        d["settings.parent.no_websites"] = "Aucun site web personnalisé ajouté."

        // Settings - Account
        d["settings.account"] = "Compte"
        d["settings.account.guest"] = "Utilisation en tant qu'invité"
        d["settings.account.guest_desc"] = "Vos données sont stockées localement sur cet appareil uniquement. Connectez-vous pour synchroniser sur plusieurs appareils."
        d["settings.account.sign_in"] = "Se connecter"
        d["settings.account.exit_guest"] = "Quitter le mode invité"
        d["settings.account.delete"] = "Supprimer le compte"
        d["settings.account.logout"] = "Déconnexion"
        d["settings.account.login"] = "Connexion"
        d["settings.account.sync_desc"] = "Connectez-vous pour synchroniser vos préférences sur plusieurs appareils"

        // Settings - Alerts
        d["settings.alert.logout.title"] = "Déconnexion"
        d["settings.alert.logout.message"] = "Voulez-vous vous déconnecter ?"
        d["settings.alert.delete.title"] = "Supprimer le compte"
        d["settings.alert.delete.message"] = "Êtes-vous sûr de vouloir supprimer le compte ? Cette action est irréversible."

        // Settings - PIN Entry
        d["settings.pin.title"] = "Entrez le PIN parental"
        d["settings.pin.subtitle"] = "Entrez votre PIN à 4 chiffres pour accéder aux paramètres parentaux"
        d["settings.pin.placeholder"] = "PIN"
        d["settings.pin.error"] = "PIN incorrect. Réessayez."
        d["settings.pin.biometric"] = "Utiliser %@"

        // Settings - Subscription & Billing
        d["settings.view_plans"] = "Voir tous les forfaits et les tarifs"
        d["settings.billing_invoices"] = "Facturation et reçus"
        d["settings.billing_desc"] = "Voir l'historique des transactions et les reçus"
        d["settings.manage_appstore"] = "Gérer dans l'App Store"
        d["settings.manage_appstore_desc"] = "Annuler, renouveler ou modifier le moyen de paiement"
        d["settings.current_plan"] = "Forfait actuel"
        d["settings.per_month"] = "par mois"
        d["settings.next_renewal"] = "Prochain renouvellement : %@"
        d["settings.transaction_history"] = "Historique des transactions"
        d["settings.no_transactions"] = "Aucune transaction"
        d["settings.transactions_placeholder"] = "Votre historique d'achats apparaîtra ici"
        d["settings.subscriptions_info"] = "Les abonnements sont gérés via votre identifiant Apple. Pour demander un remboursement, visitez reportaproblem.apple.com"
        d["settings.plan_monthly"] = "%@ Mensuel"

        // Settings - PIN Management
        d["settings.change_pin"] = "Changer le PIN"
        d["settings.change_pin_desc"] = "Définir un nouveau PIN parental à 4 chiffres"
        d["settings.forgot_pin"] = "PIN oublié ? Réinitialiser avec %@"
        d["settings.pin_updated"] = "PIN mis à jour"
        d["settings.pin_saved_msg"] = "Votre nouveau PIN parental a été enregistré."
        d["settings.set_new_pin"] = "Nouveau PIN"
        d["settings.new_pin_desc"] = "Entrez un nouveau PIN parental à 4 chiffres"
        d["settings.pin_mismatch"] = "Les PINs ne correspondent pas ou sont incomplets"
        d["settings.save_pin"] = "Enregistrer le PIN"

        // Settings - Localized UI Strings
        d["settings.logout_confirm"] = "Voulez-vous vous déconnecter ?"
        d["settings.delete_confirm"] = "Êtes-vous sûr de vouloir supprimer votre compte ? Cette action est irréversible."
        d["settings.wellness_dashboard"] = "Tableau de bord bien-être"
        d["settings.wellness_desc"] = "Tendances d'humeur, conversations, indicateurs de croissance"
        d["settings.view_insights"] = "Voir les analyses"
        d["settings.insights_desc"] = "Voir l'activité de navigation et le contenu bloqué"
        d["settings.modify_filters"] = "Modifier les filtres"
        d["settings.custom_keywords"] = "Mots-clés personnalisés"
        d["settings.no_keywords"] = "Aucun mot-clé personnalisé ajouté."
        d["settings.custom_websites"] = "Sites web personnalisés"
        d["settings.no_websites"] = "Aucun site web personnalisé ajouté."
        d["settings.using_guest"] = "Utilisation en tant qu'invité"
        d["settings.guest_data_info"] = "Vos données sont stockées localement sur cet appareil uniquement. Connectez-vous pour synchroniser sur plusieurs appareils."
        d["settings.sign_in"] = "Se connecter"
        d["settings.exit_guest"] = "Quitter le mode invité"
        d["settings.delete_account"] = "Supprimer le compte"
        d["settings.logout"] = "Déconnexion"
        d["settings.login"] = "Connexion"
        d["settings.sync_desc"] = "Connectez-vous pour synchroniser vos préférences sur plusieurs appareils"
        d["settings.enter_pin"] = "Entrez le PIN parental"
        d["settings.pin_desc"] = "Entrez votre PIN à 4 chiffres pour accéder aux paramètres parentaux"
        d["settings.incorrect_pin"] = "PIN incorrect. Réessayez."
        d["settings.use_biometric"] = "Utiliser %@"
        d["settings.enter"] = "Entrer"

        // MARK: - Riki / Talk
        d["riki.choose_friend"] = "Choisis un ami"
        d["riki.who_chat"] = "Avec qui veux-tu discuter ?"
        d["riki.typing"] = "Écrit..."
        d["riki.online"] = "En ligne"
        d["riki.listening"] = "Écoute..."
        d["riki.tap_send"] = "Appuie pour envoyer"
        d["riki.tap_talk"] = "Appuie pour parler"
        d["riki.speaking"] = "%@ parle..."
        d["riki.error_fallback"] = "Oups ! Je me suis un peu perdu. Tu peux réessayer ?"
        d["riki.friend_title"] = "%@ l'ami"
        d["riki.paused"] = "En pause"
        d["riki.tap_resume"] = "Appuie pour reprendre"

        // SEL emoji labels
        d["sel.happy"] = "Content"
        d["sel.sad"] = "Triste"
        d["sel.angry"] = "En colère"
        d["sel.worried"] = "Inquiet"
        d["sel.grateful"] = "Reconnaissant"
        d["sel.tired"] = "Fatigué"
        // Character greetings
        d["riki.greeting.momo"] = "Salut l'ami ! Je suis Momo. Qu'est-ce qui te préoccupe aujourd'hui ?"
        d["riki.greeting.goldie"] = "Coucou ! Je suis Goldie, et je suis tellement contente de te voir ! De quoi on parle ?"
        d["riki.greeting.oreo"] = "Bonjour ! Je suis Oreo. Prêt pour une discussion sympa ?"
        d["riki.greeting.leo"] = "Salut ! Je suis Leo. Raconte-moi quelque chose de courageux sur ta journée !"
        d["riki.greeting.bunny"] = "Coucou ! Je suis Bunny. Qu'est-ce que tu as fait de fun ?"
        d["riki.greeting.tiki"] = "Salut ! Je suis Tiki. Quelle aventure allons-nous vivre aujourd'hui ?"
        d["riki.greeting.fluffy"] = "Salut ! Je suis Fluffy. Viens t'asseoir avec moi pour une discussion cosy !"
        d["riki.greeting.kitty"] = "Salut ! Je suis Kitty. J'ai fait la sieste et maintenant je suis prête à discuter !"
        d["riki.greeting.panda"] = "Coucou ! Je suis Panda. On traîne ensemble et on discute un peu ?"
        d["riki.greeting.ellie"] = "Salut ! Je suis Ellie. Je n'oublie jamais mes amis ! Quoi de neuf ?"
        d["riki.greeting.ducky"] = "Salut ! Je suis Ducky. Faisons de cette journée une bonne journée — qu'est-ce qui se passe ?"

        // Character personalities
        d["riki.personality.momo"] = "Un singe joueur et curieux qui adore grimper aux arbres et explorer. Énergique et amusant, adore les blagues et les devinettes. Parle comme un vrai copain toujours prêt pour une aventure."
        d["riki.personality.goldie"] = "Une golden retriever loyale et enthousiaste. Adore jouer à la balle, se promener et rendre ses amis heureux. Super encourageante, toujours excitée d'entendre ce qui se passe dans ta vie."
        d["riki.personality.oreo"] = "Un singe intelligent et amical qui adore les puzzles et apprendre de nouvelles choses. Réfléchi et encourageant, excellent pour t'aider à résoudre les problèmes compliqués."
        d["riki.personality.leo"] = "Un lion brave et gentil qui dirige avec courage. T'encourage à être brave, essayer de nouvelles choses et croire en toi. Chaleureux et protecteur, comme un grand frère."
        d["riki.personality.bunny"] = "Une lapine douce et gentille qui adore les jardins, la nature et les choses confortables. Une présence apaisante qui est vraiment bonne pour écouter et comprendre ce que tu ressens."
        d["riki.personality.tiki"] = "Un tigre aventurier qui adore explorer et découvrir de nouvelles choses. Courageux mais doux, adore raconter des histoires sur la nature et les endroits lointains."
        d["riki.personality.fluffy"] = "Un mouton doux et chaleureux qui adore le confort et la gentillesse. Très doux et apaisant, excellent pour t'aider avec tes sentiments et tes soucis. Comme un meilleur ami qui te fait toujours sentir mieux."
        d["riki.personality.kitty"] = "Une chatte curieuse et indépendante qui adore les coins confortables et être joueuse. Drôle et amusante, parfois un peu espiègle mais toujours gentille au fond."
        d["riki.personality.panda"] = "Un panda décontracté et adorable qui aime prendre son temps et être bête. Détendu et drôle, sait toujours comment te faire rire avec des commentaires rigolos."
        d["riki.personality.ellie"] = "Une éléphante sage et bienveillante avec une excellente mémoire. Réfléchie et attentionnée, adore partager des faits amusants et t'aider à apprendre de nouvelles choses. Comme une amie très intelligente qui rend l'apprentissage facile."
        d["riki.personality.ducky"] = "Un canard joyeux et pétillant qui adore être optimiste et positif. Excellent pour te remonter le moral quand les choses sont difficiles, trouve toujours le bon côté."

        // MARK: - Reflection
        d["reflect.how_feeling"] = "Comment te sens-tu en ce moment ?"
        d["reflect.select_emotion"] = "Sélectionne une émotion pour commencer"
        d["reflect.session.title"] = "Réflexion guidée"
        d["reflect.session.breathe"] = "Prenons une grande respiration ensemble"
        d["reflect.session.think_about"] = "Pense à..."
        d["reflect.session.complete"] = "Belle réflexion !"
        d["reflect.session.done"] = "Tu as été super ! N'oublie pas, c'est normal de ressentir n'importe quelle émotion."
        d["reflect.coping.title"] = "Stratégies d'adaptation"
        d["reflect.coping.try_this"] = "Essaie ceci :"

        // Emotions
        d["reflect.emotion.happy"] = "Content"
        d["reflect.emotion.sad"] = "Triste"
        d["reflect.emotion.angry"] = "En colère"
        d["reflect.emotion.scared"] = "Effrayé"
        d["reflect.emotion.worried"] = "Inquiet"
        d["reflect.emotion.calm"] = "Calme"
        d["reflect.emotion.excited"] = "Excité"
        d["reflect.emotion.confused"] = "Confus"
        d["reflect.emotion.tired"] = "Fatigué"
        d["reflect.emotion.lonely"] = "Seul"
        d["reflect.emotion.grateful"] = "Reconnaissant"
        d["reflect.emotion.frustrated"] = "Frustré"
        d["reflect.emotion.okay"] = "Ça va"

        // Reflection exercises
        d["reflect.exercise.gratitude"] = "Nomme 3 choses pour lesquelles tu es reconnaissant aujourd'hui"
        d["reflect.exercise.breathing"] = "Respiration profonde"
        d["reflect.exercise.body_scan"] = "Scan corporel"
        d["reflect.exercise.journaling"] = "Écris sur tes sentiments"

        // Coping strategies
        d["reflect.coping.deep_breath"] = "Prends 5 grandes respirations"
        d["reflect.coping.talk"] = "Parle à quelqu'un en qui tu as confiance"
        d["reflect.coping.move"] = "Fais une promenade ou étire-toi"
        d["reflect.coping.create"] = "Dessine ou écris sur ce que tu ressens"
        d["reflect.coping.music"] = "Écoute ta musique préférée"
        d["reflect.coping.count"] = "Compte à rebours depuis 10"

        // MARK: - Digital Journey
        d["journey.title"] = "Parcours numérique"
        d["journey.tab.insights"] = "Analyses IA"
        d["journey.tab.history"] = "Historique"
        d["journey.analyzing"] = "Analyse de l'activité de navigation..."
        d["journey.no_history"] = "Aucun historique de navigation"
        d["journey.history_will_appear"] = "L'historique apparaîtra ici au fur et à mesure que votre enfant navigue"
        d["journey.needs_attention"] = "Nécessite une attention"
        d["journey.allowed_links"] = "Liens autorisés"
        d["journey.loading_history"] = "Chargement de l'historique de navigation..."
        d["journey.time_range"] = "Période"
        d["journey.links"] = "liens"
        d["journey.filter.all"] = "Tout"
        d["journey.filter.blocked"] = "Bloqué"
        d["journey.filter.gated"] = "Restreint"
        d["journey.filter.allowed"] = "Autorisé"
        d["journey.range.1h"] = "1 heure"
        d["journey.range.3h"] = "3 heures"
        d["journey.range.6h"] = "6 heures"
        d["journey.range.12h"] = "12 heures"
        d["journey.range.24h"] = "24 heures"
        d["journey.range.all"] = "Tout"
        // Legacy journey keys
        d["journey.ai_insights"] = "Analyses IA"
        d["journey.history"] = "Historique"
        d["journey.no_activity"] = "Aucune activité enregistrée"
        d["journey.time_spent"] = "Temps passé"
        d["journey.sites_visited"] = "Sites visités"
        d["journey.blocked_attempts"] = "Tentatives bloquées"

        // MARK: - Browser
        d["browser.address_placeholder"] = "Rechercher ou entrer une URL"
        d["browser.loading"] = "Chargement..."
        d["browser.new_tab"] = "Nouvel onglet"
        d["browser.tabs"] = "Onglets"
        d["browser.no_open_tabs"] = "Aucun onglet ouvert"
        d["browser.close_tab"] = "Fermer l'onglet"
        d["browser.menu"] = "Menu"
        d["browser.share"] = "Partager"
        d["browser.reload"] = "Recharger"
        d["browser.forward"] = "Suivant"
        d["browser.history"] = "Historique"
        d["browser.homepage"] = "Accueil"
        d["browser.quick_checkin"] = "Comment tu te sens ?"
        d["browser.search_or_url"] = "Rechercher ou saisir une URL"
        d["browser.past_tabs"] = "Onglets précédents"
        d["browser.no_past_tabs"] = "Aucun onglet précédent"
        d["browser.tabs_appear_here"] = "Les sites que tu visites apparaîtront ici"

        // MARK: - Blocked Content
        d["blocked.title"] = "Contenu bloqué"
        d["blocked.not_available"] = "Ce contenu n'est pas disponible"
        d["blocked.keeping_safe"] = "Komal veille sur ta sécurité !"
        d["blocked.message"] = "Cette page a été bloquée pour ta sécurité."
        d["blocked.reason"] = "Raison : %@"
        d["blocked.ask_parent"] = "Demande à un parent si tu as besoin d'y accéder."
        d["blocked.go_back"] = "Retour"
        d["blocked.countdown"] = "Retour dans %d..."
        d["blocked.emoji_prompt"] = "Comment tu te sens ?"
        d["blocked.tap_talk"] = "Appuie pour parler à Komal"
        d["blocked.fallback_response"] = "Je suis là pour toi. Allons explorer quelque chose de chouette ensemble !"

        // MARK: - Chat Content Filtering
        d["chat.content_redirect"] = "Hé, je ne peux pas parler de ça ! Et si on parlait de quelque chose de chouette ? Qu'est-ce que tu aimes faire après l'école ?"
        d["browser.checking_page"] = "Vérification de cette page pour toi..."
        d["blocked.hi_there"] = "Salut !"
        d["blocked.find_something_else"] = "Trouvons autre chose !"
        d["blocked.educational.1"] = "Cette page n'est pas tout à fait adaptée pour le moment. Et si on trouvait quelque chose de super ensemble ?"
        d["blocked.educational.2"] = "Certains coins d'internet ont besoin d'un guide adulte. Découvrons quelque chose de chouette à la place !"
        d["blocked.educational.3"] = "Il y a tellement de choses à explorer ! Trouvons un chemin qui mène à quelque chose de génial."
        d["blocked.educational.4"] = "Pas besoin d'ouvrir toutes les portes aujourd'hui. Trouvons-en une qui mène à quelque chose de super !"
        d["blocked.friendly_1"] = "Désolé, ce contenu n'est pas disponible pour le moment. Allons trouver quelque chose d'autre de chouette à explorer ensemble !"
        d["blocked.friendly_2"] = "Ce n'est pas tout à fait adapté pour nous en ce moment. Et si on cherchait quelque chose d'autre de génial ?"
        d["blocked.friendly_3"] = "Passons celui-ci et trouvons quelque chose d'encore mieux ! Je suis là pour t'aider à découvrir des choses super !"
        d["blocked.friendly_4"] = "Ce contenu n'est pas disponible pour le moment. Tu veux explorer autre chose ensemble ?"

        // MARK: - Gate (parent approval)
        d["gate.title"] = "Contenu restreint"
        d["gate.riki_pause"] = "Riki suggère une pause"
        d["gate.touches_on"] = "Cette page aborde %@. Faisons le point avant de continuer."
        d["gate.start_break"] = "Commencer une pause pleine conscience"
        d["gate.parent_approval"] = "Approbation parentale"
        d["gate.enter_pin"] = "Entrez le PIN parental"
        d["gate.approve_continue"] = "Approuver et continuer"
        d["gate.access_gated"] = "L'accès est restreint pour %@ (%@)."
        d["gate.message"] = "Ce contenu nécessite l'approbation d'un parent."

        // MARK: - Emoji Check-in
        d["checkin.how_feeling"] = "Comment te sens-tu en explorant ça ?"
        d["checkin.how_are_you"] = "Comment te sens-tu ?"
        d["checkin.whats_on_your_mind"] = "Qu'est-ce qui te passe par la tête ?"
        d["checkin.hi_there"] = "Salut !"
        d["checkin.intro_message"] = "Je suis Komal, et je surfe sur Internet avec toi ! Comment te sens-tu en ce moment ?"
        d["checkin.thanks_komal"] = "Merci, Komal !"
        d["checkin.emotion.happy"] = "Content"
        d["checkin.emotion.okay"] = "Ça va"
        d["checkin.emotion.sad"] = "Triste"
        d["checkin.emotion.tired"] = "Fatigué"
        d["checkin.emotion.curious"] = "Curieux"
        d["checkin.emotion.excited"] = "Excité"
        d["checkin.response.happy"] = "C'est merveilleux ! Je suis tellement content que tu passes un bon moment à explorer !"
        d["checkin.response.okay"] = "C'est très bien ! Si tu as besoin de quoi que ce soit, je suis là !"
        d["checkin.response.sad"] = "Je suis désolé que tu te sentes comme ça. Tu veux faire une pause ?"
        d["checkin.response.tired"] = "C'est normal de se reposer ! On pourra explorer davantage plus tard."
        d["checkin.response.curious"] = "J'adore ta curiosité ! Qu'est-ce qui t'intrigue ?"
        d["checkin.response.excited"] = "C'est génial ! Je suis excité d'explorer avec toi aussi !"

        // MARK: - Mindful Break
        d["mindful.title"] = "Pause pleine conscience"
        d["mindful.pause_message"] = "Fais une douce pause. Observe ta respiration et la pièce autour de toi."
        d["mindful.im_ready"] = "Je suis prêt"

        // MARK: - Filter Preferences
        d["filter.content_settings"] = "Paramètres de contenu"
        d["filter.customize"] = "Personnaliser le contenu autorisé"
        d["filter.block"] = "Bloquer"
        d["filter.gate"] = "Restreindre"
        d["filter.allow"] = "Autoriser"

        // MARK: - Intervention
        d["intervention.tip"] = "C'est normal d'être curieux — c'est comme ça qu'on apprend !"
        d["intervention.lets_think"] = "Réfléchissons-y..."
        d["intervention.share_thoughts"] = "Partage tes pensées..."
        d["intervention.done_reflecting"] = "Réflexion terminée"
        d["intervention.lets_talk"] = "Parlons-en"
        d["intervention.go_back"] = "Retourner en sécurité"
        d["intervention.main.search"] = "Hé, j'ai remarqué que tu as cherché quelque chose..."
        d["intervention.main.url"] = "Attends un instant !"
        d["intervention.main.image"] = "J'ai trouvé quelque chose dont on devrait parler"
        d["intervention.main.page"] = "Cette page contient du contenu pour adultes"
        d["intervention.sub.search"] = "La curiosité est tout à fait normale ! Mais certains sujets sont mieux à explorer avec un adulte de confiance."
        d["intervention.sub.url"] = "Ce site pourrait contenir du contenu destiné aux adultes. Tu veux qu'on parle de ce que tu cherches ?"
        d["intervention.sub.image"] = "J'ai repéré quelque chose qui pourrait ne pas être approprié. Discutons-en."
        d["intervention.sub.page"] = "Une partie de ce contenu est pour les plus grands. Tu veux en parler, ou chercher autre chose ?"
        d["intervention.reflect.search"] = "Qu'est-ce qui t'a rendu curieux à ce sujet ?"
        d["intervention.reflect.url"] = "Qu'est-ce que tu espérais trouver ?"
        d["intervention.reflect.image"] = "Qu'est-ce que tu as ressenti en voyant ça ?"
        d["intervention.reflect.page"] = "Tu avais des questions sur quelque chose ?"

        // MARK: - Reflection Time
        d["reflect.title"] = "Temps de réflexion"
        d["reflect.welcome.title"] = "Bienvenue au temps de réflexion"
        d["reflect.welcome.subtitle"] = "15 minutes de bien-être numérique en pleine conscience"
        d["reflect.remaining"] = "restant"
        d["reflect.feelings.title"] = "Bilan des émotions"
        d["reflect.feelings.desc"] = "Explore et comprends tes émotions"
        d["reflect.mindfulness.title"] = "Exercice de pleine conscience"
        d["reflect.mindfulness.desc"] = "Respiration calme et relaxation"
        d["reflect.guided.title"] = "Réflexion guidée"
        d["reflect.guided.desc"] = "Réfléchis à tes expériences numériques"
        d["reflect.free_chat.title"] = "Discussion libre"
        d["reflect.free_chat.desc"] = "Parle de ce qui te préoccupe"
        d["reflect.sel.title"] = "Comment te sens-tu ?"
        d["reflect.sel.subtitle"] = "C'est normal de ressentir n'importe quelle émotion. Explorons ensemble."
        d["reflect.sel.things_help"] = "Choses qui pourraient t'aider :"
        d["reflect.mindfulness.header"] = "Pleine conscience"
        d["reflect.mindfulness.calm_mind"] = "Prends un moment pour calmer ton esprit"
        d["reflect.going_deeper"] = "Approfondissons..."
        d["reflect.thinking_followup"] = "Je réfléchis à une question de suivi..."
        d["reflect.previous"] = "Précédent"
        d["reflect.next"] = "Suivant"
        d["reflect.free_chat.placeholder"] = "Écris tes pensées..."
        d["reflect.free_chat.thinking"] = "Réflexion..."
        d["reflect.completion.title"] = "Bravo !"
        d["reflect.completion.subtitle"] = "Tu as terminé ton temps de réflexion"
        d["reflect.completion.message"] = "Prendre le temps de réfléchir t'aide à mieux te connaître et à rester en bonne santé en ligne."

        // MARK: - Coping Strategies
        d["reflect.coping.sad.1"] = "Parle à quelqu'un en qui tu as confiance"
        d["reflect.coping.sad.2"] = "Dessine ou écris sur tes sentiments"
        d["reflect.coping.sad.3"] = "Écoute ta musique préférée"
        d["reflect.coping.sad.4"] = "Fais-toi un câlin"
        d["reflect.coping.angry.1"] = "Prends 5 grandes respirations"
        d["reflect.coping.angry.2"] = "Compte à rebours depuis 10"
        d["reflect.coping.angry.3"] = "Serre une balle anti-stress"
        d["reflect.coping.angry.4"] = "Fais une courte promenade"
        d["reflect.coping.worried.1"] = "Dis à un adulte ce que tu ressens"
        d["reflect.coping.worried.2"] = "Pense à 3 choses pour lesquelles tu es reconnaissant"
        d["reflect.coping.worried.3"] = "Imagine ton endroit heureux"
        d["reflect.coping.worried.4"] = "Respire lentement et profondément"
        d["reflect.coping.tired.1"] = "Repose tes yeux une minute"
        d["reflect.coping.tired.2"] = "Bois un peu d'eau"
        d["reflect.coping.tired.3"] = "Étire ton corps"
        d["reflect.coping.tired.4"] = "Fais une pause loin des écrans"
        d["reflect.coping.default.1"] = "Partage tes sentiments avec quelqu'un"
        d["reflect.coping.default.2"] = "Fais quelque chose que tu aimes"
        d["reflect.coping.default.3"] = "Prends un moment de pleine conscience"
        d["reflect.coping.default.4"] = "Sois gentil avec toi-même"

        // MARK: - Mindfulness Exercises
        d["reflect.exercise.box.title"] = "Respiration carrée"
        d["reflect.exercise.box.desc"] = "Une technique apaisante utilisée par les athlètes et les astronautes"
        d["reflect.exercise.box.step1"] = "Inspire pendant 4 secondes"
        d["reflect.exercise.box.step2"] = "Retiens pendant 4 secondes"
        d["reflect.exercise.box.step3"] = "Expire pendant 4 secondes"
        d["reflect.exercise.box.step4"] = "Retiens pendant 4 secondes"
        d["reflect.exercise.box.step5"] = "Répète 4 fois"
        d["reflect.exercise.grounding.title"] = "Ancrage 5-4-3-2-1"
        d["reflect.exercise.grounding.desc"] = "Reconnecte-toi au moment présent"
        d["reflect.exercise.grounding.step1"] = "Remarque 5 choses que tu peux VOIR"
        d["reflect.exercise.grounding.step2"] = "Remarque 4 choses que tu peux TOUCHER"
        d["reflect.exercise.grounding.step3"] = "Remarque 3 choses que tu peux ENTENDRE"
        d["reflect.exercise.grounding.step4"] = "Remarque 2 choses que tu peux SENTIR"
        d["reflect.exercise.grounding.step5"] = "Remarque 1 chose que tu peux GOÛTER"
        d["reflect.exercise.bodyscan.title"] = "Scan corporel"
        d["reflect.exercise.bodyscan.desc"] = "Détends ton corps de la tête aux pieds"
        d["reflect.exercise.bodyscan.step1"] = "Détends ton front et tes yeux"
        d["reflect.exercise.bodyscan.step2"] = "Détends ta mâchoire et tes épaules"
        d["reflect.exercise.bodyscan.step3"] = "Détends tes bras et tes mains"
        d["reflect.exercise.bodyscan.step4"] = "Détends ton ventre"
        d["reflect.exercise.bodyscan.step5"] = "Détends tes jambes et tes pieds"
        d["reflect.exercise.gratitude.title"] = "Moment de gratitude"
        d["reflect.exercise.gratitude.desc"] = "Concentre-toi sur les bonnes choses de la vie"
        d["reflect.exercise.gratitude.step1"] = "Pense à quelqu'un qui te rend heureux"
        d["reflect.exercise.gratitude.step2"] = "Pense à quelque chose dans lequel tu es doué"
        d["reflect.exercise.gratitude.step3"] = "Pense à un endroit où tu te sens en sécurité"
        d["reflect.exercise.gratitude.step4"] = "Pense à un souvenir heureux"
        d["reflect.exercise.gratitude.step5"] = "Souris et ressens la gratitude"
        d["reflect.breathe.inhale"] = "Inspire"
        d["reflect.breathe.hold"] = "Retiens"
        d["reflect.breathe.exhale"] = "Expire"

        // MARK: - Reflection Questions
        d["reflect.q1.question"] = "Quelle a été la meilleure chose que tu as vue en ligne aujourd'hui ?"
        d["reflect.q1.prompt"] = "Partage quelque chose qui t'a fait sourire ou te sentir bien..."
        d["reflect.q2.question"] = "Est-ce que quelque chose en ligne t'a mis mal à l'aise ?"
        d["reflect.q2.prompt"] = "C'est normal de parler des choses qui t'ont dérangé..."
        d["reflect.q3.question"] = "Qu'as-tu appris aujourd'hui sur Internet ?"
        d["reflect.q3.prompt"] = "Partage quelque chose d'intéressant que tu as découvert..."
        d["reflect.q4.question"] = "Combien de temps as-tu passé devant les écrans aujourd'hui ?"
        d["reflect.q4.prompt"] = "C'était trop, juste bien, ou pas assez ?"
        d["reflect.q5.question"] = "Qu'aimerais-tu faire hors écran demain ?"
        d["reflect.q5.prompt"] = "Pense à des activités amusantes loin des écrans..."

        // MARK: - Free Chat Greetings
        d["reflect.chat.greeting.1"] = "Salut ! C'est un espace sûr pour partager tes pensées. Qu'est-ce qui te préoccupe aujourd'hui ?"
        d["reflect.chat.greeting.2"] = "Coucou ! Je suis là pour t'écouter. Raconte-moi quelque chose d'intéressant qui s'est passé."
        d["reflect.chat.greeting.3"] = "Bienvenue ! Tu peux parler de tout ici. De quoi aimerais-tu discuter ?"
        d["reflect.chat.fallback.1"] = "Merci d'avoir partagé ça avec moi. Comment ça te fait sentir ?"
        d["reflect.chat.fallback.2"] = "Je t'écoute. Ça a l'air vraiment important pour toi."
        d["reflect.chat.fallback.3"] = "C'est bien que tu en parles. Tu veux m'en dire plus ?"
        d["reflect.chat.fallback.4"] = "Je comprends. C'est normal de ressentir ça."
        d["reflect.chat.fallback.5"] = "Merci de me faire confiance. Qu'est-ce qu'il y a d'autre dans ta tête ?"

        // MARK: - Insights View
        d["insights.view.title"] = "Analyses"
        d["insights.overview"] = "Vue d'ensemble"
        d["insights.sites_visited"] = "Sites visités"
        d["insights.blocked"] = "Bloqués"
        d["insights.gated"] = "Restreints"
        d["insights.sessions"] = "Sessions"
        d["insights.content_categories"] = "Catégories de contenu"
        d["insights.activity_timeline"] = "Chronologie d'activité"
        d["insights.recent_sessions"] = "Sessions récentes"
        d["insights.no_sessions"] = "Aucune session de navigation"
        d["insights.protection_summary"] = "Résumé de protection"
        d["insights.images_protected"] = "Images protégées"
        d["insights.of_scanned"] = "sur %d analysées"
        d["insights.sites_blocked"] = "Sites bloqués"
        d["insights.harmful_content"] = "contenu nuisible"
        d["insights.engagement"] = "Engagement"
        d["insights.avg_time_page"] = "Temps moyen par page"
        d["insights.avg_scroll_depth"] = "Profondeur de défilement moyenne"
        d["insights.meaningful_engagement"] = "Engagement significatif"
        d["insights.most_engaged"] = "Sites les plus consultés"
        d["insights.visits"] = "%d visites"
        d["insights.avg_time"] = "temps moyen"
        d["insights.browsing_patterns"] = "Habitudes de navigation"
        d["insights.session_depth"] = "Profondeur de session"
        d["insights.pages"] = "%d pages"
        d["insights.how_deep"] = "Jusqu'où dans les sites"
        d["insights.back_navigation"] = "Navigation arrière"
        d["insights.returning_pages"] = "Retour aux pages précédentes"
        d["insights.quick_visits"] = "Visites rapides"
        d["insights.pages_under_10s"] = "Pages vues < 10 secondes"
        d["insights.content_viewed"] = "Contenu consulté"
        d["insights.words_read"] = "Mots lus"
        d["insights.images"] = "Images"
        d["insights.videos"] = "Vidéos"
        d["insights.topics"] = "Sujets"
        d["insights.avg_time_short"] = "Temps moyen"
        d["insights.reading"] = "Lecture"
        d["insights.concerning_content"] = "Contenu préoccupant détecté"
        d["insights.keywords"] = "Mots-clés : %@"
        d["insights.found_on_pages"] = "Trouvé sur %d page(s)"
        d["insights.recent_pages"] = "Pages récemment consultées"
        d["insights.topics_viewed"] = "Sujets consultés :"
        d["insights.flagged"] = "Signalé : %@"
        d["insights.avg_time_per_page"] = "Temps moyen par page"

        // MARK: - Anchor - Morning
        d["anchor.morning.title"] = "Bonjour !"
        d["anchor.morning.greeting"] = "Bonjour !"
        d["anchor.morning.subtitle"] = "Comment te sens-tu ce matin ?"
        d["anchor.morning.how_feeling"] = "Comment te sens-tu aujourd'hui ?"
        d["anchor.morning.how_strong"] = "À quel point ce sentiment est-il fort ?"
        d["anchor.morning.set_intention"] = "Définis ton intention pour aujourd'hui"
        d["anchor.morning.looking_forward"] = "Qu'est-ce qui te réjouit aujourd'hui ?"
        d["anchor.morning.intention_placeholder"] = "Aujourd'hui je veux..."
        d["anchor.morning.looking_forward_placeholder"] = "Quelque chose de fun, un cours, voir un ami..."
        d["anchor.morning.ready"] = "Je suis prêt pour aujourd'hui !"
        d["anchor.morning.start_my_day"] = "Commencer ma journée !"

        // MARK: - Anchor - Evening
        d["anchor.evening.title"] = "Réflexion du soir"
        d["anchor.evening.greeting"] = "Bonsoir !"
        d["anchor.evening.subtitle"] = "Comment s'est passée ta journée ?"
        d["anchor.evening.wind_down"] = "Détendons-nous ensemble"
        d["anchor.evening.how_feeling"] = "Comment te sens-tu ce soir ?"
        d["anchor.evening.deep_breaths"] = "Prends 3 grandes respirations"
        d["anchor.evening.breathe_in_out"] = "Inspire... et expire..."
        d["anchor.evening.goodnight"] = "Bonne nuit !"
        d["anchor.evening.good_night"] = "Bonne nuit !"

        // MARK: - Reconnection
        d["reconnection.title"] = "Bon retour !"
        d["reconnection.welcome_back"] = "Bon retour !"
        d["reconnection.subtitle"] = "Tu nous as manqué ! Ça fait un moment."
        d["reconnection.ellie_greeting"] = "C'est Ellie ! Je n'oublie jamais mes amis, et je suis tellement contente de te revoir !"
        d["reconnection.days_since"] = "Ça fait %d jours qu'on ne s'est pas vus."
        d["reconnection.hi_ellie"] = "Salut Ellie !"
        d["reconnection.how_have_you_been"] = "Comment tu vas ?"
        d["reconnection.mood_great"] = "Super !"
        d["reconnection.mood_okay"] = "Ça va"
        d["reconnection.mood_not_great"] = "Pas top"
        d["reconnection.response_great"] = "C'est merveilleux ! Continuons sur cette lancée."
        d["reconnection.response_not_great"] = "Je suis désolé d'entendre ça. N'oublie pas, je suis toujours là pour toi."
        d["reconnection.response_okay"] = "Bon à savoir ! Amusons-nous ensemble."
        d["reconnection.what_to_do"] = "Que voudrais-tu faire ?"
        d["reconnection.browse_web"] = "Naviguer sur le Web"
        d["reconnection.chat_friend"] = "Discuter avec un ami"
        d["reconnection.reflection_time"] = "Temps de réflexion"
        d["reconnection.whats_new"] = "Voici les nouveautés depuis ta dernière visite"
        d["reconnection.lets_go"] = "C'est parti !"
        d["reconnection.missed_days"] = "Tu as été absent pendant %d jours"

        // MARK: - Growth / Journey
        d["growth.title"] = "Mon parcours"
        d["growth.milestones"] = "Jalons"
        d["growth.weekly_snapshot"] = "Bilan hebdomadaire"
        d["growth.noticed_about_you"] = "Ce qu'on a remarqué chez toi :"
        d["growth.day_streak"] = "Jours consécutifs"
        d["growth.this_week"] = "Cette semaine"
        d["growth.active_days"] = "Jours actifs"
        d["growth.chats"] = "Discussions"
        d["growth.reflections"] = "Réflexions"
        d["growth.moods"] = "Humeurs"
        d["growth.streak"] = "Série"
        d["growth.days"] = "jours"
        d["growth.level"] = "Niveau"
        d["growth.explorer"] = "Explorateur"
        d["growth.adventurer"] = "Aventurier"
        d["growth.champion"] = "Champion"
        d["growth.legend"] = "Légende"
        d["growth.earned"] = "Obtenu !"
        d["growth.locked"] = "Continue comme ça !"
        d["growth.snapshot.title"] = "Ta semaine en revue"
        d["growth.snapshot.conversations"] = "Conversations"
        d["growth.snapshot.reflections"] = "Réflexions"
        d["growth.snapshot.browsing_time"] = "Temps de navigation"
        d["growth.snapshot.mood_checks"] = "Bilans d'humeur"
        d["growth.snapshot.mood_checkins"] = "Bilans d'humeur"
        d["growth.snapshot.most_common_mood"] = "Humeur la plus fréquente"
        d["growth.snapshot.favorite_friend"] = "Ami préféré"
        d["growth.snapshot.growth_insight"] = "Aperçu de croissance"
        d["growth.snapshot.keep_going"] = "Continue comme ça !"

        // MARK: - Parent Insights
        d["insights.title"] = "Analyses parentales"
        d["insights.wellness"] = "Aperçu du bien-être"
        d["insights.mood_trends"] = "Tendances d'humeur"
        d["insights.chat_activity"] = "Activité de discussion"
        d["insights.browsing_summary"] = "Résumé de navigation"
        d["insights.alerts"] = "Alertes"
        d["insights.no_alerts"] = "Aucune alerte à afficher"
        d["insights.this_week"] = "Cette semaine"
        d["insights.this_month"] = "Ce mois"

        // MARK: - Parent Insights Dashboard
        d["insights.dashboard.title"] = "Bien-être de l'enfant"
        d["insights.dashboard.this_week_vs_last"] = "Cette semaine vs la précédente"
        d["insights.dashboard.chats"] = "Discussions"
        d["insights.dashboard.reflections"] = "Réflexions"
        d["insights.dashboard.moods"] = "Humeurs"
        d["insights.dashboard.active_days"] = "Jours actifs"
        d["insights.dashboard.conversation_starter"] = "Sujet de conversation du soir"
        d["insights.dashboard.generating_starter"] = "Génération d'un sujet de conversation..."
        d["insights.dashboard.starter_placeholder"] = "Utilisez l'application quelques jours pour obtenir des sujets de conversation personnalisés."
        d["insights.dashboard.daily_insight"] = "Aperçu quotidien"
        d["insights.dashboard.generating_insight"] = "Génération de l'aperçu..."
        d["insights.dashboard.insight_placeholder"] = "Les aperçus apparaîtront à mesure que votre enfant utilise l'application."
        d["insights.dashboard.emotional_wellness"] = "Bien-être émotionnel"
        d["insights.dashboard.last_7_days"] = "7 derniers jours"
        d["insights.dashboard.emotion_distribution"] = "Répartition des émotions sur 30 jours"
        d["insights.dashboard.no_mood_data"] = "Aucune donnée d'humeur. Les entrées d'humeur apparaîtront ici à mesure que votre enfant utilise l'application."
        d["insights.dashboard.conversation_insights"] = "Aperçu des conversations"
        d["insights.dashboard.messages"] = "Messages"
        d["insights.dashboard.characters_used"] = "Personnages utilisés"
        d["insights.dashboard.popular_topics"] = "Sujets populaires"
        d["insights.dashboard.growth_metrics"] = "Indicateurs de croissance"
        d["insights.dashboard.current_streak"] = "Série en cours"
        d["insights.dashboard.milestones"] = "Jalons"
        d["insights.dashboard.active_days_30d"] = "Jours actifs (30j)"
        d["insights.dashboard.activity_30d"] = "Activité sur 30 jours"
        d["insights.dashboard.engagement_quality"] = "Qualité de l'engagement"
        d["insights.dashboard.voluntary_returns"] = "Retours volontaires"
        d["insights.dashboard.avg_reflection_depth"] = "Profondeur moyenne de réflexion"
        d["insights.dashboard.total_sessions"] = "Sessions totales"
        d["insights.dashboard.voluntary_returns_explanation"] = "Un taux élevé de retours volontaires indique un engagement authentique plutôt qu'une utilisation poussée par les notifications."
        d["insights.dashboard.daily_checkins"] = "Bilans quotidiens"
        d["insights.dashboard.morning"] = "Matin"
        d["insights.dashboard.evening"] = "Soir"
        d["insights.dashboard.wellness_alert"] = "Alerte bien-être"
        d["insights.dashboard.wellness_alert_message"] = "Votre enfant a signalé se sentir triste lors de 3 bilans consécutifs ou plus. Envisagez d'avoir une conversation bienveillante sur ses sentiments."
        d["insights.dashboard.value_alignment"] = "Alignement des valeurs"
        d["insights.dashboard.value_alignment_desc"] = "Discutez des valeurs que votre enfant a explorées en ligne cette semaine :"
        d["insights.dashboard.generating_prompt"] = "Génération en cours..."
        d["insights.dashboard.value_kindness"] = "Qu'as-tu appris sur la gentillesse aujourd'hui ?"
        d["insights.dashboard.value_fairness"] = "Raconte-moi un moment où quelqu'un a été juste avec toi cette semaine."
        d["insights.dashboard.value_helping"] = "Comment as-tu aidé quelqu'un aujourd'hui ?"

        // MARK: - Browsing History
        d["history.title"] = "Historique de navigation"
        d["history.loading"] = "Chargement de l'historique de navigation..."
        d["history.today"] = "Aujourd'hui"
        d["history.yesterday"] = "Hier"
        d["history.earlier"] = "Plus tôt"
        d["history.no_history"] = "Aucun historique de navigation"
        d["history.empty_message"] = "L'historique apparaîtra ici au fur et à mesure que votre enfant navigue."
        d["history.time_range"] = "Période"
        d["history.pages"] = "pages"
        d["history.emoji_journey"] = "Parcours emoji"
        d["history.summary"] = "Résumé"
        d["history.pages_visited"] = "Pages visitées"
        d["history.session_detail"] = "Détail de la session"
        d["history.back_label"] = "Historique"
        d["history.clear"] = "Effacer l'historique"
        d["history.clear_confirm"] = "Êtes-vous sûr de vouloir effacer tout l'historique de navigation ?"

        // MARK: - Contextual Prompts
        d["prompt.welcome_back"] = "Bon retour ! Prêt à explorer ?"
        d["prompt.take_break"] = "Tu navigues depuis un moment. Une pause ?"
        d["prompt.try_reflect"] = "Et si tu faisais un bilan de tes émotions ?"
        d["prompt.chat_riki"] = "Tu veux discuter avec un ami ?"
        d["prompt.new_milestone"] = "Tu as gagné un nouveau jalon !"
        d["prompt.dismiss"] = "Peut-être plus tard"
        d["prompt.lets_go"] = "C'est parti !"
        d["prompt.curiosity_noticed"] = "J'ai remarqué quelque chose d'intéressant aujourd'hui... Tu veux savoir ?"
        d["prompt.curiosity_learned"] = "Curieux de savoir ce que j'ai appris de toi ? Ça pourrait te surprendre !"
        d["prompt.curiosity_question_young"] = "J'ai une question super amusante pour toi ! Tu veux jouer ?"
        d["prompt.growth_calm"] = "Tu as géré ça calmement. Comment tu as fait ?"
        d["prompt.growth_evolved"] = "Ta façon de penser a vraiment évolué. Tu veux voir le chemin parcouru ?"
        d["prompt.growth_proud_young"] = "Waouh, tu deviens tellement doué ! Je suis vraiment fier de toi !"
        d["prompt.growth_streak_celebrate"] = "Regarde cette série ! Tu construis quelque chose d'incroyable, un jour à la fois."
        d["prompt.brave_question"] = "Je peux te poser une question courageuse ? Ça pourrait te surprendre."
        d["prompt.brave_future"] = "Qu'est-ce que le toi du futur dirait d'aujourd'hui ? Découvrons-le."
        d["prompt.brave_try_young"] = "Tu veux essayer quelque chose de nouveau ensemble ? Je crois en toi !"
        d["prompt.transition_reflect"] = "Une petite réflexion avant de partir ? Juste 2 minutes."
        d["prompt.transition_progress"] = "Tu veux voir ta carte de progression ? Tu as été bien occupé !"
        d["prompt.return_changed"] = "Quelque chose a un peu changé pendant ton absence. Tu veux voir ?"
        d["prompt.return_secret"] = "Tu veux voir un aperçu secret sur toi-même ? Je l'ai gardé pour toi."
        d["prompt.return_missed_young"] = "Youpi, tu es de retour ! Tu m'as manqué ! On joue ensemble ?"
        d["prompt.emotional_check_negative"] = "Hé, j'ai remarqué que tu traverses peut-être un moment difficile. Je suis là pour toi."
        d["prompt.emotional_celebrate_positive"] = "Tu as l'air de bonne humeur ! C'est super à voir."
        d["prompt.browsing_learned"] = "Tu as appris quelque chose de chouette en naviguant ? J'adorerais en entendre parler !"
        d["prompt.browsing_break"] = "Comment te sens-tu en ce moment ? Tu veux faire un petit bilan ?"
        d["prompt.browsing_riddle_young"] = "Tu veux faire une pause amusante ? J'ai une devinette pour toi !"
        d["prompt.reflect_done_great"] = "C'était une réflexion vraiment réfléchie. Tu peux être fier de toi."
        d["prompt.reflect_deeper_teen"] = "Belle réflexion. Tu veux aller un peu plus loin ? Parfois les meilleurs aperçus arrivent après."
        d["prompt.action.tell_me"] = "Dis-moi !"
        d["prompt.action.show_me"] = "Montre-moi"
        d["prompt.action.lets_play"] = "Jouons !"
        d["prompt.action.let_me_think"] = "Laisse-moi réfléchir..."
        d["prompt.action.show_my_growth"] = "Voir ma progression"
        d["prompt.action.see_my_journey"] = "Voir mon parcours"
        d["prompt.action.go_ahead"] = "Vas-y"
        d["prompt.action.lets_explore"] = "Explorons"
        d["prompt.action.lets_try"] = "Essayons !"
        d["prompt.action.sure"] = "Bien sûr !"
        d["prompt.action.show_me_excited"] = "Montre-moi !"
        d["prompt.action.what_changed"] = "Qu'est-ce qui a changé ?"
        d["prompt.action.talk_about_it"] = "Parlons-en"
        d["prompt.action.lets_chat"] = "Discutons"
        d["prompt.action.check_in"] = "Faire le point"
        d["prompt.action.go_deeper"] = "Approfondir"

        // MARK: - Notifications
        d["notification.morning.title"] = "Bonjour !"
        d["notification.morning.body"] = "C'est Momo ! Commençons ta journée avec un petit bilan. Comment te sens-tu ?"
        d["notification.evening.title"] = "C'est l'heure de se détendre"
        d["notification.evening.body"] = "Coucou, c'est Bunny ! Prenons un moment pour réfléchir à ta journée ensemble."
        d["notification.reconnect.title"] = "Tu nous manques !"
        d["notification.reconnect.body"] = "C'est Ellie — je n'oublie jamais mes amis ! Reviens nous dire bonjour, j'ai quelque chose de chouette à partager."
        d["notification.milestone.title"] = "Nouveau jalon !"
        d["notification.milestone.body"] = "Tu as gagné une nouvelle réussite. Découvre-la !"

        // MARK: - Mood History
        d["mood.history.title"] = "Historique d'humeur"
        d["mood.history.recent"] = "Humeurs récentes"
        d["mood.history.no_entries"] = "Aucune entrée d'humeur"
        d["mood.history.trend"] = "Ta tendance d'humeur"

        // MARK: - Scan Results
        d["scan.overall_safety_score"] = "Score de sécurité global"
        d["scan.scanned"] = "Analysé"
        d["scan.live_analysis"] = "Analyse en direct"
        d["scan.demo_mode"] = "Mode démo"
        d["scan.blocked_under_16"] = "Bloqué pour les moins de 16 ans"
        d["scan.out_of_100"] = "/100"
        d["scan.age_appropriate_actions"] = "Actions adaptées à l'âge"
        d["scan.score"] = "Score"
        d["scan.safety_risks_detected"] = "Risques de sécurité détectés"
        d["scan.matches"] = "correspondances"
        d["scan.content_analysis"] = "Analyse du contenu"
        d["scan.nlp_text_analysis"] = "Analyse de texte NLP"
        d["scan.sentiment"] = "Sentiment :"
        d["scan.language_score"] = "Score linguistique :"
        d["scan.key_topics"] = "Sujets clés :"
        d["scan.vision_ai_analysis"] = "Analyse Vision IA"
        d["scan.visual_safety_score"] = "Score de sécurité visuelle :"
        d["scan.detected_objects"] = "Objets détectés :"

        // MARK: - Screen Time
        d["screentime.minimal"] = "30 min/jour"
        d["screentime.moderate"] = "1-2 heures/jour"
        d["screentime.flexible"] = "Flexible"

        // MARK: - SEL Insights
        d["sel.insight.no_data"] = "Complétez votre première session SEL pour commencer à suivre la croissance."
        d["sel.insight.improving"] = "Super progrès ! Continuez l'excellent travail."
        d["sel.insight.improving_with_strengths"] = "Super progrès ! Fort(e) en %@."
        d["sel.insight.growth_areas"] = "%@ pourrait bénéficier de plus de soutien. Pensez à plus de pratique dans ces domaines."
        d["sel.insight.balanced"] = "Développement bien équilibré dans tous les domaines. Continuez !"

        // MARK: - SEL Domain Labels
        d["sel.domain.social_communication"] = "Communication sociale"
        d["sel.domain.emotional_intelligence"] = "Intelligence émotionnelle"
        d["sel.domain.cognitive_development"] = "Développement cognitif"
        d["sel.domain.life_skills"] = "Compétences de vie"
        d["sel.domain.language_development"] = "Développement du langage"

        // MARK: - SEL Competency Labels (mock data)
        d["sel.mock.check_fallback"] = "Vérification"
        d["sel.competency.sc.1"] = "Initie les salutations"
        d["sel.competency.sc.2"] = "Démarre les conversations"
        d["sel.competency.sc.3"] = "Répond aux invitations"
        d["sel.competency.ei.1"] = "Identifie les émotions"
        d["sel.competency.ei.2"] = "Comprend les sentiments"
        d["sel.competency.ei.3"] = "Montre de l'empathie"
        d["sel.competency.cd.1"] = "Résolution de problèmes"
        d["sel.competency.cd.2"] = "Pensée séquentielle"
        d["sel.competency.cd.3"] = "Raisonnement logique"
        d["sel.competency.ls.1"] = "Conscience de la sécurité"
        d["sel.competency.ls.2"] = "Routines de soins personnels"
        d["sel.competency.ls.3"] = "Choix sains"
        d["sel.competency.ld.1"] = "Décrit les événements"
        d["sel.competency.ld.2"] = "Répond aux questions"
        d["sel.competency.ld.3"] = "Partage les expériences"

        // MARK: - SEL Scenarios: Social Communication
        d["sel.sc1.title"] = "Un nouvel ami à l'école"
        d["sel.sc1.narrative"] = "Un nouvel élève rejoint ta classe et s'assoit seul à la cantine. Personne ne lui a encore parlé."
        d["sel.sc1-1.q"] = "Que ferais-tu en le voyant assis seul ?"
        d["sel.sc1-1.o1"] = "M'approcher et dire bonjour, me présenter"
        d["sel.sc1-1.o2"] = "Lui sourire depuis ma table"
        d["sel.sc1-1.o3"] = "Continuer à manger avec mes amis"
        d["sel.sc1-2.q"] = "Il te dit qu'il aime dessiner. Que dirais-tu ?"
        d["sel.sc1-2.o1"] = "Cool ! Moi aussi j'aime dessiner ! Tu dessines quoi ?"
        d["sel.sc1-2.o2"] = "C'est bien"
        d["sel.sc1-2.o3"] = "Ah, d'accord"
        d["sel.sc1-3.q"] = "Il te demande si tu veux dessiner ensemble après l'école."
        d["sel.sc1-3.o1"] = "Oui ! Laisse-moi d'abord demander à mes parents"
        d["sel.sc1-3.o2"] = "Peut-être une autre fois"
        d["sel.sc1-3.o3"] = "Je ne sais pas..."

        d["sel.sc2.title"] = "Le projet de groupe"
        d["sel.sc2.narrative"] = "Ton professeur te met dans un groupe avec des élèves avec qui tu ne joues pas d'habitude pour un projet."
        d["sel.sc2-1.q"] = "Comment commencerais-tu à travailler avec le nouveau groupe ?"
        d["sel.sc2-1.o1"] = "Salut tout le monde ! Je suis content de travailler ensemble. On commence par quoi ?"
        d["sel.sc2-1.o2"] = "Attendre que quelqu'un d'autre commence à parler"
        d["sel.sc2-1.o3"] = "Rester silencieux et espérer qu'ils me disent quoi faire"
        d["sel.sc2-2.q"] = "Un des élèves partage une très bonne idée pour le projet."
        d["sel.sc2-2.o1"] = "C'est une super idée ! Je pense qu'on devrait l'utiliser"
        d["sel.sc2-2.o2"] = "Hocher la tête sans rien dire"
        d["sel.sc2-2.o3"] = "Je pense que mon idée est meilleure"
        d["sel.sc2-3.q"] = "Tu remarques que quelqu'un dans le groupe a du mal avec sa partie."
        d["sel.sc2-3.o1"] = "Tu veux que je t'aide avec ça ?"
        d["sel.sc2-3.o2"] = "Dire au professeur qu'il a besoin d'aide"
        d["sel.sc2-3.o3"] = "Me concentrer sur mon propre travail"

        d["sel.sc3.title"] = "Soirée jeux"
        d["sel.sc3.narrative"] = "Toi et tes amis jouez à un jeu de société. Un ami n'arrête pas de perdre et commence à s'énerver."
        d["sel.sc3-1.q"] = "Ton ami veut jouer à un autre jeu, mais tout le monde veut continuer celui-ci. Que fais-tu ?"
        d["sel.sc3-1.o1"] = "Proposer de finir ce jeu puis jouer à son choix ensuite"
        d["sel.sc3-1.o2"] = "Lui dire d'attendre"
        d["sel.sc3-1.o3"] = "L'ignorer et continuer à jouer"
        d["sel.sc3-2.q"] = "Deux amis ne sont pas d'accord sur les règles. Que ferais-tu ?"
        d["sel.sc3-2.o1"] = "Proposer de lire les règles ensemble et résoudre ça calmement"
        d["sel.sc3-2.o2"] = "M'énerver et dire que ça n'a pas d'importance"
        d["sel.sc3-2.o3"] = "Quitter le jeu"
        d["sel.sc3-3.q"] = "Un nouveau du quartier veut rejoindre le jeu. Que dis-tu ?"
        d["sel.sc3-3.o1"] = "Bien sûr ! On va t'expliquer les règles — viens t'asseoir avec nous !"
        d["sel.sc3-3.o2"] = "Tu peux regarder pour l'instant"
        d["sel.sc3-3.o3"] = "Désolé, on a déjà commencé"

        // MARK: - SEL Scenarios: Emotional Intelligence
        d["sel.ei1.title"] = "L'incident de la glace"
        d["sel.ei1.narrative"] = "Ton ami vient de faire tomber son cornet de glace par terre. C'était son parfum préféré et il l'attendait depuis toute la journée."
        d["sel.ei1-1.q"] = "Comment penses-tu que ton ami se sent en ce moment ?"
        d["sel.ei1-1.o1"] = "Triste et déçu"
        d["sel.ei1-1.o2"] = "En colère"
        d["sel.ei1-1.o3"] = "Je ne suis pas sûr"
        d["sel.ei1-2.q"] = "Pourquoi penses-tu qu'il se sent comme ça ?"
        d["sel.ei1-2.o1"] = "Il était impatient de la manger et maintenant c'est fini"
        d["sel.ei1-2.o2"] = "Parce que la glace c'est bon"
        d["sel.ei1-2.o3"] = "Je ne sais pas pourquoi"
        d["sel.ei1-3.q"] = "Que ferais-tu pour que ton ami se sente mieux ?"
        d["sel.ei1-3.o1"] = "Proposer de partager la mienne ou l'aider à en acheter une autre"
        d["sel.ei1-3.o2"] = "Lui dire que ce n'est pas grave, ne t'inquiète pas"
        d["sel.ei1-3.o3"] = "C'est juste une glace, c'est pas grave"

        d["sel.ei2.title"] = "Le spectacle de talents"
        d["sel.ei2.narrative"] = "Ton ami s'est beaucoup entraîné pour le spectacle de talents mais a oublié son texte sur scène et a dû s'arrêter. Il revient dans les coulisses l'air bouleversé."
        d["sel.ei2-1.q"] = "Ton ami regarde le sol avec les poings serrés. Que te dit son langage corporel ?"
        d["sel.ei2-1.o1"] = "Il se sent gêné et frustré"
        d["sel.ei2-1.o2"] = "Il est en colère contre le public"
        d["sel.ei2-1.o3"] = "Il est fatigué"
        d["sel.ei2-2.q"] = "Pourquoi pourrait-il ressentir plus que de la tristesse ?"
        d["sel.ei2-2.o1"] = "Il est gêné parce que tout le monde regardait, et déçu parce qu'il s'était tellement entraîné"
        d["sel.ei2-2.o2"] = "Parce qu'il n'a pas gagné"
        d["sel.ei2-2.o3"] = "Parce que le spectacle était ennuyeux"
        d["sel.ei2-3.q"] = "Que dirais-tu à ton ami ?"
        d["sel.ei2-3.o1"] = "Ça demandait beaucoup de courage. Je suis fier de toi d'avoir essayé !"
        d["sel.ei2-3.o2"] = "Ne t'inquiète pas, tout le monde oublie parfois"
        d["sel.ei2-3.o3"] = "Tu aurais dû t'entraîner davantage"

        d["sel.ei3.title"] = "Le jour du déménagement"
        d["sel.ei3.narrative"] = "Ton meilleur ami te dit que sa famille déménage dans une autre ville le mois prochain. Vous ne vous verrez plus à l'école."
        d["sel.ei3-1.q"] = "Comment te sens-tu en apprenant cette nouvelle ?"
        d["sel.ei3-1.o1"] = "Triste qu'on ne sera plus ensemble, mais content des souvenirs qu'on a"
        d["sel.ei3-1.o2"] = "Juste triste"
        d["sel.ei3-1.o3"] = "Je ne sais pas ce que je ressens"
        d["sel.ei3-2.q"] = "Ton ami semble silencieux et ne veut pas parler du déménagement. Que fais-tu ?"
        d["sel.ei3-2.o1"] = "Lui dire que c'est normal d'être triste, et que je suis là pour écouter quand il sera prêt"
        d["sel.ei3-2.o2"] = "M'énerver contre lui parce qu'il ne parle pas"
        d["sel.ei3-2.o3"] = "Le laisser tranquille"
        d["sel.ei3-3.q"] = "Tu es vraiment triste que ton ami parte. Qu'est-ce qui t'aide à gérer ces grandes émotions ?"
        d["sel.ei3-3.o1"] = "Respirer profondément, écrire dans mon journal et parler à quelqu'un de confiance de ce que je ressens"
        d["sel.ei3-3.o2"] = "Pleurer beaucoup et rester dans ma chambre"
        d["sel.ei3-3.o3"] = "Faire comme si ça n'allait pas et ignorer mes sentiments"

        // MARK: - SEL Scenarios: Cognitive Development
        d["sel.cd1.title"] = "L'animal perdu"
        d["sel.cd1.narrative"] = "Le chat de ton voisin a disparu. Ils cherchent partout mais ne le trouvent pas."
        d["sel.cd1-1.q"] = "Quelle est la première chose que tu devrais faire pour aider ?"
        d["sel.cd1-1.o1"] = "Demander au voisin où le chat a été vu pour la dernière fois et faire un plan"
        d["sel.cd1-1.o2"] = "Commencer à chercher au hasard"
        d["sel.cd1-1.o3"] = "Attendre et espérer que le chat rentre"
        d["sel.cd1-2.q"] = "Comment organiserais-tu un plan de recherche ?"
        d["sel.cd1-2.o1"] = "D'abord vérifier la maison, puis le jardin, puis demander aux voisins et mettre des affiches"
        d["sel.cd1-2.o2"] = "Chercher dans les endroits les plus proches"
        d["sel.cd1-2.o3"] = "Je ne saurais pas par où commencer"
        d["sel.cd1-3.q"] = "Il a plu hier soir. Où le chat aurait-il pu aller pour rester au sec ?"
        d["sel.cd1-3.o1"] = "Sous un porche, dans un garage ou un endroit abrité — les chats n'aiment pas être mouillés"
        d["sel.cd1-3.o2"] = "Peut-être dans un arbre ?"
        d["sel.cd1-3.o3"] = "Je ne sais pas, les chats vont partout"

        d["sel.cd2.title"] = "La vente de gâteaux"
        d["sel.cd2.narrative"] = "Ta classe organise une vente de gâteaux pour collecter des fonds. Tu veux aider en faisant des cookies."
        d["sel.cd2-1.q"] = "La vente est vendredi. On est mardi. Quand devrais-tu commencer à cuisiner ?"
        d["sel.cd2-1.o1"] = "Jeudi soir pour qu'ils soient frais. Je dois acheter les ingrédients mercredi"
        d["sel.cd2-1.o2"] = "Vendredi matin avant l'école"
        d["sel.cd2-1.o3"] = "Quand mes parents me le diront"
        d["sel.cd2-2.q"] = "Chaque cookie coûte 50 centimes à faire. À combien devrais-tu les vendre ?"
        d["sel.cd2-2.o1"] = "Plus de 50 centimes, comme 1€, pour gagner de l'argent pour l'école"
        d["sel.cd2-2.o2"] = "50 centimes chacun"
        d["sel.cd2-2.o3"] = "Les donner gratuitement"
        d["sel.cd2-3.q"] = "Tu as fait 24 cookies. À midi tu en as vendu 18. Combien en reste-t-il ?"
        d["sel.cd2-3.o1"] = "6 cookies. Je devrais baisser le prix pour les vendre avant la fin de l'école"
        d["sel.cd2-3.o2"] = "Il en reste quelques-uns, je vais continuer d'essayer"
        d["sel.cd2-3.o3"] = "Je ne suis pas sûr, les maths c'est dur"

        d["sel.cd3.title"] = "La foire scientifique"
        d["sel.cd3.narrative"] = "Tu fais un projet de foire scientifique sur la croissance des plantes. Tu as planté deux graines — une au soleil et une dans un placard sombre."
        d["sel.cd3-1.q"] = "Après une semaine, la plante au soleil est grande et verte, mais celle dans le noir est petite et jaune. Que t'apprend cela ?"
        d["sel.cd3-1.o1"] = "Les plantes ont besoin de soleil pour bien pousser — le résultat montre que la lumière fait une grande différence"
        d["sel.cd3-1.o2"] = "Une graine était probablement meilleure que l'autre"
        d["sel.cd3-1.o3"] = "Je ne suis pas sûr de ce qui s'est passé"
        d["sel.cd3-2.q"] = "Tu as oublié d'arroser la plante au soleil pendant 3 jours et elle a commencé à flétrir. Qu'est-ce qui a causé ça ?"
        d["sel.cd3-2.o1"] = "Sans eau, la plante ne peut pas rester en bonne santé même avec du soleil — l'eau et la lumière sont tous les deux importants"
        d["sel.cd3-2.o2"] = "Elle a peut-être eu trop de soleil"
        d["sel.cd3-2.o3"] = "Je ne sais pas pourquoi elle flétrit"
        d["sel.cd3-3.q"] = "Pour ta prochaine expérience, tu veux tester si la musique aide les plantes à pousser. Que prédirais-tu ?"
        d["sel.cd3-3.o1"] = "Je prédirais que la plante avec de la musique pourrait pousser différemment, mais il faudrait tester pour en être sûr"
        d["sel.cd3-3.o2"] = "La musique aide sûrement les plantes"
        d["sel.cd3-3.o3"] = "Je n'en ai aucune idée"

        // MARK: - SEL Scenarios: Life Skills
        d["sel.ls1.title"] = "Le chemin de la maison"
        d["sel.ls1.narrative"] = "Tu marches vers le parc avec ton ami. C'est un chemin que tu connais bien, mais aujourd'hui le chemin habituel est bloqué par des travaux."
        d["sel.ls1-1.q"] = "Tu dois traverser la rue. Quel est le moyen le plus sûr ?"
        d["sel.ls1-1.o1"] = "S'arrêter au passage piéton, regarder à gauche, à droite et encore à gauche, puis traverser quand c'est libre"
        d["sel.ls1-1.o2"] = "Regarder des deux côtés rapidement et traverser"
        d["sel.ls1-1.o3"] = "Traverser n'importe où, les voitures s'arrêteront"
        d["sel.ls1-2.q"] = "Un inconnu en voiture s'arrête et te demande si tu veux qu'on te ramène. Que fais-tu ?"
        d["sel.ls1-2.o1"] = "Dire non merci, continuer à marcher et prévenir un adulte de confiance tout de suite"
        d["sel.ls1-2.o2"] = "L'ignorer et marcher plus vite"
        d["sel.ls1-2.o3"] = "Demander où il va"
        d["sel.ls1-3.q"] = "Le chemin habituel est bloqué. Quel est le meilleur choix ?"
        d["sel.ls1-3.o1"] = "Prendre l'autre chemin que je connais, ou appeler mes parents pour de l'aide"
        d["sel.ls1-3.o2"] = "Essayer de contourner les travaux"
        d["sel.ls1-3.o3"] = "Passer par le chantier, c'est plus rapide"

        d["sel.ls2.title"] = "Se préparer pour l'école"
        d["sel.ls2.narrative"] = "C'est le matin et tu dois te préparer pour l'école. Ton parent est occupé avec ton petit frère ou ta petite sœur."
        d["sel.ls2-1.q"] = "Que devrais-tu faire en premier en te réveillant ?"
        d["sel.ls2-1.o1"] = "Me brosser les dents, me laver le visage et m'habiller"
        d["sel.ls2-1.o2"] = "M'habiller"
        d["sel.ls2-1.o3"] = "Regarder la télé en attendant qu'on me dise quoi faire"
        d["sel.ls2-2.q"] = "Il pleut aujourd'hui et tu as sport. Que devrais-tu porter ?"
        d["sel.ls2-2.o1"] = "Un imperméable, des baskets pour le sport et apporter des chaussettes de rechange"
        d["sel.ls2-2.o2"] = "Mes vêtements habituels"
        d["sel.ls2-2.o3"] = "Ce qui traîne par terre"
        d["sel.ls2-3.q"] = "Tu dois préparer ton déjeuner toi-même aujourd'hui. Que choisirais-tu ?"
        d["sel.ls2-3.o1"] = "Un sandwich, un fruit, une bouteille d'eau et un petit goûter"
        d["sel.ls2-3.o2"] = "Les snacks que je trouve"
        d["sel.ls2-3.o3"] = "J'achèterai des chips à l'école"

        d["sel.ls3.title"] = "La blessure au terrain de jeux"
        d["sel.ls3.narrative"] = "Tu joues à la récréation et ton ami trébuche, tombe et s'écorche le genou. Ça saigne un peu et il pleure."
        d["sel.ls3-1.q"] = "Quelle est la première chose que tu devrais faire ?"
        d["sel.ls3-1.o1"] = "Rester calme, réconforter mon ami et prévenir un professeur ou l'infirmière tout de suite"
        d["sel.ls3-1.o2"] = "Essayer de l'aider à se relever et continuer à jouer"
        d["sel.ls3-1.o3"] = "Attendre et voir s'il arrête de pleurer"
        d["sel.ls3-2.q"] = "Le professeur te demande d'aller chercher la trousse de premiers secours. Que faut-il utiliser sur une éraflure ?"
        d["sel.ls3-2.o1"] = "La nettoyer avec de l'eau, mettre un pansement et laisser l'infirmière vérifier"
        d["sel.ls3-2.o2"] = "Juste mettre de l'eau dessus"
        d["sel.ls3-2.o3"] = "Je ne sais pas quoi faire avec une trousse de premiers secours"
        d["sel.ls3-3.q"] = "Si ton ami était gravement blessé et qu'aucun adulte n'était là, qui appellerais-tu ?"
        d["sel.ls3-3.o1"] = "Appeler mes parents, ou composer le numéro d'urgence, et rester avec mon ami"
        d["sel.ls3-3.o2"] = "Courir chercher quelqu'un"
        d["sel.ls3-3.o3"] = "Paniquer et ne pas savoir quoi faire"

        // MARK: - SEL Scenarios: Language Development
        d["sel.ld1.title"] = "Montre et raconte"
        d["sel.ld1.narrative"] = "C'est le jour de Montre et Raconte. Tu as apporté ton robot jouet préféré pour le montrer à la classe."
        d["sel.ld1-1.q"] = "Comment décrirais-tu ton robot à la classe ?"
        d["sel.ld1-1.o1"] = "Voici Robo. C'est un robot rouge avec des lumières bleues. Il peut marcher et faire des sons quand on appuie sur le bouton dans son dos"
        d["sel.ld1-1.o2"] = "C'est mon robot. Il est cool et il bouge"
        d["sel.ld1-1.o3"] = "C'est un robot"
        d["sel.ld1-2.q"] = "Ton camarade demande « Où tu l'as eu et qu'est-ce qu'il fait ? »"
        d["sel.ld1-2.o1"] = "Ma mamie me l'a offert pour mon anniversaire. Il marche quand on l'allume et ses yeux s'illuminent !"
        d["sel.ld1-2.o2"] = "C'est un cadeau. Il marche."
        d["sel.ld1-2.o3"] = "Je ne me souviens pas"
        d["sel.ld1-3.q"] = "Ton professeur te demande de partager un souvenir amusant avec ton robot."
        d["sel.ld1-3.o1"] = "Une fois je l'ai emmené au parc et mon chien a cru qu'il était vrai ! Il aboyait et courait autour. C'était trop drôle !"
        d["sel.ld1-3.o2"] = "Je joue beaucoup avec à la maison"
        d["sel.ld1-3.o3"] = "C'est amusant"

        d["sel.ld2.title"] = "La fête d'anniversaire"
        d["sel.ld2.narrative"] = "Tu es allé à une super fête d'anniversaire ce week-end. Ton ami veut tout savoir !"
        d["sel.ld2-1.q"] = "Raconte à ton ami ce qui s'est passé à la fête du début à la fin."
        d["sel.ld2-1.o1"] = "D'abord on a joué à des jeux, puis on a mangé de la pizza, après on a eu le gâteau, et à la fin on a reçu des pochettes surprises !"
        d["sel.ld2-1.o2"] = "On a joué à des jeux et mangé du gâteau"
        d["sel.ld2-1.o3"] = "C'était amusant"
        d["sel.ld2-2.q"] = "Que se passait-il quand tout le monde a éclaté de rire à la fête ?"
        d["sel.ld2-2.o1"] = "L'enfant fêté a ouvert un cadeau et c'était un chapeau rigolo — tout le monde riait et jouait ensemble"
        d["sel.ld2-2.o2"] = "Quelqu'un a raconté une blague"
        d["sel.ld2-2.o3"] = "J'ai oublié"
        d["sel.ld2-3.q"] = "Tu as rencontré la cousine de ton ami à la fête. Parle-moi d'elle."
        d["sel.ld2-3.o1"] = "Elle s'appelle Maya. Elle est très grande et a les cheveux bouclés. Elle était très drôle et nous a appris un nouveau jeu !"
        d["sel.ld2-3.o2"] = "Elle était gentille"
        d["sel.ld2-3.o3"] = "Je ne me souviens pas beaucoup"

        d["sel.ld3.title"] = "Jour de film"
        d["sel.ld3.narrative"] = "Tu viens de regarder un film super avec ta famille. Ton ami à l'école te pose des questions dessus le lendemain."
        d["sel.ld3-1.q"] = "Ton ami demande « C'était quoi le film ? » Comment l'expliquerais-tu ?"
        d["sel.ld3-1.o1"] = "C'était l'histoire d'une fille courageuse qui a trouvé une carte magique et est partie à l'aventure pour sauver son village d'une tempête. À la fin elle a découvert que la carte était un puzzle !"
        d["sel.ld3-1.o2"] = "C'était l'histoire d'une fille en aventure"
        d["sel.ld3-1.o3"] = "C'était bien"
        d["sel.ld3-2.q"] = "Quel était ton moment préféré ? Décris-le pour que ton ami puisse l'imaginer."
        d["sel.ld3-2.o1"] = "Le meilleur moment c'était quand la fille a escaladé une énorme montagne couverte de neige — le vent soufflait fort et elle a failli tomber, mais elle a attrapé une liane et s'est balancée au-dessus d'un grand vide !"
        d["sel.ld3-2.o2"] = "La partie où elle escalade une montagne était cool"
        d["sel.ld3-2.o3"] = "J'ai aimé la fin"
        d["sel.ld3-3.q"] = "Ton ami n'a pas vu le film. Il demande « Je devrais le regarder ? Il y a des choses confuses ? »"
        d["sel.ld3-3.o1"] = "Oui, tu devrais ! Le début est un peu lent, mais quand elle trouve la carte ça devient vraiment passionnant. Tu pourrais te demander comment la carte marche au début, mais ils l'expliquent après"
        d["sel.ld3-3.o2"] = "Oui c'est bien, tu devrais le regarder"
        d["sel.ld3-3.o3"] = "Je ne sais pas, peut-être"

        // MARK: - SEL Journey & Daily Session
        d["sel.growth_report"] = "Rapport de croissance"
        d["sel.no_data_yet"] = "Pas encore de données. Votre enfant peut commencer un bilan quotidien depuis l'onglet Réflexion."
        d["sel.empty_state_hint"] = "Appuyez sur l'onglet Réflexion et choisissez « Bilan quotidien » pour commencer."
        d["sel.progress_description"] = "Les progrès socio-émotionnels de votre enfant au cours des 30 derniers jours."
        d["sel.overall_score"] = "Score global"
        d["sel.domain_profile"] = "Profil des domaines"
        d["sel.domain_breakdown"] = "Détail par domaine"
        d["sel.seven_day_trends"] = "Tendances sur 7 jours"
        d["sel.need_more_sessions"] = "Complétez au moins 2 sessions pour voir les tendances."
        d["sel.recent_sessions"] = "Sessions récentes"
        d["sel.mindfulness_moment"] = "MOMENT DE PLEINE CONSCIENCE"
        d["sel.deep_breaths"] = "Prenons %d grandes respirations"
        d["sel.breathe_instruction"] = "Inspirez lentement... et expirez."
        d["sel.skip_to_activities"] = "Passer aux activités"
        d["sel.wonderful_job"] = "Excellent travail !"
        d["sel.closing_message"] = "Tu as fait un super travail de réflexion sur tes émotions aujourd'hui. Continue comme ça !"
        d["sel.activities_completed"] = "%d activités terminées"
        d["sel.breath_counter"] = "Respiration %d sur %d"
        d["sel.domain_check"] = "%@ • VÉRIFICATION %d/3"
        d["sel.checks_completed"] = "%d activités terminées"
        d["sel.checks_mindfulness"] = "%d activités terminées • Pleine conscience"
        d["sel.eye_bridge.high"] = "Bonne concentration aujourd'hui — cela favorise un engagement socio-émotionnel plus profond."
        d["sel.eye_bridge.moderate"] = "Attention modérée — les activités SEL pourraient bénéficier de sessions plus courtes et ciblées."
        d["sel.eye_bridge.low"] = "Faible attention aujourd'hui — envisagez des pauses avant les activités SEL."
        d["sel.feedback.great"] = "Très bonne réflexion !"
        d["sel.feedback.good"] = "Bon choix !"
        d["sel.feedback.okay"] = "C'est bien ! Continuons"

        // MARK: - Reflection Time (additional)
        d["reflect.daily_checkin.title"] = "Bilan quotidien"
        d["reflect.daily_checkin.desc"] = "Un bilan socio-émotionnel rapide pour la journée"

        // MARK: - Eye Tracking
        d["eye.delete_button"] = "Supprimer les données"
        d["eye.delete_confirm_message"] = "Cela supprimera toutes les données de suivi oculaire. Cette action est irréversible."
        d["eye.delete_confirm_title"] = "Supprimer les données de suivi oculaire ?"
        d["eye.enable_subtitle"] = "Suivez l'attention et la fatigue de votre enfant pendant la navigation"
        d["eye.enable_toggle"] = "Activer le suivi oculaire"
        d["eye.gaze_distribution"] = "Distribution du regard"
        d["eye.interpretation_title"] = "Interprétation"
        d["eye.metric_attention"] = "Attention"
        d["eye.metric_blink"] = "Clignements"
        d["eye.metric_fatigue"] = "Fatigue"
        d["eye.metric_focus"] = "Concentration"
        d["eye.no_data_message"] = "Les données de suivi oculaire apparaîtront ici après utilisation."
        d["eye.no_data_title"] = "Pas encore de données"
        d["eye.privacy_badge"] = "Données traitées sur l'appareil"
        d["eye.report_title"] = "Rapport de suivi oculaire"
        d["eye.sel_bridge_title"] = "Lien attention & SEL"
        d["eye.settings_title"] = "Suivi oculaire"
        d["eye.trend_attention"] = "Tendance d'attention"
        d["eye.trend_blink"] = "Tendance de clignements"
        d["eye.view_report"] = "Voir le rapport"
        d["eye.view_report_desc"] = "Analyse détaillée de l'attention et de la fatigue"

        // MARK: - Guided Access
        d["guided_access.reminder.dont_remind"] = "Ne plus rappeler"
        d["guided_access.reminder.explanation"] = "L'accès guidé empêche votre enfant de quitter Komal ou de modifier les paramètres."
        d["guided_access.reminder.got_it"] = "Compris"
        d["guided_access.reminder.title"] = "Activer l'accès guidé"
        d["onboarding.guided_access.explanation"] = "L'accès guidé verrouille l'appareil sur Komal pour que votre enfant ne puisse pas accéder à d'autres applications."
        d["onboarding.guided_access.open_settings"] = "Ouvrir les réglages"
        d["onboarding.guided_access.research_note"] = "Recommandé par les experts en sécurité numérique des enfants."
        d["onboarding.guided_access.step1"] = "Allez dans Réglages > Accessibilité > Accès guidé"
        d["onboarding.guided_access.step2"] = "Activez l'accès guidé et définissez un code"
        d["onboarding.guided_access.step3"] = "Appuyez trois fois sur le bouton latéral pour activer"
        d["onboarding.guided_access.subtitle"] = "Gardez votre enfant dans l'application Komal"
        d["onboarding.guided_access.title"] = "Configurer l'accès guidé"

        // MARK: - Browser & Gate (additional)
        d["browser.before_you_go"] = "Avant de partir"
        d["browser.content_filtered"] = "Ce contenu a été filtré"
        d["browser.content_unverified"] = "Ce contenu n'a pas été vérifié"
        d["gate.locked_out"] = "Trop de tentatives. Réessayez dans %d secondes."
        d["gate.wrong_pin"] = "Code PIN incorrect. Réessayez."
        d["journey.history_empty_hint"] = "L'historique de navigation apparaîtra ici."

        // MARK: - Settings (SEL)
        d["settings.sel_journey"] = "Parcours SEL"
        d["settings.view_sel_report"] = "Voir le rapport SEL"
        d["settings.sel_progress_desc"] = "Suivez les progrès socio-émotionnels de votre enfant"

        // MARK: - Accessibility
        d["accessibility.komal_character"] = "Personnage Komal"
        d["accessibility.ellie_character"] = "Ellie l'éléphante"
        d["accessibility.emoji_react"] = "Réagir avec %@"
        d["accessibility.emotion_intensity"] = "Intensité de l'émotion"
        d["accessibility.go_back"] = "Retour"
        d["accessibility.go_forward"] = "Avancer"
        d["accessibility.tab_switcher"] = "%d onglets ouverts"
        d["accessibility.sel.breathing_circle"] = "Cercle d'exercice de respiration"
        d["accessibility.sel.completion_star"] = "Étoile de complétion"
        d["accessibility.sel.score"] = "Score : %d sur 100"
        d["accessibility.sel.sparkline"] = "Graphique de tendance des scores"
        d["accessibility.sel.no_change"] = "Aucun changement"
        d["accessibility.sel.radar_chart"] = "Graphique radar du profil par domaine"
        d["accessibility.sel.trend_chart"] = "Graphique de tendance sur 7 jours"

        // MARK: - Gate (additional)
        d["gate.approve_biometric"] = "Approuver avec %@"
        d["gate.or_enter_pin"] = "ou entrer le code PIN"

        return d
    }()
}
// swiftlint:enable file_length type_body_length
