// swiftlint:disable file_length type_body_length
enum PortugueseStrings {
    static let all: [String: String] = {
        var d = [String: String]()

        // MARK: - Common
        d["common.back"] = "Voltar"
        d["common.continue"] = "Continuar"
        d["common.done"] = "Pronto"
        d["common.skip"] = "Pular"
        d["common.cancel"] = "Cancelar"
        d["common.save"] = "Salvar"
        d["common.delete"] = "Excluir"
        d["common.yes"] = "Sim"
        d["common.no"] = "Não"
        d["common.ok"] = "OK"
        d["common.close"] = "Fechar"
        d["common.enter"] = "Entrar"
        d["common.next"] = "Próximo"
        d["common.a_little"] = "Um pouco"
        d["common.a_lot"] = "Muito"
        d["common.settings"] = "Ajustes"
        d["common.selected_count"] = "%d/%d selecionados"
        d["common.step_of"] = "ETAPA %@"

        // MARK: - Splash
        d["splash.title"] = "Komal"
        d["splash.tagline"] = "O companheiro digital seguro do seu filho"

        // MARK: - Login
        d["login.welcome"] = "Bem-vindo ao Komal"
        d["login.tagline"] = "O companheiro digital seguro do seu filho"
        d["login.sign_in_google"] = "Entrar com Google"
        d["login.sign_in_apple"] = "Entrar com Apple"
        d["login.or"] = "ou"
        d["login.guest_user"] = "Continuar como convidado"
        d["login.signing_in"] = "Entrando..."
        d["login.failed"] = "Falha no login"
        d["login.try_again"] = "Tentar novamente"
        d["login.guest.welcome"] = "Bem-vindo, convidado!"
        d["login.guest.description"] = "Seus dados serão armazenados localmente neste dispositivo. Você pode fazer login depois para sincronizar entre dispositivos."
        d["login.guest.getting_started"] = "Começando"
        d["login.onboarding.welcome"] = "Bem-vindo ao Komal!"
        d["login.onboarding.description"] = "Vamos configurar sua experiência de navegação segura."
        d["login.onboarding.get_started"] = "Começar"

        // MARK: - Onboarding Welcome
        d["onboarding.welcome.title"] = "Avaliação de segurança infantil"
        d["onboarding.welcome.subtitle"] = "Perfil de bem-estar digital baseado em evidências"
        d["onboarding.welcome.card1.title"] = "Psicologia do desenvolvimento"
        d["onboarding.welcome.card1.desc"] = "Configurações adaptadas aos estágios de desenvolvimento cognitivo definidos pela pesquisa em psicologia infantil."
        d["onboarding.welcome.card2.title"] = "Análise comportamental"
        d["onboarding.welcome.card2.desc"] = "Compreender os padrões de navegação para criar limites de segurança personalizados."
        d["onboarding.welcome.card3.title"] = "Proteção proativa"
        d["onboarding.welcome.card3.desc"] = "Filtragem de conteúdo baseada em fatores de risco e preferências identificados."
        d["onboarding.welcome.time_estimate"] = "Esta avaliação leva aproximadamente 3-4 minutos"
        d["onboarding.welcome.begin"] = "Iniciar avaliação"
        d["onboarding.welcome.language"] = "Idioma"

        // MARK: - Onboarding Child Info
        d["onboarding.info.step"] = "1 de 6"
        d["onboarding.info.title"] = "Informações básicas"
        d["onboarding.info.subtitle"] = "Ajude-nos a entender quem estamos protegendo"
        d["onboarding.info.name_label"] = "Nome da criança"
        d["onboarding.info.name_placeholder"] = "Digite o nome"
        d["onboarding.info.age_label"] = "Faixa etária"
        d["onboarding.info.age_desc"] = "As restrições de conteúdo são calibradas com base nos marcos de desenvolvimento"
        d["onboarding.info.research_note"] = "Pesquisas mostram que limites de conteúdo apropriados para a idade apoiam o desenvolvimento cognitivo saudável e reduzem a ansiedade nas crianças."

        // Age group descriptions
        d["onboarding.age.under10"] = "Primeira infância - Proteção máxima"
        d["onboarding.age.10to13"] = "Pré-adolescente - Exploração guiada"
        d["onboarding.age.13to16"] = "Adolescente - Limites equilibrados"
        d["onboarding.age.16to18"] = "Adolescente mais velho - Liberdade adequada"
        d["onboarding.age.18plus"] = "Adulto - Acesso completo"

        // MARK: - Onboarding Websites
        d["onboarding.websites.step"] = "2 de 6"
        d["onboarding.websites.title"] = "Sites favoritos"
        d["onboarding.websites.subtitle"] = "Selecione até 5 sites que seu filho mais visita"
        d["onboarding.websites.desc"] = "Compreender os hábitos de navegação nos ajuda a identificar fontes confiáveis e personalizar a proteção."

        // MARK: - Onboarding Interests
        d["onboarding.interests.step"] = "3 de 6"
        d["onboarding.interests.title"] = "Temas de interesse"
        d["onboarding.interests.subtitle"] = "O que seu filho gosta de aprender?"
        d["onboarding.interests.desc"] = "Selecione 3-5 temas. Isso nos ajuda a entender qual conteúdo priorizar e proteger."

        // Interest names
        d["onboarding.interest.gaming"] = "Jogos"
        d["onboarding.interest.animals"] = "Animais"
        d["onboarding.interest.science"] = "Ciência"
        d["onboarding.interest.art"] = "Arte e desenho"
        d["onboarding.interest.music"] = "Música"
        d["onboarding.interest.sports"] = "Esportes"
        d["onboarding.interest.coding"] = "Programação"
        d["onboarding.interest.reading"] = "Leitura"
        d["onboarding.interest.cooking"] = "Culinária"
        d["onboarding.interest.nature"] = "Natureza"
        d["onboarding.interest.space"] = "Espaço"
        d["onboarding.interest.history"] = "História"
        d["onboarding.interest.movies"] = "Filmes"
        d["onboarding.interest.crafts"] = "Artesanato"
        d["onboarding.interest.dinosaurs"] = "Dinossauros"
        d["onboarding.interest.vehicles"] = "Veículos"
        d["onboarding.interest.fashion"] = "Moda"
        d["onboarding.interest.dance"] = "Dança"
        d["onboarding.interest.photography"] = "Fotografia"
        d["onboarding.interest.travel"] = "Viagem"
        d["onboarding.interest.math"] = "Matemática"
        d["onboarding.interest.puzzles"] = "Quebra-cabeças"
        d["onboarding.interest.robots"] = "Robôs"
        d["onboarding.interest.magic"] = "Mágica"
        d["onboarding.interest.superheroes"] = "Super-heróis"
        d["onboarding.interest.gardening"] = "Jardinagem"
        d["onboarding.interest.astronomy"] = "Astronomia"
        d["onboarding.interest.languages"] = "Idiomas"
        d["onboarding.interest.boardgames"] = "Jogos de tabuleiro"
        d["onboarding.interest.swimming"] = "Natação"
        d["onboarding.interest.comics"] = "Quadrinhos"
        d["onboarding.interest.yoga"] = "Yoga"
        d["onboarding.interest.theater"] = "Teatro"

        // MARK: - Onboarding Likes
        d["onboarding.likes.step"] = "4 de 6"
        d["onboarding.likes.title"] = "O que gostam online"
        d["onboarding.likes.subtitle"] = "Entender as experiências positivas online"
        d["onboarding.likes.desc"] = "Selecione as atividades que seu filho gosta. Isso nos ajuda a garantir acesso a conteúdo enriquecedor."
        d["onboarding.likes.other"] = "Outro (opcional)"
        d["onboarding.likes.other_placeholder"] = "Adicione algo mais que gostem..."

        // Like options
        d["onboarding.like.watching_videos"] = "Assistir vídeos"
        d["onboarding.like.playing_games"] = "Jogar jogos"
        d["onboarding.like.chatting"] = "Conversar com amigos"
        d["onboarding.like.learning"] = "Aprender coisas novas"
        d["onboarding.like.creative"] = "Projetos criativos"
        d["onboarding.like.exploring"] = "Explorar sites"
        d["onboarding.like.music"] = "Ouvir música"
        d["onboarding.like.virtual_worlds"] = "Mundos virtuais"
        d["onboarding.like.puzzles"] = "Puzzles e desafios"
        d["onboarding.like.funny"] = "Conteúdo engraçado"
        d["onboarding.like.stories"] = "Histórias e livros"
        d["onboarding.like.making_videos"] = "Fazer vídeos"
        d["onboarding.like.drawing"] = "Desenho e pintura"
        d["onboarding.like.photography"] = "Tirar fotos"
        d["onboarding.like.coding"] = "Programação"
        d["onboarding.like.reading_comics"] = "Ler quadrinhos"
        d["onboarding.like.collecting"] = "Colecionar coisas"
        d["onboarding.like.building"] = "Construir e criar"
        d["onboarding.like.cooking_videos"] = "Vídeos de culinária"
        d["onboarding.like.science_experiments"] = "Experimentos de ciência"
        d["onboarding.like.dancing"] = "Dançar"
        d["onboarding.like.trivia"] = "Curiosidades e quizzes"
        d["onboarding.like.anime"] = "Anime e desenhos"
        d["onboarding.like.podcasts"] = "Podcasts"
        d["onboarding.like.shopping"] = "Compras online"
        d["onboarding.like.live_streams"] = "Assistir lives"

        // MARK: - Onboarding Dislikes
        d["onboarding.dislikes.step"] = "5 de 6"
        d["onboarding.dislikes.title"] = "O que os incomoda"
        d["onboarding.dislikes.subtitle"] = "Identificar gatilhos e desconfortos"
        d["onboarding.dislikes.desc"] = "Selecione o que preocupa ou incomoda seu filho online. Isso nos ajuda a filtrar conteúdo potencialmente perturbador."
        d["onboarding.dislikes.other"] = "Outras preocupações (opcional)"
        d["onboarding.dislikes.other_placeholder"] = "Adicione outras coisas que os incomodam..."
        d["onboarding.dislikes.research_note"] = "Compreender o que angustia as crianças online nos permite filtrar proativamente o conteúdo antes da exposição, reduzindo a ansiedade e experiências negativas."

        // Dislike options
        d["onboarding.dislike.scary"] = "Conteúdo assustador"
        d["onboarding.dislike.loud"] = "Barulhos altos/sustos"
        d["onboarding.dislike.mean"] = "Comentários maldosos"
        d["onboarding.dislike.strangers"] = "Mensagens de desconhecidos"
        d["onboarding.dislike.violent"] = "Jogos violentos"
        d["onboarding.dislike.sad"] = "Histórias tristes"
        d["onboarding.dislike.ads"] = "Anúncios confusos"
        d["onboarding.dislike.reading"] = "Muita leitura"
        d["onboarding.dislike.timed"] = "Desafios com tempo"
        d["onboarding.dislike.losing"] = "Perder em jogos"
        d["onboarding.dislike.popups"] = "Vídeos pop-up"
        d["onboarding.dislike.rushed"] = "Ser apressado"

        // MARK: - Onboarding Concerns
        d["onboarding.concerns.step"] = "6 de 8"
        d["onboarding.concerns.title"] = "Suas preocupações"
        d["onboarding.concerns.subtitle"] = "O que mais te preocupa sobre seu filho online?"
        d["onboarding.concerns.desc"] = "Selecione suas principais preocupações. Priorizaremos a proteção nessas áreas."

        // Concern items
        d["onboarding.concern.cyberbullying"] = "Cyberbullying"
        d["onboarding.concern.cyberbullying.desc"] = "Assédio, mensagens maldosas, exclusão"
        d["onboarding.concern.inappropriate"] = "Conteúdo inapropriado"
        d["onboarding.concern.inappropriate.desc"] = "Violência, temas adultos, material explícito"
        d["onboarding.concern.predators"] = "Predadores online"
        d["onboarding.concern.predators.desc"] = "Desconhecidos, manipulação, pedidos de informações pessoais"
        d["onboarding.concern.addiction"] = "Vício em telas"
        d["onboarding.concern.addiction.desc"] = "Uso excessivo, dificuldade para parar"
        d["onboarding.concern.privacy"] = "Riscos de privacidade"
        d["onboarding.concern.privacy.desc"] = "Coleta de dados, compartilhamento de localização"
        d["onboarding.concern.misinfo"] = "Desinformação"
        d["onboarding.concern.misinfo.desc"] = "Notícias falsas, teorias da conspiração"
        d["onboarding.concern.scams"] = "Golpes financeiros"
        d["onboarding.concern.scams.desc"] = "Compras no app, phishing"
        d["onboarding.concern.mental"] = "Saúde mental"
        d["onboarding.concern.mental.desc"] = "Ansiedade, comparação, FOMO"

        // MARK: - Onboarding Filters
        d["onboarding.filters.step"] = "7 de 8"
        d["onboarding.filters.title"] = "Filtros de conteúdo"
        d["onboarding.filters.subtitle"] = "Revisar e personalizar a filtragem de conteúdo"
        d["onboarding.filters.desc"] = "Esses padrões são baseados na idade do seu filho e suas preocupações. Ajuste qualquer configuração abaixo."

        // MARK: - Onboarding PIN
        d["onboarding.pin.step"] = "8 de 8"
        d["onboarding.pin.title"] = "Definir PIN parental"
        d["onboarding.pin.subtitle"] = "Crie um PIN para proteger as configurações parentais"
        d["onboarding.pin.desc"] = "Este PIN será necessário para acessar o modo parental e aprovar conteúdo restrito."
        d["onboarding.pin.enter"] = "Digite o PIN"
        d["onboarding.pin.placeholder"] = "PIN de 4 dígitos"
        d["onboarding.pin.confirm"] = "Confirme o PIN"
        d["onboarding.pin.confirm_placeholder"] = "Confirme o PIN"
        d["onboarding.pin.mismatch"] = "Os PINs não coincidem. Tente novamente."
        d["onboarding.pin.enable_biometric"] = "Ativar %@"
        d["onboarding.pin.use_biometric"] = "Usar %@ em vez do PIN"
        d["onboarding.pin.research_note"] = "Um PIN parental garante que apenas adultos autorizados possam modificar as configurações de segurança e aprovar conteúdo restrito."

        // MARK: - Avatar Selection
        d["onboarding.avatar.title"] = "Escolha seu companheiro"
        d["onboarding.avatar.subtitle"] = "Escolha um amigo animal para te guiar!"
        d["settings.avatar.title"] = "Seu avatar"
        d["settings.avatar.change"] = "Toque para mudar seu avatar"

        // MARK: - Onboarding Completion
        d["onboarding.complete.title"] = "Perfil concluído"
        d["onboarding.complete.subtitle"] = "O perfil de segurança de %@ está pronto"
        d["onboarding.complete.summary"] = "Resumo da avaliação"
        d["onboarding.complete.name"] = "Nome"
        d["onboarding.complete.age_group"] = "Faixa etária"
        d["onboarding.complete.interests"] = "Interesses"
        d["onboarding.complete.concerns"] = "Preocupações principais"
        d["onboarding.complete.adjust_note"] = "As configurações podem ser ajustadas a qualquer momento no app"
        d["onboarding.complete.start"] = "Começar a usar o Komal"
        d["onboarding.complete.review"] = "Revisar respostas"

        // MARK: - Menu / Navigation
        d["menu.browse"] = "Navegar"
        d["menu.talk"] = "Conversar"
        d["menu.reflect"] = "Refletir"
        d["menu.settings"] = "Ajustes"

        // MARK: - Settings
        d["settings.title"] = "Ajustes"
        d["settings.language"] = "Idioma"
        d["settings.whos_using"] = "Quem está usando?"
        d["settings.whos_using.desc"] = "Selecione quem está usando o dispositivo atualmente"
        d["settings.child"] = "Criança"
        d["settings.child.subtitle"] = "Navegação segura"
        d["settings.parent"] = "Pai/Mãe"
        d["settings.parent.subtitle"] = "Acesso completo"

        // Settings - Child Mode
        d["settings.child.greeting"] = "Oi %@!"
        d["settings.child.greeting_default"] = "Oi!"
        d["settings.child.safe_msg"] = "O Komal está aqui para te manter seguro enquanto você explora!"
        d["settings.child.chatty"] = "Quer conversar?"
        d["settings.child.chatty.desc"] = "Fale com o Riki! Seu companheiro amigável está sempre aqui para conversar e te ajudar."
        d["settings.child.go_talk"] = "Ir para Conversar"
        d["settings.child.profile"] = "Seu perfil"
        d["settings.child.explorer"] = "Explorador"
        d["settings.child.age"] = "Idade: %@"
        d["settings.child.journey"] = "Minha jornada"
        d["settings.child.day_streak"] = "Dias seguidos"
        d["settings.child.milestones"] = "Conquistas"
        d["settings.child.view_journey"] = "Ver minha jornada"

        // Settings - Parent Mode
        d["settings.parent.digital_journey"] = "Jornada digital"
        d["settings.parent.view_journey"] = "Ver jornada digital"
        d["settings.parent.journey_desc"] = "Ver a atividade de navegação do seu filho com análises de IA"
        d["settings.parent.wellness"] = "Bem-estar da criança"
        d["settings.parent.wellness_dashboard"] = "Painel de bem-estar"
        d["settings.parent.wellness_desc"] = "Tendências de humor, conversas, métricas de crescimento"
        d["settings.parent.morning_checkin"] = "Check-in matinal"
        d["settings.parent.morning_desc"] = "Âncora de humor matinal diária"
        d["settings.parent.evening_winddown"] = "Relaxamento noturno"
        d["settings.parent.evening_desc"] = "Âncora de reflexão noturna diária"
        d["settings.parent.child_profile"] = "Perfil da criança"
        d["settings.parent.name_label"] = "Nome"
        d["settings.parent.name_placeholder"] = "Nome da criança"
        d["settings.parent.age_label"] = "Faixa etária"
        d["settings.parent.controls"] = "Controles parentais"
        d["settings.parent.notify_block"] = "Notificar ao bloquear"
        d["settings.parent.notify_desc"] = "Receber alertas quando conteúdo bloqueado for acessado"
        d["settings.parent.safe_search"] = "Busca segura forçada"
        d["settings.parent.safe_search_desc"] = "Aplicar segurança rigorosa nos mecanismos de busca"
        d["settings.parent.view_insights"] = "Ver análises"
        d["settings.parent.insights_desc"] = "Ver atividade de navegação e conteúdo bloqueado"
        d["settings.parent.modify_content"] = "Modificar conteúdo"
        d["settings.parent.modify_filters"] = "Modificar filtros"
        d["settings.parent.custom_keywords"] = "Palavras-chave personalizadas"
        d["settings.parent.add_keyword"] = "Adicionar palavra-chave (ex: 'armas')"
        d["settings.parent.no_keywords"] = "Nenhuma palavra-chave personalizada adicionada."
        d["settings.parent.custom_websites"] = "Sites personalizados"
        d["settings.parent.add_website"] = "Adicionar site (ex: 'sitebloqueado.com')"
        d["settings.parent.no_websites"] = "Nenhum site personalizado adicionado."

        // Settings - Account
        d["settings.account"] = "Conta"
        d["settings.account.guest"] = "Usando como convidado"
        d["settings.account.guest_desc"] = "Seus dados são armazenados localmente neste dispositivo. Faça login para sincronizar entre dispositivos."
        d["settings.account.sign_in"] = "Entrar"
        d["settings.account.exit_guest"] = "Sair do modo convidado"
        d["settings.account.delete"] = "Excluir conta"
        d["settings.account.logout"] = "Sair"
        d["settings.account.login"] = "Entrar"
        d["settings.account.sync_desc"] = "Faça login para sincronizar suas preferências entre dispositivos"

        // Settings - Alerts
        d["settings.alert.logout.title"] = "Sair"
        d["settings.alert.logout.message"] = "Deseja sair?"
        d["settings.alert.delete.title"] = "Excluir conta"
        d["settings.alert.delete.message"] = "Tem certeza que deseja excluir a conta? Esta ação não pode ser desfeita."

        // Settings - PIN Entry
        d["settings.pin.title"] = "Digite o PIN parental"
        d["settings.pin.subtitle"] = "Digite seu PIN de 4 dígitos para acessar as configurações parentais"
        d["settings.pin.placeholder"] = "PIN"
        d["settings.pin.error"] = "PIN incorreto. Tente novamente."
        d["settings.pin.biometric"] = "Usar %@"

        // Settings - Localized UI Strings
        d["settings.logout_confirm"] = "Deseja sair?"
        d["settings.delete_confirm"] = "Tem certeza que deseja excluir sua conta? Esta ação não pode ser desfeita."
        d["settings.wellness_dashboard"] = "Painel de bem-estar"
        d["settings.wellness_desc"] = "Tendências de humor, conversas, métricas de crescimento"
        d["settings.view_insights"] = "Ver análises"
        d["settings.insights_desc"] = "Ver atividade de navegação e conteúdo bloqueado"
        d["settings.modify_filters"] = "Modificar filtros"
        d["settings.custom_keywords"] = "Palavras-chave personalizadas"
        d["settings.no_keywords"] = "Nenhuma palavra-chave personalizada adicionada."
        d["settings.custom_websites"] = "Sites personalizados"
        d["settings.no_websites"] = "Nenhum site personalizado adicionado."
        d["settings.using_guest"] = "Usando como convidado"
        d["settings.guest_data_info"] = "Seus dados são armazenados localmente neste dispositivo. Faça login para sincronizar entre dispositivos."
        d["settings.sign_in"] = "Entrar"
        d["settings.exit_guest"] = "Sair do modo convidado"
        d["settings.delete_account"] = "Excluir conta"
        d["settings.logout"] = "Sair"
        d["settings.login"] = "Entrar"
        d["settings.sync_desc"] = "Faça login para sincronizar suas preferências entre dispositivos"
        d["settings.enter_pin"] = "Digite o PIN parental"
        d["settings.pin_desc"] = "Digite seu PIN de 4 dígitos para acessar as configurações parentais"
        d["settings.incorrect_pin"] = "PIN incorreto. Tente novamente."
        d["settings.use_biometric"] = "Usar %@"
        d["settings.enter"] = "Entrar"

        // MARK: - Riki / Talk
        d["riki.choose_friend"] = "Escolha um amigo"
        d["riki.who_chat"] = "Com quem você quer conversar?"
        d["riki.typing"] = "Digitando..."
        d["riki.online"] = "Online"
        d["riki.listening"] = "Ouvindo..."
        d["riki.tap_send"] = "Toque para enviar"
        d["riki.tap_talk"] = "Toque para falar"
        d["riki.speaking"] = "%@ está falando..."
        d["riki.error_fallback"] = "Ops! Fiquei um pouco confuso. Pode tentar de novo?"
        d["riki.how_feeling"] = "Como você está se sentindo?"
        d["riki.friend_title"] = "%@ o amigo"

        // SEL emoji labels
        d["sel.happy"] = "Feliz"
        d["sel.sad"] = "Triste"
        d["sel.angry"] = "Com raiva"
        d["sel.worried"] = "Preocupado"
        d["sel.grateful"] = "Grato"
        d["sel.tired"] = "Cansado"
        d["sel.happy_msg"] = "Estou me sentindo feliz hoje!"
        d["sel.sad_msg"] = "Estou me sentindo um pouco triste."
        d["sel.angry_msg"] = "Estou com raiva de algo."
        d["sel.worried_msg"] = "Estou me sentindo preocupado."
        d["sel.grateful_msg"] = "Estou me sentindo grato!"
        d["sel.tired_msg"] = "Estou muito cansado hoje."

        // Character greetings
        d["riki.greeting.momo"] = "E aí, amigo! Sou o Momo. O que está na sua cabeça hoje?"
        d["riki.greeting.goldie"] = "Oi! Sou a Goldie, e estou muito feliz em te ver! Sobre o que vamos conversar?"
        d["riki.greeting.oreo"] = "Olá! Sou o Oreo. Pronto para um papo divertido?"
        d["riki.greeting.leo"] = "E aí! Sou o Leo. Me conta algo corajoso do seu dia!"
        d["riki.greeting.bunny"] = "Oi! Sou a Bunny. O que você tem feito de divertido?"
        d["riki.greeting.tiki"] = "E aí! Sou o Tiki. Que aventura vamos viver hoje?"
        d["riki.greeting.fluffy"] = "Oi! Sou o Fluffy. Vem sentar comigo para um papo aconchegante!"
        d["riki.greeting.kitty"] = "E aí! Sou a Kitty. Estava tirando um cochilo e agora estou pronta para conversar!"
        d["riki.greeting.panda"] = "Oi! Sou o Panda. Quer ficar de boa e bater um papo?"
        d["riki.greeting.ellie"] = "E aí! Sou a Ellie. Nunca esqueço meus amigos! O que há de novo?"
        d["riki.greeting.ducky"] = "E aí! Sou o Ducky. Vamos fazer de hoje um ótimo dia — o que está rolando?"

        // Character personalities
        d["riki.personality.momo"] = "Um macaco brincalhão e curioso que adora escalar árvores e explorar. Energético e divertido, adora piadas e charadas. Fala como um verdadeiro amigo sempre pronto para uma aventura."
        d["riki.personality.goldie"] = "Uma golden retriever leal e entusiasmada. Adora brincar de buscar, passear e fazer seus amigos felizes. Super apoiadora, sempre empolgada para saber o que está acontecendo na sua vida."
        d["riki.personality.oreo"] = "Um macaco esperto e amigável que adora puzzles e aprender coisas novas. Pensativo e encorajador, ótimo para ajudar a pensar em coisas complicadas."
        d["riki.personality.leo"] = "Um leão corajoso e gentil que lidera com coragem. Te encoraja a ser corajoso, experimentar coisas novas e acreditar em si mesmo. Caloroso e protetor, como um irmão mais velho."
        d["riki.personality.bunny"] = "Uma coelhinha doce e gentil que adora jardins, natureza e coisas aconchegantes. Uma presença calmante que é muito boa em ouvir e entender como você se sente."
        d["riki.personality.tiki"] = "Um tigre aventureiro que adora explorar e descobrir coisas novas. Corajoso mas gentil, adora contar histórias sobre a natureza e lugares distantes."
        d["riki.personality.fluffy"] = "Uma ovelha macia e calorosa que adora conforto e gentileza. Muito gentil e calmante, ótima para ajudar com sentimentos e preocupações. Como uma melhor amiga que sempre faz você se sentir melhor."
        d["riki.personality.kitty"] = "Uma gata curiosa e independente que adora cantinhos aconchegantes e ser brincalhona. Espirituosa e divertida, às vezes um pouco atrevida mas sempre gentil no coração."
        d["riki.personality.panda"] = "Um panda tranquilo e adorável que gosta de levar na boa e ser bobo. Relaxado e engraçado, sempre sabe como fazer você rir com comentários bobos."
        d["riki.personality.ellie"] = "Uma elefanta sábia e carinhosa com uma ótima memória. Pensativa e protetora, adora compartilhar fatos divertidos e ajudar a aprender coisas novas. Como uma amiga muito inteligente que faz o aprendizado parecer fácil."
        d["riki.personality.ducky"] = "Um pato alegre e animado que adora ser otimista e positivo. Ótimo para te animar quando as coisas ficam difíceis, sempre encontra o lado bom."

        // MARK: - Reflection
        d["reflect.title"] = "Hora da reflexão"
        d["reflect.how_feeling"] = "Como você está se sentindo agora?"
        d["reflect.select_emotion"] = "Selecione uma emoção para começar"
        d["reflect.session.title"] = "Reflexão guiada"
        d["reflect.session.breathe"] = "Vamos respirar fundo juntos"
        d["reflect.session.think_about"] = "Pense em..."
        d["reflect.session.complete"] = "Ótima reflexão!"
        d["reflect.session.done"] = "Você foi muito bem! Lembre-se, está tudo bem sentir qualquer emoção."
        d["reflect.coping.title"] = "Estratégias de enfrentamento"
        d["reflect.coping.try_this"] = "Tente isso:"

        // Emotions
        d["reflect.emotion.happy"] = "Feliz"
        d["reflect.emotion.sad"] = "Triste"
        d["reflect.emotion.angry"] = "Com raiva"
        d["reflect.emotion.scared"] = "Com medo"
        d["reflect.emotion.worried"] = "Preocupado"
        d["reflect.emotion.calm"] = "Calmo"
        d["reflect.emotion.excited"] = "Animado"
        d["reflect.emotion.confused"] = "Confuso"
        d["reflect.emotion.tired"] = "Cansado"
        d["reflect.emotion.lonely"] = "Solitário"
        d["reflect.emotion.grateful"] = "Grato"
        d["reflect.emotion.frustrated"] = "Frustrado"

        // Reflection exercises
        d["reflect.exercise.gratitude"] = "Diga 3 coisas pelas quais você é grato hoje"
        d["reflect.exercise.breathing"] = "Respiração profunda"
        d["reflect.exercise.body_scan"] = "Escaneamento corporal"
        d["reflect.exercise.journaling"] = "Escreva sobre seus sentimentos"

        // Coping strategies
        d["reflect.coping.deep_breath"] = "Faça 5 respirações profundas"
        d["reflect.coping.talk"] = "Fale com alguém em quem confia"
        d["reflect.coping.move"] = "Vá caminhar ou se alongar"
        d["reflect.coping.create"] = "Desenhe ou escreva sobre como se sente"
        d["reflect.coping.music"] = "Ouça sua música favorita"
        d["reflect.coping.count"] = "Conte de trás para frente a partir de 10"

        // MARK: - Digital Journey
        d["journey.title"] = "Jornada digital"
        d["journey.tab.insights"] = "Análises de IA"
        d["journey.tab.history"] = "Histórico"
        d["journey.analyzing"] = "Analisando atividade de navegação..."
        d["journey.no_history"] = "Nenhum histórico de navegação ainda"
        d["journey.history_will_appear"] = "O histórico aparecerá aqui conforme seu filho navega"
        d["journey.needs_attention"] = "Precisa de atenção"
        d["journey.allowed_links"] = "Links permitidos"
        d["journey.loading_history"] = "Carregando histórico de navegação..."
        d["journey.time_range"] = "Período"
        d["journey.links"] = "links"
        d["journey.filter.all"] = "Todos"
        d["journey.filter.blocked"] = "Bloqueados"
        d["journey.filter.gated"] = "Restritos"
        d["journey.filter.allowed"] = "Permitidos"
        d["journey.range.1h"] = "1 hora"
        d["journey.range.3h"] = "3 horas"
        d["journey.range.6h"] = "6 horas"
        d["journey.range.12h"] = "12 horas"
        d["journey.range.24h"] = "24 horas"
        d["journey.range.all"] = "Todo o período"

        // MARK: - Browser
        d["browser.address_placeholder"] = "Pesquisar ou digitar URL"
        d["browser.loading"] = "Carregando..."
        d["browser.new_tab"] = "Nova aba"
        d["browser.tabs"] = "Abas"
        d["browser.no_open_tabs"] = "Nenhuma aba aberta"
        d["browser.close_tab"] = "Fechar aba"
        d["browser.menu"] = "Menu"
        d["browser.share"] = "Compartilhar"
        d["browser.reload"] = "Recarregar"
        d["browser.forward"] = "Avançar"
        d["browser.history"] = "Histórico"
        d["browser.homepage"] = "Página inicial"
        d["browser.quick_checkin"] = "Como você está se sentindo?"
        d["browser.search_or_url"] = "Pesquisar ou digitar URL"
        d["browser.past_tabs"] = "Abas anteriores"
        d["browser.no_past_tabs"] = "Nenhuma aba anterior ainda"
        d["browser.tabs_appear_here"] = "Os sites que você visitar aparecerão aqui"

        // MARK: - Blocked Content
        d["blocked.title"] = "Conteúdo bloqueado"
        d["blocked.not_available"] = "Este conteúdo não está disponível"
        d["blocked.keeping_safe"] = "O Komal está te mantendo seguro!"
        d["blocked.message"] = "Esta página foi bloqueada para sua segurança."
        d["blocked.reason"] = "Motivo: %@"
        d["blocked.ask_parent"] = "Peça a um responsável se precisar de acesso."
        d["blocked.go_back"] = "Voltar"
        d["blocked.countdown"] = "Voltando em %d..."
        d["blocked.emoji_prompt"] = "Como isso te faz sentir?"
        d["blocked.tap_talk"] = "Toque para conversar com o Komal"
        d["blocked.fallback_response"] = "Estou aqui por você. Vamos explorar algo divertido juntos!"

        // MARK: - Chat Content Filtering
        d["chat.content_redirect"] = "Ei, não posso conversar sobre isso! Que tal falarmos de algo legal? O que você mais gosta de fazer depois da escola?"
        d["browser.checking_page"] = "Verificando esta página para você..."
        d["blocked.hi_there"] = "Oi! 👋"
        d["blocked.find_something_else"] = "Vamos encontrar outra coisa!"
        d["blocked.friendly_1"] = "Desculpe, mas este conteúdo não está disponível agora. Vamos encontrar algo divertido para explorar juntos! 🌟"
        d["blocked.friendly_2"] = "Isso não é bem pra gente agora. Que tal procurarmos algo incrível? 💙"
        d["blocked.friendly_3"] = "Vamos pular esse e encontrar algo ainda melhor! Estou aqui para te ajudar a descobrir coisas legais! 🎈"
        d["blocked.friendly_4"] = "Este conteúdo não está disponível no momento. Quer explorar outra coisa juntos? 😊"

        // MARK: - Gate (parent approval)
        d["gate.title"] = "Conteúdo restrito"
        d["gate.riki_pause"] = "Riki sugere uma pausa"
        d["gate.touches_on"] = "Esta página aborda %@. Vamos verificar antes de continuar."
        d["gate.start_break"] = "Iniciar pausa consciente"
        d["gate.parent_approval"] = "Aprovação parental"
        d["gate.enter_pin"] = "Digite o PIN parental"
        d["gate.approve_continue"] = "Aprovar e continuar"
        d["gate.access_gated"] = "O acesso está restrito para %@ (%@)."
        d["gate.message"] = "Este conteúdo precisa de aprovação parental para acessar."

        // MARK: - Emoji Check-in
        d["checkin.how_feeling"] = "Como você está se sentindo explorando isso?"
        d["checkin.how_are_you"] = "Como você está se sentindo?"
        d["checkin.hi_there"] = "Oi! 👋"
        d["checkin.intro_message"] = "Sou o Komal, e estou aqui navegando na internet com você! Como você está se sentindo agora?"
        d["checkin.thanks_komal"] = "Obrigado, Komal! 😊"
        d["checkin.emotion.happy"] = "Feliz"
        d["checkin.emotion.okay"] = "De boa"
        d["checkin.emotion.sad"] = "Triste"
        d["checkin.emotion.tired"] = "Cansado"
        d["checkin.emotion.curious"] = "Curioso"
        d["checkin.emotion.excited"] = "Animado"
        d["checkin.response.happy"] = "Que maravilha! Fico muito feliz que você está se divertindo explorando! 🌟"
        d["checkin.response.okay"] = "Tudo bem! Se precisar de algo, estou aqui para ajudar! 💙"
        d["checkin.response.sad"] = "Sinto muito que você está se sentindo assim. Quer fazer uma pausa? 🫂"
        d["checkin.response.tired"] = "Tudo bem descansar! Talvez a gente possa explorar mais depois? 😴"
        d["checkin.response.curious"] = "Adoro sua curiosidade! Sobre o que você está curioso? 🤔"
        d["checkin.response.excited"] = "Que legal! Também estou animado para explorar com você! 🎉"

        // MARK: - Mindful Break
        d["mindful.title"] = "Pausa consciente"
        d["mindful.pause_message"] = "Faça uma pausa gentil. Perceba sua respiração e o ambiente ao seu redor."
        d["mindful.im_ready"] = "Estou pronto"

        // MARK: - Filter Preferences
        d["filter.content_settings"] = "Configurações de conteúdo"
        d["filter.customize"] = "Personalize qual conteúdo é permitido"
        d["filter.block"] = "Bloquear"
        d["filter.gate"] = "Restringir"
        d["filter.allow"] = "Permitir"

        // MARK: - Intervention
        d["intervention.tip"] = "Tudo bem ser curioso — é assim que a gente aprende!"
        d["intervention.lets_think"] = "Vamos pensar sobre isso..."
        d["intervention.share_thoughts"] = "Compartilhe seus pensamentos..."
        d["intervention.done_reflecting"] = "Terminei de refletir"
        d["intervention.lets_talk"] = "Vamos conversar sobre isso"
        d["intervention.go_back"] = "Voltar para a segurança"
        d["intervention.main.search"] = "Ei, notei que você pesquisou algo..."
        d["intervention.main.url"] = "Espera um momentinho!"
        d["intervention.main.image"] = "Encontrei algo sobre o qual devemos conversar"
        d["intervention.main.page"] = "Esta página tem conteúdo para adultos"
        d["intervention.sub.search"] = "Curiosidade é totalmente normal! Mas alguns assuntos são melhores para explorar com um adulto de confiança."
        d["intervention.sub.url"] = "Este site pode ter conteúdo feito para adultos. Quer conversar sobre o que você está procurando?"
        d["intervention.sub.image"] = "Notei algo que pode não ser apropriado. Vamos conversar sobre isso."
        d["intervention.sub.page"] = "Parte do que está aqui é para pessoas mais velhas. Quer conversar ou encontrar outra coisa?"
        d["intervention.reflect.search"] = "O que te deixou curioso sobre isso?"
        d["intervention.reflect.url"] = "O que você esperava encontrar?"
        d["intervention.reflect.image"] = "Como você se sentiu ao ver isso?"
        d["intervention.reflect.page"] = "Tem algo sobre o qual você tinha dúvidas?"

        // MARK: - Reflection Time
        d["reflect.welcome.title"] = "Bem-vindo ao momento de reflexão"
        d["reflect.welcome.subtitle"] = "15 minutos de bem-estar digital consciente"
        d["reflect.remaining"] = "restante"
        d["reflect.feelings.title"] = "Check-in de sentimentos"
        d["reflect.feelings.desc"] = "Explore e entenda suas emoções"
        d["reflect.mindfulness.title"] = "Exercício de mindfulness"
        d["reflect.mindfulness.desc"] = "Respiração calma e relaxamento"
        d["reflect.guided.title"] = "Reflexão guiada"
        d["reflect.guided.desc"] = "Pense sobre suas experiências digitais"
        d["reflect.free_chat.title"] = "Conversa livre"
        d["reflect.free_chat.desc"] = "Fale sobre qualquer coisa que estiver na sua mente"
        d["reflect.sel.title"] = "Como você está se sentindo?"
        d["reflect.sel.subtitle"] = "Tudo bem sentir qualquer emoção. Vamos explorar juntos."
        d["reflect.sel.intensity"] = "Quão forte é esse sentimento?"
        d["reflect.sel.a_little"] = "Um pouco"
        d["reflect.sel.a_lot"] = "Muito"
        d["reflect.sel.things_help"] = "Coisas que podem ajudar:"
        d["reflect.mindfulness.header"] = "Mindfulness"
        d["reflect.mindfulness.calm_mind"] = "Reserve um momento para acalmar sua mente"
        d["reflect.going_deeper"] = "Aprofundando..."
        d["reflect.thinking_followup"] = "Pensando em uma continuação..."
        d["reflect.previous"] = "Anterior"
        d["reflect.next"] = "Próximo"
        d["reflect.free_chat.placeholder"] = "Digite seus pensamentos..."
        d["reflect.free_chat.thinking"] = "Pensando..."
        d["reflect.completion.title"] = "Muito bem!"
        d["reflect.completion.subtitle"] = "Você completou seu momento de reflexão"
        d["reflect.completion.message"] = "Reservar tempo para refletir ajuda você a se entender melhor e a se manter saudável online."

        // MARK: - SEL Emotions
        d["reflect.emotion.okay"] = "De boa"

        // MARK: - Coping Strategies
        d["reflect.coping.sad.1"] = "Fale com alguém em quem confia"
        d["reflect.coping.sad.2"] = "Desenhe ou escreva sobre seus sentimentos"
        d["reflect.coping.sad.3"] = "Ouça sua música favorita"
        d["reflect.coping.sad.4"] = "Dê um abraço em si mesmo"
        d["reflect.coping.angry.1"] = "Faça 5 respirações profundas"
        d["reflect.coping.angry.2"] = "Conte de trás para frente a partir de 10"
        d["reflect.coping.angry.3"] = "Aperte uma bolinha antiestresse"
        d["reflect.coping.angry.4"] = "Dê uma caminhada curta"
        d["reflect.coping.worried.1"] = "Conte a um adulto como você se sente"
        d["reflect.coping.worried.2"] = "Pense em 3 coisas pelas quais é grato"
        d["reflect.coping.worried.3"] = "Imagine seu lugar feliz"
        d["reflect.coping.worried.4"] = "Respire devagar e fundo"
        d["reflect.coping.tired.1"] = "Descanse os olhos por um minuto"
        d["reflect.coping.tired.2"] = "Beba um pouco de água"
        d["reflect.coping.tired.3"] = "Alongue seu corpo"
        d["reflect.coping.tired.4"] = "Faça uma pausa das telas"
        d["reflect.coping.default.1"] = "Compartilhe seus sentimentos com alguém"
        d["reflect.coping.default.2"] = "Faça algo que você goste"
        d["reflect.coping.default.3"] = "Tire um momento consciente"
        d["reflect.coping.default.4"] = "Seja gentil consigo mesmo"

        // MARK: - Mindfulness Exercises
        d["reflect.exercise.box.title"] = "Respiração quadrada"
        d["reflect.exercise.box.desc"] = "Uma técnica calmante usada por atletas e astronautas"
        d["reflect.exercise.box.step1"] = "Inspire por 4 segundos"
        d["reflect.exercise.box.step2"] = "Segure por 4 segundos"
        d["reflect.exercise.box.step3"] = "Expire por 4 segundos"
        d["reflect.exercise.box.step4"] = "Segure por 4 segundos"
        d["reflect.exercise.box.step5"] = "Repita 4 vezes"
        d["reflect.exercise.grounding.title"] = "Aterramento 5-4-3-2-1"
        d["reflect.exercise.grounding.desc"] = "Conecte-se com o momento presente"
        d["reflect.exercise.grounding.step1"] = "Note 5 coisas que você pode VER"
        d["reflect.exercise.grounding.step2"] = "Note 4 coisas que você pode TOCAR"
        d["reflect.exercise.grounding.step3"] = "Note 3 coisas que você pode OUVIR"
        d["reflect.exercise.grounding.step4"] = "Note 2 coisas que você pode CHEIRAR"
        d["reflect.exercise.grounding.step5"] = "Note 1 coisa que você pode SENTIR O GOSTO"
        d["reflect.exercise.bodyscan.title"] = "Escaneamento corporal"
        d["reflect.exercise.bodyscan.desc"] = "Relaxe o corpo da cabeça aos pés"
        d["reflect.exercise.bodyscan.step1"] = "Relaxe a testa e os olhos"
        d["reflect.exercise.bodyscan.step2"] = "Relaxe o maxilar e os ombros"
        d["reflect.exercise.bodyscan.step3"] = "Relaxe os braços e as mãos"
        d["reflect.exercise.bodyscan.step4"] = "Relaxe a barriga"
        d["reflect.exercise.bodyscan.step5"] = "Relaxe as pernas e os pés"
        d["reflect.exercise.gratitude.title"] = "Momento de gratidão"
        d["reflect.exercise.gratitude.desc"] = "Foque nas coisas boas da vida"
        d["reflect.exercise.gratitude.step1"] = "Pense em alguém que te faz feliz"
        d["reflect.exercise.gratitude.step2"] = "Pense em algo em que você é bom"
        d["reflect.exercise.gratitude.step3"] = "Pense em um lugar que te faz sentir seguro"
        d["reflect.exercise.gratitude.step4"] = "Pense em uma lembrança feliz"
        d["reflect.exercise.gratitude.step5"] = "Sorria e sinta gratidão"
        d["reflect.breathe.inhale"] = "Inspire"
        d["reflect.breathe.hold"] = "Segure"
        d["reflect.breathe.exhale"] = "Expire"

        // MARK: - Reflection Questions
        d["reflect.q1.question"] = "Qual foi a melhor coisa que você viu online hoje?"
        d["reflect.q1.prompt"] = "Compartilhe algo que te fez sorrir ou se sentir bem..."
        d["reflect.q2.question"] = "Alguma coisa online te deixou desconfortável?"
        d["reflect.q2.prompt"] = "Tudo bem falar sobre coisas que te incomodaram..."
        d["reflect.q3.question"] = "O que você aprendeu hoje na internet?"
        d["reflect.q3.prompt"] = "Compartilhe algo interessante que você descobriu..."
        d["reflect.q4.question"] = "Quanto tempo você passou em telas hoje?"
        d["reflect.q4.prompt"] = "Foi muito, na medida certa ou pouco?"
        d["reflect.q5.question"] = "O que você gostaria de fazer offline amanhã?"
        d["reflect.q5.prompt"] = "Pense em atividades divertidas longe das telas..."

        // MARK: - Free Chat Greetings
        d["reflect.chat.greeting.1"] = "Oi! Este é um espaço seguro para compartilhar seus pensamentos. O que está na sua mente hoje?"
        d["reflect.chat.greeting.2"] = "E aí! Estou aqui para ouvir. Me conta algo interessante que aconteceu."
        d["reflect.chat.greeting.3"] = "Bem-vindo! Você pode falar sobre qualquer coisa aqui. Sobre o que gostaria de conversar?"
        d["reflect.chat.fallback.1"] = "Obrigado por compartilhar isso comigo. Como isso te faz sentir?"
        d["reflect.chat.fallback.2"] = "Entendo. Parece que isso é muito importante para você."
        d["reflect.chat.fallback.3"] = "Que bom que você está falando sobre isso. Me conta mais?"
        d["reflect.chat.fallback.4"] = "Eu entendo. Tudo bem se sentir assim."
        d["reflect.chat.fallback.5"] = "Obrigado por confiar em mim. O que mais está na sua mente?"

        // MARK: - Insights View
        d["insights.view.title"] = "Análises"
        d["insights.overview"] = "Visão geral"
        d["insights.sites_visited"] = "Sites visitados"
        d["insights.blocked"] = "Bloqueados"
        d["insights.gated"] = "Restritos"
        d["insights.sessions"] = "Sessões"
        d["insights.content_categories"] = "Categorias de conteúdo"
        d["insights.activity_timeline"] = "Linha do tempo de atividade"
        d["insights.recent_sessions"] = "Sessões recentes"
        d["insights.no_sessions"] = "Nenhuma sessão de navegação ainda"
        d["insights.protection_summary"] = "Resumo de proteção"
        d["insights.images_protected"] = "Imagens protegidas"
        d["insights.of_scanned"] = "de %d analisadas"
        d["insights.sites_blocked"] = "Sites bloqueados"
        d["insights.harmful_content"] = "conteúdo prejudicial"
        d["insights.engagement"] = "Engajamento"
        d["insights.avg_time_page"] = "Tempo médio por página"
        d["insights.avg_scroll_depth"] = "Profundidade média de rolagem"
        d["insights.meaningful_engagement"] = "Engajamento significativo"
        d["insights.most_engaged"] = "Sites mais acessados"
        d["insights.visits"] = "%d visitas"
        d["insights.avg_time"] = "tempo médio"
        d["insights.browsing_patterns"] = "Padrões de navegação"
        d["insights.session_depth"] = "Profundidade da sessão"
        d["insights.pages"] = "%d páginas"
        d["insights.how_deep"] = "Até onde navega nos sites"
        d["insights.back_navigation"] = "Navegação de retorno"
        d["insights.returning_pages"] = "Retornando a páginas anteriores"
        d["insights.quick_visits"] = "Visitas rápidas"
        d["insights.pages_under_10s"] = "Páginas vistas em menos de 10 segundos"
        d["insights.content_viewed"] = "Conteúdo visualizado"
        d["insights.words_read"] = "Palavras lidas"
        d["insights.images"] = "Imagens"
        d["insights.videos"] = "Vídeos"
        d["insights.topics"] = "Temas"
        d["insights.avg_time_short"] = "Tempo médio"
        d["insights.reading"] = "Leitura"
        d["insights.concerning_content"] = "Conteúdo preocupante detectado"
        d["insights.keywords"] = "Palavras-chave: %@"
        d["insights.found_on_pages"] = "Encontrado em %d página(s)"
        d["insights.recent_pages"] = "Páginas vistas recentemente"
        d["insights.topics_viewed"] = "Temas visualizados:"
        d["insights.flagged"] = "Sinalizado: %@"
        d["insights.avg_time_per_page"] = "Tempo médio por página"

        // MARK: - Anchor - Morning
        d["anchor.morning.title"] = "Bom dia!"
        d["anchor.morning.greeting"] = "Bom dia!"
        d["anchor.morning.subtitle"] = "Como você está se sentindo esta manhã?"
        d["anchor.morning.how_feeling"] = "Como você está se sentindo hoje?"
        d["anchor.morning.how_strong"] = "Quão forte é esse sentimento?"
        d["anchor.morning.set_intention"] = "Defina sua intenção para hoje"
        d["anchor.morning.looking_forward"] = "O que você está esperando para hoje?"
        d["anchor.morning.intention_placeholder"] = "Hoje eu quero..."
        d["anchor.morning.looking_forward_placeholder"] = "Algo divertido, uma aula, ver um amigo..."
        d["anchor.morning.ready"] = "Estou pronto para hoje!"
        d["anchor.morning.start_my_day"] = "Começar meu dia!"

        // MARK: - Anchor - Evening
        d["anchor.evening.title"] = "Reflexão noturna"
        d["anchor.evening.greeting"] = "Boa noite!"
        d["anchor.evening.subtitle"] = "Como foi seu dia?"
        d["anchor.evening.wind_down"] = "Vamos relaxar juntos"
        d["anchor.evening.how_feeling"] = "Como você está se sentindo esta noite?"
        d["anchor.evening.best_part"] = "Qual foi a melhor parte do seu dia?"
        d["anchor.evening.best_placeholder"] = "A melhor parte foi..."
        d["anchor.evening.best_part_placeholder"] = "Me conta sobre isso..."
        d["anchor.evening.anything_bothering"] = "Algo te incomodando?"
        d["anchor.evening.bothering_placeholder"] = "Tudo bem compartilhar..."
        d["anchor.evening.learned"] = "O que você aprendeu hoje?"
        d["anchor.evening.learned_placeholder"] = "Eu aprendi..."
        d["anchor.evening.deep_breaths"] = "Faça 3 respirações profundas"
        d["anchor.evening.breathe_in_out"] = "Inspire... e expire..."
        d["anchor.evening.goodnight"] = "Boa noite!"
        d["anchor.evening.good_night"] = "Boa noite!"

        // MARK: - Reconnection
        d["reconnection.title"] = "Bem-vindo de volta!"
        d["reconnection.welcome_back"] = "Bem-vindo de volta!"
        d["reconnection.subtitle"] = "Sentimos sua falta! Faz um tempo."
        d["reconnection.ellie_greeting"] = "É a Ellie! Eu nunca esqueço meus amigos, e estou tão feliz em te ver de novo!"
        d["reconnection.days_since"] = "Faz %d dias desde a última vez que ficamos juntos."
        d["reconnection.hi_ellie"] = "Oi Ellie!"
        d["reconnection.how_have_you_been"] = "Como você tem estado?"
        d["reconnection.mood_great"] = "Ótimo!"
        d["reconnection.mood_okay"] = "De boa"
        d["reconnection.mood_not_great"] = "Não muito bem"
        d["reconnection.response_great"] = "Que maravilha saber disso! Vamos manter essa energia boa."
        d["reconnection.response_not_great"] = "Sinto muito por isso. Lembre-se, estou sempre aqui por você."
        d["reconnection.response_okay"] = "Que bom saber! Vamos passar um tempo juntos e nos divertir."
        d["reconnection.what_to_do"] = "O que você gostaria de fazer?"
        d["reconnection.browse_web"] = "Navegar na internet"
        d["reconnection.chat_friend"] = "Conversar com um amigo"
        d["reconnection.reflection_time"] = "Momento de reflexão"
        d["reconnection.whats_new"] = "Veja o que há de novo desde sua última visita"
        d["reconnection.lets_go"] = "Vamos lá!"
        d["reconnection.missed_days"] = "Você ficou ausente por %d dias"

        // MARK: - Growth / Journey
        d["growth.title"] = "Minha jornada"
        d["growth.milestones"] = "Conquistas"
        d["growth.weekly_snapshot"] = "Resumo semanal"
        d["growth.noticed_about_you"] = "O que percebemos sobre você:"
        d["growth.day_streak"] = "Dias seguidos"
        d["growth.this_week"] = "Esta semana"
        d["growth.active_days"] = "Dias ativos"
        d["growth.chats"] = "Conversas"
        d["growth.reflections"] = "Reflexões"
        d["growth.moods"] = "Humores"
        d["growth.streak"] = "Sequência"
        d["growth.days"] = "dias"
        d["growth.level"] = "Nível"
        d["growth.explorer"] = "Explorador"
        d["growth.adventurer"] = "Aventureiro"
        d["growth.champion"] = "Campeão"
        d["growth.legend"] = "Lenda"
        d["growth.earned"] = "Conquistado!"
        d["growth.locked"] = "Continue assim!"
        d["growth.snapshot.title"] = "Sua semana em revisão"
        d["growth.snapshot.conversations"] = "Conversas"
        d["growth.snapshot.reflections"] = "Reflexões"
        d["growth.snapshot.browsing_time"] = "Tempo de navegação"
        d["growth.snapshot.mood_checks"] = "Verificações de humor"
        d["growth.snapshot.mood_checkins"] = "Check-ins de humor"
        d["growth.snapshot.most_common_mood"] = "Humor mais comum"
        d["growth.snapshot.favorite_friend"] = "Amigo favorito"
        d["growth.snapshot.growth_insight"] = "Percepção de crescimento"
        d["growth.snapshot.keep_going"] = "Continue assim!"

        // MARK: - Parent Insights
        d["insights.title"] = "Análises parentais"
        d["insights.wellness"] = "Visão geral do bem-estar"
        d["insights.mood_trends"] = "Tendências de humor"
        d["insights.chat_activity"] = "Atividade de chat"
        d["insights.browsing_summary"] = "Resumo de navegação"
        d["insights.alerts"] = "Alertas"
        d["insights.no_alerts"] = "Nenhum alerta para mostrar"
        d["insights.this_week"] = "Esta semana"
        d["insights.this_month"] = "Este mês"

        // MARK: - Parent Insights Dashboard
        d["insights.dashboard.title"] = "Bem-estar da criança"
        d["insights.dashboard.this_week_vs_last"] = "Esta semana vs anterior"
        d["insights.dashboard.chats"] = "Conversas"
        d["insights.dashboard.reflections"] = "Reflexões"
        d["insights.dashboard.moods"] = "Humores"
        d["insights.dashboard.active_days"] = "Dias ativos"
        d["insights.dashboard.conversation_starter"] = "Tema de conversa para esta noite"
        d["insights.dashboard.generating_starter"] = "Gerando um tema de conversa..."
        d["insights.dashboard.starter_placeholder"] = "Use o app por alguns dias para receber temas de conversa personalizados."
        d["insights.dashboard.daily_insight"] = "Percepção diária"
        d["insights.dashboard.generating_insight"] = "Gerando percepção..."
        d["insights.dashboard.insight_placeholder"] = "As percepções aparecerão conforme seu filho usar mais o app."
        d["insights.dashboard.emotional_wellness"] = "Bem-estar emocional"
        d["insights.dashboard.last_7_days"] = "Últimos 7 dias"
        d["insights.dashboard.emotion_distribution"] = "Distribuição emocional de 30 dias"
        d["insights.dashboard.no_mood_data"] = "Nenhum dado de humor ainda. As entradas de humor aparecerão aqui conforme seu filho usar o app."
        d["insights.dashboard.conversation_insights"] = "Percepções de conversas"
        d["insights.dashboard.messages"] = "Mensagens"
        d["insights.dashboard.characters_used"] = "Personagens usados"
        d["insights.dashboard.popular_topics"] = "Temas populares"
        d["insights.dashboard.growth_metrics"] = "Métricas de crescimento"
        d["insights.dashboard.current_streak"] = "Sequência atual"
        d["insights.dashboard.milestones"] = "Conquistas"
        d["insights.dashboard.active_days_30d"] = "Dias ativos (30d)"
        d["insights.dashboard.activity_30d"] = "Atividade de 30 dias"
        d["insights.dashboard.engagement_quality"] = "Qualidade de engajamento"
        d["insights.dashboard.voluntary_returns"] = "Retornos voluntários"
        d["insights.dashboard.avg_reflection_depth"] = "Profundidade média de reflexão"
        d["insights.dashboard.total_sessions"] = "Total de sessões"
        d["insights.dashboard.voluntary_returns_explanation"] = "Taxas mais altas de retorno voluntário indicam engajamento genuíno em vez de uso motivado por notificações."
        d["insights.dashboard.daily_checkins"] = "Check-ins diários"
        d["insights.dashboard.morning"] = "Manhã"
        d["insights.dashboard.evening"] = "Noite"
        d["insights.dashboard.wellness_alert"] = "Alerta de bem-estar"
        d["insights.dashboard.wellness_alert_message"] = "Seu filho relatou estar triste por 3 ou mais check-ins consecutivos. Considere ter uma conversa gentil sobre como ele está se sentindo."

        // MARK: - Browsing History
        d["history.title"] = "Histórico de navegação"
        d["history.loading"] = "Carregando histórico de navegação..."
        d["history.today"] = "Hoje"
        d["history.yesterday"] = "Ontem"
        d["history.earlier"] = "Anterior"
        d["history.no_history"] = "Nenhum histórico de navegação ainda"
        d["history.empty_message"] = "O histórico aparecerá aqui conforme seu filho navega."
        d["history.time_range"] = "Período"
        d["history.pages"] = "páginas"
        d["history.emoji_journey"] = "Jornada de emojis"
        d["history.summary"] = "Resumo"
        d["history.pages_visited"] = "Páginas visitadas"
        d["history.session_detail"] = "Detalhes da sessão"
        d["history.back_label"] = "Histórico"
        d["history.clear"] = "Limpar histórico"
        d["history.clear_confirm"] = "Tem certeza que deseja limpar todo o histórico de navegação?"

        // MARK: - Contextual Prompts
        d["prompt.welcome_back"] = "Bem-vindo de volta! Pronto para explorar?"
        d["prompt.take_break"] = "Você está navegando há um tempo. Que tal uma pausa?"
        d["prompt.try_reflect"] = "Que tal verificar como você está se sentindo?"
        d["prompt.chat_riki"] = "Quer conversar com um amigo?"
        d["prompt.new_milestone"] = "Você ganhou uma nova conquista!"
        d["prompt.dismiss"] = "Talvez depois"
        d["prompt.lets_go"] = "Vamos lá!"
        d["prompt.curiosity_noticed"] = "Notei algo interessante hoje... Quer saber o que é?"
        d["prompt.curiosity_learned"] = "Curioso sobre o que aprendi com você? Pode se surpreender!"
        d["prompt.curiosity_question_young"] = "Tenho uma pergunta super divertida pra você! Quer brincar?"
        d["prompt.growth_calm"] = "Você lidou com isso com calma. Como você fez?"
        d["prompt.growth_evolved"] = "Seu pensamento evoluiu muito. Quer ver o quanto avançou?"
        d["prompt.growth_proud_young"] = "Uau, você está ficando muito bom nisso! Estou muito orgulhoso de você!"
        d["prompt.growth_streak_celebrate"] = "Olha essa sequência! Você está construindo algo incrível, um dia de cada vez."
        d["prompt.brave_question"] = "Posso te fazer uma pergunta corajosa? Pode te surpreender."
        d["prompt.brave_future"] = "O que o você do futuro diria sobre hoje? Vamos descobrir."
        d["prompt.brave_try_young"] = "Quer tentar algo novo juntos? Eu acredito em você!"
        d["prompt.transition_reflect"] = "Uma reflexão rápida antes de ir? Só 2 minutinhos."
        d["prompt.transition_progress"] = "Quer ver seu mapa de progresso? Você esteve ocupado!"
        d["prompt.return_changed"] = "Algo pequeno mudou enquanto você estava fora. Quer ver?"
        d["prompt.return_secret"] = "Quer ver uma percepção secreta sobre você? Guardei pra você."
        d["prompt.return_missed_young"] = "Eba, você voltou! Senti sua falta! Quer brincar juntos?"
        d["prompt.emotional_check_negative"] = "Ei, percebi que talvez você esteja passando por um momento difícil. Estou aqui por você."
        d["prompt.emotional_celebrate_positive"] = "Parece que você está de bom humor! Que maravilha ver isso."
        d["prompt.browsing_learned"] = "Aprendeu algo legal navegando? Adoraria saber!"
        d["prompt.browsing_break"] = "Como você está se sentindo agora? Quer fazer um check-in rápido?"
        d["prompt.browsing_riddle_young"] = "Quer fazer uma pausa divertida? Tenho uma charada pra você!"
        d["prompt.reflect_done_great"] = "Essa foi uma reflexão muito boa. Você deveria ter orgulho de si mesmo."
        d["prompt.reflect_deeper_teen"] = "Boa reflexão. Quer ir um pouco mais fundo? Às vezes as melhores percepções vêm depois."
        d["prompt.action.tell_me"] = "Me conta!"
        d["prompt.action.show_me"] = "Me mostra"
        d["prompt.action.lets_play"] = "Vamos brincar!"
        d["prompt.action.let_me_think"] = "Deixa eu pensar..."
        d["prompt.action.show_my_growth"] = "Mostrar meu crescimento"
        d["prompt.action.see_my_journey"] = "Ver minha jornada"
        d["prompt.action.go_ahead"] = "Pode falar"
        d["prompt.action.lets_explore"] = "Vamos explorar"
        d["prompt.action.lets_try"] = "Vamos tentar!"
        d["prompt.action.sure"] = "Claro!"
        d["prompt.action.show_me_excited"] = "Me mostra!"
        d["prompt.action.what_changed"] = "O que mudou?"
        d["prompt.action.talk_about_it"] = "Falar sobre isso"
        d["prompt.action.lets_chat"] = "Vamos conversar"
        d["prompt.action.check_in"] = "Fazer check-in"
        d["prompt.action.go_deeper"] = "Aprofundar"

        // MARK: - Notifications
        d["notification.morning.title"] = "Bom dia!"
        d["notification.morning.body"] = "Momo aqui! Vamos começar seu dia com um check-in rápido. Como você está se sentindo?"
        d["notification.evening.title"] = "Hora de relaxar"
        d["notification.evening.body"] = "Ei, é a Bunny! Vamos reservar um momento para refletir sobre seu dia juntos."
        d["notification.reconnect.title"] = "Sentimos sua falta!"
        d["notification.reconnect.body"] = "Ellie aqui — eu nunca esqueço meus amigos! Volta pra dizer oi, tenho algo divertido pra compartilhar."
        d["notification.milestone.title"] = "Nova conquista!"
        d["notification.milestone.body"] = "Você ganhou uma nova conquista. Confira!"

        // MARK: - Mood History
        d["mood.history.title"] = "Histórico de humor"
        d["mood.history.recent"] = "Humores recentes"
        d["mood.history.no_entries"] = "Nenhuma entrada de humor ainda"
        d["mood.history.trend"] = "Sua tendência de humor"

        // MARK: - Scan Results
        d["scan.overall_safety_score"] = "Pontuação geral de segurança"
        d["scan.scanned"] = "Analisado"
        d["scan.live_analysis"] = "Análise ao vivo"
        d["scan.demo_mode"] = "Modo demonstração"
        d["scan.blocked_under_16"] = "Bloqueado para menores de 16"
        d["scan.out_of_100"] = "/100"
        d["scan.age_appropriate_actions"] = "Ações apropriadas para a idade"
        d["scan.score"] = "Pontuação"
        d["scan.safety_risks_detected"] = "Riscos de segurança detectados"
        d["scan.matches"] = "correspondências"
        d["scan.content_analysis"] = "Análise de conteúdo"
        d["scan.nlp_text_analysis"] = "Análise de texto NLP"
        d["scan.sentiment"] = "Sentimento:"
        d["scan.language_score"] = "Pontuação de linguagem:"
        d["scan.key_topics"] = "Temas principais:"
        d["scan.vision_ai_analysis"] = "Análise de IA visual"
        d["scan.visual_safety_score"] = "Pontuação de segurança visual:"
        d["scan.detected_objects"] = "Objetos detectados:"

        // MARK: - Screen Time
        d["screentime.minimal"] = "30 min/dia"
        d["screentime.moderate"] = "1-2 horas/dia"
        d["screentime.flexible"] = "Flexível"

        return d
    }()
}
// swiftlint:enable file_length type_body_length
