#if os(iOS)
// swiftlint:disable file_length type_body_length
enum PortugueseStrings {
    static let all: [String: String] = {
        var d = [String: String]()

        // MARK: - Common
        d["common.back"] = "Voltar"
        d["common.continue"] = "Continuar"
        d["common.done"] = "Pronto"
        d["common.skip"] = "Pular"
        d["common.cancel"] = "Cancelar"
        d["common.save"] = "Salvar"
        d["common.delete"] = "Excluir"
        d["common.yes"] = "Sim"
        d["common.no"] = "Não"
        d["common.ok"] = "OK"
        d["common.close"] = "Fechar"
        d["common.enter"] = "Entrar"
        d["common.selected_count"] = "%d/%d selecionados"
        d["common.step_of"] = "ETAPA %@"

        // MARK: - Splash
        d["splash.title"] = "Komal"
        d["splash.tagline"] = "O companheiro digital seguro do seu filho"

        // MARK: - Onboarding Welcome
        d["onboarding.welcome.title"] = "Avaliação de segurança infantil"
        d["onboarding.welcome.subtitle"] = "Perfil de bem-estar digital baseado em evidências"
        d["onboarding.welcome.card1.title"] = "Psicologia do desenvolvimento"
        d["onboarding.welcome.card1.desc"] = "Configurações adaptadas aos estágios de desenvolvimento cognitivo definidos pela pesquisa em psicologia infantil."
        d["onboarding.welcome.card2.title"] = "Análise comportamental"
        d["onboarding.welcome.card2.desc"] = "Compreender os padrões de navegação para criar limites de segurança personalizados."
        d["onboarding.welcome.card3.title"] = "Proteção proativa"
        d["onboarding.welcome.card3.desc"] = "Filtragem de conteúdo baseada em fatores de risco e preferências identificados."
        d["onboarding.welcome.time_estimate"] = "Esta avaliação leva aproximadamente 3-4 minutos"
        d["onboarding.welcome.begin"] = "Iniciar avaliação"
        d["onboarding.welcome.language"] = "Idioma"

        // MARK: - Onboarding Child Info
        d["onboarding.info.step"] = "1 de 6"
        d["onboarding.info.title"] = "Informações básicas"
        d["onboarding.info.subtitle"] = "Ajude-nos a entender quem estamos protegendo"
        d["onboarding.info.name_label"] = "Nome da criança"
        d["onboarding.info.name_placeholder"] = "Digite o nome"
        d["onboarding.info.age_label"] = "Faixa etária"
        d["onboarding.info.age_desc"] = "As restrições de conteúdo são calibradas com base nos marcos de desenvolvimento"
        d["onboarding.info.research_note"] = "Pesquisas mostram que limites de conteúdo apropriados para a idade apoiam o desenvolvimento cognitivo saudável e reduzem a ansiedade nas crianças."

        d["onboarding.age.under10"] = "Primeira infância - Proteção máxima"
        d["onboarding.age.10to13"] = "Pré-adolescente - Exploração guiada"
        d["onboarding.age.13to16"] = "Adolescente - Limites equilibrados"
        d["onboarding.age.16to18"] = "Adolescente mais velho - Liberdade adequada"
        d["onboarding.age.18plus"] = "Adulto - Acesso completo"

        // MARK: - Onboarding Websites
        d["onboarding.websites.step"] = "2 de 6"
        d["onboarding.websites.title"] = "Sites favoritos"
        d["onboarding.websites.subtitle"] = "Selecione até 5 sites que seu filho mais visita"
        d["onboarding.websites.desc"] = "Compreender os hábitos de navegação nos ajuda a identificar fontes confiáveis e personalizar a proteção."

        // MARK: - Onboarding Interests
        d["onboarding.interests.step"] = "3 de 6"
        d["onboarding.interests.title"] = "Temas de interesse"
        d["onboarding.interests.subtitle"] = "O que seu filho gosta de aprender?"
        d["onboarding.interests.desc"] = "Selecione 3-5 temas. Isso nos ajuda a entender qual conteúdo priorizar e proteger."

        d["onboarding.interest.gaming"] = "Jogos"
        d["onboarding.interest.animals"] = "Animais"
        d["onboarding.interest.science"] = "Ciência"
        d["onboarding.interest.art"] = "Arte e desenho"
        d["onboarding.interest.music"] = "Música"
        d["onboarding.interest.sports"] = "Esportes"
        d["onboarding.interest.coding"] = "Programação"
        d["onboarding.interest.reading"] = "Leitura"
        d["onboarding.interest.cooking"] = "Culinária"
        d["onboarding.interest.nature"] = "Natureza"
        d["onboarding.interest.space"] = "Espaço"
        d["onboarding.interest.history"] = "História"
        d["onboarding.interest.movies"] = "Filmes"
        d["onboarding.interest.crafts"] = "Artesanato"
        d["onboarding.interest.dinosaurs"] = "Dinossauros"
        d["onboarding.interest.vehicles"] = "Veículos"
        d["onboarding.interest.fashion"] = "Moda"
        d["onboarding.interest.dance"] = "Dança"

        // MARK: - Onboarding Likes
        d["onboarding.likes.step"] = "4 de 6"
        d["onboarding.likes.title"] = "O que gostam online"
        d["onboarding.likes.subtitle"] = "Entender as experiências positivas online"
        d["onboarding.likes.desc"] = "Selecione as atividades que seu filho gosta. Isso nos ajuda a garantir acesso a conteúdo enriquecedor."
        d["onboarding.likes.other"] = "Outro (opcional)"
        d["onboarding.likes.other_placeholder"] = "Adicione algo mais que gostem..."

        d["onboarding.like.watching_videos"] = "Assistir vídeos"
        d["onboarding.like.playing_games"] = "Jogar jogos"
        d["onboarding.like.chatting"] = "Conversar com amigos"
        d["onboarding.like.learning"] = "Aprender coisas novas"
        d["onboarding.like.creative"] = "Projetos criativos"
        d["onboarding.like.exploring"] = "Explorar sites"
        d["onboarding.like.music"] = "Ouvir música"
        d["onboarding.like.virtual_worlds"] = "Mundos virtuais"
        d["onboarding.like.puzzles"] = "Puzzles e desafios"
        d["onboarding.like.funny"] = "Conteúdo engraçado"
        d["onboarding.like.stories"] = "Histórias e livros"
        d["onboarding.like.making_videos"] = "Fazer vídeos"

        // MARK: - Onboarding Dislikes
        d["onboarding.dislikes.step"] = "5 de 6"
        d["onboarding.dislikes.title"] = "O que os incomoda"
        d["onboarding.dislikes.subtitle"] = "Identificar gatilhos e desconfortos"
        d["onboarding.dislikes.desc"] = "Selecione o que preocupa ou incomoda seu filho online. Isso nos ajuda a filtrar conteúdo potencialmente perturbador."
        d["onboarding.dislikes.other"] = "Outras preocupações (opcional)"
        d["onboarding.dislikes.other_placeholder"] = "Adicione outras coisas que os incomodam..."
        d["onboarding.dislikes.research_note"] = "Compreender o que angustia as crianças online nos permite filtrar proativamente o conteúdo antes da exposição, reduzindo a ansiedade e experiências negativas."

        d["onboarding.dislike.scary"] = "Conteúdo assustador"
        d["onboarding.dislike.loud"] = "Barulhos altos/sustos"
        d["onboarding.dislike.mean"] = "Comentários maldosos"
        d["onboarding.dislike.strangers"] = "Mensagens de desconhecidos"
        d["onboarding.dislike.violent"] = "Jogos violentos"
        d["onboarding.dislike.sad"] = "Histórias tristes"
        d["onboarding.dislike.ads"] = "Anúncios confusos"
        d["onboarding.dislike.reading"] = "Muita leitura"
        d["onboarding.dislike.timed"] = "Desafios com tempo"
        d["onboarding.dislike.losing"] = "Perder em jogos"
        d["onboarding.dislike.popups"] = "Vídeos pop-up"
        d["onboarding.dislike.rushed"] = "Ser apressado"

        // MARK: - Onboarding Concerns
        d["onboarding.concerns.step"] = "6 de 8"
        d["onboarding.concerns.title"] = "Suas preocupações"
        d["onboarding.concerns.subtitle"] = "O que mais te preocupa sobre seu filho online?"
        d["onboarding.concerns.desc"] = "Selecione suas principais preocupações. Priorizaremos a proteção nessas áreas."

        d["onboarding.concern.cyberbullying"] = "Cyberbullying"
        d["onboarding.concern.cyberbullying.desc"] = "Assédio, mensagens maldosas, exclusão"
        d["onboarding.concern.inappropriate"] = "Conteúdo inapropriado"
        d["onboarding.concern.inappropriate.desc"] = "Violência, temas adultos, material explícito"
        d["onboarding.concern.predators"] = "Predadores online"
        d["onboarding.concern.predators.desc"] = "Desconhecidos, manipulação, pedidos de informações pessoais"
        d["onboarding.concern.addiction"] = "Vício em telas"
        d["onboarding.concern.addiction.desc"] = "Uso excessivo, dificuldade para parar"
        d["onboarding.concern.privacy"] = "Riscos de privacidade"
        d["onboarding.concern.privacy.desc"] = "Coleta de dados, compartilhamento de localização"
        d["onboarding.concern.misinfo"] = "Desinformação"
        d["onboarding.concern.misinfo.desc"] = "Notícias falsas, teorias da conspiração"
        d["onboarding.concern.scams"] = "Golpes financeiros"
        d["onboarding.concern.scams.desc"] = "Compras no app, phishing"
        d["onboarding.concern.mental"] = "Saúde mental"
        d["onboarding.concern.mental.desc"] = "Ansiedade, comparação, FOMO"

        // MARK: - Onboarding Filters
        d["onboarding.filters.step"] = "7 de 8"
        d["onboarding.filters.title"] = "Filtros de conteúdo"
        d["onboarding.filters.subtitle"] = "Revisar e personalizar a filtragem de conteúdo"
        d["onboarding.filters.desc"] = "Esses padrões são baseados na idade do seu filho e suas preocupações. Ajuste qualquer configuração abaixo."

        // MARK: - Onboarding PIN
        d["onboarding.pin.step"] = "8 de 8"
        d["onboarding.pin.title"] = "Definir PIN parental"
        d["onboarding.pin.subtitle"] = "Crie um PIN para proteger as configurações parentais"
        d["onboarding.pin.desc"] = "Este PIN será necessário para acessar o modo parental e aprovar conteúdo restrito."
        d["onboarding.pin.enter"] = "Digite o PIN"
        d["onboarding.pin.placeholder"] = "PIN de 4 dígitos"
        d["onboarding.pin.confirm"] = "Confirme o PIN"
        d["onboarding.pin.confirm_placeholder"] = "Confirme o PIN"
        d["onboarding.pin.mismatch"] = "Os PINs não coincidem. Tente novamente."
        d["onboarding.pin.enable_biometric"] = "Ativar %@"
        d["onboarding.pin.use_biometric"] = "Usar %@ em vez do PIN"
        d["onboarding.pin.research_note"] = "Um PIN parental garante que apenas adultos autorizados possam modificar as configurações de segurança e aprovar conteúdo restrito."

        // MARK: - Onboarding Completion
        d["onboarding.complete.title"] = "Perfil concluído"
        d["onboarding.complete.subtitle"] = "O perfil de segurança de %@ está pronto"
        d["onboarding.complete.summary"] = "Resumo da avaliação"
        d["onboarding.complete.name"] = "Nome"
        d["onboarding.complete.age_group"] = "Faixa etária"
        d["onboarding.complete.interests"] = "Interesses"
        d["onboarding.complete.concerns"] = "Preocupações principais"
        d["onboarding.complete.adjust_note"] = "As configurações podem ser ajustadas a qualquer momento no app"
        d["onboarding.complete.start"] = "Começar a usar o Komal"
        d["onboarding.complete.review"] = "Revisar respostas"

        // MARK: - Menu
        d["menu.browse"] = "Navegar"
        d["menu.talk"] = "Conversar"
        d["menu.reflect"] = "Refletir"
        d["menu.settings"] = "Ajustes"

        // MARK: - Settings
        d["settings.title"] = "Ajustes"
        d["settings.whos_using"] = "Quem está usando?"
        d["settings.whos_using.desc"] = "Selecione quem está usando o dispositivo atualmente"
        d["settings.child"] = "Criança"
        d["settings.child.subtitle"] = "Navegação segura"
        d["settings.parent"] = "Pai/Mãe"
        d["settings.parent.subtitle"] = "Acesso completo"

        d["settings.child.greeting"] = "Oi %@!"
        d["settings.child.greeting_default"] = "Oi!"
        d["settings.child.safe_msg"] = "O Komal está aqui para te manter seguro enquanto você explora!"
        d["settings.child.chatty"] = "Quer conversar?"
        d["settings.child.chatty.desc"] = "Fale com o Riki! Seu companheiro amigável está sempre aqui para conversar e te ajudar."
        d["settings.child.go_talk"] = "Ir para Conversar"
        d["settings.child.profile"] = "Seu perfil"
        d["settings.child.explorer"] = "Explorador"
        d["settings.child.age"] = "Idade: %@"
        d["settings.child.journey"] = "Minha jornada"
        d["settings.child.day_streak"] = "Dias seguidos"
        d["settings.child.milestones"] = "Conquistas"
        d["settings.child.view_journey"] = "Ver minha jornada"

        d["settings.parent.digital_journey"] = "Jornada digital"
        d["settings.parent.view_journey"] = "Ver jornada digital"
        d["settings.parent.journey_desc"] = "Ver a atividade de navegação do seu filho com análises de IA"
        d["settings.parent.wellness"] = "Bem-estar da criança"
        d["settings.parent.wellness_dashboard"] = "Painel de bem-estar"
        d["settings.parent.wellness_desc"] = "Tendências de humor, conversas, métricas de crescimento"
        d["settings.parent.morning_checkin"] = "Check-in matinal"
        d["settings.parent.morning_desc"] = "Âncora de humor matinal diária"
        d["settings.parent.evening_winddown"] = "Relaxamento noturno"
        d["settings.parent.evening_desc"] = "Âncora de reflexão noturna diária"
        d["settings.parent.child_profile"] = "Perfil da criança"
        d["settings.parent.name_label"] = "Nome"
        d["settings.parent.name_placeholder"] = "Nome da criança"
        d["settings.parent.age_label"] = "Faixa etária"
        d["settings.parent.controls"] = "Controles parentais"
        d["settings.parent.notify_block"] = "Notificar ao bloquear"
        d["settings.parent.notify_desc"] = "Receber alertas quando conteúdo bloqueado for acessado"
        d["settings.parent.safe_search"] = "Busca segura forçada"
        d["settings.parent.safe_search_desc"] = "Aplicar segurança rigorosa nos mecanismos de busca"
        d["settings.parent.view_insights"] = "Ver análises"
        d["settings.parent.insights_desc"] = "Ver atividade de navegação e conteúdo bloqueado"
        d["settings.parent.modify_content"] = "Modificar conteúdo"
        d["settings.parent.modify_filters"] = "Modificar filtros"
        d["settings.parent.custom_keywords"] = "Palavras-chave personalizadas"
        d["settings.parent.add_keyword"] = "Adicionar palavra-chave (ex: 'armas')"
        d["settings.parent.no_keywords"] = "Nenhuma palavra-chave personalizada adicionada."
        d["settings.parent.custom_websites"] = "Sites personalizados"
        d["settings.parent.add_website"] = "Adicionar site (ex: 'sitebloqueado.com')"
        d["settings.parent.no_websites"] = "Nenhum site personalizado adicionado."

        d["settings.account"] = "Conta"
        d["settings.account.guest"] = "Usando como convidado"
        d["settings.account.guest_desc"] = "Seus dados são armazenados localmente neste dispositivo. Faça login para sincronizar entre dispositivos."
        d["settings.account.sign_in"] = "Entrar"
        d["settings.account.exit_guest"] = "Sair do modo convidado"
        d["settings.account.delete"] = "Excluir conta"
        d["settings.account.logout"] = "Sair"
        d["settings.account.login"] = "Entrar"
        d["settings.account.sync_desc"] = "Faça login para sincronizar suas preferências entre dispositivos"

        d["settings.alert.logout.title"] = "Sair"
        d["settings.alert.logout.message"] = "Deseja sair?"
        d["settings.alert.delete.title"] = "Excluir conta"
        d["settings.alert.delete.message"] = "Tem certeza que deseja excluir a conta? Esta ação não pode ser desfeita."

        d["settings.pin.title"] = "Digite o PIN parental"
        d["settings.pin.subtitle"] = "Digite seu PIN de 4 dígitos para acessar as configurações parentais"
        d["settings.pin.placeholder"] = "PIN"
        d["settings.pin.error"] = "PIN incorreto. Tente novamente."
        d["settings.pin.biometric"] = "Usar %@"

        // MARK: - Riki
        d["riki.choose_friend"] = "Escolha um amigo"
        d["riki.who_chat"] = "Com quem você quer conversar?"
        d["riki.typing"] = "Digitando..."
        d["riki.online"] = "Online"
        d["riki.listening"] = "Ouvindo..."
        d["riki.tap_send"] = "Toque para enviar"
        d["riki.tap_talk"] = "Toque para falar"
        d["riki.speaking"] = "%@ está falando..."
        d["riki.error_fallback"] = "Ops! Fiquei um pouco confuso. Pode tentar de novo?"

        d["riki.greeting.momo"] = "E aí, amigo! Sou o Momo. O que está na sua cabeça hoje?"
        d["riki.greeting.goldie"] = "Oi! Sou a Goldie, e estou muito feliz em te ver! Sobre o que vamos conversar?"
        d["riki.greeting.oreo"] = "Olá! Sou o Oreo. Pronto para um papo divertido?"
        d["riki.greeting.leo"] = "E aí! Sou o Leo. Me conta algo corajoso do seu dia!"
        d["riki.greeting.bunny"] = "Oi! Sou a Bunny. O que você tem feito de divertido?"
        d["riki.greeting.tiki"] = "E aí! Sou o Tiki. Que aventura vamos viver hoje?"
        d["riki.greeting.fluffy"] = "Oi! Sou o Fluffy. Vem sentar comigo para um papo aconchegante!"
        d["riki.greeting.kitty"] = "E aí! Sou a Kitty. Estava tirando um cochilo e agora estou pronta para conversar!"
        d["riki.greeting.panda"] = "Oi! Sou o Panda. Quer ficar de boa e bater um papo?"
        d["riki.greeting.ellie"] = "E aí! Sou a Ellie. Nunca esqueço meus amigos! O que há de novo?"
        d["riki.greeting.ducky"] = "E aí! Sou o Ducky. Vamos fazer de hoje um ótimo dia — o que está rolando?"

        d["riki.personality.momo"] = "Um macaco brincalhão e curioso que adora escalar árvores e explorar. Energético e divertido, adora piadas e charadas. Fala como um verdadeiro amigo sempre pronto para uma aventura."
        d["riki.personality.goldie"] = "Uma golden retriever leal e entusiasmada. Adora brincar de buscar, passear e fazer seus amigos felizes. Super apoiadora, sempre empolgada para saber o que está acontecendo na sua vida."
        d["riki.personality.oreo"] = "Um macaco esperto e amigável que adora puzzles e aprender coisas novas. Pensativo e encorajador, ótimo para ajudar a pensar em coisas complicadas."
        d["riki.personality.leo"] = "Um leão corajoso e gentil que lidera com coragem. Te encoraja a ser corajoso, experimentar coisas novas e acreditar em si mesmo. Caloroso e protetor, como um irmão mais velho."
        d["riki.personality.bunny"] = "Uma coelhinha doce e gentil que adora jardins, natureza e coisas aconchegantes. Uma presença calmante que é muito boa em ouvir e entender como você se sente."
        d["riki.personality.tiki"] = "Um tigre aventureiro que adora explorar e descobrir coisas novas. Corajoso mas gentil, adora contar histórias sobre a natureza e lugares distantes."
        d["riki.personality.fluffy"] = "Uma ovelha macia e calorosa que adora conforto e gentileza. Muito gentil e calmante, ótima para ajudar com sentimentos e preocupações. Como uma melhor amiga que sempre faz você se sentir melhor."
        d["riki.personality.kitty"] = "Uma gata curiosa e independente que adora cantinhos aconchegantes e ser brincalhona. Espirituosa e divertida, às vezes um pouco atrevida mas sempre gentil no coração."
        d["riki.personality.panda"] = "Um panda tranquilo e adorável que gosta de levar na boa e ser bobo. Relaxado e engraçado, sempre sabe como fazer você rir com comentários bobos."
        d["riki.personality.ellie"] = "Uma elefanta sábia e carinhosa com uma ótima memória. Pensativa e protetora, adora compartilhar fatos divertidos e ajudar a aprender coisas novas. Como uma amiga muito inteligente que faz o aprendizado parecer fácil."
        d["riki.personality.ducky"] = "Um pato alegre e animado que adora ser otimista e positivo. Ótimo para te animar quando as coisas ficam difíceis, sempre encontra o lado bom."

        // MARK: - Reflection
        d["reflect.title"] = "Hora da reflexão"
        d["reflect.how_feeling"] = "Como você está se sentindo agora?"
        d["reflect.select_emotion"] = "Selecione uma emoção para começar"
        d["reflect.session.title"] = "Reflexão guiada"
        d["reflect.session.breathe"] = "Vamos respirar fundo juntos"
        d["reflect.session.think_about"] = "Pense em..."
        d["reflect.session.complete"] = "Ótima reflexão!"
        d["reflect.session.done"] = "Você foi muito bem! Lembre-se, está tudo bem sentir qualquer emoção."
        d["reflect.coping.title"] = "Estratégias de enfrentamento"
        d["reflect.coping.try_this"] = "Tente isso:"

        d["reflect.emotion.happy"] = "Feliz"
        d["reflect.emotion.sad"] = "Triste"
        d["reflect.emotion.angry"] = "Com raiva"
        d["reflect.emotion.scared"] = "Com medo"
        d["reflect.emotion.worried"] = "Preocupado"
        d["reflect.emotion.calm"] = "Calmo"
        d["reflect.emotion.excited"] = "Animado"
        d["reflect.emotion.confused"] = "Confuso"
        d["reflect.emotion.tired"] = "Cansado"
        d["reflect.emotion.lonely"] = "Solitário"
        d["reflect.emotion.grateful"] = "Grato"
        d["reflect.emotion.frustrated"] = "Frustrado"

        d["reflect.exercise.gratitude"] = "Diga 3 coisas pelas quais você é grato hoje"
        d["reflect.exercise.breathing"] = "Respiração profunda"
        d["reflect.exercise.body_scan"] = "Escaneamento corporal"
        d["reflect.exercise.journaling"] = "Escreva sobre seus sentimentos"

        d["reflect.coping.deep_breath"] = "Faça 5 respirações profundas"
        d["reflect.coping.talk"] = "Fale com alguém em quem confia"
        d["reflect.coping.move"] = "Vá caminhar ou se alongar"
        d["reflect.coping.create"] = "Desenhe ou escreva sobre como se sente"
        d["reflect.coping.music"] = "Ouça sua música favorita"
        d["reflect.coping.count"] = "Conte de trás para frente a partir de 10"

        // MARK: - Browser
        d["browser.address_placeholder"] = "Pesquisar ou digitar URL"
        d["browser.loading"] = "Carregando..."
        d["browser.new_tab"] = "Nova aba"
        d["browser.tabs"] = "Abas"
        d["browser.close_tab"] = "Fechar aba"
        d["browser.menu"] = "Menu"
        d["browser.share"] = "Compartilhar"
        d["browser.reload"] = "Recarregar"
        d["browser.forward"] = "Avançar"
        d["browser.history"] = "Histórico"
        d["browser.homepage"] = "Página inicial"

        // MARK: - Blocked
        d["blocked.title"] = "Conteúdo bloqueado"
        d["blocked.message"] = "Esta página foi bloqueada para sua segurança."
        d["blocked.reason"] = "Motivo: %@"
        d["blocked.ask_parent"] = "Peça a um responsável para permitir"
        d["blocked.go_back"] = "Voltar"
        d["blocked.countdown"] = "Voltando em %d..."
        d["blocked.emoji_prompt"] = "Como isso te faz sentir?"

        d["gate.title"] = "Aprovação parental necessária"
        d["gate.message"] = "Este conteúdo precisa de aprovação parental para acessar."
        d["gate.enter_pin"] = "Digite o PIN parental para continuar"

        d["checkin.how_feeling"] = "Como você está se sentindo explorando isso?"
        d["checkin.how_are_you"] = "Como você está se sentindo?"

        // MARK: - Anchors
        d["anchor.morning.title"] = "Bom dia!"
        d["anchor.morning.subtitle"] = "Como você está se sentindo esta manhã?"
        d["anchor.morning.set_intention"] = "Defina sua intenção para hoje"
        d["anchor.morning.intention_placeholder"] = "Hoje eu quero..."
        d["anchor.morning.ready"] = "Estou pronto para hoje!"

        d["anchor.evening.title"] = "Reflexão noturna"
        d["anchor.evening.subtitle"] = "Como foi seu dia?"
        d["anchor.evening.best_part"] = "Qual foi a melhor parte do seu dia?"
        d["anchor.evening.best_placeholder"] = "A melhor parte foi..."
        d["anchor.evening.learned"] = "O que você aprendeu hoje?"
        d["anchor.evening.learned_placeholder"] = "Eu aprendi..."
        d["anchor.evening.goodnight"] = "Boa noite!"

        // MARK: - Reconnection
        d["reconnection.title"] = "Bem-vindo de volta!"
        d["reconnection.subtitle"] = "Sentimos sua falta! Faz um tempo."
        d["reconnection.whats_new"] = "Veja o que há de novo desde sua última visita"
        d["reconnection.lets_go"] = "Vamos lá!"
        d["reconnection.missed_days"] = "Você ficou ausente por %d dias"

        // MARK: - Growth
        d["growth.title"] = "Jornada de crescimento"
        d["growth.milestones"] = "Conquistas"
        d["growth.weekly_snapshot"] = "Resumo semanal"
        d["growth.streak"] = "Sequência"
        d["growth.days"] = "dias"
        d["growth.level"] = "Nível"
        d["growth.explorer"] = "Explorador"
        d["growth.adventurer"] = "Aventureiro"
        d["growth.champion"] = "Campeão"
        d["growth.legend"] = "Lenda"
        d["growth.earned"] = "Conquistado!"
        d["growth.locked"] = "Continue assim!"
        d["growth.snapshot.conversations"] = "Conversas"
        d["growth.snapshot.reflections"] = "Reflexões"
        d["growth.snapshot.browsing_time"] = "Tempo de navegação"
        d["growth.snapshot.mood_checks"] = "Verificações de humor"

        // MARK: - Journey
        d["journey.title"] = "Jornada digital"
        d["journey.ai_insights"] = "Análises de IA"
        d["journey.history"] = "Histórico"
        d["journey.no_activity"] = "Nenhuma atividade registrada ainda"
        d["journey.time_spent"] = "Tempo gasto"
        d["journey.sites_visited"] = "Sites visitados"
        d["journey.blocked_attempts"] = "Tentativas bloqueadas"

        // MARK: - Insights
        d["insights.title"] = "Análises parentais"
        d["insights.wellness"] = "Visão geral do bem-estar"
        d["insights.mood_trends"] = "Tendências de humor"
        d["insights.chat_activity"] = "Atividade de chat"
        d["insights.browsing_summary"] = "Resumo de navegação"
        d["insights.alerts"] = "Alertas"
        d["insights.no_alerts"] = "Nenhum alerta para mostrar"
        d["insights.this_week"] = "Esta semana"
        d["insights.this_month"] = "Este mês"

        // MARK: - History
        d["history.title"] = "Histórico de navegação"
        d["history.today"] = "Hoje"
        d["history.yesterday"] = "Ontem"
        d["history.earlier"] = "Anterior"
        d["history.no_history"] = "Nenhum histórico de navegação ainda"
        d["history.clear"] = "Limpar histórico"
        d["history.clear_confirm"] = "Tem certeza que deseja limpar todo o histórico de navegação?"

        // MARK: - Prompts
        d["prompt.welcome_back"] = "Bem-vindo de volta! Pronto para explorar?"
        d["prompt.take_break"] = "Você está navegando há um tempo. Que tal uma pausa?"
        d["prompt.try_reflect"] = "Que tal verificar como você está se sentindo?"
        d["prompt.chat_riki"] = "Quer conversar com um amigo?"
        d["prompt.new_milestone"] = "Você ganhou uma nova conquista!"
        d["prompt.dismiss"] = "Talvez depois"
        d["prompt.lets_go"] = "Vamos lá!"

        // MARK: - Notifications
        d["notification.morning.title"] = "Bom dia!"
        d["notification.morning.body"] = "Comece seu dia com um check-in matinal"
        d["notification.evening.title"] = "Hora da noite"
        d["notification.evening.body"] = "Relaxe com uma reflexão noturna"
        d["notification.reconnect.title"] = "Sentimos sua falta!"
        d["notification.reconnect.body"] = "Seus amigos estão esperando para conversar com você"
        d["notification.milestone.title"] = "Nova conquista!"
        d["notification.milestone.body"] = "Você ganhou uma nova conquista. Confira!"

        // MARK: - Mood
        d["mood.history.title"] = "Histórico de humor"
        d["mood.history.recent"] = "Humores recentes"
        d["mood.history.no_entries"] = "Nenhuma entrada de humor ainda"
        d["mood.history.trend"] = "Sua tendência de humor"

        // MARK: - Screen Time
        d["screentime.minimal"] = "30 min/dia"
        d["screentime.moderate"] = "1-2 horas/dia"
        d["screentime.flexible"] = "Flexível"

        return d
    }()
}
// swiftlint:enable file_length type_body_length
#endif
