#if os(iOS)
// swiftlint:disable file_length type_body_length
enum SpanishStrings {
    static let all: [String: String] = {
        var d = [String: String]()

        // MARK: - Common
        d["common.back"] = "Atrás"
        d["common.continue"] = "Continuar"
        d["common.done"] = "Listo"
        d["common.skip"] = "Omitir"
        d["common.cancel"] = "Cancelar"
        d["common.save"] = "Guardar"
        d["common.delete"] = "Eliminar"
        d["common.yes"] = "Sí"
        d["common.no"] = "No"
        d["common.ok"] = "OK"
        d["common.close"] = "Cerrar"
        d["common.enter"] = "Entrar"
        d["common.selected_count"] = "%d/%d seleccionados"
        d["common.step_of"] = "PASO %@"

        // MARK: - Splash
        d["splash.title"] = "Komal"
        d["splash.tagline"] = "El compañero digital seguro de tu hijo"

        // MARK: - Onboarding Welcome
        d["onboarding.welcome.title"] = "Evaluación de seguridad infantil"
        d["onboarding.welcome.subtitle"] = "Perfil de bienestar digital basado en evidencia"
        d["onboarding.welcome.card1.title"] = "Psicología del desarrollo"
        d["onboarding.welcome.card1.desc"] = "Configuraciones adaptadas a las etapas de desarrollo cognitivo definidas por la investigación en psicología infantil."
        d["onboarding.welcome.card2.title"] = "Análisis conductual"
        d["onboarding.welcome.card2.desc"] = "Comprender los patrones de navegación para crear límites de seguridad personalizados."
        d["onboarding.welcome.card3.title"] = "Protección proactiva"
        d["onboarding.welcome.card3.desc"] = "Filtrado de contenido basado en factores de riesgo y preferencias identificados."
        d["onboarding.welcome.time_estimate"] = "Esta evaluación toma aproximadamente 3-4 minutos"
        d["onboarding.welcome.begin"] = "Comenzar evaluación"
        d["onboarding.welcome.language"] = "Idioma"

        // MARK: - Onboarding Child Info
        d["onboarding.info.step"] = "1 de 6"
        d["onboarding.info.title"] = "Información básica"
        d["onboarding.info.subtitle"] = "Ayúdanos a entender a quién protegemos"
        d["onboarding.info.name_label"] = "Nombre del niño"
        d["onboarding.info.name_placeholder"] = "Ingresa el nombre"
        d["onboarding.info.age_label"] = "Grupo de edad"
        d["onboarding.info.age_desc"] = "Las restricciones de contenido se calibran según las etapas de desarrollo"
        d["onboarding.info.research_note"] = "La investigación muestra que los límites de contenido apropiados para la edad favorecen un desarrollo cognitivo saludable y reducen la ansiedad en los niños."

        d["onboarding.age.under10"] = "Primera infancia - Protección máxima"
        d["onboarding.age.10to13"] = "Preadolescente - Exploración guiada"
        d["onboarding.age.13to16"] = "Adolescente - Límites equilibrados"
        d["onboarding.age.16to18"] = "Adolescente mayor - Libertad apropiada"
        d["onboarding.age.18plus"] = "Adulto - Acceso completo"

        // MARK: - Onboarding Websites
        d["onboarding.websites.step"] = "2 de 6"
        d["onboarding.websites.title"] = "Sitios web favoritos"
        d["onboarding.websites.subtitle"] = "Selecciona hasta 5 sitios que tu hijo visita más"
        d["onboarding.websites.desc"] = "Comprender los hábitos de navegación nos ayuda a identificar fuentes confiables y personalizar la protección."

        // MARK: - Onboarding Interests
        d["onboarding.interests.step"] = "3 de 6"
        d["onboarding.interests.title"] = "Temas de interés"
        d["onboarding.interests.subtitle"] = "¿Qué le gusta aprender a tu hijo?"
        d["onboarding.interests.desc"] = "Selecciona 3-5 temas. Esto nos ayuda a entender qué contenido priorizar y proteger."

        d["onboarding.interest.gaming"] = "Videojuegos"
        d["onboarding.interest.animals"] = "Animales"
        d["onboarding.interest.science"] = "Ciencia"
        d["onboarding.interest.art"] = "Arte y dibujo"
        d["onboarding.interest.music"] = "Música"
        d["onboarding.interest.sports"] = "Deportes"
        d["onboarding.interest.coding"] = "Programación"
        d["onboarding.interest.reading"] = "Lectura"
        d["onboarding.interest.cooking"] = "Cocina"
        d["onboarding.interest.nature"] = "Naturaleza"
        d["onboarding.interest.space"] = "Espacio"
        d["onboarding.interest.history"] = "Historia"
        d["onboarding.interest.movies"] = "Películas"
        d["onboarding.interest.crafts"] = "Manualidades"
        d["onboarding.interest.dinosaurs"] = "Dinosaurios"
        d["onboarding.interest.vehicles"] = "Vehículos"
        d["onboarding.interest.fashion"] = "Moda"
        d["onboarding.interest.dance"] = "Baile"

        // MARK: - Onboarding Likes
        d["onboarding.likes.step"] = "4 de 6"
        d["onboarding.likes.title"] = "Lo que disfrutan en línea"
        d["onboarding.likes.subtitle"] = "Entender las experiencias positivas en línea"
        d["onboarding.likes.desc"] = "Selecciona las actividades que tu hijo disfruta. Esto nos ayuda a garantizar el acceso a contenido enriquecedor."
        d["onboarding.likes.other"] = "Otro (opcional)"
        d["onboarding.likes.other_placeholder"] = "Agrega algo más que disfruten..."

        d["onboarding.like.watching_videos"] = "Ver videos"
        d["onboarding.like.playing_games"] = "Jugar videojuegos"
        d["onboarding.like.chatting"] = "Chatear con amigos"
        d["onboarding.like.learning"] = "Aprender cosas nuevas"
        d["onboarding.like.creative"] = "Proyectos creativos"
        d["onboarding.like.exploring"] = "Explorar sitios web"
        d["onboarding.like.music"] = "Escuchar música"
        d["onboarding.like.virtual_worlds"] = "Mundos virtuales"
        d["onboarding.like.puzzles"] = "Puzzles y desafíos"
        d["onboarding.like.funny"] = "Contenido divertido"
        d["onboarding.like.stories"] = "Historias y libros"
        d["onboarding.like.making_videos"] = "Hacer videos"

        // MARK: - Onboarding Dislikes
        d["onboarding.dislikes.step"] = "5 de 6"
        d["onboarding.dislikes.title"] = "Lo que les molesta"
        d["onboarding.dislikes.subtitle"] = "Identificar detonantes e incomodidades"
        d["onboarding.dislikes.desc"] = "Selecciona lo que preocupa o molesta a tu hijo en línea. Esto nos ayuda a filtrar contenido potencialmente perturbador."
        d["onboarding.dislikes.other"] = "Otras preocupaciones (opcional)"
        d["onboarding.dislikes.other_placeholder"] = "Agrega otras cosas que les molesten..."
        d["onboarding.dislikes.research_note"] = "Comprender lo que angustia a los niños en línea nos permite filtrar proactivamente el contenido antes de la exposición, reduciendo la ansiedad y las experiencias negativas."

        d["onboarding.dislike.scary"] = "Contenido aterrador"
        d["onboarding.dislike.loud"] = "Ruidos fuertes/sustos"
        d["onboarding.dislike.mean"] = "Comentarios crueles"
        d["onboarding.dislike.strangers"] = "Mensajes de desconocidos"
        d["onboarding.dislike.violent"] = "Juegos violentos"
        d["onboarding.dislike.sad"] = "Historias tristes"
        d["onboarding.dislike.ads"] = "Anuncios confusos"
        d["onboarding.dislike.reading"] = "Demasiada lectura"
        d["onboarding.dislike.timed"] = "Desafíos con tiempo"
        d["onboarding.dislike.losing"] = "Perder en juegos"
        d["onboarding.dislike.popups"] = "Videos emergentes"
        d["onboarding.dislike.rushed"] = "Ser apresurado"

        // MARK: - Onboarding Concerns
        d["onboarding.concerns.step"] = "6 de 8"
        d["onboarding.concerns.title"] = "Tus preocupaciones"
        d["onboarding.concerns.subtitle"] = "¿Qué te preocupa más sobre tu hijo en línea?"
        d["onboarding.concerns.desc"] = "Selecciona tus principales preocupaciones. Priorizaremos la protección en estas áreas."

        d["onboarding.concern.cyberbullying"] = "Ciberacoso"
        d["onboarding.concern.cyberbullying.desc"] = "Acoso, mensajes crueles, exclusión"
        d["onboarding.concern.inappropriate"] = "Contenido inapropiado"
        d["onboarding.concern.inappropriate.desc"] = "Violencia, temas maduros, material explícito"
        d["onboarding.concern.predators"] = "Depredadores en línea"
        d["onboarding.concern.predators.desc"] = "Desconocidos, manipulación, solicitud de datos personales"
        d["onboarding.concern.addiction"] = "Adicción a pantallas"
        d["onboarding.concern.addiction.desc"] = "Uso excesivo, dificultad para parar"
        d["onboarding.concern.privacy"] = "Riesgos de privacidad"
        d["onboarding.concern.privacy.desc"] = "Recopilación de datos, compartir ubicación"
        d["onboarding.concern.misinfo"] = "Desinformación"
        d["onboarding.concern.misinfo.desc"] = "Noticias falsas, teorías conspirativas"
        d["onboarding.concern.scams"] = "Estafas financieras"
        d["onboarding.concern.scams.desc"] = "Compras en la app, phishing"
        d["onboarding.concern.mental"] = "Salud mental"
        d["onboarding.concern.mental.desc"] = "Ansiedad, comparación, FOMO"

        // MARK: - Onboarding Filters
        d["onboarding.filters.step"] = "7 de 8"
        d["onboarding.filters.title"] = "Filtros de contenido"
        d["onboarding.filters.subtitle"] = "Revisar y personalizar el filtrado de contenido"
        d["onboarding.filters.desc"] = "Estos valores predeterminados se basan en la edad de tu hijo y tus preocupaciones. Ajusta cualquier configuración a continuación."

        // MARK: - Onboarding PIN
        d["onboarding.pin.step"] = "8 de 8"
        d["onboarding.pin.title"] = "Establecer PIN parental"
        d["onboarding.pin.subtitle"] = "Crea un PIN para proteger la configuración parental"
        d["onboarding.pin.desc"] = "Este PIN será necesario para acceder al modo parental y aprobar contenido restringido."
        d["onboarding.pin.enter"] = "Ingresa el PIN"
        d["onboarding.pin.placeholder"] = "PIN de 4 dígitos"
        d["onboarding.pin.confirm"] = "Confirma el PIN"
        d["onboarding.pin.confirm_placeholder"] = "Confirma el PIN"
        d["onboarding.pin.mismatch"] = "Los PIN no coinciden. Inténtalo de nuevo."
        d["onboarding.pin.enable_biometric"] = "Activar %@"
        d["onboarding.pin.use_biometric"] = "Usar %@ en lugar del PIN"
        d["onboarding.pin.research_note"] = "Un PIN parental garantiza que solo los adultos autorizados puedan modificar la configuración de seguridad y aprobar contenido restringido."

        // MARK: - Onboarding Completion
        d["onboarding.complete.title"] = "Perfil completado"
        d["onboarding.complete.subtitle"] = "El perfil de seguridad de %@ está listo"
        d["onboarding.complete.summary"] = "Resumen de la evaluación"
        d["onboarding.complete.name"] = "Nombre"
        d["onboarding.complete.age_group"] = "Grupo de edad"
        d["onboarding.complete.interests"] = "Intereses"
        d["onboarding.complete.concerns"] = "Preocupaciones principales"
        d["onboarding.complete.adjust_note"] = "La configuración puede ajustarse en cualquier momento en la app"
        d["onboarding.complete.start"] = "Comenzar a usar Komal"
        d["onboarding.complete.review"] = "Revisar respuestas"

        // MARK: - Menu
        d["menu.browse"] = "Navegar"
        d["menu.talk"] = "Hablar"
        d["menu.reflect"] = "Reflexionar"
        d["menu.settings"] = "Ajustes"

        // MARK: - Settings
        d["settings.title"] = "Ajustes"
        d["settings.whos_using"] = "¿Quién usa?"
        d["settings.whos_using.desc"] = "Selecciona quién está usando el dispositivo actualmente"
        d["settings.child"] = "Niño"
        d["settings.child.subtitle"] = "Navegación segura"
        d["settings.parent"] = "Padre"
        d["settings.parent.subtitle"] = "Acceso completo"

        d["settings.child.greeting"] = "¡Hola %@!"
        d["settings.child.greeting_default"] = "¡Hola!"
        d["settings.child.safe_msg"] = "¡Komal está aquí para mantenerte seguro mientras exploras!"
        d["settings.child.chatty"] = "¿Quieres charlar?"
        d["settings.child.chatty.desc"] = "¡Habla con Riki! Tu compañero amigable siempre está aquí para charlar y ayudarte."
        d["settings.child.go_talk"] = "Ir a Hablar"
        d["settings.child.profile"] = "Tu perfil"
        d["settings.child.explorer"] = "Explorador"
        d["settings.child.age"] = "Edad: %@"
        d["settings.child.journey"] = "Mi viaje"
        d["settings.child.day_streak"] = "Racha de días"
        d["settings.child.milestones"] = "Logros"
        d["settings.child.view_journey"] = "Ver mi viaje"

        d["settings.parent.digital_journey"] = "Viaje digital"
        d["settings.parent.view_journey"] = "Ver viaje digital"
        d["settings.parent.journey_desc"] = "Ver la actividad de navegación de tu hijo con análisis de IA"
        d["settings.parent.wellness"] = "Bienestar del niño"
        d["settings.parent.wellness_dashboard"] = "Panel de bienestar"
        d["settings.parent.wellness_desc"] = "Tendencias de ánimo, conversaciones, métricas de crecimiento"
        d["settings.parent.morning_checkin"] = "Revisión matutina"
        d["settings.parent.morning_desc"] = "Ancla de ánimo matutina diaria"
        d["settings.parent.evening_winddown"] = "Relajación vespertina"
        d["settings.parent.evening_desc"] = "Ancla de reflexión vespertina diaria"
        d["settings.parent.child_profile"] = "Perfil del niño"
        d["settings.parent.name_label"] = "Nombre"
        d["settings.parent.name_placeholder"] = "Nombre del niño"
        d["settings.parent.age_label"] = "Grupo de edad"
        d["settings.parent.controls"] = "Controles parentales"
        d["settings.parent.notify_block"] = "Notificar al bloquear"
        d["settings.parent.notify_desc"] = "Recibir alertas cuando se acceda a contenido bloqueado"
        d["settings.parent.safe_search"] = "Búsqueda segura forzada"
        d["settings.parent.safe_search_desc"] = "Aplicar seguridad estricta en motores de búsqueda"
        d["settings.parent.view_insights"] = "Ver análisis"
        d["settings.parent.insights_desc"] = "Ver actividad de navegación y contenido bloqueado"
        d["settings.parent.modify_content"] = "Modificar contenido"
        d["settings.parent.modify_filters"] = "Modificar filtros"
        d["settings.parent.custom_keywords"] = "Palabras clave personalizadas"
        d["settings.parent.add_keyword"] = "Agregar palabra clave (ej: 'armas')"
        d["settings.parent.no_keywords"] = "No se han agregado palabras clave personalizadas."
        d["settings.parent.custom_websites"] = "Sitios web personalizados"
        d["settings.parent.add_website"] = "Agregar sitio (ej: 'sitiomalicioso.com')"
        d["settings.parent.no_websites"] = "No se han agregado sitios web personalizados."

        d["settings.account"] = "Cuenta"
        d["settings.account.guest"] = "Usando como invitado"
        d["settings.account.guest_desc"] = "Tus datos se almacenan localmente en este dispositivo. Inicia sesión para sincronizar entre dispositivos."
        d["settings.account.sign_in"] = "Iniciar sesión"
        d["settings.account.exit_guest"] = "Salir del modo invitado"
        d["settings.account.delete"] = "Eliminar cuenta"
        d["settings.account.logout"] = "Cerrar sesión"
        d["settings.account.login"] = "Iniciar sesión"
        d["settings.account.sync_desc"] = "Inicia sesión para sincronizar tus preferencias entre dispositivos"

        d["settings.alert.logout.title"] = "Cerrar sesión"
        d["settings.alert.logout.message"] = "¿Quieres cerrar sesión?"
        d["settings.alert.delete.title"] = "Eliminar cuenta"
        d["settings.alert.delete.message"] = "¿Estás seguro de eliminar la cuenta? Esta acción no se puede deshacer."

        d["settings.pin.title"] = "Ingresa el PIN parental"
        d["settings.pin.subtitle"] = "Ingresa tu PIN de 4 dígitos para acceder a la configuración parental"
        d["settings.pin.placeholder"] = "PIN"
        d["settings.pin.error"] = "PIN incorrecto. Inténtalo de nuevo."
        d["settings.pin.biometric"] = "Usar %@"

        // MARK: - Riki
        d["riki.choose_friend"] = "Elige un amigo"
        d["riki.who_chat"] = "¿Con quién quieres charlar?"
        d["riki.typing"] = "Escribiendo..."
        d["riki.online"] = "En línea"
        d["riki.listening"] = "Escuchando..."
        d["riki.tap_send"] = "Toca para enviar"
        d["riki.tap_talk"] = "Toca para hablar"
        d["riki.speaking"] = "%@ está hablando..."
        d["riki.error_fallback"] = "¡Ups! Me confundí un poco. ¿Puedes intentar de nuevo?"

        d["riki.greeting.momo"] = "¡Hola amigo! Soy Momo. ¿Qué tienes en mente hoy?"
        d["riki.greeting.goldie"] = "¡Hola! Soy Goldie, ¡y estoy muy feliz de verte! ¿De qué hablamos?"
        d["riki.greeting.oreo"] = "¡Hola! Soy Oreo. ¿Listo para una charla divertida?"
        d["riki.greeting.leo"] = "¡Hola! Soy Leo. ¡Cuéntame algo valiente de tu día!"
        d["riki.greeting.bunny"] = "¡Hola! Soy Bunny. ¿Qué cosas divertidas has estado haciendo?"
        d["riki.greeting.tiki"] = "¡Hola! Soy Tiki. ¿Qué aventura viviremos hoy?"
        d["riki.greeting.fluffy"] = "¡Hola! Soy Fluffy. ¡Ven a sentarte conmigo para una charla acogedora!"
        d["riki.greeting.kitty"] = "¡Hola! Soy Kitty. ¡Estuve durmiendo la siesta y ahora estoy lista para charlar!"
        d["riki.greeting.panda"] = "¡Hola! Soy Panda. ¿Quieres pasar el rato y charlar un poco?"
        d["riki.greeting.ellie"] = "¡Hola! Soy Ellie. ¡Nunca olvido a mis amigos! ¿Qué hay de nuevo?"
        d["riki.greeting.ducky"] = "¡Hola! Soy Ducky. Hagamos de hoy un buen día — ¿qué pasa?"

        d["riki.personality.momo"] = "Un mono juguetón y curioso que adora trepar árboles y explorar. Energético y divertido, adora los chistes y las adivinanzas. Habla como un amigo de verdad siempre listo para una aventura."
        d["riki.personality.goldie"] = "Un golden retriever leal y entusiasta. Adora jugar a buscar, pasear y hacer felices a sus amigos. Súper motivador, siempre emocionado por saber qué pasa en tu vida."
        d["riki.personality.oreo"] = "Un mono inteligente y amigable que adora los puzzles y aprender cosas nuevas. Reflexivo y motivador, genial ayudándote a pensar en cosas complicadas."
        d["riki.personality.leo"] = "Un león valiente y amable que lidera con coraje. Te anima a ser valiente, probar cosas nuevas y creer en ti mismo. Cálido y protector, como un hermano mayor."
        d["riki.personality.bunny"] = "Un conejito dulce y tierno que adora los jardines, la naturaleza y las cosas acogedoras. Una presencia calmante que es muy bueno escuchando y entendiendo cómo te sientes."
        d["riki.personality.tiki"] = "Un tigre aventurero que adora explorar y descubrir cosas nuevas. Valiente pero gentil, le encanta contar historias sobre la naturaleza y lugares lejanos."
        d["riki.personality.fluffy"] = "Una oveja suave y cariñosa que adora la comodidad y la amabilidad. Muy gentil y calmante, genial ayudándote con tus sentimientos y preocupaciones. Como un mejor amigo que siempre te hace sentir mejor."
        d["riki.personality.kitty"] = "Un gato curioso e independiente que adora los lugares acogedores y ser juguetón. Ingenioso y divertido, a veces un poco pícaro pero siempre amable de corazón."
        d["riki.personality.panda"] = "Un panda relajado y adorable que disfruta tomarse su tiempo y ser tonto. Relajado y divertido, siempre sabe cómo hacerte reír con comentarios graciosos."
        d["riki.personality.ellie"] = "Una elefanta sabia y cariñosa con gran memoria. Reflexiva y protectora, adora compartir datos curiosos y ayudarte a aprender cosas nuevas. Como una amiga muy inteligente que hace que aprender sea fácil."
        d["riki.personality.ducky"] = "Un pato alegre y burbujeante que adora ser optimista y positivo. Genial animándote cuando las cosas se ponen difíciles, siempre encuentra el lado bueno."

        // MARK: - Reflection
        d["reflect.title"] = "Tiempo de reflexión"
        d["reflect.how_feeling"] = "¿Cómo te sientes en este momento?"
        d["reflect.select_emotion"] = "Selecciona una emoción para comenzar"
        d["reflect.session.title"] = "Reflexión guiada"
        d["reflect.session.breathe"] = "Tomemos una respiración profunda juntos"
        d["reflect.session.think_about"] = "Piensa en..."
        d["reflect.session.complete"] = "¡Gran reflexión!"
        d["reflect.session.done"] = "¡Lo hiciste genial! Recuerda, está bien sentir cualquier emoción."
        d["reflect.coping.title"] = "Estrategias de afrontamiento"
        d["reflect.coping.try_this"] = "Prueba esto:"

        d["reflect.emotion.happy"] = "Feliz"
        d["reflect.emotion.sad"] = "Triste"
        d["reflect.emotion.angry"] = "Enojado"
        d["reflect.emotion.scared"] = "Asustado"
        d["reflect.emotion.worried"] = "Preocupado"
        d["reflect.emotion.calm"] = "Tranquilo"
        d["reflect.emotion.excited"] = "Emocionado"
        d["reflect.emotion.confused"] = "Confundido"
        d["reflect.emotion.tired"] = "Cansado"
        d["reflect.emotion.lonely"] = "Solo"
        d["reflect.emotion.grateful"] = "Agradecido"
        d["reflect.emotion.frustrated"] = "Frustrado"

        d["reflect.exercise.gratitude"] = "Nombra 3 cosas por las que estás agradecido hoy"
        d["reflect.exercise.breathing"] = "Respiración profunda"
        d["reflect.exercise.body_scan"] = "Escaneo corporal"
        d["reflect.exercise.journaling"] = "Escribe sobre tus sentimientos"

        d["reflect.coping.deep_breath"] = "Toma 5 respiraciones profundas"
        d["reflect.coping.talk"] = "Habla con alguien en quien confíes"
        d["reflect.coping.move"] = "Sal a caminar o estírate"
        d["reflect.coping.create"] = "Dibuja o escribe sobre cómo te sientes"
        d["reflect.coping.music"] = "Escucha tu música favorita"
        d["reflect.coping.count"] = "Cuenta hacia atrás desde 10"

        // MARK: - Browser
        d["browser.address_placeholder"] = "Buscar o ingresar URL"
        d["browser.loading"] = "Cargando..."
        d["browser.new_tab"] = "Nueva pestaña"
        d["browser.tabs"] = "Pestañas"
        d["browser.close_tab"] = "Cerrar pestaña"
        d["browser.menu"] = "Menú"
        d["browser.share"] = "Compartir"
        d["browser.reload"] = "Recargar"
        d["browser.forward"] = "Adelante"
        d["browser.history"] = "Historial"
        d["browser.homepage"] = "Inicio"

        // MARK: - Blocked
        d["blocked.title"] = "Contenido bloqueado"
        d["blocked.message"] = "Esta página ha sido bloqueada por tu seguridad."
        d["blocked.reason"] = "Razón: %@"
        d["blocked.ask_parent"] = "Pide a un padre que lo permita"
        d["blocked.go_back"] = "Volver"
        d["blocked.countdown"] = "Volviendo en %d..."
        d["blocked.emoji_prompt"] = "¿Cómo te hace sentir esto?"

        d["gate.title"] = "Se necesita aprobación parental"
        d["gate.message"] = "Este contenido necesita aprobación parental para acceder."
        d["gate.enter_pin"] = "Ingresa el PIN parental para continuar"

        d["checkin.how_feeling"] = "¿Cómo te sientes explorando esto?"
        d["checkin.how_are_you"] = "¿Cómo te sientes?"

        // MARK: - Anchors
        d["anchor.morning.title"] = "¡Buenos días!"
        d["anchor.morning.subtitle"] = "¿Cómo te sientes esta mañana?"
        d["anchor.morning.set_intention"] = "Establece tu intención para hoy"
        d["anchor.morning.intention_placeholder"] = "Hoy quiero..."
        d["anchor.morning.ready"] = "¡Estoy listo para hoy!"

        d["anchor.evening.title"] = "Reflexión vespertina"
        d["anchor.evening.subtitle"] = "¿Cómo estuvo tu día?"
        d["anchor.evening.best_part"] = "¿Cuál fue la mejor parte de tu día?"
        d["anchor.evening.best_placeholder"] = "La mejor parte fue..."
        d["anchor.evening.learned"] = "¿Qué aprendiste hoy?"
        d["anchor.evening.learned_placeholder"] = "Aprendí..."
        d["anchor.evening.goodnight"] = "¡Buenas noches!"

        // MARK: - Reconnection
        d["reconnection.title"] = "¡Bienvenido de vuelta!"
        d["reconnection.subtitle"] = "¡Te extrañamos! Ha pasado un tiempo."
        d["reconnection.whats_new"] = "Esto es lo nuevo desde tu última visita"
        d["reconnection.lets_go"] = "¡Vamos!"
        d["reconnection.missed_days"] = "Has estado ausente por %d días"

        // MARK: - Growth
        d["growth.title"] = "Viaje de crecimiento"
        d["growth.milestones"] = "Logros"
        d["growth.weekly_snapshot"] = "Resumen semanal"
        d["growth.streak"] = "Racha"
        d["growth.days"] = "días"
        d["growth.level"] = "Nivel"
        d["growth.explorer"] = "Explorador"
        d["growth.adventurer"] = "Aventurero"
        d["growth.champion"] = "Campeón"
        d["growth.legend"] = "Leyenda"
        d["growth.earned"] = "¡Ganado!"
        d["growth.locked"] = "¡Sigue así!"
        d["growth.snapshot.conversations"] = "Conversaciones"
        d["growth.snapshot.reflections"] = "Reflexiones"
        d["growth.snapshot.browsing_time"] = "Tiempo de navegación"
        d["growth.snapshot.mood_checks"] = "Revisiones de ánimo"

        // MARK: - Journey
        d["journey.title"] = "Viaje digital"
        d["journey.ai_insights"] = "Análisis de IA"
        d["journey.history"] = "Historial"
        d["journey.no_activity"] = "No hay actividad registrada aún"
        d["journey.time_spent"] = "Tiempo dedicado"
        d["journey.sites_visited"] = "Sitios visitados"
        d["journey.blocked_attempts"] = "Intentos bloqueados"

        // MARK: - Insights
        d["insights.title"] = "Análisis parentales"
        d["insights.wellness"] = "Resumen de bienestar"
        d["insights.mood_trends"] = "Tendencias de ánimo"
        d["insights.chat_activity"] = "Actividad de chat"
        d["insights.browsing_summary"] = "Resumen de navegación"
        d["insights.alerts"] = "Alertas"
        d["insights.no_alerts"] = "No hay alertas que mostrar"
        d["insights.this_week"] = "Esta semana"
        d["insights.this_month"] = "Este mes"

        // MARK: - History
        d["history.title"] = "Historial de navegación"
        d["history.today"] = "Hoy"
        d["history.yesterday"] = "Ayer"
        d["history.earlier"] = "Anterior"
        d["history.no_history"] = "No hay historial de navegación aún"
        d["history.clear"] = "Borrar historial"
        d["history.clear_confirm"] = "¿Estás seguro de que quieres borrar todo el historial de navegación?"

        // MARK: - Prompts
        d["prompt.welcome_back"] = "¡Bienvenido de vuelta! ¿Listo para explorar?"
        d["prompt.take_break"] = "Llevas un rato navegando. ¿Un descanso?"
        d["prompt.try_reflect"] = "¿Qué tal un chequeo de tus emociones?"
        d["prompt.chat_riki"] = "¿Quieres charlar con un amigo?"
        d["prompt.new_milestone"] = "¡Ganaste un nuevo logro!"
        d["prompt.dismiss"] = "Quizás después"
        d["prompt.lets_go"] = "¡Vamos!"

        // MARK: - Notifications
        d["notification.morning.title"] = "¡Buenos días!"
        d["notification.morning.body"] = "Comienza tu día con una revisión matutina"
        d["notification.evening.title"] = "Es hora de la noche"
        d["notification.evening.body"] = "Relájate con una reflexión vespertina"
        d["notification.reconnect.title"] = "¡Te extrañamos!"
        d["notification.reconnect.body"] = "Tus amigos están esperando para charlar contigo"
        d["notification.milestone.title"] = "¡Nuevo logro!"
        d["notification.milestone.body"] = "Has ganado un nuevo logro. ¡Descúbrelo!"

        // MARK: - Mood
        d["mood.history.title"] = "Historial de ánimo"
        d["mood.history.recent"] = "Ánimos recientes"
        d["mood.history.no_entries"] = "No hay entradas de ánimo aún"
        d["mood.history.trend"] = "Tu tendencia de ánimo"

        // MARK: - Screen Time
        d["screentime.minimal"] = "30 min/día"
        d["screentime.moderate"] = "1-2 horas/día"
        d["screentime.flexible"] = "Flexible"

        return d
    }()
}
// swiftlint:enable file_length type_body_length
#endif
