// swiftlint:disable file_length type_body_length
enum SpanishStrings {
    static let all: [String: String] = {
        var d = [String: String]()

        // MARK: - Common
        d["common.back"] = "Atrás"
        d["common.continue"] = "Continuar"
        d["common.done"] = "Listo"
        d["common.skip"] = "Omitir"
        d["common.cancel"] = "Cancelar"
        d["common.save"] = "Guardar"
        d["common.delete"] = "Eliminar"
        d["common.yes"] = "Sí"
        d["common.no"] = "No"
        d["common.ok"] = "OK"
        d["common.close"] = "Cerrar"
        d["common.enter"] = "Entrar"
        d["common.next"] = "Siguiente"
        d["common.a_little"] = "Un poco"
        d["common.a_lot"] = "Mucho"
        d["common.settings"] = "Ajustes"
        d["common.selected_count"] = "%d/%d seleccionados"
        d["common.step_of"] = "PASO %@"

        // MARK: - Splash
        d["splash.title"] = "Komal"
        d["splash.tagline"] = "El compañero digital seguro de tu hijo"

        // MARK: - Login
        d["login.welcome"] = "Bienvenido a Komal"
        d["login.tagline"] = "El compañero digital seguro de tu hijo"
        d["login.sign_in_google"] = "Iniciar sesión con Google"
        d["login.sign_in_apple"] = "Iniciar sesión con Apple"
        d["login.or"] = "o"
        d["login.guest_user"] = "Continuar como invitado"
        d["login.signing_in"] = "Iniciando sesión..."
        d["login.failed"] = "Error de inicio de sesión"
        d["login.try_again"] = "Intentar de nuevo"
        d["login.guest.welcome"] = "¡Bienvenido, invitado!"
        d["login.guest.description"] = "Tus datos se guardarán localmente en este dispositivo. Puedes iniciar sesión después para sincronizar entre dispositivos."
        d["login.guest.getting_started"] = "Comenzar"
        d["login.onboarding.welcome"] = "¡Bienvenido a Komal!"
        d["login.onboarding.description"] = "Vamos a configurar tu experiencia de navegación segura."
        d["login.onboarding.get_started"] = "Comenzar"

        // MARK: - Onboarding Welcome
        d["onboarding.welcome.title"] = "Evaluación de seguridad infantil"
        d["onboarding.welcome.subtitle"] = "Perfil de bienestar digital basado en evidencia"
        d["onboarding.welcome.card1.title"] = "Psicología del desarrollo"
        d["onboarding.welcome.card1.desc"] = "Configuraciones adaptadas a las etapas de desarrollo cognitivo definidas por la investigación en psicología infantil."
        d["onboarding.welcome.card2.title"] = "Análisis conductual"
        d["onboarding.welcome.card2.desc"] = "Comprender los patrones de navegación para crear límites de seguridad personalizados."
        d["onboarding.welcome.card3.title"] = "Protección proactiva"
        d["onboarding.welcome.card3.desc"] = "Filtrado de contenido basado en factores de riesgo y preferencias identificados."
        d["onboarding.welcome.time_estimate"] = "Esta evaluación toma aproximadamente 3-4 minutos"
        d["onboarding.welcome.begin"] = "Comenzar evaluación"
        d["onboarding.welcome.language"] = "Idioma"

        // MARK: - Onboarding Child Info
        d["onboarding.info.step"] = "1 de 6"
        d["onboarding.info.title"] = "Información básica"
        d["onboarding.info.subtitle"] = "Ayúdanos a entender a quién protegemos"
        d["onboarding.info.name_label"] = "Nombre del niño"
        d["onboarding.info.name_placeholder"] = "Ingresa el nombre"
        d["onboarding.info.age_label"] = "Grupo de edad"
        d["onboarding.info.age_desc"] = "Las restricciones de contenido se calibran según las etapas de desarrollo"
        d["onboarding.info.research_note"] = "La investigación muestra que los límites de contenido apropiados para la edad favorecen un desarrollo cognitivo saludable y reducen la ansiedad en los niños."

        // Age group descriptions
        d["onboarding.age.under10"] = "Primera infancia - Protección máxima"
        d["onboarding.age.10to13"] = "Preadolescente - Exploración guiada"
        d["onboarding.age.13to16"] = "Adolescente - Límites equilibrados"
        d["onboarding.age.16to18"] = "Adolescente mayor - Libertad apropiada"
        d["onboarding.age.18plus"] = "Adulto - Acceso completo"

        // MARK: - Onboarding Websites
        d["onboarding.websites.step"] = "2 de 6"
        d["onboarding.websites.title"] = "Sitios web favoritos"
        d["onboarding.websites.subtitle"] = "Selecciona hasta 5 sitios que tu hijo visita más"
        d["onboarding.websites.desc"] = "Comprender los hábitos de navegación nos ayuda a identificar fuentes confiables y personalizar la protección."

        // MARK: - Onboarding Interests
        d["onboarding.interests.step"] = "3 de 6"
        d["onboarding.interests.title"] = "Temas de interés"
        d["onboarding.interests.subtitle"] = "¿Qué le gusta aprender a tu hijo?"
        d["onboarding.interests.desc"] = "Selecciona 3-5 temas. Esto nos ayuda a entender qué contenido priorizar y proteger."

        // Interest names
        d["onboarding.interest.gaming"] = "Videojuegos"
        d["onboarding.interest.animals"] = "Animales"
        d["onboarding.interest.science"] = "Ciencia"
        d["onboarding.interest.art"] = "Arte y dibujo"
        d["onboarding.interest.music"] = "Música"
        d["onboarding.interest.sports"] = "Deportes"
        d["onboarding.interest.coding"] = "Programación"
        d["onboarding.interest.reading"] = "Lectura"
        d["onboarding.interest.cooking"] = "Cocina"
        d["onboarding.interest.nature"] = "Naturaleza"
        d["onboarding.interest.space"] = "Espacio"
        d["onboarding.interest.history"] = "Historia"
        d["onboarding.interest.movies"] = "Películas"
        d["onboarding.interest.crafts"] = "Manualidades"
        d["onboarding.interest.dinosaurs"] = "Dinosaurios"
        d["onboarding.interest.vehicles"] = "Vehículos"
        d["onboarding.interest.fashion"] = "Moda"
        d["onboarding.interest.dance"] = "Baile"
        d["onboarding.interest.photography"] = "Fotografía"
        d["onboarding.interest.travel"] = "Viajes"
        d["onboarding.interest.math"] = "Matemáticas"
        d["onboarding.interest.puzzles"] = "Rompecabezas"
        d["onboarding.interest.robots"] = "Robots"
        d["onboarding.interest.magic"] = "Magia"
        d["onboarding.interest.superheroes"] = "Superhéroes"
        d["onboarding.interest.gardening"] = "Jardinería"
        d["onboarding.interest.astronomy"] = "Astronomía"
        d["onboarding.interest.languages"] = "Idiomas"
        d["onboarding.interest.boardgames"] = "Juegos de mesa"
        d["onboarding.interest.swimming"] = "Natación"
        d["onboarding.interest.comics"] = "Cómics"
        d["onboarding.interest.yoga"] = "Yoga"
        d["onboarding.interest.theater"] = "Teatro"

        // MARK: - Onboarding Likes
        d["onboarding.likes.step"] = "4 de 6"
        d["onboarding.likes.title"] = "Lo que disfrutan en línea"
        d["onboarding.likes.subtitle"] = "Entender las experiencias positivas en línea"
        d["onboarding.likes.desc"] = "Selecciona las actividades que tu hijo disfruta. Esto nos ayuda a garantizar el acceso a contenido enriquecedor."
        d["onboarding.likes.other"] = "Otro (opcional)"
        d["onboarding.likes.other_placeholder"] = "Agrega algo más que disfruten..."

        // Like options
        d["onboarding.like.watching_videos"] = "Ver videos"
        d["onboarding.like.playing_games"] = "Jugar videojuegos"
        d["onboarding.like.chatting"] = "Chatear con amigos"
        d["onboarding.like.learning"] = "Aprender cosas nuevas"
        d["onboarding.like.creative"] = "Proyectos creativos"
        d["onboarding.like.exploring"] = "Explorar sitios web"
        d["onboarding.like.music"] = "Escuchar música"
        d["onboarding.like.virtual_worlds"] = "Mundos virtuales"
        d["onboarding.like.puzzles"] = "Puzzles y desafíos"
        d["onboarding.like.funny"] = "Contenido divertido"
        d["onboarding.like.stories"] = "Historias y libros"
        d["onboarding.like.making_videos"] = "Hacer videos"
        d["onboarding.like.drawing"] = "Dibujar y pintar"
        d["onboarding.like.photography"] = "Tomar fotos"
        d["onboarding.like.coding"] = "Programación"
        d["onboarding.like.reading_comics"] = "Leer cómics"
        d["onboarding.like.collecting"] = "Coleccionar cosas"
        d["onboarding.like.building"] = "Construir y crear"
        d["onboarding.like.cooking_videos"] = "Videos de cocina"
        d["onboarding.like.science_experiments"] = "Experimentos de ciencia"
        d["onboarding.like.dancing"] = "Bailar"
        d["onboarding.like.trivia"] = "Trivia y cuestionarios"
        d["onboarding.like.anime"] = "Anime y dibujos"
        d["onboarding.like.podcasts"] = "Podcasts"
        d["onboarding.like.shopping"] = "Compras en línea"
        d["onboarding.like.live_streams"] = "Ver transmisiones en vivo"

        // MARK: - Onboarding Dislikes
        d["onboarding.dislikes.step"] = "5 de 6"
        d["onboarding.dislikes.title"] = "Lo que les molesta"
        d["onboarding.dislikes.subtitle"] = "Identificar detonantes e incomodidades"
        d["onboarding.dislikes.desc"] = "Selecciona lo que preocupa o molesta a tu hijo en línea. Esto nos ayuda a filtrar contenido potencialmente perturbador."
        d["onboarding.dislikes.other"] = "Otras preocupaciones (opcional)"
        d["onboarding.dislikes.other_placeholder"] = "Agrega otras cosas que les molesten..."
        d["onboarding.dislikes.research_note"] = "Comprender lo que angustia a los niños en línea nos permite filtrar proactivamente el contenido antes de la exposición, reduciendo la ansiedad y las experiencias negativas."

        // Dislike options
        d["onboarding.dislike.scary"] = "Contenido aterrador"
        d["onboarding.dislike.loud"] = "Ruidos fuertes/sustos"
        d["onboarding.dislike.mean"] = "Comentarios crueles"
        d["onboarding.dislike.strangers"] = "Mensajes de desconocidos"
        d["onboarding.dislike.violent"] = "Juegos violentos"
        d["onboarding.dislike.sad"] = "Historias tristes"
        d["onboarding.dislike.ads"] = "Anuncios confusos"
        d["onboarding.dislike.reading"] = "Demasiada lectura"
        d["onboarding.dislike.timed"] = "Desafíos con tiempo"
        d["onboarding.dislike.losing"] = "Perder en juegos"
        d["onboarding.dislike.popups"] = "Videos emergentes"
        d["onboarding.dislike.rushed"] = "Ser apresurado"

        // MARK: - Onboarding Concerns
        d["onboarding.concerns.step"] = "6 de 8"
        d["onboarding.concerns.title"] = "Tus preocupaciones"
        d["onboarding.concerns.subtitle"] = "¿Qué te preocupa más sobre tu hijo en línea?"
        d["onboarding.concerns.desc"] = "Selecciona tus principales preocupaciones. Priorizaremos la protección en estas áreas."

        // Concern items
        d["onboarding.concern.cyberbullying"] = "Ciberacoso"
        d["onboarding.concern.cyberbullying.desc"] = "Acoso, mensajes crueles, exclusión"
        d["onboarding.concern.inappropriate"] = "Contenido inapropiado"
        d["onboarding.concern.inappropriate.desc"] = "Violencia, temas maduros, material explícito"
        d["onboarding.concern.predators"] = "Depredadores en línea"
        d["onboarding.concern.predators.desc"] = "Desconocidos, manipulación, solicitud de datos personales"
        d["onboarding.concern.addiction"] = "Adicción a pantallas"
        d["onboarding.concern.addiction.desc"] = "Uso excesivo, dificultad para parar"
        d["onboarding.concern.privacy"] = "Riesgos de privacidad"
        d["onboarding.concern.privacy.desc"] = "Recopilación de datos, compartir ubicación"
        d["onboarding.concern.misinfo"] = "Desinformación"
        d["onboarding.concern.misinfo.desc"] = "Noticias falsas, teorías conspirativas"
        d["onboarding.concern.scams"] = "Estafas financieras"
        d["onboarding.concern.scams.desc"] = "Compras en la app, phishing"
        d["onboarding.concern.mental"] = "Salud mental"
        d["onboarding.concern.mental.desc"] = "Ansiedad, comparación, FOMO"

        // MARK: - Onboarding Filters
        d["onboarding.filters.step"] = "7 de 8"
        d["onboarding.filters.title"] = "Filtros de contenido"
        d["onboarding.filters.subtitle"] = "Revisar y personalizar el filtrado de contenido"
        d["onboarding.filters.desc"] = "Estos valores predeterminados se basan en la edad de tu hijo y tus preocupaciones. Ajusta cualquier configuración a continuación."

        // MARK: - Onboarding PIN
        d["onboarding.pin.step"] = "8 de 8"
        d["onboarding.pin.title"] = "Establecer PIN parental"
        d["onboarding.pin.subtitle"] = "Crea un PIN para proteger la configuración parental"
        d["onboarding.pin.desc"] = "Este PIN será necesario para acceder al modo parental y aprobar contenido restringido."
        d["onboarding.pin.enter"] = "Ingresa el PIN"
        d["onboarding.pin.placeholder"] = "PIN de 4 dígitos"
        d["onboarding.pin.confirm"] = "Confirma el PIN"
        d["onboarding.pin.confirm_placeholder"] = "Confirma el PIN"
        d["onboarding.pin.mismatch"] = "Los PIN no coinciden. Inténtalo de nuevo."
        d["onboarding.pin.enable_biometric"] = "Activar %@"
        d["onboarding.pin.use_biometric"] = "Usar %@ en lugar del PIN"
        d["onboarding.pin.research_note"] = "Un PIN parental garantiza que solo los adultos autorizados puedan modificar la configuración de seguridad y aprobar contenido restringido."

        // MARK: - Avatar Selection
        d["onboarding.avatar.title"] = "Elige tu compañero"
        d["onboarding.avatar.subtitle"] = "¡Elige un amigo animal para que te guíe!"
        d["settings.avatar.title"] = "Tu avatar"
        d["settings.avatar.change"] = "Toca para cambiar tu avatar"

        // MARK: - Onboarding Completion
        d["onboarding.complete.title"] = "Perfil completado"
        d["onboarding.complete.subtitle"] = "El perfil de seguridad de %@ está listo"
        d["onboarding.complete.summary"] = "Resumen de la evaluación"
        d["onboarding.complete.name"] = "Nombre"
        d["onboarding.complete.age_group"] = "Grupo de edad"
        d["onboarding.complete.interests"] = "Intereses"
        d["onboarding.complete.concerns"] = "Preocupaciones principales"
        d["onboarding.complete.adjust_note"] = "La configuración puede ajustarse en cualquier momento en la app"
        d["onboarding.complete.start"] = "Comenzar a usar Komal"
        d["onboarding.complete.review"] = "Revisar respuestas"

        // MARK: - Menu / Navigation
        d["menu.browse"] = "Navegar"
        d["menu.talk"] = "Hablar"
        d["menu.reflect"] = "Reflexionar"
        d["menu.settings"] = "Ajustes"

        // MARK: - Settings
        d["settings.title"] = "Ajustes"
        d["settings.language"] = "Idioma"
        d["settings.whos_using"] = "¿Quién usa?"
        d["settings.whos_using.desc"] = "Selecciona quién está usando el dispositivo actualmente"
        d["settings.child"] = "Niño"
        d["settings.child.subtitle"] = "Navegación segura"
        d["settings.parent"] = "Padre"
        d["settings.parent.subtitle"] = "Acceso completo"

        // Settings - Child Mode
        d["settings.child.greeting"] = "¡Hola %@!"
        d["settings.child.greeting_default"] = "¡Hola!"
        d["settings.child.safe_msg"] = "¡Komal está aquí para mantenerte seguro mientras exploras!"
        d["settings.child.chatty"] = "¿Quieres charlar?"
        d["settings.child.chatty.desc"] = "¡Habla con Riki! Tu compañero amigable siempre está aquí para charlar y ayudarte."
        d["settings.child.go_talk"] = "Ir a Hablar"
        d["settings.child.profile"] = "Tu perfil"
        d["settings.child.explorer"] = "Explorador"
        d["settings.child.age"] = "Edad: %@"
        d["settings.child.journey"] = "Mi viaje"
        d["settings.child.day_streak"] = "Racha de días"
        d["settings.child.milestones"] = "Logros"
        d["settings.child.view_journey"] = "Ver mi viaje"

        // Settings - Parent Mode
        d["settings.parent.digital_journey"] = "Viaje digital"
        d["settings.parent.view_journey"] = "Ver viaje digital"
        d["settings.parent.journey_desc"] = "Ver la actividad de navegación de tu hijo con análisis de IA"
        d["settings.parent.wellness"] = "Bienestar del niño"
        d["settings.parent.wellness_dashboard"] = "Panel de bienestar"
        d["settings.parent.wellness_desc"] = "Tendencias de ánimo, conversaciones, métricas de crecimiento"
        d["settings.parent.morning_checkin"] = "Revisión matutina"
        d["settings.parent.morning_desc"] = "Ancla de ánimo matutina diaria"
        d["settings.parent.evening_winddown"] = "Relajación vespertina"
        d["settings.parent.evening_desc"] = "Ancla de reflexión vespertina diaria"
        d["settings.parent.child_profile"] = "Perfil del niño"
        d["settings.parent.name_label"] = "Nombre"
        d["settings.parent.name_placeholder"] = "Nombre del niño"
        d["settings.parent.age_label"] = "Grupo de edad"
        d["settings.parent.controls"] = "Controles parentales"
        d["settings.parent.notify_block"] = "Notificar al bloquear"
        d["settings.parent.notify_desc"] = "Recibir alertas cuando se acceda a contenido bloqueado"
        d["settings.parent.safe_search"] = "Búsqueda segura forzada"
        d["settings.parent.safe_search_desc"] = "Aplicar seguridad estricta en motores de búsqueda"
        d["settings.parent.view_insights"] = "Ver análisis"
        d["settings.parent.insights_desc"] = "Ver actividad de navegación y contenido bloqueado"
        d["settings.parent.modify_content"] = "Modificar contenido"
        d["settings.parent.modify_filters"] = "Modificar filtros"
        d["settings.parent.custom_keywords"] = "Palabras clave personalizadas"
        d["settings.parent.add_keyword"] = "Agregar palabra clave (ej: 'armas')"
        d["settings.parent.no_keywords"] = "No se han agregado palabras clave personalizadas."
        d["settings.parent.custom_websites"] = "Sitios web personalizados"
        d["settings.parent.add_website"] = "Agregar sitio (ej: 'sitiomalicioso.com')"
        d["settings.parent.no_websites"] = "No se han agregado sitios web personalizados."

        // Settings - Account
        d["settings.account"] = "Cuenta"
        d["settings.account.guest"] = "Usando como invitado"
        d["settings.account.guest_desc"] = "Tus datos se almacenan localmente en este dispositivo. Inicia sesión para sincronizar entre dispositivos."
        d["settings.account.sign_in"] = "Iniciar sesión"
        d["settings.account.exit_guest"] = "Salir del modo invitado"
        d["settings.account.delete"] = "Eliminar cuenta"
        d["settings.account.logout"] = "Cerrar sesión"
        d["settings.account.login"] = "Iniciar sesión"
        d["settings.account.sync_desc"] = "Inicia sesión para sincronizar tus preferencias entre dispositivos"

        // Settings - Alerts
        d["settings.alert.logout.title"] = "Cerrar sesión"
        d["settings.alert.logout.message"] = "¿Quieres cerrar sesión?"
        d["settings.alert.delete.title"] = "Eliminar cuenta"
        d["settings.alert.delete.message"] = "¿Estás seguro de eliminar la cuenta? Esta acción no se puede deshacer."

        // Settings - PIN Entry
        d["settings.pin.title"] = "Ingresa el PIN parental"
        d["settings.pin.subtitle"] = "Ingresa tu PIN de 4 dígitos para acceder a la configuración parental"
        d["settings.pin.placeholder"] = "PIN"
        d["settings.pin.error"] = "PIN incorrecto. Inténtalo de nuevo."
        d["settings.pin.biometric"] = "Usar %@"

        // Settings - Localized UI Strings
        d["settings.logout_confirm"] = "¿Quieres cerrar sesión?"
        d["settings.delete_confirm"] = "¿Estás seguro de que quieres eliminar tu cuenta? Esta acción no se puede deshacer."
        d["settings.wellness_dashboard"] = "Panel de bienestar"
        d["settings.wellness_desc"] = "Tendencias de ánimo, conversaciones, métricas de crecimiento"
        d["settings.view_insights"] = "Ver análisis"
        d["settings.insights_desc"] = "Ver actividad de navegación y contenido bloqueado"
        d["settings.modify_filters"] = "Modificar filtros"
        d["settings.custom_keywords"] = "Palabras clave personalizadas"
        d["settings.no_keywords"] = "No se han agregado palabras clave personalizadas."
        d["settings.custom_websites"] = "Sitios web personalizados"
        d["settings.no_websites"] = "No se han agregado sitios web personalizados."
        d["settings.using_guest"] = "Usando como invitado"
        d["settings.guest_data_info"] = "Tus datos se almacenan localmente en este dispositivo. Inicia sesión para sincronizar entre dispositivos."
        d["settings.sign_in"] = "Iniciar sesión"
        d["settings.exit_guest"] = "Salir del modo invitado"
        d["settings.delete_account"] = "Eliminar cuenta"
        d["settings.logout"] = "Cerrar sesión"
        d["settings.login"] = "Iniciar sesión"
        d["settings.sync_desc"] = "Inicia sesión para sincronizar tus preferencias entre dispositivos"
        d["settings.enter_pin"] = "Ingresa el PIN parental"
        d["settings.pin_desc"] = "Ingresa tu PIN de 4 dígitos para acceder a la configuración parental"
        d["settings.incorrect_pin"] = "PIN incorrecto. Inténtalo de nuevo."
        d["settings.use_biometric"] = "Usar %@"
        d["settings.enter"] = "Entrar"

        // MARK: - Riki / Talk
        d["riki.choose_friend"] = "Elige un amigo"
        d["riki.who_chat"] = "¿Con quién quieres charlar?"
        d["riki.typing"] = "Escribiendo..."
        d["riki.online"] = "En línea"
        d["riki.listening"] = "Escuchando..."
        d["riki.tap_send"] = "Toca para enviar"
        d["riki.tap_talk"] = "Toca para hablar"
        d["riki.speaking"] = "%@ está hablando..."
        d["riki.error_fallback"] = "¡Ups! Me confundí un poco. ¿Puedes intentar de nuevo?"
        d["riki.how_feeling"] = "¿Cómo te sientes?"
        d["riki.friend_title"] = "%@ el amigo"

        // SEL emoji labels
        d["sel.happy"] = "Feliz"
        d["sel.sad"] = "Triste"
        d["sel.angry"] = "Enojado"
        d["sel.worried"] = "Preocupado"
        d["sel.grateful"] = "Agradecido"
        d["sel.tired"] = "Cansado"
        d["sel.happy_msg"] = "¡Me siento feliz hoy!"
        d["sel.sad_msg"] = "Me siento un poco triste."
        d["sel.angry_msg"] = "Estoy enojado por algo."
        d["sel.worried_msg"] = "Me siento preocupado."
        d["sel.grateful_msg"] = "¡Me siento agradecido!"
        d["sel.tired_msg"] = "Estoy muy cansado hoy."

        // Character greetings
        d["riki.greeting.momo"] = "¡Hola amigo! Soy Momo. ¿Qué tienes en mente hoy?"
        d["riki.greeting.goldie"] = "¡Hola! Soy Goldie, ¡y estoy muy feliz de verte! ¿De qué hablamos?"
        d["riki.greeting.oreo"] = "¡Hola! Soy Oreo. ¿Listo para una charla divertida?"
        d["riki.greeting.leo"] = "¡Hola! Soy Leo. ¡Cuéntame algo valiente de tu día!"
        d["riki.greeting.bunny"] = "¡Hola! Soy Bunny. ¿Qué cosas divertidas has estado haciendo?"
        d["riki.greeting.tiki"] = "¡Hola! Soy Tiki. ¿Qué aventura viviremos hoy?"
        d["riki.greeting.fluffy"] = "¡Hola! Soy Fluffy. ¡Ven a sentarte conmigo para una charla acogedora!"
        d["riki.greeting.kitty"] = "¡Hola! Soy Kitty. ¡Estuve durmiendo la siesta y ahora estoy lista para charlar!"
        d["riki.greeting.panda"] = "¡Hola! Soy Panda. ¿Quieres pasar el rato y charlar un poco?"
        d["riki.greeting.ellie"] = "¡Hola! Soy Ellie. ¡Nunca olvido a mis amigos! ¿Qué hay de nuevo?"
        d["riki.greeting.ducky"] = "¡Hola! Soy Ducky. Hagamos de hoy un buen día — ¿qué pasa?"

        // Character personalities
        d["riki.personality.momo"] = "Un mono juguetón y curioso que adora trepar árboles y explorar. Energético y divertido, adora los chistes y las adivinanzas. Habla como un amigo de verdad siempre listo para una aventura."
        d["riki.personality.goldie"] = "Un golden retriever leal y entusiasta. Adora jugar a buscar, pasear y hacer felices a sus amigos. Súper motivador, siempre emocionado por saber qué pasa en tu vida."
        d["riki.personality.oreo"] = "Un mono inteligente y amigable que adora los puzzles y aprender cosas nuevas. Reflexivo y motivador, genial ayudándote a pensar en cosas complicadas."
        d["riki.personality.leo"] = "Un león valiente y amable que lidera con coraje. Te anima a ser valiente, probar cosas nuevas y creer en ti mismo. Cálido y protector, como un hermano mayor."
        d["riki.personality.bunny"] = "Un conejito dulce y tierno que adora los jardines, la naturaleza y las cosas acogedoras. Una presencia calmante que es muy bueno escuchando y entendiendo cómo te sientes."
        d["riki.personality.tiki"] = "Un tigre aventurero que adora explorar y descubrir cosas nuevas. Valiente pero gentil, le encanta contar historias sobre la naturaleza y lugares lejanos."
        d["riki.personality.fluffy"] = "Una oveja suave y cariñosa que adora la comodidad y la amabilidad. Muy gentil y calmante, genial ayudándote con tus sentimientos y preocupaciones. Como un mejor amigo que siempre te hace sentir mejor."
        d["riki.personality.kitty"] = "Un gato curioso e independiente que adora los lugares acogedores y ser juguetón. Ingenioso y divertido, a veces un poco pícaro pero siempre amable de corazón."
        d["riki.personality.panda"] = "Un panda relajado y adorable que disfruta tomarse su tiempo y ser tonto. Relajado y divertido, siempre sabe cómo hacerte reír con comentarios graciosos."
        d["riki.personality.ellie"] = "Una elefanta sabia y cariñosa con gran memoria. Reflexiva y protectora, adora compartir datos curiosos y ayudarte a aprender cosas nuevas. Como una amiga muy inteligente que hace que aprender sea fácil."
        d["riki.personality.ducky"] = "Un pato alegre y burbujeante que adora ser optimista y positivo. Genial animándote cuando las cosas se ponen difíciles, siempre encuentra el lado bueno."

        // MARK: - Reflection
        d["reflect.title"] = "Tiempo de reflexión"
        d["reflect.how_feeling"] = "¿Cómo te sientes en este momento?"
        d["reflect.select_emotion"] = "Selecciona una emoción para comenzar"
        d["reflect.session.title"] = "Reflexión guiada"
        d["reflect.session.breathe"] = "Tomemos una respiración profunda juntos"
        d["reflect.session.think_about"] = "Piensa en..."
        d["reflect.session.complete"] = "¡Gran reflexión!"
        d["reflect.session.done"] = "¡Lo hiciste genial! Recuerda, está bien sentir cualquier emoción."
        d["reflect.coping.title"] = "Estrategias de afrontamiento"
        d["reflect.coping.try_this"] = "Prueba esto:"

        // Emotions
        d["reflect.emotion.happy"] = "Feliz"
        d["reflect.emotion.sad"] = "Triste"
        d["reflect.emotion.angry"] = "Enojado"
        d["reflect.emotion.scared"] = "Asustado"
        d["reflect.emotion.worried"] = "Preocupado"
        d["reflect.emotion.calm"] = "Tranquilo"
        d["reflect.emotion.excited"] = "Emocionado"
        d["reflect.emotion.confused"] = "Confundido"
        d["reflect.emotion.tired"] = "Cansado"
        d["reflect.emotion.lonely"] = "Solo"
        d["reflect.emotion.grateful"] = "Agradecido"
        d["reflect.emotion.frustrated"] = "Frustrado"

        // Reflection exercises
        d["reflect.exercise.gratitude"] = "Nombra 3 cosas por las que estás agradecido hoy"
        d["reflect.exercise.breathing"] = "Respiración profunda"
        d["reflect.exercise.body_scan"] = "Escaneo corporal"
        d["reflect.exercise.journaling"] = "Escribe sobre tus sentimientos"

        // Coping strategies
        d["reflect.coping.deep_breath"] = "Toma 5 respiraciones profundas"
        d["reflect.coping.talk"] = "Habla con alguien en quien confíes"
        d["reflect.coping.move"] = "Sal a caminar o estírate"
        d["reflect.coping.create"] = "Dibuja o escribe sobre cómo te sientes"
        d["reflect.coping.music"] = "Escucha tu música favorita"
        d["reflect.coping.count"] = "Cuenta hacia atrás desde 10"

        // MARK: - Digital Journey
        d["journey.title"] = "Viaje digital"
        d["journey.tab.insights"] = "Análisis de IA"
        d["journey.tab.history"] = "Historial"
        d["journey.analyzing"] = "Analizando actividad de navegación..."
        d["journey.no_history"] = "No hay historial de navegación aún"
        d["journey.history_will_appear"] = "El historial aparecerá aquí mientras tu hijo navega"
        d["journey.needs_attention"] = "Necesita atención"
        d["journey.allowed_links"] = "Enlaces permitidos"
        d["journey.loading_history"] = "Cargando historial de navegación..."
        d["journey.time_range"] = "Rango de tiempo"
        d["journey.links"] = "enlaces"
        d["journey.filter.all"] = "Todos"
        d["journey.filter.blocked"] = "Bloqueados"
        d["journey.filter.gated"] = "Restringidos"
        d["journey.filter.allowed"] = "Permitidos"
        d["journey.range.1h"] = "1 hora"
        d["journey.range.3h"] = "3 horas"
        d["journey.range.6h"] = "6 horas"
        d["journey.range.12h"] = "12 horas"
        d["journey.range.24h"] = "24 horas"
        d["journey.range.all"] = "Todo el tiempo"
        // Legacy journey keys
        d["journey.ai_insights"] = "Análisis de IA"
        d["journey.history"] = "Historial"
        d["journey.no_activity"] = "No hay actividad registrada aún"
        d["journey.time_spent"] = "Tiempo dedicado"
        d["journey.sites_visited"] = "Sitios visitados"
        d["journey.blocked_attempts"] = "Intentos bloqueados"

        // MARK: - Browser
        d["browser.address_placeholder"] = "Buscar o ingresar URL"
        d["browser.loading"] = "Cargando..."
        d["browser.new_tab"] = "Nueva pestaña"
        d["browser.tabs"] = "Pestañas"
        d["browser.no_open_tabs"] = "No hay pestañas abiertas"
        d["browser.close_tab"] = "Cerrar pestaña"
        d["browser.menu"] = "Menú"
        d["browser.share"] = "Compartir"
        d["browser.reload"] = "Recargar"
        d["browser.forward"] = "Adelante"
        d["browser.history"] = "Historial"
        d["browser.homepage"] = "Inicio"
        d["browser.quick_checkin"] = "¿Cómo te sientes?"
        d["browser.search_or_url"] = "Buscar o escribir URL"
        d["browser.past_tabs"] = "Pestañas anteriores"
        d["browser.no_past_tabs"] = "No hay pestañas anteriores aún"
        d["browser.tabs_appear_here"] = "Los sitios web que visites aparecerán aquí"

        // MARK: - Blocked Content
        d["blocked.title"] = "Contenido bloqueado"
        d["blocked.not_available"] = "Este contenido no está disponible"
        d["blocked.keeping_safe"] = "¡Komal te está manteniendo seguro!"
        d["blocked.message"] = "Esta página ha sido bloqueada por tu seguridad."
        d["blocked.reason"] = "Razón: %@"
        d["blocked.ask_parent"] = "Pide a un padre que lo permita."
        d["blocked.go_back"] = "Volver"
        d["blocked.countdown"] = "Volviendo en %d..."
        d["blocked.emoji_prompt"] = "¿Cómo te hace sentir esto?"
        d["blocked.tap_talk"] = "Toca para hablar con Komal"
        d["blocked.fallback_response"] = "Estoy aquí para ti. ¡Vamos a explorar algo divertido juntos!"

        // MARK: - Chat Content Filtering
        d["chat.content_redirect"] = "¡Oye, no puedo hablar de eso! ¿Qué tal si hablamos de algo divertido? ¿Qué es lo que más te gusta hacer después de la escuela?"
        d["browser.checking_page"] = "Revisando esta página para ti..."
        d["blocked.hi_there"] = "¡Hola!"
        d["blocked.find_something_else"] = "¡Busquemos otra cosa!"
        d["blocked.friendly_1"] = "Lo siento, pero este contenido no está disponible ahora. ¡Busquemos algo más divertido para explorar juntos!"
        d["blocked.friendly_2"] = "Esto no es lo mejor para nosotros ahora. ¿Qué tal si buscamos algo genial?"
        d["blocked.friendly_3"] = "¡Saltemos esto y encontremos algo aún mejor! ¡Estoy aquí para ayudarte a descubrir cosas increíbles!"
        d["blocked.friendly_4"] = "Este contenido no está disponible en este momento. ¿Quieres explorar algo más juntos?"

        // MARK: - Gate (parent approval)
        d["gate.title"] = "Contenido restringido"
        d["gate.riki_pause"] = "Riki sugiere una pausa"
        d["gate.touches_on"] = "Esta página trata sobre %@. Revisemos antes de continuar."
        d["gate.start_break"] = "Iniciar pausa consciente"
        d["gate.parent_approval"] = "Aprobación parental"
        d["gate.enter_pin"] = "Ingresa el PIN parental"
        d["gate.approve_continue"] = "Aprobar y continuar"
        d["gate.access_gated"] = "El acceso está restringido para %@ (%@)."
        d["gate.message"] = "Este contenido necesita aprobación parental para acceder."

        // MARK: - Emoji Check-in
        d["checkin.how_feeling"] = "¿Cómo te sientes explorando esto?"
        d["checkin.how_are_you"] = "¿Cómo te sientes?"
        d["checkin.hi_there"] = "¡Hola!"
        d["checkin.intro_message"] = "Soy Komal, ¡y estoy navegando por internet contigo! ¿Cómo te sientes ahora?"
        d["checkin.thanks_komal"] = "¡Gracias, Komal!"
        d["checkin.emotion.happy"] = "Feliz"
        d["checkin.emotion.okay"] = "Bien"
        d["checkin.emotion.sad"] = "Triste"
        d["checkin.emotion.tired"] = "Cansado"
        d["checkin.emotion.curious"] = "Curioso"
        d["checkin.emotion.excited"] = "Emocionado"
        d["checkin.response.happy"] = "¡Qué bueno! ¡Me alegra mucho que la estés pasando bien explorando!"
        d["checkin.response.okay"] = "¡Está bien! Si necesitas algo, ¡aquí estoy para ayudarte!"
        d["checkin.response.sad"] = "Lamento que te sientas así. ¿Te gustaría tomar un descanso?"
        d["checkin.response.tired"] = "¡Está bien descansar! ¿Qué tal si exploramos más después?"
        d["checkin.response.curious"] = "¡Me encanta tu curiosidad! ¿Qué te estás preguntando?"
        d["checkin.response.excited"] = "¡Genial! ¡Yo también estoy emocionado de explorar contigo!"

        // MARK: - Mindful Break
        d["mindful.title"] = "Pausa consciente"
        d["mindful.pause_message"] = "Tómate una pausa suave. Nota tu respiración y el espacio a tu alrededor."
        d["mindful.im_ready"] = "Estoy listo"

        // MARK: - Filter Preferences
        d["filter.content_settings"] = "Ajustes de contenido"
        d["filter.customize"] = "Personaliza qué contenido se permite"
        d["filter.block"] = "Bloquear"
        d["filter.gate"] = "Restringir"
        d["filter.allow"] = "Permitir"

        // MARK: - Intervention
        d["intervention.tip"] = "Está bien ser curioso, ¡así es como aprendemos!"
        d["intervention.lets_think"] = "Vamos a pensarlo..."
        d["intervention.share_thoughts"] = "Comparte tus pensamientos..."
        d["intervention.done_reflecting"] = "Terminé de reflexionar"
        d["intervention.lets_talk"] = "Hablemos de esto"
        d["intervention.go_back"] = "Volver a un lugar seguro"
        d["intervention.main.search"] = "Oye, noté que buscaste algo..."
        d["intervention.main.url"] = "¡Espera un momento!"
        d["intervention.main.image"] = "Encontré algo de lo que deberíamos hablar"
        d["intervention.main.page"] = "Esta página tiene contenido para adultos"
        d["intervention.sub.search"] = "¡La curiosidad es totalmente normal! Pero algunos temas es mejor explorarlos con un adulto de confianza."
        d["intervention.sub.url"] = "Este sitio web podría tener contenido para adultos. ¿Quieres hablar sobre lo que estás buscando?"
        d["intervention.sub.image"] = "Noté algo que podría no ser apropiado. Hablemos de eso."
        d["intervention.sub.page"] = "Algo de lo que hay aquí es para personas mayores. ¿Quieres hablar o buscar otra cosa?"
        d["intervention.reflect.search"] = "¿Qué te dio curiosidad sobre esto?"
        d["intervention.reflect.url"] = "¿Qué esperabas encontrar?"
        d["intervention.reflect.image"] = "¿Cómo te hizo sentir ver eso?"
        d["intervention.reflect.page"] = "¿Hay algo sobre lo que tenías preguntas?"

        // MARK: - Reflection Time
        d["reflect.welcome.title"] = "Bienvenido al tiempo de reflexión"
        d["reflect.welcome.subtitle"] = "15 minutos de bienestar digital consciente"
        d["reflect.remaining"] = "restante"
        d["reflect.feelings.title"] = "Revisión de sentimientos"
        d["reflect.feelings.desc"] = "Explora y comprende tus emociones"
        d["reflect.mindfulness.title"] = "Ejercicio de atención plena"
        d["reflect.mindfulness.desc"] = "Respiración calmante y relajación"
        d["reflect.guided.title"] = "Reflexión guiada"
        d["reflect.guided.desc"] = "Piensa en tus experiencias digitales"
        d["reflect.free_chat.title"] = "Charla libre"
        d["reflect.free_chat.desc"] = "Habla sobre lo que tengas en mente"
        d["reflect.sel.title"] = "¿Cómo te sientes?"
        d["reflect.sel.subtitle"] = "Está bien sentir cualquier emoción. Exploremos juntos."
        d["reflect.sel.intensity"] = "¿Qué tan fuerte es este sentimiento?"
        d["reflect.sel.a_little"] = "Un poco"
        d["reflect.sel.a_lot"] = "Mucho"
        d["reflect.sel.things_help"] = "Cosas que podrían ayudar:"
        d["reflect.mindfulness.header"] = "Atención plena"
        d["reflect.mindfulness.calm_mind"] = "Tómate un momento para calmar tu mente"
        d["reflect.going_deeper"] = "Profundizando..."
        d["reflect.thinking_followup"] = "Pensando en un seguimiento..."
        d["reflect.previous"] = "Anterior"
        d["reflect.next"] = "Siguiente"
        d["reflect.free_chat.placeholder"] = "Escribe tus pensamientos..."
        d["reflect.free_chat.thinking"] = "Pensando..."
        d["reflect.completion.title"] = "¡Buen trabajo!"
        d["reflect.completion.subtitle"] = "Completaste tu tiempo de reflexión"
        d["reflect.completion.message"] = "Tomarte el tiempo para reflexionar te ayuda a conocerte mejor y mantenerte saludable en línea."

        // MARK: - SEL Emotions
        d["reflect.emotion.okay"] = "Bien"

        // MARK: - Coping Strategies
        d["reflect.coping.sad.1"] = "Habla con alguien en quien confíes"
        d["reflect.coping.sad.2"] = "Dibuja o escribe sobre tus sentimientos"
        d["reflect.coping.sad.3"] = "Escucha tu música favorita"
        d["reflect.coping.sad.4"] = "Date un abrazo"
        d["reflect.coping.angry.1"] = "Toma 5 respiraciones profundas"
        d["reflect.coping.angry.2"] = "Cuenta hacia atrás desde 10"
        d["reflect.coping.angry.3"] = "Aprieta una pelota antiestrés"
        d["reflect.coping.angry.4"] = "Sal a dar una caminata corta"
        d["reflect.coping.worried.1"] = "Cuéntale a un adulto cómo te sientes"
        d["reflect.coping.worried.2"] = "Piensa en 3 cosas por las que estás agradecido"
        d["reflect.coping.worried.3"] = "Imagina tu lugar feliz"
        d["reflect.coping.worried.4"] = "Toma respiraciones lentas y profundas"
        d["reflect.coping.tired.1"] = "Descansa la vista por un minuto"
        d["reflect.coping.tired.2"] = "Toma un poco de agua"
        d["reflect.coping.tired.3"] = "Estira tu cuerpo"
        d["reflect.coping.tired.4"] = "Tómate un descanso de las pantallas"
        d["reflect.coping.default.1"] = "Comparte tus sentimientos con alguien"
        d["reflect.coping.default.2"] = "Haz algo que disfrutes"
        d["reflect.coping.default.3"] = "Tómate un momento de atención plena"
        d["reflect.coping.default.4"] = "Sé amable contigo mismo"

        // MARK: - Mindfulness Exercises
        d["reflect.exercise.box.title"] = "Respiración cuadrada"
        d["reflect.exercise.box.desc"] = "Una técnica calmante usada por atletas y astronautas"
        d["reflect.exercise.box.step1"] = "Inhala por 4 segundos"
        d["reflect.exercise.box.step2"] = "Mantén por 4 segundos"
        d["reflect.exercise.box.step3"] = "Exhala por 4 segundos"
        d["reflect.exercise.box.step4"] = "Mantén por 4 segundos"
        d["reflect.exercise.box.step5"] = "Repite 4 veces"
        d["reflect.exercise.grounding.title"] = "Técnica 5-4-3-2-1"
        d["reflect.exercise.grounding.desc"] = "Conéctate con el momento presente"
        d["reflect.exercise.grounding.step1"] = "Nota 5 cosas que puedas VER"
        d["reflect.exercise.grounding.step2"] = "Nota 4 cosas que puedas TOCAR"
        d["reflect.exercise.grounding.step3"] = "Nota 3 cosas que puedas OÍR"
        d["reflect.exercise.grounding.step4"] = "Nota 2 cosas que puedas OLER"
        d["reflect.exercise.grounding.step5"] = "Nota 1 cosa que puedas SABOREAR"
        d["reflect.exercise.bodyscan.title"] = "Escaneo corporal"
        d["reflect.exercise.bodyscan.desc"] = "Relaja tu cuerpo de la cabeza a los pies"
        d["reflect.exercise.bodyscan.step1"] = "Relaja la frente y los ojos"
        d["reflect.exercise.bodyscan.step2"] = "Relaja la mandíbula y los hombros"
        d["reflect.exercise.bodyscan.step3"] = "Relaja los brazos y las manos"
        d["reflect.exercise.bodyscan.step4"] = "Relaja el estómago"
        d["reflect.exercise.bodyscan.step5"] = "Relaja las piernas y los pies"
        d["reflect.exercise.gratitude.title"] = "Momento de gratitud"
        d["reflect.exercise.gratitude.desc"] = "Enfócate en las cosas buenas de la vida"
        d["reflect.exercise.gratitude.step1"] = "Piensa en alguien que te hace feliz"
        d["reflect.exercise.gratitude.step2"] = "Piensa en algo en lo que eres bueno"
        d["reflect.exercise.gratitude.step3"] = "Piensa en un lugar que te hace sentir seguro"
        d["reflect.exercise.gratitude.step4"] = "Piensa en un recuerdo feliz"
        d["reflect.exercise.gratitude.step5"] = "Sonríe y siéntete agradecido"
        d["reflect.breathe.inhale"] = "Inhala"
        d["reflect.breathe.hold"] = "Mantén"
        d["reflect.breathe.exhale"] = "Exhala"

        // MARK: - Reflection Questions
        d["reflect.q1.question"] = "¿Qué fue lo mejor que viste en línea hoy?"
        d["reflect.q1.prompt"] = "Comparte algo que te hizo sonreír o sentir bien..."
        d["reflect.q2.question"] = "¿Algo en línea te hizo sentir incómodo?"
        d["reflect.q2.prompt"] = "Está bien hablar de las cosas que te molestaron..."
        d["reflect.q3.question"] = "¿Qué aprendiste hoy de internet?"
        d["reflect.q3.prompt"] = "Comparte algo interesante que descubriste..."
        d["reflect.q4.question"] = "¿Cuánto tiempo pasaste frente a las pantallas hoy?"
        d["reflect.q4.prompt"] = "¿Fue demasiado, justo lo necesario o poco?"
        d["reflect.q5.question"] = "¿Qué te gustaría hacer sin pantallas mañana?"
        d["reflect.q5.prompt"] = "Piensa en actividades divertidas lejos de las pantallas..."

        // MARK: - Free Chat Greetings
        d["reflect.chat.greeting.1"] = "¡Hola! Este es un espacio seguro para compartir tus pensamientos. ¿Qué tienes en mente hoy?"
        d["reflect.chat.greeting.2"] = "¡Hola! Estoy aquí para escucharte. Cuéntame algo interesante que haya pasado."
        d["reflect.chat.greeting.3"] = "¡Bienvenido! Puedes hablar de lo que quieras aquí. ¿De qué te gustaría charlar?"
        d["reflect.chat.fallback.1"] = "Gracias por compartir eso conmigo. ¿Cómo te hace sentir?"
        d["reflect.chat.fallback.2"] = "Te escucho. Eso suena realmente importante para ti."
        d["reflect.chat.fallback.3"] = "Qué bueno que estés hablando de esto. ¿Me cuentas más?"
        d["reflect.chat.fallback.4"] = "Entiendo. Está bien sentirse así."
        d["reflect.chat.fallback.5"] = "Gracias por confiar en mí. ¿Qué más tienes en mente?"

        // MARK: - Insights View
        d["insights.view.title"] = "Análisis"
        d["insights.overview"] = "Resumen"
        d["insights.sites_visited"] = "Sitios visitados"
        d["insights.blocked"] = "Bloqueados"
        d["insights.gated"] = "Restringidos"
        d["insights.sessions"] = "Sesiones"
        d["insights.content_categories"] = "Categorías de contenido"
        d["insights.activity_timeline"] = "Línea de tiempo de actividad"
        d["insights.recent_sessions"] = "Sesiones recientes"
        d["insights.no_sessions"] = "No hay sesiones de navegación aún"
        d["insights.protection_summary"] = "Resumen de protección"
        d["insights.images_protected"] = "Imágenes protegidas"
        d["insights.of_scanned"] = "de %d analizadas"
        d["insights.sites_blocked"] = "Sitios bloqueados"
        d["insights.harmful_content"] = "contenido dañino"
        d["insights.engagement"] = "Interacción"
        d["insights.avg_time_page"] = "Tiempo promedio por página"
        d["insights.avg_scroll_depth"] = "Profundidad de desplazamiento promedio"
        d["insights.meaningful_engagement"] = "Interacción significativa"
        d["insights.most_engaged"] = "Sitios con más interacción"
        d["insights.visits"] = "%d visitas"
        d["insights.avg_time"] = "tiempo prom."
        d["insights.browsing_patterns"] = "Patrones de navegación"
        d["insights.session_depth"] = "Profundidad de sesión"
        d["insights.pages"] = "%d páginas"
        d["insights.how_deep"] = "Qué tan profundo en los sitios"
        d["insights.back_navigation"] = "Navegación hacia atrás"
        d["insights.returning_pages"] = "Regresando a páginas anteriores"
        d["insights.quick_visits"] = "Visitas rápidas"
        d["insights.pages_under_10s"] = "Páginas vistas < 10 segundos"
        d["insights.content_viewed"] = "Contenido visto"
        d["insights.words_read"] = "Palabras leídas"
        d["insights.images"] = "Imágenes"
        d["insights.videos"] = "Videos"
        d["insights.topics"] = "Temas"
        d["insights.avg_time_short"] = "Tiempo prom."
        d["insights.reading"] = "Lectura"
        d["insights.concerning_content"] = "Contenido preocupante detectado"
        d["insights.keywords"] = "Palabras clave: %@"
        d["insights.found_on_pages"] = "Encontrado en %d página(s)"
        d["insights.recent_pages"] = "Páginas vistas recientemente"
        d["insights.topics_viewed"] = "Temas vistos:"
        d["insights.flagged"] = "Marcado: %@"
        d["insights.avg_time_per_page"] = "Tiempo prom. por página"

        // MARK: - Anchor - Morning
        d["anchor.morning.title"] = "¡Buenos días!"
        d["anchor.morning.greeting"] = "¡Buenos días!"
        d["anchor.morning.subtitle"] = "¿Cómo te sientes esta mañana?"
        d["anchor.morning.how_feeling"] = "¿Cómo te sientes hoy?"
        d["anchor.morning.how_strong"] = "¿Qué tan fuerte es este sentimiento?"
        d["anchor.morning.set_intention"] = "Establece tu intención para hoy"
        d["anchor.morning.looking_forward"] = "¿Qué esperas con ganas hoy?"
        d["anchor.morning.intention_placeholder"] = "Hoy quiero..."
        d["anchor.morning.looking_forward_placeholder"] = "Algo divertido, una clase, ver a un amigo..."
        d["anchor.morning.ready"] = "¡Estoy listo para hoy!"
        d["anchor.morning.start_my_day"] = "¡Empezar mi día!"

        // MARK: - Anchor - Evening
        d["anchor.evening.title"] = "Reflexión vespertina"
        d["anchor.evening.greeting"] = "¡Buenas noches!"
        d["anchor.evening.subtitle"] = "¿Cómo estuvo tu día?"
        d["anchor.evening.wind_down"] = "Relajémonos juntos"
        d["anchor.evening.how_feeling"] = "¿Cómo te sientes esta noche?"
        d["anchor.evening.best_part"] = "¿Cuál fue la mejor parte de tu día?"
        d["anchor.evening.best_placeholder"] = "La mejor parte fue..."
        d["anchor.evening.best_part_placeholder"] = "Cuéntame sobre eso..."
        d["anchor.evening.anything_bothering"] = "¿Algo te preocupa?"
        d["anchor.evening.bothering_placeholder"] = "Está bien compartir..."
        d["anchor.evening.learned"] = "¿Qué aprendiste hoy?"
        d["anchor.evening.learned_placeholder"] = "Aprendí..."
        d["anchor.evening.deep_breaths"] = "Toma 3 respiraciones profundas"
        d["anchor.evening.breathe_in_out"] = "Inhala... y exhala..."
        d["anchor.evening.goodnight"] = "¡Buenas noches!"
        d["anchor.evening.good_night"] = "¡Buenas noches!"

        // MARK: - Reconnection
        d["reconnection.title"] = "¡Bienvenido de vuelta!"
        d["reconnection.welcome_back"] = "¡Bienvenido de vuelta!"
        d["reconnection.subtitle"] = "¡Te extrañamos! Ha pasado un tiempo."
        d["reconnection.ellie_greeting"] = "¡Soy Ellie! Nunca olvido a mis amigos, ¡y estoy muy feliz de verte de nuevo!"
        d["reconnection.days_since"] = "Han pasado %d días desde la última vez que estuvimos juntos."
        d["reconnection.hi_ellie"] = "¡Hola Ellie!"
        d["reconnection.how_have_you_been"] = "¿Cómo has estado?"
        d["reconnection.mood_great"] = "¡Genial!"
        d["reconnection.mood_okay"] = "Bien"
        d["reconnection.mood_not_great"] = "No tan bien"
        d["reconnection.response_great"] = "¡Qué bueno saberlo! Sigamos con la buena vibra."
        d["reconnection.response_not_great"] = "Lamento escuchar eso. Recuerda, siempre estoy aquí para ti."
        d["reconnection.response_okay"] = "¡Qué bueno! Pasemos el rato y divirtámonos."
        d["reconnection.what_to_do"] = "¿Qué te gustaría hacer?"
        d["reconnection.browse_web"] = "Navegar por internet"
        d["reconnection.chat_friend"] = "Charlar con un amigo"
        d["reconnection.reflection_time"] = "Tiempo de reflexión"
        d["reconnection.whats_new"] = "Esto es lo nuevo desde tu última visita"
        d["reconnection.lets_go"] = "¡Vamos!"
        d["reconnection.missed_days"] = "Has estado ausente por %d días"

        // MARK: - Growth / Journey
        d["growth.title"] = "Mi viaje"
        d["growth.milestones"] = "Logros"
        d["growth.weekly_snapshot"] = "Resumen semanal"
        d["growth.noticed_about_you"] = "Lo que hemos notado sobre ti:"
        d["growth.day_streak"] = "Racha de días"
        d["growth.this_week"] = "Esta semana"
        d["growth.active_days"] = "Días activos"
        d["growth.chats"] = "Chats"
        d["growth.reflections"] = "Reflexiones"
        d["growth.moods"] = "Estados de ánimo"
        d["growth.streak"] = "Racha"
        d["growth.days"] = "días"
        d["growth.level"] = "Nivel"
        d["growth.explorer"] = "Explorador"
        d["growth.adventurer"] = "Aventurero"
        d["growth.champion"] = "Campeón"
        d["growth.legend"] = "Leyenda"
        d["growth.earned"] = "¡Ganado!"
        d["growth.locked"] = "¡Sigue así!"
        d["growth.snapshot.title"] = "Tu semana en resumen"
        d["growth.snapshot.conversations"] = "Conversaciones"
        d["growth.snapshot.reflections"] = "Reflexiones"
        d["growth.snapshot.browsing_time"] = "Tiempo de navegación"
        d["growth.snapshot.mood_checks"] = "Revisiones de ánimo"
        d["growth.snapshot.mood_checkins"] = "Revisiones de ánimo"
        d["growth.snapshot.most_common_mood"] = "Estado de ánimo más frecuente"
        d["growth.snapshot.favorite_friend"] = "Amigo favorito"
        d["growth.snapshot.growth_insight"] = "Dato de crecimiento"
        d["growth.snapshot.keep_going"] = "¡Sigue así!"

        // MARK: - Parent Insights
        d["insights.title"] = "Análisis parentales"
        d["insights.wellness"] = "Resumen de bienestar"
        d["insights.mood_trends"] = "Tendencias de ánimo"
        d["insights.chat_activity"] = "Actividad de chat"
        d["insights.browsing_summary"] = "Resumen de navegación"
        d["insights.alerts"] = "Alertas"
        d["insights.no_alerts"] = "No hay alertas que mostrar"
        d["insights.this_week"] = "Esta semana"
        d["insights.this_month"] = "Este mes"

        // MARK: - Parent Insights Dashboard
        d["insights.dashboard.title"] = "Bienestar del niño"
        d["insights.dashboard.this_week_vs_last"] = "Esta semana vs la anterior"
        d["insights.dashboard.chats"] = "Chats"
        d["insights.dashboard.reflections"] = "Reflexiones"
        d["insights.dashboard.moods"] = "Estados de ánimo"
        d["insights.dashboard.active_days"] = "Días activos"
        d["insights.dashboard.conversation_starter"] = "Tema de conversación para esta noche"
        d["insights.dashboard.generating_starter"] = "Generando un tema de conversación..."
        d["insights.dashboard.starter_placeholder"] = "Usa la app por unos días para obtener temas de conversación personalizados."
        d["insights.dashboard.daily_insight"] = "Dato del día"
        d["insights.dashboard.generating_insight"] = "Generando dato..."
        d["insights.dashboard.insight_placeholder"] = "Los datos aparecerán a medida que tu hijo use más la app."
        d["insights.dashboard.emotional_wellness"] = "Bienestar emocional"
        d["insights.dashboard.last_7_days"] = "Últimos 7 días"
        d["insights.dashboard.emotion_distribution"] = "Distribución emocional de 30 días"
        d["insights.dashboard.no_mood_data"] = "No hay datos de ánimo aún. Las entradas de ánimo aparecerán aquí a medida que tu hijo use la app."
        d["insights.dashboard.conversation_insights"] = "Datos de conversaciones"
        d["insights.dashboard.messages"] = "Mensajes"
        d["insights.dashboard.characters_used"] = "Personajes usados"
        d["insights.dashboard.popular_topics"] = "Temas populares"
        d["insights.dashboard.growth_metrics"] = "Métricas de crecimiento"
        d["insights.dashboard.current_streak"] = "Racha actual"
        d["insights.dashboard.milestones"] = "Logros"
        d["insights.dashboard.active_days_30d"] = "Días activos (30d)"
        d["insights.dashboard.activity_30d"] = "Actividad de 30 días"
        d["insights.dashboard.engagement_quality"] = "Calidad de interacción"
        d["insights.dashboard.voluntary_returns"] = "Regresos voluntarios"
        d["insights.dashboard.avg_reflection_depth"] = "Profundidad prom. de reflexión"
        d["insights.dashboard.total_sessions"] = "Sesiones totales"
        d["insights.dashboard.voluntary_returns_explanation"] = "Las tasas más altas de regreso voluntario indican una interacción genuina en lugar de uso impulsado por notificaciones."
        d["insights.dashboard.daily_checkins"] = "Revisiones diarias"
        d["insights.dashboard.morning"] = "Mañana"
        d["insights.dashboard.evening"] = "Noche"
        d["insights.dashboard.wellness_alert"] = "Alerta de bienestar"
        d["insights.dashboard.wellness_alert_message"] = "Tu hijo ha reportado sentirse triste en 3 o más revisiones consecutivas. Considera tener una conversación amable sobre cómo se siente."

        // MARK: - Browsing History
        d["history.title"] = "Historial de navegación"
        d["history.loading"] = "Cargando historial de navegación..."
        d["history.today"] = "Hoy"
        d["history.yesterday"] = "Ayer"
        d["history.earlier"] = "Anterior"
        d["history.no_history"] = "No hay historial de navegación aún"
        d["history.empty_message"] = "El historial aparecerá aquí mientras tu hijo navega."
        d["history.time_range"] = "Rango de tiempo"
        d["history.pages"] = "páginas"
        d["history.emoji_journey"] = "Viaje de emojis"
        d["history.summary"] = "Resumen"
        d["history.pages_visited"] = "Páginas visitadas"
        d["history.session_detail"] = "Detalle de sesión"
        d["history.back_label"] = "Historial"
        d["history.clear"] = "Borrar historial"
        d["history.clear_confirm"] = "¿Estás seguro de que quieres borrar todo el historial de navegación?"

        // MARK: - Contextual Prompts
        d["prompt.welcome_back"] = "¡Bienvenido de vuelta! ¿Listo para explorar?"
        d["prompt.take_break"] = "Llevas un rato navegando. ¿Un descanso?"
        d["prompt.try_reflect"] = "¿Qué tal un chequeo de tus emociones?"
        d["prompt.chat_riki"] = "¿Quieres charlar con un amigo?"
        d["prompt.new_milestone"] = "¡Ganaste un nuevo logro!"
        d["prompt.dismiss"] = "Quizás después"
        d["prompt.lets_go"] = "¡Vamos!"
        d["prompt.curiosity_noticed"] = "Noté algo interesante hoy... ¿Quieres saber?"
        d["prompt.curiosity_learned"] = "¿Curioso por lo que aprendí de ti? ¡Te vas a sorprender!"
        d["prompt.curiosity_question_young"] = "¡Tengo una pregunta súper divertida para ti! ¿Quieres jugar?"
        d["prompt.growth_calm"] = "Lo manejaste con calma. ¿Cómo lo hiciste?"
        d["prompt.growth_evolved"] = "Tu forma de pensar ha evolucionado mucho. ¿Quieres ver cuánto has avanzado?"
        d["prompt.growth_proud_young"] = "¡Guau, te estás volviendo muy bueno en esto! ¡Estoy muy orgulloso de ti!"
        d["prompt.growth_streak_celebrate"] = "¡Mira esa racha! Estás construyendo algo increíble, un día a la vez."
        d["prompt.brave_question"] = "¿Puedo hacerte una pregunta valiente? Podría sorprenderte."
        d["prompt.brave_future"] = "¿Qué diría tu yo del futuro sobre hoy? Descubrámoslo."
        d["prompt.brave_try_young"] = "¿Quieres intentar algo nuevo juntos? ¡Yo creo en ti!"
        d["prompt.transition_reflect"] = "¿Una reflexión rápida antes de irte? Solo 2 minutos."
        d["prompt.transition_progress"] = "¿Quieres ver tu mapa de progreso? ¡Has estado muy activo!"
        d["prompt.return_changed"] = "Algo pequeño cambió mientras no estabas. ¿Quieres ver?"
        d["prompt.return_secret"] = "¿Quieres ver un dato secreto sobre ti? Lo guardé para ti."
        d["prompt.return_missed_young"] = "¡Yay, regresaste! ¡Te extrañé! ¿Quieres jugar juntos?"
        d["prompt.emotional_check_negative"] = "Oye, noté que quizás la estás pasando difícil. Estoy aquí para ti."
        d["prompt.emotional_celebrate_positive"] = "¡Parece que estás de muy buen humor! Qué bueno verte así."
        d["prompt.browsing_learned"] = "¿Aprendiste algo interesante mientras navegabas? ¡Me encantaría saberlo!"
        d["prompt.browsing_break"] = "¿Cómo te sientes ahora? ¿Quieres hacer una revisión rápida?"
        d["prompt.browsing_riddle_young"] = "¿Quieres un descanso divertido? ¡Tengo una adivinanza para ti!"
        d["prompt.reflect_done_great"] = "Esa fue una reflexión muy buena. Deberías sentirte orgulloso."
        d["prompt.reflect_deeper_teen"] = "Buena reflexión. ¿Quieres ir un poco más profundo? A veces los mejores datos llegan después."
        d["prompt.action.tell_me"] = "¡Cuéntame!"
        d["prompt.action.show_me"] = "Muéstrame"
        d["prompt.action.lets_play"] = "¡Vamos a jugar!"
        d["prompt.action.let_me_think"] = "Déjame pensar..."
        d["prompt.action.show_my_growth"] = "Muestra mi crecimiento"
        d["prompt.action.see_my_journey"] = "Ver mi viaje"
        d["prompt.action.go_ahead"] = "Adelante"
        d["prompt.action.lets_explore"] = "Vamos a explorar"
        d["prompt.action.lets_try"] = "¡Intentemos!"
        d["prompt.action.sure"] = "¡Claro!"
        d["prompt.action.show_me_excited"] = "¡Muéstrame!"
        d["prompt.action.what_changed"] = "¿Qué cambió?"
        d["prompt.action.talk_about_it"] = "Hablemos de eso"
        d["prompt.action.lets_chat"] = "Vamos a charlar"
        d["prompt.action.check_in"] = "Revisión rápida"
        d["prompt.action.go_deeper"] = "Ir más profundo"

        // MARK: - Notifications
        d["notification.morning.title"] = "¡Buenos días!"
        d["notification.morning.body"] = "¡Soy Momo! Empecemos tu día con una revisión rápida. ¿Cómo te sientes?"
        d["notification.evening.title"] = "Es hora de relajarse"
        d["notification.evening.body"] = "¡Hola, soy Bunny! Tomemos un momento para reflexionar sobre tu día juntos."
        d["notification.reconnect.title"] = "¡Te extrañamos!"
        d["notification.reconnect.body"] = "Soy Ellie, ¡nunca olvido a mis amigos! Regresa y salúdame, tengo algo divertido para compartir."
        d["notification.milestone.title"] = "¡Nuevo logro!"
        d["notification.milestone.body"] = "Has ganado un nuevo logro. ¡Descúbrelo!"

        // MARK: - Mood History
        d["mood.history.title"] = "Historial de ánimo"
        d["mood.history.recent"] = "Ánimos recientes"
        d["mood.history.no_entries"] = "No hay entradas de ánimo aún"
        d["mood.history.trend"] = "Tu tendencia de ánimo"

        // MARK: - Scan Results
        d["scan.overall_safety_score"] = "Puntaje general de seguridad"
        d["scan.scanned"] = "Analizado"
        d["scan.live_analysis"] = "Análisis en vivo"
        d["scan.demo_mode"] = "Modo demo"
        d["scan.blocked_under_16"] = "Bloqueado para menores de 16"
        d["scan.out_of_100"] = "/100"
        d["scan.age_appropriate_actions"] = "Acciones apropiadas para la edad"
        d["scan.score"] = "Puntaje"
        d["scan.safety_risks_detected"] = "Riesgos de seguridad detectados"
        d["scan.matches"] = "coincidencias"
        d["scan.content_analysis"] = "Análisis de contenido"
        d["scan.nlp_text_analysis"] = "Análisis de texto NLP"
        d["scan.sentiment"] = "Sentimiento:"
        d["scan.language_score"] = "Puntaje de lenguaje:"
        d["scan.key_topics"] = "Temas clave:"
        d["scan.vision_ai_analysis"] = "Análisis de visión IA"
        d["scan.visual_safety_score"] = "Puntaje de seguridad visual:"
        d["scan.detected_objects"] = "Objetos detectados:"

        // MARK: - Screen Time
        d["screentime.minimal"] = "30 min/día"
        d["screentime.moderate"] = "1-2 horas/día"
        d["screentime.flexible"] = "Flexible"

        return d
    }()
}
// swiftlint:enable file_length type_body_length
